Repository openmeterio/openmeter, pull requests merged in 2023-10, with the labels that each got.

#281 Python client
  api/client/node/.nvmrc
  api/client/python/.gitattributes
  api/client/python/.gitignore
  api/client/python/Makefile
  api/client/python/README.md
  api/client/python/config.yaml
  api/client/python/examples/async/ingest.py
  api/client/python/examples/async/poetry.lock
  api/client/python/examples/async/pyproject.toml
  api/client/python/poetry.lock
  api/client/python/pyproject.toml
  api/client/python/src/openmeter/__init__.py
  api/client/python/src/openmeter/_client.py
  api/client/python/src/openmeter/_configuration.py
  api/client/python/src/openmeter/_operations/__init__.py
  api/client/python/src/openmeter/_operations/_operations.py
  api/client/python/src/openmeter/_operations/_patch.py
  api/client/python/src/openmeter/_patch.py
  api/client/python/src/openmeter/_serialization.py
  api/client/python/src/openmeter/_vendor.py
  api/client/python/src/openmeter/aio/__init__.py
  api/client/python/src/openmeter/aio/_client.py
  api/client/python/src/openmeter/aio/_configuration.py
  api/client/python/src/openmeter/aio/_operations/__init__.py
  api/client/python/src/openmeter/aio/_operations/_operations.py
  api/client/python/src/openmeter/aio/_operations/_patch.py
  api/client/python/src/openmeter/aio/_patch.py
  api/client/python/src/openmeter/aio/_vendor.py
  api/client/python/src/openmeter/py.typed
  flake.lock
  flake.nix
Labels: kind/feature, area/api, release-note/feature

#294 feat(api): query events
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  go.mod
  go.sum
  internal/server/router/router.go
  internal/server/server_test.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
  internal/streaming/connector.go
  pkg/kafkaconnect/client.gen.go
  pkg/models/error.go
Labels: area/api, area/processor, release-note/feature

#296 feat(api): add events query to node
  api/client/node/README.md
  api/client/node/clients/event.ts
  api/client/node/clients/meter.ts
  api/client/node/schemas/openapi.ts
  api/client/node/test/agent.ts
  api/client/node/test/api.test.ts
  api/client/node/test/mocks.ts
Labels: area/api, release-note/feature

#297 feat(api): rename query events to list
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/README.md
  api/client/node/clients/event.ts
  api/client/node/test/api.test.ts
  api/openapi.yaml
  internal/server/router/router.go
  internal/server/server_test.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/connector.go
Labels: area/api, release-note/ignore

#283 feat(api): add vercel ai helper to node sdk
  api/client/node/README.md
  api/client/node/index.ts
  api/client/node/next.ts
  api/client/node/package-lock.json
  api/client/node/package.json
  api/client/node/schemas/openapi.ts
  api/client/node/test/next.test.ts
Labels: release-note/feature, javascript

#298 chore(api): release node sdk 1.0.0-beta.9
  api/client/node/README.md
  api/client/node/package-lock.json
  api/client/node/package.json
Labels: area/api, release-note/ignore

#300 chore: upgrade flake
  flake.lock
  flake.nix
Labels: release-note/misc

#307 Export OpenMeter as a library
  openmeter/dedupe/dedupe.go
  openmeter/dedupe/memorydedupe/memorydedupe.go
  openmeter/dedupe/redisdedupe/redisdedupe.go
  openmeter/ingest/dedupe.go
  openmeter/ingest/httpingest/httpingest.go
  openmeter/ingest/ingest.go
  openmeter/ingest/inmemory.go
  openmeter/ingest/kafkaingest/collector.go
  openmeter/ingest/kafkaingest/namespace.go
  openmeter/ingest/kafkaingest/serializer/json.go
  openmeter/ingest/kafkaingest/serializer/serializer.go
  openmeter/meter/inmemory.go
  openmeter/meter/meter.go
  openmeter/namespace/namespace.go
  openmeter/openmeter.go
  openmeter/server/router/router.go
  openmeter/server/server.go
  openmeter/streaming/clickhouse_connector/connector.go
  openmeter/streaming/clickhouse_connector/model.go
  openmeter/streaming/connector.go
Labels: kind/feature

#314 chore: update kafka connect
  docker-compose.yaml
  etc/kafka-connect/Dockerfile
Labels: release-note/misc

#315 Minor wording change in event-ingestion.md
  docs/event-ingestion.md
Labels: release-note/misc

#323 feat(meter): add list all meters and add namespace to meter
  config/config.go
  config/config_test.go
  internal/meter/inmemory.go
  internal/meter/meter.go
  pkg/models/meter.go
Labels: release-note/feature

#320 Kafka Consumer Worker
  .github/workflows/ci.yaml
  Dockerfile
  Makefile
  cmd/server/.air.toml
  cmd/server/main.go
  cmd/server/version.go
  cmd/sink-worker/.air.toml
  cmd/sink-worker/main.go
  cmd/sink-worker/version.go
  config.example.yaml
  config/config.go
  config/config_test.go
  config/dedupe.go
  config/ingest.go
  config/sink.go
  config/testdata/complete.yaml
  docker-compose.yaml
  go.mod
  go.sum
  internal/dedupe/dedupe.go
  internal/dedupe/memorydedupe/memorydedupe.go
  internal/dedupe/memorydedupe/memorydedupe_test.go
  internal/dedupe/redisdedupe/redisdedupe.go
  internal/ingest/dedupe.go
  internal/sink/buffer.go
  internal/sink/buffer_test.go
  internal/sink/kafka_connect.go
  internal/sink/model.go
  internal/sink/namespaces.go
  internal/sink/namespaces_test.go
  internal/sink/offset.go
  internal/sink/offset_test.go
  internal/sink/sink.go
  internal/sink/storage.go
  internal/sink/storage_test.go
  internal/streaming/clickhouse_connector/connector.go
  openmeter/dedupe/dedupe.go
  openmeter/ingest/dedupe.go
  openmeter/sink/sink.go
  pkg/kafkaconnect/Makefile
  pkg/kafkaconnect/client.gen.go
  pkg/kafkaconnect/client.go
  pkg/kafkaconnect/codegen.yaml
  pkg/kafkaconnect/openapi.yaml
  pkg/models/meter.go
  quickstart/config.yaml
  quickstart/docker-compose.ci.yaml
  quickstart/docker-compose.yaml
Labels: area/processor, release-note/breaking-change, release-note/feature, area/dedupe

#330 fix(openmeter): export dedupe
  openmeter/ingest/dedupe.go
Labels: release-note/bug-fix

#329 feat(dedupe): set multiple keys once
  cmd/sink-worker/main.go
  internal/dedupe/redisdedupe/redisdedupe.go
Labels: release-note/bug-fix, release-note/feature, area/dedupe

#328 feat(sink): with retry
  go.mod
  go.sum
  internal/sink/sink.go
Labels: area/processor, release-note/feature

#331 feat(sink): export configure sink
  config/config.go
  config/sink.go
Labels: release-note/feature, dependencies

#332 fix(api): use struct instead of interface for response problem type
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
Labels: area/api, release-note/bug-fix

#339 chore: upgrade oapi codegen
  api/api.gen.go
  api/api.go
  api/client/go/client.gen.go
  go.mod
  go.sum
  internal/server/server.go
Labels: area/dependencies

#335 feat(sink): otel integration for worker
  cmd/sink-worker/main.go
  internal/sink/sink.go
Labels: area/processor, release-note/feature

#340 fix(quickstart): sink worker image
  quickstart/docker-compose.yaml
Labels: kind/bug, release-note/ignore

#341 fix(router): default to json with invalid mime
  internal/server/router/router.go
Labels: area/api, release-note/bug-fix

#349 fix(client): node openapi generation
  api/client/node/.gitignore
  api/client/node/package-lock.json
  api/client/node/package.json
  api/client/openapi.ts
Labels: area/api, release-note/bug-fix

#353 Fix OpenAPI and regenerate Python client
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/python/config.yaml
  api/client/python/src/openmeter/__init__.py
  api/client/python/src/openmeter/_client.py
  api/client/python/src/openmeter/_configuration.py
  api/client/python/src/openmeter/_operations/__init__.py
  api/client/python/src/openmeter/_operations/_operations.py
  api/client/python/src/openmeter/_serialization.py
  api/client/python/src/openmeter/_vendor.py
  api/client/python/src/openmeter/aio/__init__.py
  api/client/python/src/openmeter/aio/_client.py
  api/client/python/src/openmeter/aio/_configuration.py
  api/client/python/src/openmeter/aio/_operations/__init__.py
  api/client/python/src/openmeter/aio/_operations/_operations.py
  api/client/python/src/openmeter/aio/_vendor.py
  api/openapi.yaml
Labels: area/api, release-note/misc

#237 feat(examples): switch to query api
  examples/export-stripe-node/app.ts
  examples/ingest-fastify-node/app.ts
  examples/ingest-openai-node/app.ts
Labels: release-note/misc

#354 ci(api): add Node.js client generation workflow
  .github/workflows/generate-client-node.yaml
Labels: area/api, release-note/misc

#355 ci(api): temporarily enable manual workflow dispatch
  .github/workflows/generate-client-node.yaml
Labels: release-note/ignore

#348 feat!: remove meter values endpoint
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/python/src/openmeter/_operations/_operations.py
  api/client/python/src/openmeter/aio/_operations/_operations.py
  api/openapi.yaml
  internal/server/router/router.go
  internal/server/server_test.go
  pkg/models/meter.go
  pkg/models/meter_test.go
  quickstart/verify.sh
Labels: area/api, release-note/breaking-change

#360 ci(api): use bot to open PR
  .github/workflows/generate-client-python.yaml
Labels: area/api, release-note/ignore

#358 ci: upgrade dagger to modules
  .github/workflows/ci.yaml
  .golangci.yaml
  Makefile
  ci/.gitignore
  ci/dagger.json
  ci/go.mod
  ci/go.sum
  ci/magefile.go
  ci/main.go
  flake.lock
  flake.nix
Labels: release-note/ignore

#342 Fix typos in docs/
  docs/decisions/0001-event-streaming-platform.md
  docs/decisions/0003-idempotency.md
  docs/decisions/0004-partitioning.md
  docs/event-ingestion.md
  docs/seeder.md
Labels: release-note/misc

#365 chore: update dependencies
  go.mod
  go.sum
Labels: area/dependencies

#368 build: use official dagger flake
  flake.lock
  flake.nix
Labels: release-note/misc

#367 Lint openapi
  .spectral.yaml
  Makefile
  api/openapi.yaml
  ci/dagger.json
  ci/main.go
Labels: release-note/misc

#370 feat(connector): meter subjects from to
  internal/server/router/router.go
  internal/server/server_test.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
  internal/streaming/connector.go
Labels: area/api, release-note/feature

#374 ci: do not generate api clients on tag
  .github/workflows/generate-client-node.yaml
  .github/workflows/generate-client-python.yaml
Labels: release-note/misc

#343 Fixed typos in examples/
  examples/export-stripe-go/README.md
  examples/export-stripe-node/README.md
  examples/ingest-fastify-node/README.md
  examples/ingest-kubernetes-pod-time-go/README.md
  examples/ingest-openai-node/README.md
Labels: release-note/misc
