Repository openmeterio/openmeter, pull requests merged in 2023-06, with the labels that each got.

#53 ci: add quickstart test
  .github/workflows/artifacts.yaml
  .github/workflows/ci.yaml
  Dockerfile
  quickstart/docker-compose.ci.yaml
  quickstart/ingest.sh
  quickstart/verify.sh
Labels: release-note/misc

#55 chore: label config changes
  .github/dependabot.yaml
  .github/release.yml
  .github/workflows/pr-checks.yaml
Labels: release-note/ignore

#49 refactor: separate kafka ingest from streaming connector
  internal/ingest/httpingest/httpingest.go
  internal/ingest/httpingest/httpingest_test.go
  internal/ingest/kafkaingest/kafkaingest.go
  internal/ingest/kafkaingest/schema.go
  internal/ingest/kafkaingest/schema/event_key.json
  internal/ingest/kafkaingest/schema/event_value.json
  internal/server/router/router.go
  internal/server/server.go
  internal/streaming/connector.go
  internal/streaming/kafka_connector/cloudevents.go
  internal/streaming/kafka_connector/connector.go
  internal/streaming/kafka_connector/schema.go
  main.go
Labels: kind/refactor

#62 docs: add nix installation instructions
  README.md
Labels: kind/documentation, release-note/misc

#63 ci: rewrite label list
  .github/workflows/pr-checks.yaml
Labels: release-note/ignore

#69 feat(clients): add Node.js client generation
  api/clients/node/README.md
  api/clients/node/index.ts
  api/clients/node/package-lock.json
  api/clients/node/package.json
  api/clients/node/scripts/postgenerate.ts
  api/clients/node/test/api.test.ts
  api/clients/node/tsconfig.json
  api/clients/node/vitest.config.ts
Labels: kind/feature, area/api, release-note/feature

#71 fix(quickstart): docker compose always pull
  quickstart/docker-compose.yaml
Labels: kind/bug

#72 fix(clients): patch generated code of Node.js client
  api/clients/node/.eslintignore
  api/clients/node/.eslintrc.json
  api/clients/node/.gitignore
  api/clients/node/.npmignore
  api/clients/node/.nvmrc
  api/clients/node/.prettierignore
  api/clients/node/.prettierrc.json
  api/clients/node/package.json
  api/clients/node/scripts/postgenerate.ts
Labels: area/api, release-note/bug-fix

#73 feat(examples): use node client
  examples/export-stripe-node/.prettierrc.json
  examples/export-stripe-node/app.ts
  examples/export-stripe-node/openapi.d.ts
  examples/export-stripe-node/package-lock.json
  examples/export-stripe-node/package.json
  examples/export-stripe-node/setup.ts
  examples/ingest-openai-node/.gitignore
  examples/ingest-openai-node/.prettierrc.json
  examples/ingest-openai-node/README.md
  examples/ingest-openai-node/app.ts
  examples/ingest-openai-node/openapi.d.ts
  examples/ingest-openai-node/package-lock.json
  examples/ingest-openai-node/package.json
  examples/ingest-openai-node/tsconfig.json
Labels: kind/refactor

#74 ci: add licensei
  flake.nix
Labels: release-note/ignore

#76 Go client
  api/api.gen.go
  api/client/go/README.md
  api/client/go/client.gen.go
  api/client/go/client.go
  api/client/go/codegen.yaml
  api/client/go/error.go
  api/codegen.yml
  examples/export-stripe-go/main.go
  examples/export-stripe-go/report.go
  examples/ingest-kubernetes-pod-time-go/main.go
Labels: kind/feature

#77 Relocate node
  api/api.go
  api/client/go/client.go
  api/client/node/.eslintignore
  api/client/node/.eslintrc.json
  api/client/node/.gitignore
  api/client/node/.npmignore
  api/client/node/.nvmrc
  api/client/node/.prettierignore
  api/client/node/.prettierrc.json
  api/client/node/README.md
  api/client/node/index.ts
  api/client/node/package-lock.json
  api/client/node/package.json
  api/client/node/scripts/postgenerate.ts
  api/client/node/test/api.test.ts
  api/client/node/tsconfig.json
  api/client/node/vitest.config.ts
  api/codegen.yaml
  api/openapi.yaml
  examples/export-stripe-node/package.json
  examples/ingest-openai-node/package.json
Labels: kind/refactor

#78 docs: add client SDKs to README
  .github/workflows/pr-checks.yaml
  README.md
Labels: kind/documentation
