Repository openmeterio/openmeter, pull requests merged in 2023-08, with the labels that each got.

#126 feat(dedupe): add redis dedupe
  config.go
  docker-compose.yaml
  go.mod
  go.sum
  internal/ingest/dedupe.go
  internal/ingest/httpingest/httpingest.go
  internal/ingest/memorydedupe/collector.go
  internal/ingest/memorydedupe/collector_test.go
  internal/ingest/redisdedupe/collector.go
  main.go
  quickstart/docker-compose.yaml
Labels: kind/feature, area/api, area/ingest

#128 feat(namespace): configure default and management
  config.go
  internal/ingest/httpingest/httpingest.go
  internal/ingest/httpingest/httpingest_test.go
  internal/ingest/kafkaingest/namespace.go
  internal/namespace/namespace.go
  internal/namespace/namespace_test.go
  internal/server/router/router.go
  internal/server/server_test.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/ksqldb_connector/meter_test.go
  internal/streaming/ksqldb_connector/namespace.go
  internal/streaming/ksqldb_connector/query_test.go
  main.go
Labels: kind/feature

#131 feat(sink): strengthen connect topics regex
  internal/streaming/clickhouse_connector/connector.go
Labels: kind/feature, area/processor, release-note/feature

#136 feat(dedupe): support redis username
  config.go
  main.go
Labels: kind/feature, area/ingest, release-note/feature

#138 Beta release
  .github/workflows/release.yaml
Labels: kind/refactor

#137 feat(namespace): case sensitive
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/streaming/clickhouse_connector/connector.go
Labels: kind/feature, area/api, area/processor, release-note/feature

#139 Do not require meters to be defined in config
  config.go
Labels: kind/feature

#140 fix(processor): check if kafka connect is enabled in clickhouse
  internal/streaming/clickhouse_connector/connector.go
  main.go
Labels: area/processor, release-note/bug-fix

#134 feat(processor): order clickhouse query response
  internal/streaming/clickhouse_connector/query_test.go
  internal/streaming/clickhouse_connector/sql/query_meter_view.tpl.sql
Labels: kind/feature, area/processor, release-note/feature

#142 feat: add redis sentinel support
  config.go
  main.go
Labels: kind/feature

#141 chore: update helm Chart.lock digest
  deploy/charts/openmeter/Chart.lock
Labels: area/dependencies

#145 feat(query): without meter in config
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/server/router/router.go
  internal/server/server_test.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/clickhouse_connector/model.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
  internal/streaming/clickhouse_connector/sql/describe_meter_view.tpl.sql
  internal/streaming/connector.go
  internal/streaming/ksqldb_connector/connector.go
  internal/streaming/ksqldb_connector/meter.go
  internal/streaming/ksqldb_connector/meter_test.go
  internal/streaming/ksqldb_connector/query.go
  internal/streaming/ksqldb_connector/query_test.go
  internal/streaming/ksqldb_connector/sql/values.tpl.sql
  pkg/models/error.go
  pkg/models/meter.go
  pkg/models/meter_test.go
Labels: kind/feature, area/api, area/ingest, release-note/breaking-change, release-note/feature

#146 feat(router): optional group by in resp
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/server/router/router.go
  internal/server/server_test.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/connector.go
  internal/streaming/ksqldb_connector/connector.go
  pkg/models/meter.go
Labels: kind/feature, area/api, release-note/feature

#151 refactor(processor): clickhouse sql builder
  go.mod
  go.sum
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
  internal/streaming/clickhouse_connector/sql/create_events_table.tpl.sql
  internal/streaming/clickhouse_connector/sql/create_meter_view.tpl.sql
  internal/streaming/clickhouse_connector/sql/delete_meter_view.tpl.sql
  internal/streaming/clickhouse_connector/sql/describe_meter_view.tpl.sql
  internal/streaming/clickhouse_connector/sql/query_meter_view.tpl.sql
Labels: area/processor, kind/refactor

#155 fix(openapi): make fields required in meter values
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
Labels: area/api, release-note/bug-fix

#159 fix(processor): clickhouse query from and to
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
Labels: kind/bug, release-note/bug-fix

#162 feat(route): debug log query execution time
  internal/server/router/router.go
  internal/streaming/clickhouse_connector/connector.go
Labels: area/api, release-note/feature

#163 feat(router): remove execution time logging
  internal/server/router/router.go
Labels: area/api, release-note/feature

#167 refactor(client): node schema formatting
  api/client/node/README.md
  api/client/node/package-lock.json
  api/client/node/package.json
  api/client/node/schemas/openapi.ts
Labels: release-note/ignore, kind/refactor

#168 fix(openapi): return 204 status code for ingest
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/.npmignore
  api/client/node/clients/client.ts
  api/client/node/package.json
  api/openapi.yaml
  internal/ingest/httpingest/httpingest.go
  internal/ingest/httpingest/httpingest_test.go
Labels: area/api, release-note/feature

#169 fix(processor): date filters with clickhouse
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
Labels: kind/bug, release-note/bug-fix

#148 fix(backend): remove invalid default key from OpenAPI
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
Labels: area/api, release-note/bug-fix

#161 Refactor deduplication
  config.go
  internal/dedupe/dedupe.go
  internal/dedupe/memorydedupe/memorydedupe.go
  internal/dedupe/memorydedupe/memorydedupe_test.go
  internal/dedupe/redisdedupe/redisdedupe.go
  internal/ingest/dedupe.go
  internal/ingest/dedupe_test.go
  internal/ingest/ingest.go
  internal/ingest/inmemory.go
  internal/ingest/inmemory_test.go
  internal/ingest/memorydedupe/collector.go
  internal/ingest/memorydedupe/collector_test.go
  internal/ingest/redisdedupe/collector.go
  main.go
Labels: kind/refactor

#156 Get rid of unnecessary namespace model
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/server/router/router.go
  internal/server/server_test.go
  pkg/models/namespace.go
Labels: kind/refactor

#172 Refactor log config
  config.go
  main.go
Labels: kind/refactor

#176 feat(examples): add ingest-logs
  examples/ingest-logs/README.md
  examples/ingest-logs/docker-compose.yaml
  examples/ingest-logs/vector.yaml
Labels: release-note/misc

#175 feat(router): add error logging
  internal/server/router/router.go
  internal/server/server_test.go
  internal/streaming/clickhouse_connector/connector.go
  pkg/models/problem.go
Labels: area/api, release-note/ignore

#173 Refactor dedupe configuration
  config.go
  go.mod
  go.sum
  main.go
Labels: release-note/breaking-change, kind/refactor

#174 Basic otel trace support
  config.go
  go.mod
  go.sum
  main.go
Labels: kind/feature, area/api

#179 ci: add next build
  .github/workflows/artifacts.yaml
  .github/workflows/ci.yaml
Labels: release-note/ignore

#181 feat(clickhouse): allow empty valueProperty for count aggregation
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/server/router/router.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
Labels: area/api, area/processor, release-note/feature

#183 fix: redis expiration config parser
  config.go
Labels: kind/bug

#184 fix(dedupe): config default typo
  config.go
Labels: kind/bug, release-note/bug-fix

#171 fix(client): Node client auth
  .editorconfig
  api/client/node/.eslintrc.json
  api/client/node/.prettierrc.json
  api/client/node/README.md
  api/client/node/clients/client.ts
  api/client/node/clients/event.ts
  api/client/node/clients/meter.ts
  api/client/node/index.ts
  api/client/node/package-lock.json
  api/client/node/package.json
  api/client/node/pnpm-lock.yaml
  api/client/node/schemas/openapi.ts
  api/client/node/test/agent.ts
  api/client/node/test/api.test.ts
  api/client/node/test/mocks.ts
  api/client/node/tsconfig.json
  api/client/node/vitest.config.ts
Labels: area/api, release-note/bug-fix

#187 chore: update flake
  flake.lock
Labels: area/dependencies

#188 ci: run quickstart tests for ClickHouse
  .github/workflows/ci.yaml
  docker-compose.yaml
  quickstart/config.clickhouse.yaml
  quickstart/config.ksqldb.yaml
  quickstart/docker-compose.yaml
Labels: kind/refactor

#189 feat(kafka): send log messages to the standard logger
  config.go
  main.go
  pkg/kafka/kafka.go
  pkg/kafka/log.go
Labels: kind/feature

#194 Run pre-commit hooks in CI
  .github/workflows/ci.yaml
  flake.nix
Labels: kind/refactor

#186 ci: remove next from build targets
  .github/workflows/artifacts.yaml
  .github/workflows/ci.yaml
Labels: kind/refactor

#197 Redis TLS
  config.go
Labels: kind/feature, area/dedupe

#198 feat: instrument redis
  config.go
  go.mod
  go.sum
Labels: kind/feature, area/dedupe

#201 Upgrade Go to 1.21
  ci/magefile.go
  config.go
  flake.lock
  flake.nix
  go.mod
  go.sum
  internal/ingest/httpingest/httpingest.go
  internal/ingest/kafkaingest/collector.go
  internal/ingest/kafkaingest/namespace.go
  internal/server/logger.go
  internal/server/router/router.go
  internal/server/server.go
  internal/sink/kafka_connect.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/ksqldb_connector/connector.go
  internal/streaming/ksqldb_connector/meter.go
  main.go
  pkg/gosundheit/logger.go
  pkg/kafka/log.go
Labels: kind/refactor

#203 docs: add a community section to readme & an adopters.md
  ADOPTERS.md
  README.md
Labels: kind/documentation, release-note/ignore

#199 feat: simplify kafka setup
  .github/workflows/ci.yaml
  Dockerfile.kafka-connect
  docker-compose.yaml
  etc/kafka-connect/Dockerfile
  flake.nix
  quickstart/README.md
  quickstart/config.clickhouse.yaml
  quickstart/config.ksqldb.yaml
  quickstart/config.yaml
  quickstart/docker-compose.ci.yaml
  quickstart/docker-compose.yaml
Labels: kind/feature

#204 feat: propagate context in ingest collector
  internal/ingest/dedupe.go
  internal/ingest/dedupe_test.go
  internal/ingest/httpingest/httpingest.go
  internal/ingest/httpingest/httpingest_test.go
  internal/ingest/ingest.go
  internal/ingest/inmemory.go
  internal/ingest/inmemory_test.go
  internal/ingest/kafkaingest/collector.go
Labels: kind/feature, area/ingest

#206 refactor: move log configuration under telemetry
  config.go
  main.go
Labels: kind/refactor

#209 Relocate config
  config.go
  config/config.go
  config/config_test.go
  config/dedupe.go
  config/ingest.go
  config/namespace.go
  config/processor.go
  config/schema.go
  config/sink.go
  config/telemetry.go
  config/testdata/complete.yaml
  config/viper.go
  main.go
Labels: kind/refactor

#211 build: fix version propagation into the container
  .github/workflows/artifacts.yaml
  Dockerfile
Labels: kind/bug

#216 fix(config): clickhouse defaults
  .air.toml
  config/processor.go
Labels: kind/bug

#217 fix(config): sink clickhouse defaults
  config/sink.go
Labels: kind/bug, release-note/bug-fix

#218 feat!: drop ksqldb support
  .github/workflows/ci.yaml
  config/config.go
  config/config_test.go
  config/processor.go
  config/schema.go
  config/sink.go
  config/testdata/complete.yaml
  docker-compose.yaml
  go.mod
  go.sum
  internal/ingest/kafkaingest/serializer/event_key.json
  internal/ingest/kafkaingest/serializer/event_value.json
  internal/ingest/kafkaingest/serializer/json_schema.go
  internal/streaming/ksqldb_connector/connector.go
  internal/streaming/ksqldb_connector/meter.go
  internal/streaming/ksqldb_connector/meter_test.go
  internal/streaming/ksqldb_connector/namespace.go
  internal/streaming/ksqldb_connector/query.go
  internal/streaming/ksqldb_connector/query_test.go
  internal/streaming/ksqldb_connector/sql/README.md
  internal/streaming/ksqldb_connector/sql/delete_meter_table.tpl.sql
  internal/streaming/ksqldb_connector/sql/detected_events_stream.tpl.sql
  internal/streaming/ksqldb_connector/sql/detected_events_table.tpl.sql
  internal/streaming/ksqldb_connector/sql/events_connector_sink.sql
  internal/streaming/ksqldb_connector/sql/events_stream.tpl.sql
  internal/streaming/ksqldb_connector/sql/meter_connector_sink.sql
  internal/streaming/ksqldb_connector/sql/meter_table.tpl.sql
  internal/streaming/ksqldb_connector/sql/meter_table_describe.tpl.sql
  internal/streaming/ksqldb_connector/sql/values.tpl.sql
  internal/streaming/ksqldb_connector/util.go
  main.go
  pkg/gosundheit/ksqldbcheck/ksqldbcheck.go
  quickstart/README.md
  quickstart/config.clickhouse.yaml
  quickstart/config.ksqldb.yaml
  quickstart/config.yaml
  quickstart/docker-compose.yaml
Labels: release-note/breaking-change

#219 ci: add nix cache
  .github/workflows/ci.yaml
Labels: kind/refactor

#221 Meter query changes for the new query endpoint
  internal/server/router/router.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
  internal/streaming/connector.go
  pkg/slicesx/map.go
  pkg/slicesx/map_test.go
Labels: kind/feature

#220 feat: add new meter query endpoint to openapi spec
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/server/router/router.go
  internal/streaming/clickhouse_connector/connector.go
  pkg/models/meter.go
Labels: kind/feature, area/api

#224 New list meter subjects endpoint
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  docker-compose.yaml
  etc/kafka-connect/Dockerfile
  internal/server/router/router.go
  internal/server/server_test.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/connector.go
Labels: kind/feature, area/api, release-note/feature
