Repository openmeterio/openmeter, pull requests merged in 2023-11, with the labels that each got.

#377 chore: upgrade oapi-codegen to v2
  api/api.gen.go
  api/api.go
  api/client/go/client.gen.go
  api/client/go/client.go
  go.mod
  go.sum
  tools.go
Labels: area/dependencies

#380 feat(sink): call hook on successful flush
  internal/sink/sink.go
Labels: area/ingest, release-note/feature

#371 feat(api)!: remove stateful management APIs
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/ingest/httpingest/httpingest.go
  internal/ingest/httpingest/httpingest_test.go
  internal/server/router/router.go
  internal/server/server_test.go
Labels: area/api, release-note/breaking-change

#381 feat(api)!: remove aggregation from query api
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/server/router/router.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
  internal/streaming/connector.go
Labels: area/api, release-note/breaking-change

#389 Update dagger
  ci/dagger.json
  ci/go.mod
  ci/go.sum
  ci/main.go
  flake.lock
Labels: release-note/misc

#390 fix(api): fix meterIdOrSlug parameter schema
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  pkg/models/meter.go
Labels: area/api, release-note/bug-fix

#395 fix(streaming): query params validator and timezones
  internal/ingest/httpingest/httpingest.go
  internal/server/router/router.go
  internal/streaming/connector.go
  internal/streaming/query_params.go
  internal/streaming/query_params_test.go
Labels: kind/bug, area/api, release-note/bug-fix

#396 fix(meters): restricted slug name: events
  pkg/models/meter.go
Labels: area/api, release-note/bug-fix

#397 feat(api): add portal
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/README.md
  api/client/node/clients/portal.ts
  api/client/node/index.ts
  api/client/node/schemas/openapi.ts
  api/client/node/test/agent.ts
  api/client/node/test/api.test.ts
  api/openapi.yaml
  internal/server/router/portal.go
  internal/server/server_test.go
Labels: area/api, release-note/ignore

#400 chore(python): release 1.0.0-beta.19
  api/client/python/README.md
  api/client/python/pyproject.toml
Labels: area/api, release-note/ignore

#402 feat(client): improve go api
  api/client/go/README.md
  api/client/go/client.go
Labels: area/api, release-note/feature

#403 feat(clickhouse): use timezone for tumbling windows
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/server/router/router.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
  internal/streaming/query_params.go
  internal/streaming/query_params_test.go
Labels: area/api, area/processor, release-note/feature

#411 Automatically publish clients on new tag
  .github/workflows/generate-client-node.yaml
  .github/workflows/publish-client-node.yaml
  .github/workflows/publish-python-client.yaml
  api/client/node/package.json
  api/client/python/pyproject.toml
Labels: release-note/ignore

#410 feat(connector): single events table across namespaces
  cmd/server/main.go
  cmd/sink-worker/main.go
  config/aggregation.go
  internal/sink/sink.go
  internal/sink/storage.go
  internal/sink/storage_test.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
Labels: area/processor, release-note/breaking-change

#418 fix(connector): pass sql args to list events
  internal/streaming/clickhouse_connector/connector.go
Labels: area/api, release-note/bug-fix

#419 fix(streaming): namespace shadow
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
Labels: area/processor, release-note/bug-fix

#420 fix(sink): do not close consumer
  internal/sink/sink.go
Labels: area/ingest, release-note/bug-fix

#433 feat(ingest): allow optional group by
  examples/export-stripe-go/report.go
  internal/server/router/router.go
  internal/server/server_test.go
  internal/sink/namespaces.go
  internal/sink/namespaces_test.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/connector.go
  openmeter/streaming/connector.go
  pkg/models/meter.go
Labels: area/api, area/ingest, release-note/feature

#432 feat(event)!: store validation error in raw events table
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/server/router/event.go
  internal/server/router/router.go
  internal/server/server_test.go
  internal/sink/model.go
  internal/sink/namespaces.go
  internal/sink/namespaces_test.go
  internal/sink/sink.go
  internal/sink/storage.go
  internal/sink/storage_test.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
  internal/streaming/connector.go
Labels: area/api, area/ingest, release-note/breaking-change

#441 fix(route): validate query group by
  api/openapi.yaml
  internal/server/router/router.go
  internal/server/server_test.go
Labels: kind/bug, release-note/bug-fix

#447 feat(connector): filter by group by
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
  internal/streaming/query_params.go
Labels: area/processor, release-note/feature

#450 If total value is queried for a period, replace the window start and end with the period for each row
  internal/server/router/router.go
Labels: area/api, release-note/breaking-change

#453 refactor(router): separate files
  internal/server/router/meter.go
  internal/server/router/meter_query.go
  internal/server/router/meter_subject.go
  internal/server/router/router.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
  internal/streaming/query_params.go
Labels: release-note/ignore, kind/refactor

#454 Revert "chore(deps): bump github.com/getkin/kin-openapi from 0.120.0 to 0.121.0"
  go.mod
  go.sum
Labels: release-note/ignore

#446 Update event.ts
  api/client/node/clients/event.ts
Labels: area/api, release-note/bug-fix
