Repository openmeterio/openmeter, pull requests merged in 2023-09, with the labels that each got.

#225 feat(sink): handle invalid kafka connect message
  config/config_test.go
  config/sink.go
  internal/ingest/kafkaingest/collector.go
  internal/streaming/clickhouse_connector/connector.go
  main.go
Labels: kind/bug, area/ingest, release-note/bug-fix

#223 Add seeder
  Makefile
  docs/seeder.md
  etc/seed/seed.yaml
  flake.nix
Labels: kind/feature

#228 refactor: remove unnecessary enabled flag from clickhouse
  config/config_test.go
  config/processor.go
  config/testdata/complete.yaml
  main.go
Labels: kind/refactor

#229 Refactor kafka connect
  internal/sink/kafka_connect.go
  internal/streaming/clickhouse_connector/connector.go
  main.go
  pkg/kafkaconnect/Makefile
  pkg/kafkaconnect/client.gen.go
  pkg/kafkaconnect/client.go
  pkg/kafkaconnect/codegen.yaml
  pkg/kafkaconnect/openapi.yaml
Labels: kind/refactor

#233 chore: update flake
  ci/go.mod
  ci/go.sum
  ci/magefile.go
  flake.lock
Labels: kind/feature

#234 feat(api): node client beta6
  api/client/node/README.md
  api/client/node/clients/meter.ts
  api/client/node/package-lock.json
  api/client/node/package.json
  api/client/node/schemas/openapi.ts
  api/client/node/test/agent.ts
  api/client/node/test/api.test.ts
Labels: area/api, release-note/ignore

#238 Kafka connect refactor
  config/config_test.go
  config/dedupe.go
  config/sink.go
  config/testdata/complete.yaml
  internal/sink/kafka_connect.go
  main.go
  quickstart/config.yaml
Labels: kind/refactor

#249 feat: expose configuration
  config/config.go
  config/dedupe.go
  config/ingest.go
  config/namespace.go
  config/processor.go
Labels: kind/feature

#247 refactor: return a single query result struct
  internal/server/router/router.go
  internal/server/server_test.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/connector.go
Labels: kind/refactor

#246 refactor: remove unused template code
  internal/streaming/query.go
Labels: kind/refactor

#248 feat: add meter repository
  internal/meter/inmemory.go
  internal/meter/meter.go
  internal/streaming/clickhouse_connector/connector.go
  main.go
Labels: kind/feature

#244 feat(api): always include windowStart and windowEnd in query values
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/server/router/router.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
  pkg/models/meter.go
Labels: area/api, release-note/feature

#245 chore: update example config
  config.example.yaml
Labels: kind/refactor

#257 feat: rename processing to aggregation
  config/aggregation.go
  config/config.go
  config/config_test.go
  config/processor.go
  config/sink.go
  config/testdata/complete.yaml
  main.go
  quickstart/config.yaml
Labels: kind/feature

#258 feat: deprecate values endpoint
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/openapi.yaml
Labels: kind/feature, area/api

#260 feat(meter): query with accept csv support
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  go.mod
  go.sum
  internal/server/router/router.go
  internal/server/server_test.go
  quickstart/README.md
Labels: area/api, release-note/feature

#262 fix(processor): clickhouse materialized view type shadow
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
Labels: kind/bug, release-note/bug-fix

#263 feat: add otel trace details to logs
  go.mod
  go.sum
  main.go
Labels: kind/feature

#261 chore(client): update node client to 1.0.0-beta.8
  api/client/node/package-lock.json
  api/client/node/package.json
  api/client/node/schemas/openapi.ts
Labels: release-note/ignore

#265 feat: add otlp metrics support
  config/config_test.go
  config/telemetry.go
  config/testdata/complete.yaml
  go.mod
  go.sum
  main.go
Labels: kind/feature

#267 docs(decisions): adopting clickhouse
  docs/decisions/0005-clickhouse.md
Labels: kind/documentation, release-note/ignore

#264 fix(seed): seed random int generators
  etc/seed/seed.yaml
Labels: release-note/ignore
