Repository openmeterio/openmeter, pull requests merged in 2023-12, with the labels that each got.

#459 feat: update helm chart to latest version
  deploy/README.md
  deploy/charts/openmeter/.gitignore
  deploy/charts/openmeter/Chart.lock
  deploy/charts/openmeter/Chart.yaml
  deploy/charts/openmeter/templates/_helpers.tpl
  deploy/charts/openmeter/templates/clickhouse.yaml
  deploy/charts/openmeter/templates/configmap.yaml
  deploy/charts/openmeter/templates/deployment.yaml
  deploy/charts/openmeter/templates/hpa.yaml
  deploy/charts/openmeter/templates/ingress.yaml
  deploy/charts/openmeter/templates/kafka.yaml
  deploy/charts/openmeter/templates/service.yaml
  deploy/charts/openmeter/templates/serviceaccount.yaml
  deploy/charts/openmeter/values.example.yaml
  deploy/charts/openmeter/values.yaml
Labels: kind/feature

#473 Add meter query result API object
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/python/src/openmeter/__init__.py
  api/client/python/src/openmeter/_client.py
  api/client/python/src/openmeter/_configuration.py
  api/client/python/src/openmeter/_operations/__init__.py
  api/client/python/src/openmeter/_operations/_operations.py
  api/client/python/src/openmeter/_vendor.py
  api/client/python/src/openmeter/aio/__init__.py
  api/client/python/src/openmeter/aio/_client.py
  api/client/python/src/openmeter/aio/_configuration.py
  api/client/python/src/openmeter/aio/_operations/__init__.py
  api/client/python/src/openmeter/aio/_operations/_operations.py
  api/client/python/src/openmeter/aio/_vendor.py
  api/openapi.yaml
  go.mod
  go.sum
Labels: kind/feature, area/api

#477 chore: add wiretap to dev tools
  docker-compose.yaml
  etc/wiretap/config.docker.yaml
Labels: release-note/misc

#487 feat(namespace): delete
  internal/ingest/kafkaingest/namespace.go
  internal/namespace/namespace.go
  internal/namespace/namespace_test.go
  internal/streaming/clickhouse_connector/connector.go
Labels: area/ingest, area/processor, release-note/feature

#484 feat(api): portal token list
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/server/authenticator/portal.go
  internal/server/router/portal.go
  internal/server/server_test.go
Labels: area/api, release-note/feature

#488 ci: ignore cache errors
  .dockerignore
  .github/workflows/artifacts.yaml
Labels: kind/refactor

#481 docs: generate Helm chart docs from values file
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  ci/build.go
  ci/dagger.json
  ci/main.go
  deploy/charts/Makefile
  deploy/charts/README.tmpl.md
  deploy/charts/openmeter/.helmignore
  deploy/charts/openmeter/README.md
  deploy/charts/openmeter/values.yaml
  flake.nix
Labels: kind/documentation, area/distribution

#503 fix(server): kafka run group
  cmd/server/main.go
  docker-compose.yaml
Labels: kind/bug, release-note/bug-fix

#500 docs: openmeter helm chart
  ci/build.go
  deploy/README.md
  deploy/charts/Makefile
  deploy/charts/README.tmpl.md
  deploy/charts/openmeter/Chart.yaml
  deploy/charts/openmeter/README.md
  deploy/charts/openmeter/README.tmpl.md
  deploy/charts/template.md
Labels: kind/documentation

#508 Do not upload trivy results
  .github/workflows/artifacts.yaml
Labels: kind/bug
