Repository openmeterio/openmeter, pull requests merged in 2023-07, with the labels that each got.

#92 feat(example): list meters in fastify example
  examples/ingest-fastify-node/README.md
  examples/ingest-fastify-node/app.ts
  examples/ingest-fastify-node/package-lock.json
  examples/ingest-fastify-node/package.json
Labels: kind/feature

#95 docs(readme): add quickstart demo video
  README.md
Labels: kind/documentation

#99 feat(schema): improve json schemas
  internal/ingest/kafkaingest/schema/event_key.json
  internal/ingest/kafkaingest/schema/event_value.json
Labels: kind/feature

#101 fix(ingest): parse data
  internal/ingest/kafkaingest/schema.go
Labels: kind/bug

#97 feat(config): add auth support
  config.go
  deploy/charts/openmeter/templates/configmap.yaml
  main.go
  quickstart/config.yaml
Labels: kind/feature, area/ingest, area/processor, release-note/breaking-change

#103 Refactors
  config.go
  main.go
Labels: kind/refactor

#112 feat!: remove topic prefix from schema
  internal/ingest/kafkaingest/schema.go
  main.go
Labels: kind/feature, area/ingest, release-note/breaking-change

#120 feat(example): add query example to openai
  examples/ingest-openai-node/app.ts
  examples/ingest-openai-node/package-lock.json
  examples/ingest-openai-node/package.json
Labels: kind/documentation

#118 Kafka topic creation
  docker-compose.yaml
  internal/ingest/kafkaingest/kafkaingest.go
  internal/streaming/kafka_connector/connector.go
  internal/streaming/kafka_connector/query.go
  internal/streaming/kafka_connector/query_test.go
  internal/streaming/kafka_connector/sql/detected_events_table.tpl.sql
  internal/streaming/kafka_connector/sql/events_stream.tpl.sql
  main.go
Labels: kind/refactor

#116 Update OpenAPI
  README.md
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/.eslintrc.json
  api/client/node/README.md
  api/client/node/index.ts
  api/client/node/package-lock.json
  api/client/node/package.json
  api/client/node/test/api.test.ts
  api/client/node/tsconfig.json
  api/error.go
  api/openapi.yaml
  config.example.yaml
  deploy/charts/openmeter/values.yaml
  docs/event-ingestion.md
  examples/export-stripe-go/go.mod
  examples/export-stripe-go/go.sum
  examples/export-stripe-go/report.go
  examples/export-stripe-go/setup.go
  examples/export-stripe-node/app.ts
  examples/export-stripe-node/package-lock.json
  examples/export-stripe-node/package.json
  examples/export-stripe-node/setup.ts
  examples/ingest-fastify-node/README.md
  examples/ingest-fastify-node/app.ts
  examples/ingest-fastify-node/package-lock.json
  examples/ingest-fastify-node/package.json
  examples/ingest-kubernetes-pod-time-go/go.mod
  examples/ingest-kubernetes-pod-time-go/go.sum
  examples/ingest-openai-node/app.ts
  examples/ingest-openai-node/package-lock.json
  examples/ingest-openai-node/package.json
  go.mod
  go.sum
  internal/ingest/httpingest/httpingest.go
  internal/server/logger.go
  internal/server/router/router.go
  internal/server/server.go
  internal/server/server_test.go
  internal/streaming/kafka_connector/meter_test.go
  internal/streaming/kafka_connector/query_test.go
  internal/streaming/kafka_connector/sql/meter_table.tpl.sql
  internal/streaming/kafka_connector/sql/meter_table_describe.tpl.sql
  internal/streaming/kafka_connector/sql/values.tpl.sql
  pkg/models/meter.go
  pkg/models/meter_test.go
  pkg/models/problem.go
  quickstart/README.md
  quickstart/config.yaml
  quickstart/ingest.sh
  quickstart/verify.sh
Labels: kind/feature, area/api, release-note/breaking-change

#122 Add namespace support
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/.eslintrc.json
  api/client/node/README.md
  api/client/node/index.ts
  api/openapi.yaml
  internal/ingest/httpingest/httpingest.go
  internal/ingest/httpingest/httpingest_test.go
  internal/ingest/kafkaingest/kafkaingest.go
  internal/namespace/namespace.go
  internal/namespace/namespace_test.go
  internal/namespace/namespaceadapter/kafkaingest.go
  internal/server/router/router.go
  internal/server/server_test.go
  internal/streaming/connector.go
  internal/streaming/kafka_connector/connector.go
  internal/streaming/kafka_connector/meter.go
  internal/streaming/kafka_connector/meter_test.go
  internal/streaming/kafka_connector/namespace.go
  internal/streaming/kafka_connector/query.go
  internal/streaming/kafka_connector/query_test.go
  internal/streaming/kafka_connector/sql/detected_events_stream.tpl.sql
  internal/streaming/kafka_connector/sql/detected_events_table.tpl.sql
  internal/streaming/kafka_connector/sql/events_connector_sink.sql
  internal/streaming/kafka_connector/sql/events_stream.tpl.sql
  internal/streaming/kafka_connector/sql/meter_table.tpl.sql
  internal/streaming/kafka_connector/sql/meter_table_describe.tpl.sql
  internal/streaming/kafka_connector/sql/values.tpl.sql
  main.go
  pkg/models/namespace.go
  quickstart/README.md
Labels: kind/feature

#121 feat: namespace management
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/.eslintrc.json
  api/client/node/README.md
  api/client/node/index.ts
  api/openapi.yaml
  internal/ingest/httpingest/httpingest.go
  internal/ingest/httpingest/httpingest_test.go
  internal/ingest/kafkaingest/kafkaingest.go
  internal/namespace/namespace.go
  internal/namespace/namespace_test.go
  internal/namespace/namespaceadapter/kafkaingest.go
  internal/server/router/router.go
  internal/server/server_test.go
  internal/streaming/connector.go
  internal/streaming/kafka_connector/connector.go
  internal/streaming/kafka_connector/meter.go
  internal/streaming/kafka_connector/meter_test.go
  internal/streaming/kafka_connector/namespace.go
  internal/streaming/kafka_connector/query.go
  internal/streaming/kafka_connector/query_test.go
  internal/streaming/kafka_connector/sql/detected_events_stream.tpl.sql
  internal/streaming/kafka_connector/sql/detected_events_table.tpl.sql
  internal/streaming/kafka_connector/sql/events_connector_sink.sql
  internal/streaming/kafka_connector/sql/events_stream.tpl.sql
  internal/streaming/kafka_connector/sql/meter_table.tpl.sql
  internal/streaming/kafka_connector/sql/meter_table_describe.tpl.sql
  internal/streaming/kafka_connector/sql/values.tpl.sql
  main.go
  pkg/models/namespace.go
  quickstart/README.md
Labels: kind/feature

#125 Move API version to v1
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/test/api.test.ts
  api/openapi.yaml
  internal/server/server_test.go
  quickstart/README.md
  quickstart/ingest.sh
  quickstart/verify.sh
Labels: area/api, release-note/breaking-change

#124 Add ClickHouse streaming processor
  .air.toml
  .github/workflows/ci.yaml
  Dockerfile.kafka-connect
  Makefile
  config.go
  docker-compose.yaml
  go.mod
  go.sum
  internal/ingest/kafkaingest/serializer/event_value.json
  internal/ingest/kafkaingest/serializer/serializer.go
  internal/server/router/router.go
  internal/sink/kafka_connect.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
  internal/streaming/clickhouse_connector/sql/create_events_table.tpl.sql
  internal/streaming/clickhouse_connector/sql/create_meter_view.tpl.sql
  internal/streaming/clickhouse_connector/sql/query_meter_view.tpl.sql
  internal/streaming/ksqldb_connector/connector.go
  internal/streaming/ksqldb_connector/meter.go
  internal/streaming/ksqldb_connector/namespace.go
  internal/streaming/ksqldb_connector/query.go
  internal/streaming/ksqldb_connector/query_test.go
  internal/streaming/query.go
  main.go
  quickstart/README.md
  quickstart/docker-compose.yaml
Labels: kind/feature, area/processor
