Repository openmeterio/openmeter, pull requests merged in 2024-01, with the labels that each got.

#521 chore: update flake
  Makefile
  ci/dagger.json
  ci/go.mod
  ci/main.go
  flake.lock
Labels: area/dependencies

#523 chore: remove kube example
  examples/ingest-kubernetes-pod-time-go/Dockerfile
  examples/ingest-kubernetes-pod-time-go/README.md
  examples/ingest-kubernetes-pod-time-go/go.mod
  examples/ingest-kubernetes-pod-time-go/go.sum
  examples/ingest-kubernetes-pod-time-go/main.go
Labels: kind/refactor

#524 refactor(models/meter): remove redundant len check in `Validate`
  pkg/models/meter.go
Labels: kind/refactor

#525 ci: update CI modules
  .github/workflows/ci.yaml
  ci/build.go
  ci/dagger.json
  ci/main.go
  ci/utils.go
Labels: kind/refactor

#530 ci: fix dagger secret
  .github/workflows/release.yaml
Labels: kind/refactor

#534 feat(api): add subjects
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/server/router/subject.go
  internal/server/server_test.go
Labels: kind/feature, area/api, release-note/feature

#545 Upgrade Dagger
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  flake.lock
Labels: kind/refactor

#544 feat(api): add subject get and delete
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/clients/event.ts
  api/client/node/clients/portal.ts
  api/client/node/clients/subject.ts
  api/client/node/index.ts
  api/client/node/schemas/openapi.ts
  api/client/node/test/agent.ts
  api/client/node/test/api.test.ts
  api/client/node/test/mocks.ts
  api/openapi.yaml
  internal/server/router/subject.go
  internal/server/server_test.go
Labels: area/api, release-note/feature, dependency/javascript

#550 fix(clickhouse): fix query events implementation
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
Labels: kind/bug, release-note/bug-fix

#552 Add benthos collector
  .github/workflows/artifacts.yaml
  benthos-collector.Dockerfile
  ci/build.go
  ci/dagger.json
  ci/main.go
  cloudevents.spec.json
  cmd/benthos-collector/main.go
  deploy/charts/benthos-collector/.helmignore
  deploy/charts/benthos-collector/Chart.yaml
  deploy/charts/benthos-collector/README.md
  deploy/charts/benthos-collector/README.tmpl.md
  deploy/charts/benthos-collector/templates/_helpers.tpl
  deploy/charts/benthos-collector/templates/deployment.yaml
  deploy/charts/benthos-collector/templates/rbac.yaml
  deploy/charts/benthos-collector/templates/secret.yaml
  deploy/charts/benthos-collector/templates/serviceaccount.yaml
  deploy/charts/benthos-collector/values.yaml
  go.mod
  go.sum
Labels: kind/feature, area/collectors

#555 feat: add benthos collector presets
  benthos-collector.Dockerfile
  collector/benthos/presets/http-server/input.yaml
  collector/benthos/presets/http-server/output.yaml
  collector/benthos/presets/kubernetes-pod-exec-time/config.yaml
  deploy/charts/benthos-collector/templates/_helpers.tpl
Labels: kind/feature, area/collectors

#556 feat(collector/benthos): move plugins to this repo for now
  cmd/benthos-collector/main.go
  collector/benthos/input/kubernetes.go
  collector/benthos/input/schedule.go
  collector/benthos/output/openmeter.go
  go.mod
  go.sum
Labels: kind/feature, area/collectors

#558 CI improvements
  ci/build.go
  ci/dagger.json
  ci/e2e.go
  ci/go.mod
  ci/go.sum
  ci/lint.go
  ci/main.go
  ci/release.go
  ci/utils.go
Labels: kind/refactor

#559 chore: add release script
  .github/workflows/release.yaml
  flake.nix
  justfile
Labels: kind/refactor

#566 ci: fix benthos collector dockerfile
  .github/workflows/artifacts.yaml
  ci/build.go
  ci/release.go
Labels: kind/bug

#557 feat(sink): treat commit offset fatal
  internal/sink/sink.go
Labels: area/ingest, release-note/feature

#567 Collector examples
  .envrc
  .gitignore
  examples/collectors/.gitignore
  examples/collectors/README.md
  examples/collectors/database/.env.dist
  examples/collectors/database/README.md
  examples/collectors/database/config.yaml
  examples/collectors/database/docker-compose.common.yaml
  examples/collectors/database/docker-compose.yaml
  examples/collectors/database/seed/config.yaml
  examples/collectors/database/seed/init.clickhouse.sql
  examples/collectors/database/seed/init.postgres.sql
  examples/collectors/generate/README.md
  examples/collectors/generate/config.yaml
  examples/collectors/http-server/.env.dist
  examples/collectors/http-server/README.md
  examples/collectors/http-server/docker-compose.yaml
  examples/collectors/http-server/seed/batch.json
  examples/collectors/http-server/seed/config.yaml
  examples/collectors/http-server/seed/event.json
  examples/collectors/kubernetes-pod-exec-time/README.md
  examples/collectors/kubernetes-pod-exec-time/seed/pod.yaml
  flake.nix
Labels: kind/documentation

#568 feat(sink): kafka cooperative consumer
  cmd/sink-worker/main.go
  internal/sink/partition.go
  internal/sink/sink.go
Labels: area/ingest, release-note/feature

#570 feat(sink): ensure we only commit for assigned partitions
  internal/sink/offset.go
  internal/sink/offset_test.go
  internal/sink/sink.go
Labels: area/ingest, release-note/feature

#573 fix(sink): offset commit
  cmd/sink-worker/main.go
  e2e/config.yaml
  e2e/e2e_test.go
  internal/sink/buffer.go
  internal/sink/buffer_test.go
  internal/sink/offset.go
  internal/sink/offset_test.go
  internal/sink/sink.go
Labels: area/ingest, release-note/feature

#574 docs(readme): add web and python sdk links
  README.md
Labels: release-note/ignore

#572 feat(router): improve request logging
  internal/ingest/httpingest/httpingest.go
  internal/server/authenticator/authenticator.go
  internal/server/logger.go
  internal/server/router/event.go
  internal/server/router/meter.go
  internal/server/router/meter_query.go
  internal/server/router/meter_subject.go
  internal/server/router/portal.go
  internal/server/router/subject.go
  internal/server/server.go
  pkg/models/problem.go
Labels: area/api, release-note/feature
