Repository openmeterio/openmeter, pull requests merged in 2024-10, with the labels that each got.

#1603 chore(api): inline scalars without friendlyName
  api/spec/package.json
  api/spec/patches/@typespec__openapi.patch
  api/spec/pnpm-lock.yaml
  api/spec/src/types.tsp
Labels: area/api, release-note/ignore

#1604 fix: list features by multiple Ids or Keys
  openmeter/productcatalog/adapter/feature.go
Labels: kind/bug, area/api, release-note/bug-fix, area/entitlements

#1586 fix: typespec openapi diff in notifications
  api/spec/src/notification/channel.tsp
  api/spec/src/notification/rule.tsp
Labels: kind/bug

#1605 fix: typo in entitlements typespec
  api/spec/src/entitlements/entitlements.tsp
Labels: release-note/ignore

#1602 refactor: mk webhook event type register non-critical
  cmd/notification-service/main.go
  cmd/server/main.go
  config.example.yaml
  config/config_test.go
  config/notification.go
  openmeter/notification/webhook/svix.go
  openmeter/notification/webhook/webhook.go
  test/notification/testenv.go
  test/notification/webhook.go
Labels: release-note/misc

#1607 fix(streaming): alias meter query where
  openmeter/streaming/clickhouse_connector/query.go
  openmeter/streaming/clickhouse_connector/query_test.go
Labels: area/processor, release-note/bug-fix

#1609 fix: make id in subject a required-readOnly field
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  openmeter/event/models/subject.go
  openmeter/notification/consumer/balancetreshold.go
  openmeter/notification/internal/rule.go
  openmeter/server/server.go
  test/notification/event.go
Labels: kind/bug

#1608 Typespec fixes
  .dagger/generate.go
  api/spec/src/cloud/subjects.tsp
  api/spec/src/entitlements/entitlements.tsp
  api/spec/src/entitlements/feature.tsp
  api/spec/src/main.tsp
  api/spec/src/meters.tsp
  api/spec/src/notification/event.tsp
  api/spec/src/subjects.tsp
  api/spec/src/types.tsp
Labels: kind/refactor

#1561 Return all validation errors from configuration
  cmd/balance-worker/main.go
  cmd/notification-service/main.go
  cmd/server/main.go
  cmd/sink-worker/main.go
  config/aggregation.go
  config/balanceworker.go
  config/config.go
  config/dedupe.go
  config/events.go
  config/ingest.go
  config/kafka.go
  config/namespace.go
  config/notification.go
  config/portal.go
  config/postgres.go
  config/sink.go
  config/telemetry.go
  openmeter/notification/webhook/svix.go
  pkg/errorsx/errorsx.go
  pkg/errorsx/errorsx_test.go
Labels: kind/refactor

#1606 Use default returns for TX Repo helpers
  openmeter/entitlement/adapter/entitlement.go
  openmeter/entitlement/adapter/usage_reset.go
  pkg/framework/entutils/transaction.go
Labels: release-note/misc

#1615 fix: fix slice init length
  openmeter/dedupe/redisdedupe/redisdedupe.go
Labels: kind/bug, release-note/bug-fix

#1614 refactor: docker compose deployment
  docker-compose.yaml
  etc/postgres-init/svix.sql
  quickstart/config.yaml
  quickstart/docker-compose.ci.yaml
  quickstart/docker-compose.yaml
Labels: release-note/misc, kind/refactor

#1627 refactor: log list events validation error on warn level
  openmeter/server/router/event.go
  pkg/errorsx/errorsx.go
  pkg/errorsx/handler.go
Labels: release-note/misc

#1630 Adds edge cache & notification fixes
  openmeter/entitlement/adapter/entitlement.go
  openmeter/entitlement/balanceworker/cachehandler.go
  openmeter/entitlement/balanceworker/entitlementhandler.go
  openmeter/entitlement/balanceworker/worker.go
  openmeter/entitlement/edge/event.go
  openmeter/notification/consumer/balancetreshold.go
Labels: release-note/misc

#1632 Final TSP fixes
  .dagger/ci.go
  .github/workflows/ci.yaml
  .spectral.yaml
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/cloud/main.tsp
  api/spec/src/cloud/subjects.tsp
  api/spec/src/entitlements/entitlements.tsp
  api/spec/src/entitlements/feature.tsp
  api/spec/src/entitlements/grant.tsp
  api/spec/src/entitlements/subjects.tsp
  api/spec/src/events.tsp
  api/spec/src/main.tsp
  api/spec/src/meters.tsp
  api/spec/src/notification/channel.tsp
  api/spec/src/notification/event.tsp
  api/spec/src/notification/rule.tsp
  api/spec/src/portal.tsp
  api/spec/src/types.tsp
  e2e/e2e_test.go
  openmeter/credit/driver/grant.go
  openmeter/customer/httpdriver/customer.go
  openmeter/entitlement/driver/entitlement.go
  openmeter/entitlement/driver/metered.go
  openmeter/entitlement/driver/parser.go
  openmeter/notification/channel.go
  openmeter/notification/event.go
  openmeter/notification/httpdriver/channel.go
  openmeter/notification/httpdriver/event.go
  openmeter/notification/httpdriver/rule.go
  openmeter/notification/internal/rule.go
  openmeter/notification/rule.go
  openmeter/notification/service/channel.go
  openmeter/productcatalog/driver/feature.go
  openmeter/server/router/credit.go
  openmeter/server/router/entitlement.go
  openmeter/server/router/notification.go
  openmeter/server/router/product_catalog.go
  quickstart/docker-compose.yaml
  test/notification/channel.go
Labels: area/api, kind/refactor

#1633 Wire refactor
  .vscode/settings.json
  cmd/balance-worker/main.go
  cmd/balance-worker/wire.go
  cmd/balance-worker/wire_gen.go
  cmd/notification-service/main.go
  cmd/notification-service/wire.go
  cmd/notification-service/wire_gen.go
  cmd/server/main.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  cmd/sink-worker/main.go
  cmd/sink-worker/wire.go
  cmd/sink-worker/wire_gen.go
  go.mod
  go.sum
  openmeter/app/clickhouse.go
  openmeter/app/database.go
  openmeter/app/kafka.go
  openmeter/app/openmeter.go
  openmeter/app/telemetry.go
  openmeter/app/watermill.go
  openmeter/app/wire.go
  tools.go
Labels: kind/refactor

#1638 fix: exit if application initialization fails
  cmd/balance-worker/main.go
  cmd/notification-service/main.go
  cmd/server/main.go
  cmd/sink-worker/main.go
Labels: kind/bug

#1642 chore: expose telemetry config
  config/config.go
  config/telemetry.go
Labels: kind/refactor

#1600 feat: kafka topic provisoner
  cmd/balance-worker/main.go
  cmd/notification-service/.air.toml
  cmd/notification-service/main.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  cmd/sink-worker/main.go
  config.example.yaml
  config/config_test.go
  config/ingest.go
  config/testdata/complete.yaml
  openmeter/app/kafka.go
  openmeter/app/openmeter.go
  openmeter/app/watermill.go
  openmeter/app/wire.go
  openmeter/ingest/kafkaingest/namespace.go
  openmeter/watermill/driver/kafka/publisher.go
  openmeter/watermill/driver/kafka/topic_provision.go
  pkg/kafka/provisiontopic.go
  pkg/kafka/topicprovisioner.go
Labels: release-note/misc, kind/refactor

#1643 refactor: move config to a different wire set
  cmd/balance-worker/wire.go
  cmd/notification-service/wire.go
  cmd/server/wire.go
  cmd/sink-worker/wire.go
  cmd/sink-worker/wire_gen.go
  openmeter/app/wire.go
Labels: kind/refactor

#1644 fix: run pnpm install when necessary
  .dagger/main.go
Labels: release-note/ignore

#1646 fix(api): subject key is a string
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/cloud/subjects.tsp
  api/spec/src/subjects.tsp
Labels: area/api, release-note/ignore

#1648 add generate target to just
  justfile
Labels: kind/refactor

#1645 refactor: topic provisioner config
  cmd/balance-worker/main.go
  cmd/notification-service/main.go
  cmd/sink-worker/main.go
  config/config_test.go
  config/ingest.go
  config/testdata/complete.yaml
  config/topicprovisioner.go
  config/viper.go
  openmeter/app/kafka.go
Labels: release-note/misc

#1649 fix(api): stripeCustomerId to be nullable
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/cloud/subjects.tsp
  api/spec/src/subjects.tsp
Labels: area/api, release-note/bug-fix

#1651 fix(api): notification channel request
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/notification/channel.tsp
  api/spec/src/notification/rule.tsp
Labels: area/api, release-note/bug-fix

#1654 chore(deps): bump oapi-codegen to v2.4.1
  api/api.gen.go
  api/api.go
  go.mod
  go.sum
  tools.go
Labels: dependency/go, release-note/misc

#1655 fix: Go client gen
  api/client/go/client.go
Labels: release-note/ignore

#1653 Wire refactor round 2
  cmd/balance-worker/main.go
  cmd/balance-worker/wire.go
  cmd/balance-worker/wire_gen.go
  cmd/notification-service/main.go
  cmd/notification-service/wire.go
  cmd/notification-service/wire_gen.go
  cmd/server/main.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  cmd/sink-worker/main.go
  cmd/sink-worker/wire.go
  cmd/sink-worker/wire_gen.go
  openmeter/app/globals.go
  openmeter/app/kafka.go
  openmeter/app/telemetry.go
  openmeter/app/wire.go
Labels: kind/refactor

#1657 fix: use kafka configuration to create admin client
  cmd/balance-worker/wire_gen.go
  cmd/notification-service/wire_gen.go
  cmd/server/wire_gen.go
  cmd/sink-worker/wire_gen.go
  openmeter/app/kafka.go
Labels: kind/bug

#1656 build: update dagger
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .github/workflows/sdk-node.yaml
  .github/workflows/sdk-python.yaml
  .github/workflows/sdk-web.yaml
  .github/workflows/snapshot.yaml
  dagger.json
  flake.lock
Labels: area/dependencies

#1659 ci: try ci
  .github/workflows/ci.yaml
Labels: release-note/ignore

#1661 Try new runners
  .github/workflows/ci.yaml
Labels: release-note/ignore

#1662 refactor: otel initialization
  cmd/balance-worker/main.go
  cmd/balance-worker/wire.go
  cmd/balance-worker/wire_gen.go
  cmd/notification-service/main.go
  cmd/notification-service/wire.go
  cmd/notification-service/wire_gen.go
  cmd/server/main.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  cmd/sink-worker/main.go
  cmd/sink-worker/wire.go
  cmd/sink-worker/wire_gen.go
  openmeter/app/app.go
  openmeter/app/telemetry.go
  openmeter/app/watermill.go
  openmeter/app/wire.go
Labels: kind/refactor

#1664 ci: disable dagger cloud
  .github/workflows/ci.yaml
Labels: release-note/ignore

#1665 ci: enable dagger cloud
  .github/workflows/ci.yaml
Labels: release-note/ignore

#1666 ci: disable new runners
  .github/workflows/ci.yaml
Labels: release-note/ignore

#1660 Update kafka
  flake.nix
  go.mod
  go.sum
Labels: area/dependencies

#1667 Wire refactor round 3
  cmd/balance-worker/main.go
  cmd/balance-worker/wire.go
  cmd/balance-worker/wire_gen.go
  cmd/notification-service/main.go
  cmd/notification-service/wire.go
  cmd/notification-service/wire_gen.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  cmd/sink-worker/main.go
  cmd/sink-worker/wire.go
  cmd/sink-worker/wire_gen.go
  config/config_test.go
  config/telemetry.go
  openmeter/app/openmeter.go
  openmeter/app/openmeter_provisiontopics.go
  openmeter/app/telemetry.go
  openmeter/app/watermill.go
  openmeter/app/wire.go
Labels: release-note/ignore, kind/refactor

#1680 Relocate app packages
  app/common/app.go
  app/common/clickhouse.go
  app/common/database.go
  app/common/globals.go
  app/common/kafka.go
  app/common/openmeter.go
  app/common/openmeter_provisiontopics.go
  app/common/telemetry.go
  app/common/watermill.go
  app/common/wire.go
  app/config/aggregation.go
  app/config/balanceworker.go
  app/config/config.go
  app/config/config_test.go
  app/config/dedupe.go
  app/config/entitlements.go
  app/config/events.go
  app/config/helpers.go
  app/config/ingest.go
  app/config/ingest_test.go
  app/config/kafka.go
  app/config/namespace.go
  app/config/notification.go
  app/config/portal.go
  app/config/postgres.go
  app/config/sink.go
  app/config/svix.go
  app/config/telemetry.go
  app/config/testdata/complete.yaml
  app/config/topicprovisioner.go
  app/config/viper.go
  cmd/balance-worker/main.go
  cmd/balance-worker/wire.go
  cmd/balance-worker/wire_gen.go
  cmd/jobs/config/loader.go
  cmd/jobs/entitlement/init.go
  cmd/jobs/service/otel.go
  cmd/notification-service/main.go
  cmd/notification-service/wire.go
  cmd/notification-service/wire_gen.go
  cmd/server/main.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  cmd/sink-worker/main.go
  cmd/sink-worker/wire.go
  cmd/sink-worker/wire_gen.go
  openmeter/registry/startup/db.go
  openmeter/watermill/driver/kafka/broker.go
  openmeter/watermill/eventbus/eventbus.go
  openmeter/watermill/router/router.go
  openmeter/watermill/router/router_test.go
Labels: kind/refactor

#1682 refactor: add migrator to wire
  app/common/database.go
  app/common/wire.go
  cmd/balance-worker/main.go
  cmd/balance-worker/wire.go
  cmd/balance-worker/wire_gen.go
  cmd/notification-service/main.go
  cmd/notification-service/wire.go
  cmd/notification-service/wire_gen.go
  cmd/server/main.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  openmeter/registry/startup/db.go
Labels: release-note/ignore, kind/refactor

#1683 Finish wire refactor in balance worker
  app/common/app.go
  app/common/openmeter_balanceworker.go
  app/common/openmeter_provisiontopics.go
  app/common/wire.go
  cmd/balance-worker/main.go
  cmd/balance-worker/wire.go
  cmd/balance-worker/wire_gen.go
Labels: release-note/ignore, kind/refactor

#1689 fix(api): meter's valueProperty is not required when aggregation type is COUNT
  api/openapi.yaml
  api/spec/src/meters.tsp
Labels: release-note/ignore

#1691 chore: regenerate api
  api/api.gen.go
Labels: release-note/ignore

#1688 fix: mandate enum prefixes for generated APIs
  api/api.gen.go
  api/codegen.yaml
  api/openapi.yaml
  api/spec/src/app/app.tsp
  api/spec/src/app/stripe.tsp
  api/spec/src/entitlements/entitlements.tsp
  api/spec/src/notification/channel.tsp
  api/spec/src/notification/event.tsp
  api/spec/src/notification/rule.tsp
  api/spec/src/query.tsp
  openmeter/app/httpdriver/app.go
  openmeter/app/httpdriver/marketplace.go
  openmeter/entitlement/driver/parser.go
  openmeter/notification/channel.go
  openmeter/notification/consumer/balancethreshold_test.go
  openmeter/notification/consumer/balancetreshold.go
  openmeter/notification/event.go
  openmeter/notification/internal/rule.go
  openmeter/notification/rule.go
  test/notification/consumer_balance.go
Labels: release-note/misc, kind/refactor

#1617 Entitlement Scheduling Internals
  .editorconfig
  e2e/e2e_test.go
  openmeter/ent/db/entitlement.go
  openmeter/ent/db/entitlement/entitlement.go
  openmeter/ent/db/entitlement/where.go
  openmeter/ent/db/entitlement_create.go
  openmeter/ent/db/entitlement_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/entitlement.go
  openmeter/entitlement/adapter/entitlement.go
  openmeter/entitlement/balanceworker/cachehandler.go
  openmeter/entitlement/balanceworker/entitlementhandler.go
  openmeter/entitlement/balanceworker/worker.go
  openmeter/entitlement/boolean/connector.go
  openmeter/entitlement/connector.go
  openmeter/entitlement/driver/entitlement.go
  openmeter/entitlement/driver/parser.go
  openmeter/entitlement/edge/event.go
  openmeter/entitlement/entitlement.go
  openmeter/entitlement/entitlement_types.go
  openmeter/entitlement/errors.go
  openmeter/entitlement/metered/connector.go
  openmeter/entitlement/metered/entitlement_grant.go
  openmeter/entitlement/metered/reset.go
  openmeter/entitlement/repository.go
  openmeter/entitlement/scheduling.go
  openmeter/entitlement/scheduling_test.go
  openmeter/entitlement/static/connector.go
  openmeter/entitlement/uniqueness.go
  openmeter/entitlement/uniqueness_test.go
  openmeter/entitlement/utils_test.go
  openmeter/notification/consumer/balancetreshold.go
  pkg/clock/clock.go
  tools/migrate/migrations/20241017135535_entitlement_scheduling.down.sql
  tools/migrate/migrations/20241017135535_entitlement_scheduling.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/misc

#1693 chore(api): update typespec
  api/spec/package.json
  api/spec/patches/@typespec__http.patch
  api/spec/patches/@typespec__openapi.patch
  api/spec/patches/@typespec__openapi3.patch
  api/spec/pnpm-lock.yaml
Labels: release-note/ignore

#1695 refactor: align resource types in typespec and db
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/app/marketplace.tsp
  openmeter/app/adapter/app.go
  openmeter/app/adapter/marketplace.go
  openmeter/app/entity/app.go
  openmeter/app/entity/base/app.go
  openmeter/app/entity/marketplace.go
  openmeter/app/entity/registry.go
  openmeter/app/httpdriver/app.go
  openmeter/app/httpdriver/marketplace.go
  openmeter/app/stripe/adapter/factory.go
  openmeter/billing/adapter/profile.go
  openmeter/billing/profile.go
  openmeter/customer/adapter/customer.go
  openmeter/customer/adapter/entitymapping.go
  openmeter/customer/entity/customer.go
  openmeter/customer/httpdriver/apimapping.go
  openmeter/ent/db/app.go
  openmeter/ent/db/app/where.go
  openmeter/ent/db/app_create.go
  openmeter/ent/db/app_update.go
  openmeter/ent/db/billingprofile.go
  openmeter/ent/db/billingprofile/billingprofile.go
  openmeter/ent/db/billingprofile/where.go
  openmeter/ent/db/billingprofile_create.go
  openmeter/ent/db/billingprofile_update.go
  openmeter/ent/db/customer.go
  openmeter/ent/db/customer/customer.go
  openmeter/ent/db/customer/where.go
  openmeter/ent/db/customer_create.go
  openmeter/ent/db/customer_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/app.go
  openmeter/ent/schema/customer.go
  pkg/framework/entutils/mixins.go
  pkg/models/model.go
  test/app/stripe/appstripe.go
  test/billing/customeroverride_test.go
  test/billing/invoice_test.go
  test/billing/profile_test.go
  test/customer/customer.go
  tools/migrate/migrations/20241017090045_unify-resource-def.down.sql
  tools/migrate/migrations/20241017090045_unify-resource-def.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/ignore

#1641 feat: invoicing api
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/billing.tsp
  api/spec/src/billing/customeroverride.tsp
  api/spec/src/billing/invoices.tsp
  api/spec/src/billing/invoices/README.md
  api/spec/src/billing/invoices/docref.tsp
  api/spec/src/billing/invoices/invoice.tsp
  api/spec/src/billing/invoices/main.tsp
  api/spec/src/billing/invoices/org.tsp
  api/spec/src/billing/invoices/pay.tsp
  api/spec/src/billing/invoices/tax.tsp
  api/spec/src/billing/main.tsp
  api/spec/src/billing/profile.tsp
  api/spec/src/billing/tax.tsp
  api/spec/src/cloud/main.tsp
  api/spec/src/customer.tsp
  api/spec/src/main.tsp
  api/spec/src/ratecards.tsp
  api/spec/src/types.tsp
  openmeter/billing/invoice.go
  openmeter/server/router/billing.go
Labels: release-note/feature, area/billing

#1698 Fixes entitlement creation
  openmeter/entitlement/adapter/entitlement.go
Labels: release-note/bug-fix

#1699 feat(sink): extends poll config
  app/config/config_test.go
  app/config/sink.go
  cmd/sink-worker/main.go
  openmeter/sink/sink.go
  pkg/kafka/config.go
Labels: release-note/feature, area/sink-worker

#1700 feat(sink): config validation
  openmeter/sink/sink.go
Labels: kind/feature, release-note/feature, area/sink-worker

#1701 feat(sink): make async insert configurable
  app/config/config_test.go
  app/config/sink.go
  cmd/sink-worker/main.go
  openmeter/sink/storage.go
Labels: kind/feature, area/sink-worker

#1704 fix(storage): async insert
  openmeter/sink/storage.go
Labels: kind/bug, area/sink-worker

#1705 fix(sink): remove max poll records config
  pkg/kafka/config.go
Labels: kind/bug, release-note/bug-fix, area/sink-worker

#1686 feat: add Plan API to typespec
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/billing/invoices/invoice.tsp
  api/spec/src/billing/invoices/main.tsp
  api/spec/src/cloud/main.tsp
  api/spec/src/discounts.tsp
  api/spec/src/main.tsp
  api/spec/src/productcatalog/discounts.tsp
  api/spec/src/productcatalog/main.tsp
  api/spec/src/productcatalog/plan.tsp
  api/spec/src/productcatalog/prices.tsp
  api/spec/src/productcatalog/ratecards.tsp
  api/spec/src/productcatalog/routes.tsp
  api/spec/src/types.tsp
  openmeter/server/router/plan.go
Labels: area/api, release-note/feature

#1707 chore(api): update typespec prettier config
  api/spec/.prettierrc.json
  api/spec/lib/rules/casing.js
  api/spec/lib/rules/docs.js
  api/spec/lib/rules/friendlyName.js
  api/spec/src/app/marketplace.tsp
  api/spec/src/app/stripe.tsp
  api/spec/src/billing/invoices.tsp
  api/spec/src/billing/profile.tsp
  api/spec/src/cloud/main.tsp
  api/spec/src/cloud/subjects.tsp
  api/spec/src/customer.tsp
  api/spec/src/entitlements/entitlements.tsp
  api/spec/src/entitlements/feature.tsp
  api/spec/src/entitlements/subjects.tsp
  api/spec/src/events.tsp
  api/spec/src/meters.tsp
  api/spec/src/notification/channel.tsp
  api/spec/src/notification/event.tsp
  api/spec/src/notification/rule.tsp
  api/spec/src/portal.tsp
  api/spec/src/productcatalog/ratecards.tsp
  api/spec/src/productcatalog/routes.tsp
  api/spec/src/types.tsp
Labels: release-note/ignore

#1708 feat(sink): query settings
  app/config/sink.go
  cmd/sink-worker/main.go
  openmeter/sink/storage.go
Labels: release-note/feature, area/sink-worker

#1709 Fix OpenAPI types
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/cloud/subjects.tsp
  api/spec/src/notification/event.tsp
  api/spec/src/notification/rule.tsp
Labels: release-note/ignore

#1711 fix(api): typespec types
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/cloud/main.tsp
  api/spec/src/entitlements/subjects.tsp
  api/spec/src/events.tsp
Labels: release-note/ignore

#1713 fix(api): add go-type annotations to create meter body type
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/cloud/main.tsp
Labels: release-note/ignore

#1715 fix(api): make subject display name nullable
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/subjects.tsp
Labels: release-note/ignore

#1717 fix(api): property typo
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/productcatalog/ratecards.tsp
Labels: release-note/ignore

#1719 chore: update otelslog
  app/common/telemetry.go
  cmd/jobs/service/otel.go
  cmd/sink-worker/wire.go
  cmd/sink-worker/wire_gen.go
  go.mod
  go.sum
Labels: area/dependencies

#1728 refactor: Kafka config defaults
  app/config/kafka.go
Labels: kind/refactor

#1733 Generate Go SDK from new OpenAPI
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  api/spec/src/app/app.tsp
  api/spec/src/app/stripe.tsp
  api/spec/src/entitlements/entitlements.tsp
  api/spec/src/entitlements/feature.tsp
  api/spec/src/entitlements/grant.tsp
  api/spec/src/errors.tsp
  e2e/e2e_test.go
  justfile
  openmeter/app/httpdriver/marketplace.go
  openmeter/app/stripe/httpdriver/checkout_session.go
  openmeter/entitlement/driver/metered.go
  openmeter/server/router/marketplace.go
Labels: kind/bug, area/api

#1731 feat(ingest): adopt topic provisioner
  app/common/openmeter.go
  cmd/server/wire_gen.go
  openmeter/ingest/kafkaingest/collector.go
Labels: area/ingest, release-note/misc

#1729 refactor(sink): namespace and topic subscription update
  app/config/config_test.go
  app/config/sink.go
  app/config/testdata/complete.yaml
  cmd/sink-worker/main.go
  e2e/config.yaml
  openmeter/ingest/kafkaingest/collector.go
  openmeter/sink/sink.go
  quickstart/config.yaml
Labels: release-note/misc, area/sink-worker

#1734 refactor: kafka config
  app/config/config_test.go
  app/config/kafka.go
  app/config/testdata/complete.yaml
  config.example.yaml
  pkg/kafka/config.go
  pkg/kafka/config_test.go
Labels: release-note/misc, kind/refactor

#1736 Drop separate logger initialization
  app/common/telemetry.go
  app/common/wire.go
  cmd/balance-worker/main.go
  cmd/balance-worker/wire.go
  cmd/balance-worker/wire_gen.go
  cmd/notification-service/main.go
  cmd/notification-service/wire.go
  cmd/notification-service/wire_gen.go
  cmd/server/main.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  cmd/sink-worker/main.go
  cmd/sink-worker/wire.go
  cmd/sink-worker/wire_gen.go
Labels: kind/refactor

#1737 fix(sink): no topic to subscibe warning
  openmeter/sink/sink.go
Labels: release-note/ignore

#1740 refactor(kafka): topic provisioning
  app/common/kafka.go
  app/common/openmeter.go
  app/config/config_test.go
  app/config/ingest.go
  app/config/testdata/complete.yaml
  app/config/topicprovisioner.go
  cmd/server/wire_gen.go
  openmeter/ingest/kafkaingest/namespace.go
  pkg/kafka/topicprovisioner.go
  pkg/kafka/topicprovisioner_test.go
Labels: release-note/misc, kind/refactor

#1742 refactor: fix circular dependency
  app/common/watermill.go
  app/config/events.go
  cmd/jobs/entitlement/init.go
  openmeter/testutils/logger.go
  openmeter/watermill/eventbus/eventbus.go
  pkg/kafka/topicprovisioner_test.go
Labels: release-note/ignore, kind/refactor

#1743 refactor: Plan API typespec
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  api/spec/src/cloud/main.tsp
  api/spec/src/productcatalog/discounts.tsp
  api/spec/src/productcatalog/prices.tsp
  api/spec/src/productcatalog/ratecards.tsp
  api/spec/src/productcatalog/routes.tsp
Labels: area/api, release-note/misc, kind/refactor

#1745 refactor(api): mv TaxConfig to ProductCatalog
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  api/spec/src/billing/invoices/tax.tsp
  api/spec/src/billing/main.tsp
  api/spec/src/billing/tax.tsp
  api/spec/src/productcatalog/main.tsp
  api/spec/src/productcatalog/ratecards.tsp
  api/spec/src/productcatalog/tax.tsp
Labels: area/api, release-note/misc, kind/refactor

#1739 Use transacting repos for customer package
  openmeter/app/adapter/adapter.go
  openmeter/app/adapter/app.go
  openmeter/app/stripe/adapter/adapter.go
  openmeter/app/stripe/adapter/customer.go
  openmeter/app/stripe/adapter/stripe.go
  openmeter/customer/adapter/adapter.go
  openmeter/customer/adapter/app.go
  openmeter/customer/adapter/customer.go
Labels: release-note/misc

#1746 feat(api): remove key from customer paths
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/customer.tsp
  openmeter/customer/httpdriver/customer.go
  openmeter/server/router/customer.go
Labels: area/api, release-note/feature

#1730 feat: add otel log support
  app/common/telemetry.go
  app/common/wire.go
  app/config/telemetry.go
  cmd/balance-worker/wire_gen.go
  cmd/notification-service/wire_gen.go
  cmd/server/wire_gen.go
  cmd/sink-worker/wire_gen.go
  go.mod
  go.sum
Labels: kind/feature

#1748 feat(compose): add ch-ui
  README.md
  docker-compose.yaml
Labels: release-note/feature

#1751 refactor(ingest): prefix metrics with openmeter
  openmeter/ingest/ingestadapter/metrics.go
Labels: area/ingest, kind/refactor

#1752 Update dagger
  .dagger/go.mod
  .dagger/go.sum
  .github/workflows/ci-exp.yaml
  .github/workflows/ci.yaml
  .github/workflows/sdk-node.yaml
  .github/workflows/sdk-python.yaml
  .github/workflows/sdk-web.yaml
  .github/workflows/snapshot.yaml
  dagger.json
  flake.lock
Labels: release-note/ignore

#1765 fix(api): paginated responses
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/app/app.tsp
  api/spec/src/customer.tsp
Labels: area/api, release-note/ignore

#1764 feat(secret): add app id and key to secret id
  openmeter/app/stripe/adapter/stripe.go
  openmeter/app/stripe/entity/app/app.go
  openmeter/secret/adapter/secret.go
  openmeter/secret/entity/secret.go
Labels: release-note/feature

#1763 feat: create invoice backend logic
  openmeter/billing/adapter.go
  openmeter/billing/adapter/customeroverride.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/customeroverride.go
  openmeter/billing/entity/invoice.go
  openmeter/billing/errors.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/invoice.go
  openmeter/billing/invoiceline.go
  openmeter/billing/service.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/service/service.go
  test/billing/invoice_test.go
Labels: release-note/misc, area/billing

#1767 fix: treat inactive entitlement as deleted
  openmeter/entitlement/balanceworker/recalculate.go
Labels: release-note/bug-fix, area/entitlements, area/notification

#1768 feat: add invoice workflow management API changes
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/billing/invoices.tsp
  api/spec/src/billing/invoices/invoice.tsp
  openmeter/server/router/billing.go
Labels: release-note/misc

#1769 feat: validation issue models
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/billing/invoices/invoice.tsp
Labels: release-note/ignore, area/billing

#1766 feat: invoice lifecycle
  go.mod
  go.sum
  openmeter/billing/adapter.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/profile.go
  openmeter/billing/entity/invoice.go
  openmeter/billing/entity/invoicecalc.go
  openmeter/billing/entity/profile.go
  openmeter/billing/errors.go
  openmeter/billing/httpdriver/defaults.go
  openmeter/billing/httpdriver/errors.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/httpdriver/profile.go
  openmeter/billing/invoice.go
  openmeter/billing/profile.go
  openmeter/billing/service.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/service/invoicestate.go
  openmeter/billing/service/profile.go
  openmeter/ent/db/billinginvoice.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/billinginvoice/where.go
  openmeter/ent/db/billinginvoice_create.go
  openmeter/ent/db/billinginvoice_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  test/billing/customeroverride_test.go
  test/billing/invoice_test.go
  test/billing/profile_test.go
  tools/migrate/migrations/20241030140919_billing-draft-until.down.sql
  tools/migrate/migrations/20241030140919_billing-draft-until.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/billing

#1770 Update client dependencies
  api/client/node/package.json
  api/client/node/pnpm-lock.yaml
  api/client/web/package.json
  api/client/web/pnpm-lock.yaml
  api/client/web/src/client/index.ts
Labels: release-note/dependency-update

#1774 test(recurrance): fix flaky
  pkg/recurrence/recurrence_test.go
Labels: release-note/ignore

#1773 fix(telemetry): filter otel logs by log level
  app/common/telemetry.go
  app/common/telemetry_test.go
Labels: area/dependencies, release-note/bug-fix
