Repository openmeterio/openmeter, pull requests merged in 2024-04, with the labels that each got.

#745 chore(api): update Node client dependencies
  .github/workflows/generate-client-node.yaml
  api/client/node/package.json
  api/client/node/pnpm-lock.yaml
  api/client/node/test/api.test.ts
Labels: area/api, release-note/misc

#750 fix(ci): Node client test
  .github/workflows/generate-client-node.yaml
Labels: release-note/ignore

#751 chore(github): update dependabot
  .github/dependabot.yaml
Labels: release-note/ignore

#791 feat(meter): add unique count aggregation
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/sink/namespaces.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
  pkg/models/meter.go
  pkg/models/meter_test.go
Labels: area/api, release-note/feature

#798 refactor(query): move window size setter to connector
  internal/server/router/meter_query.go
  internal/streaming/clickhouse_connector/connector.go
Labels: area/processor, release-note/ignore

#811 chore: update OTEL deps
  go.mod
  go.sum
Labels: area/dependencies, dependency/go

#810 chore: remove unnecessary labels
  .github/dependabot.yaml
Labels: release-note/misc

#819 chore: update dagger
  ci/.gitattributes
  ci/.gitignore
  ci/go.mod
  ci/go.sum
  dagger.json
  flake.lock
Labels: release-note/ignore

#823 chore: upgrade dagger in GHA
  .github/workflows/ci.yaml
Labels: release-note/ignore

#829 fix(client): Node client dual module and commonjs build
  api/client/node/.eslintrc.json
  api/client/node/.npmignore
  api/client/node/package.json
  api/client/node/pnpm-lock.yaml
  api/client/node/rollup.config.js
  api/client/node/tsconfig.json
Labels: release-note/bug-fix

#831 chore: tweak dependabot config
  .github/dependabot.yaml
Labels: release-note/ignore

#837 chore: update net package in dagger
  ci/go.mod
  ci/go.sum
Labels: area/dependencies, dependency/go

#838 chore: update k8s deps
  .github/dependabot.yaml
  go.mod
  go.sum
Labels: area/dependencies, dependency/go
