Repository openmeterio/openmeter, pull requests merged in 2024-11, with the labels that each got.

#1776 fix(telemetry): fix level filter
  app/common/telemetry.go
  app/common/telemetry_test.go
Labels: release-note/ignore

#1775 feat(telemetry): log exporter stdout
  app/config/telemetry.go
  go.mod
  go.sum
Labels: release-note/ignore

#1777 feat(kafka): reduce verbosity of kafka logs
  pkg/kafka/log.go
Labels: area/processor, release-note/feature

#1778 feat(customer): add filters
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/customer.tsp
  api/spec/src/query.tsp
  openmeter/customer/adapter/customer.go
  openmeter/customer/entity/customer.go
  openmeter/customer/httpdriver/customer.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/schema/customer.go
  test/customer/customer.go
  tools/migrate/migrations/20241102151321_customer_filters.down.sql
  tools/migrate/migrations/20241102151321_customer_filters.up.sql
  tools/migrate/migrations/atlas.sum
Labels: area/api, release-note/feature

#1772 feat: validation errors api
  openmeter/app/sandbox/app.go
  openmeter/app/sandbox/mock.go
  openmeter/billing/adapter/customeroverride.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/profile.go
  openmeter/billing/adapter/validationissue.go
  openmeter/billing/entity/app.go
  openmeter/billing/entity/errors.go
  openmeter/billing/entity/invoice.go
  openmeter/billing/entity/invoicecalc.go
  openmeter/billing/entity/validationissue.go
  openmeter/billing/entity/validationissue_test.go
  openmeter/billing/errors.go
  openmeter/billing/httpdriver/errors.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/invoice.go
  openmeter/billing/service.go
  openmeter/billing/service/customeroverride.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoicecalc.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/service/invoicestate.go
  openmeter/billing/service/profile.go
  openmeter/billing/service/service.go
  openmeter/ent/db/billinginvoice.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/billinginvoice/where.go
  openmeter/ent/db/billinginvoice_create.go
  openmeter/ent/db/billinginvoice_query.go
  openmeter/ent/db/billinginvoice_update.go
  openmeter/ent/db/billinginvoicevalidationissue.go
  openmeter/ent/db/billinginvoicevalidationissue/billinginvoicevalidationissue.go
  openmeter/ent/db/billinginvoicevalidationissue/where.go
  openmeter/ent/db/billinginvoicevalidationissue_create.go
  openmeter/ent/db/billinginvoicevalidationissue_delete.go
  openmeter/ent/db/billinginvoicevalidationissue_query.go
  openmeter/ent/db/billinginvoicevalidationissue_update.go
  openmeter/ent/db/client.go
  openmeter/ent/db/ent.go
  openmeter/ent/db/expose.go
  openmeter/ent/db/hook/hook.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/paginate.go
  openmeter/ent/db/predicate/predicate.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/db/tx.go
  openmeter/ent/schema/billing.go
  openmeter/entitlement/driver/errors.go
  pkg/framework/commonhttp/errors.go
  pkg/gobl/convert.go
  pkg/gobl/validation/error.go
  test/billing/customeroverride_test.go
  test/billing/invoice_test.go
  test/billing/profile_test.go
  test/billing/suite_test.go
  tools/migrate/migrations/20241103150058_billing-validation-issues.down.sql
  tools/migrate/migrations/20241103150058_billing-validation-issues.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/billing

#1789 Fix: typespec API
  .dagger/generate.go
  Makefile
  api/api.gen.go
  api/openapi.yaml
  api/spec/lib/rules/casing.js
  api/spec/lib/rules/friendlyName.js
  api/spec/src/app/oauth.tsp
  api/spec/src/app/stripe.tsp
  api/spec/src/cloud/main.tsp
  api/spec/src/portal.tsp
  api/spec/src/productcatalog/subscription.tsp
  api/spec/src/types.tsp
  api/spec/tspconfig.yaml
  openmeter/server/router/meter.go
  openmeter/server/router/subject.go
  openmeter/server/server_test.go
Labels: release-note/ignore

#1791 fix(api): generic instead of extend
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/billing/invoices/pay.tsp
Labels: release-note/ignore

#1790 fix(client): generate node client
  api/client/node/clients/client.ts
  api/client/node/clients/entitlement.ts
  api/client/node/clients/event.ts
  api/client/node/clients/notifications.ts
  api/client/node/pnpm-lock.yaml
  api/client/node/schemas/openapi.ts
  api/client/node/test/mocks.ts
Labels: release-note/ignore

#1792 chore(api): update node & web dependencies
  api/client/node/package.json
  api/client/node/pnpm-lock.yaml
  api/client/web/package.json
  api/client/web/pnpm-lock.yaml
Labels: release-note/dependency-update

#1793 feat(client): go generate
  .dagger/generate.go
  Makefile
  api/client/go/client.gen.go
  api/client/go/client.go
  api/client/go/client_test.go
  api/client/node/package.json
  api/client/node/schemas/openapi.ts
  api/openapi.cloud.yaml
Labels: release-note/ignore

#1795 chore(python): disable client gen action
  .github/workflows/sdk-python.yaml
Labels: release-note/ignore

#1796 feat(client): update web client & add new linter to typespec
  Makefile
  api/client/go/client.gen.go
  api/client/web/.eslintignore
  api/client/web/.eslintrc.json
  api/client/web/eslint.config.mjs
  api/client/web/package.json
  api/client/web/pnpm-lock.yaml
  api/client/web/src/client/openapi.ts
  api/client/web/test/react.test.tsx
  api/openapi.cloud.yaml
  api/spec/lib/index.js
  api/spec/lib/rules/discriminatedUnions.js
  api/spec/src/billing/customeroverride.tsp
  api/spec/src/billing/profile.tsp
  api/spec/src/notification/event.tsp
  api/spec/src/productcatalog/plan.tsp
  api/spec/src/productcatalog/ratecards.tsp
  api/spec/src/productcatalog/subscription.tsp
Labels: release-note/ignore

#1797 refactor(api): Plan API
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  api/spec/src/productcatalog/discounts.tsp
  api/spec/src/productcatalog/plan.tsp
  api/spec/src/productcatalog/prices.tsp
  api/spec/src/productcatalog/ratecards.tsp
  api/spec/src/productcatalog/routes.tsp
  api/spec/src/productcatalog/subscription.tsp
  openmeter/server/router/plan.go
Labels: area/api, release-note/misc, kind/refactor

#1800 Fix env parsing for POISTGRES_URL
  app/config/postgres.go
Labels: release-note/misc

#1801 feat: add initial version of Plan API implementation
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/productcatalog/routes.tsp
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/schema/productcatalog.go
  openmeter/productcatalog/plan/adapter/adapter.go
  openmeter/productcatalog/plan/adapter/adapter_test.go
  openmeter/productcatalog/plan/adapter/mapping.go
  openmeter/productcatalog/plan/adapter/phase.go
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/assert.go
  openmeter/productcatalog/plan/errors.go
  openmeter/productcatalog/plan/httpdriver/driver.go
  openmeter/productcatalog/plan/httpdriver/errors.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/plan/httpdriver/phase.go
  openmeter/productcatalog/plan/httpdriver/plan.go
  openmeter/productcatalog/plan/service.go
  openmeter/productcatalog/plan/service/phase.go
  openmeter/productcatalog/plan/service/plan.go
  openmeter/productcatalog/plan/service/service.go
  openmeter/server/router/plan.go
  pkg/datex/date.go
  tools/migrate/migrations/20241108055754_plan.down.sql
  tools/migrate/migrations/20241108055754_plan.up.sql
  tools/migrate/migrations/atlas.sum
Labels: area/api, release-note/feature, area/product-catalog

#1787 feat: support usage based pricing
  cmd/server/main.go
  openmeter/billing/README.md
  openmeter/billing/adapter.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/entity/defaults.go
  openmeter/billing/entity/errors.go
  openmeter/billing/entity/invoice.go
  openmeter/billing/entity/invoiceline.go
  openmeter/billing/entity/tax.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/invoiceline.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/service/invoicestate.go
  openmeter/billing/service/lineservice/doc.go
  openmeter/billing/service/lineservice/linebase.go
  openmeter/billing/service/lineservice/manualfeeline.go
  openmeter/billing/service/lineservice/manualusagebasedline.go
  openmeter/billing/service/lineservice/meters.go
  openmeter/billing/service/lineservice/service.go
  openmeter/billing/service/service.go
  openmeter/ent/db/billinginvoice.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/billinginvoice_create.go
  openmeter/ent/db/billinginvoice_update.go
  openmeter/ent/db/billinginvoiceline.go
  openmeter/ent/db/billinginvoiceline/billinginvoiceline.go
  openmeter/ent/db/billinginvoiceline/where.go
  openmeter/ent/db/billinginvoiceline_create.go
  openmeter/ent/db/billinginvoiceline_query.go
  openmeter/ent/db/billinginvoiceline_update.go
  openmeter/ent/db/billinginvoicemanualusagebasedlineconfig.go
  openmeter/ent/db/billinginvoicemanualusagebasedlineconfig/billinginvoicemanualusagebasedlineconfig.go
  openmeter/ent/db/billinginvoicemanualusagebasedlineconfig/where.go
  openmeter/ent/db/billinginvoicemanualusagebasedlineconfig_create.go
  openmeter/ent/db/billinginvoicemanualusagebasedlineconfig_delete.go
  openmeter/ent/db/billinginvoicemanualusagebasedlineconfig_query.go
  openmeter/ent/db/billinginvoicemanualusagebasedlineconfig_update.go
  openmeter/ent/db/client.go
  openmeter/ent/db/ent.go
  openmeter/ent/db/expose.go
  openmeter/ent/db/hook/hook.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/paginate.go
  openmeter/ent/db/predicate/predicate.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/db/tx.go
  openmeter/ent/schema/billing.go
  openmeter/meter/inmemory.go
  openmeter/streaming/testutils/streaming.go
  pkg/slicesx/map.go
  test/billing/invoice_test.go
  test/billing/suite_test.go
  tools/migrate/migrations/20241108120252_billing-line-splitting.down.sql
  tools/migrate/migrations/20241108120252_billing-line-splitting.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/billing

#1806 chore: disable dagger cloud
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .github/workflows/sdk-node.yaml
  .github/workflows/sdk-python.yaml
  .github/workflows/sdk-web.yaml
  .github/workflows/snapshot.yaml
  Makefile
Labels: release-note/ignore

#1808 refactor: add TX support to Plan API
  openmeter/productcatalog/plan/adapter/adapter.go
  openmeter/productcatalog/plan/adapter/phase.go
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/plan/httpdriver/phase.go
  openmeter/productcatalog/plan/httpdriver/plan.go
  openmeter/productcatalog/plan/repository.go
  openmeter/productcatalog/plan/service/phase.go
  openmeter/productcatalog/plan/service/plan.go
Labels: area/api, release-note/misc

#1812 fix(entitlement): use at when getting active entitlements
  openmeter/entitlement/adapter/entitlement.go
  openmeter/entitlement/balanceworker/entitlementhandler.go
  openmeter/entitlement/balanceworker/ingesthandler.go
  openmeter/entitlement/connector.go
Labels: release-note/bug-fix

#1821 Revert "chore: disable dagger cloud"
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .github/workflows/sdk-node.yaml
  .github/workflows/sdk-python.yaml
  .github/workflows/sdk-web.yaml
  .github/workflows/snapshot.yaml
  Makefile
Labels: release-note/ignore

#1811 chore: rename line service files
  openmeter/billing/service/lineservice/feeline.go
  openmeter/billing/service/lineservice/usagebasedline.go
Labels: release-note/ignore

#1803 Update Helm Chart with new services & features
  deploy/charts/openmeter/Chart.lock
  deploy/charts/openmeter/Chart.yaml
  deploy/charts/openmeter/README.md
  deploy/charts/openmeter/README.tmpl.md
  deploy/charts/openmeter/templates/NOTES.txt
  deploy/charts/openmeter/templates/_helpers.tpl
  deploy/charts/openmeter/templates/configmap.yaml
  deploy/charts/openmeter/templates/deployment.yaml
  deploy/charts/openmeter/templates/kafka.yaml
  deploy/charts/openmeter/templates/svix.yaml
  deploy/charts/openmeter/values.yaml
  flake.nix
Labels: area/dependencies, release-note/misc

#1824 fix: multiple issues in Plan API
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/productcatalog/plan/adapter/adapter_test.go
  openmeter/productcatalog/plan/adapter/mapping.go
  openmeter/productcatalog/plan/adapter/phase.go
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/errors.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/plan/plan.go
  openmeter/productcatalog/plan/plan_test.go
  openmeter/productcatalog/plan/price.go
  openmeter/productcatalog/plan/price_test.go
  openmeter/productcatalog/plan/ratecard.go
  openmeter/productcatalog/plan/service.go
  openmeter/productcatalog/plan/service/plan.go
  openmeter/productcatalog/plan/service/service.go
  openmeter/productcatalog/plan/service/service_test.go
Labels: area/api, release-note/bug-fix

#1810 fix(telemetry): service name
  app/common/app.go
  cmd/balance-worker/wire.go
  cmd/balance-worker/wire_gen.go
  cmd/notification-service/wire.go
  cmd/notification-service/wire_gen.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  cmd/sink-worker/wire.go
  cmd/sink-worker/wire_gen.go
Labels: release-note/bug-fix

#1825 feat(otel): upgrade semconv to 1.27.0
  app/common/telemetry.go
  pkg/framework/pgdriver/driver.go
Labels: release-note/ignore

#1829 fix(log): contextual logging
  cmd/server/main.go
  cmd/sink-worker/main.go
  openmeter/entitlement/repository.go
  pkg/framework/operation/log.go
Labels: release-note/bug-fix

#1827 feat(api): add plan service to the server
  app/config/config.go
  app/config/productcatalog.go
  cmd/server/main.go
  config.example.yaml
  openmeter/productcatalog/plan/httpdriver/phase.go
  openmeter/productcatalog/plan/httpdriver/plan.go
  openmeter/server/router/plan.go
  openmeter/server/router/router.go
Labels: area/api, release-note/feature

#1830 chore(api): update TypeSpec & regenerate types
  .dagger/generate.go
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/package.json
  api/spec/patches/@typespec__http.patch
  api/spec/patches/@typespec__openapi.patch
  api/spec/patches/@typespec__openapi3.patch
  api/spec/pnpm-lock.yaml
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/server/router/subscription.go
Labels: area/api, release-note/ignore

#1833 fix: Plan API
  openmeter/productcatalog/plan/adapter/phase.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
Labels: release-note/bug-fix, area/product-catalog

#1836 feat(api): change notification api to beta
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/cloud/main.tsp
  api/spec/src/notification/channel.tsp
  api/spec/src/notification/event.tsp
  api/spec/src/notification/rule.tsp
  api/spec/src/notification/svix.tsp
Labels: area/api, release-note/feature

#1837 feat(api): change entitlements api to beta
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/cloud/main.tsp
  api/spec/src/entitlements/entitlements.tsp
  api/spec/src/entitlements/feature.tsp
  api/spec/src/entitlements/grant.tsp
  api/spec/src/entitlements/subjects.tsp
Labels: area/api, release-note/feature

#1838 fix(logger): http context on logs
  app/common/telemetry.go
  cmd/jobs/service/otel.go
  cmd/server/main.go
  cmd/sink-worker/main.go
  openmeter/server/logger.go
  openmeter/server/server.go
  pkg/contextx/attr.go
  pkg/framework/internal/operation/name.go
  pkg/framework/operation/log.go
  pkg/framework/operation/name.go
  pkg/framework/operation/name_test.go
  pkg/framework/operation/operation.go
  pkg/framework/transport/httptransport/handler.go
  pkg/server/attributes.go
  pkg/server/logger.go
Labels: release-note/bug-fix

#1840 fix: Plan Discount JSON serialization
  openmeter/productcatalog/plan/discount.go
  openmeter/productcatalog/plan/discount_test.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
Labels: release-note/bug-fix, area/product-catalog

#1841 refactor: JSON serialization
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/productcatalog/plan/adapter/adapter_test.go
  openmeter/productcatalog/plan/adapter/mapping.go
  openmeter/productcatalog/plan/assert.go
  openmeter/productcatalog/plan/entitlement.go
  openmeter/productcatalog/plan/entitlement_test.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/plan/price.go
  openmeter/productcatalog/plan/price_test.go
  openmeter/productcatalog/plan/ratecard.go
  openmeter/productcatalog/plan/ratecard_test.go
  openmeter/productcatalog/plan/service/service_test.go
  test/billing/invoice_test.go
Labels: release-note/misc, area/product-catalog

#1843 feat(entitlement): pass context to get value
  openmeter/entitlement/boolean/connector.go
  openmeter/entitlement/connector.go
  openmeter/entitlement/entitlement_types.go
  openmeter/entitlement/metered/connector.go
  openmeter/entitlement/static/connector.go
  openmeter/entitlement/utils_test.go
Labels: release-note/ignore

#1844 feat(log): with context
  app/common/watermill.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/profile.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceline.go
  openmeter/customer/adapter/customer.go
  openmeter/entitlement/balanceworker/ingesthandler.go
  openmeter/ingest/kafkaingest/collector.go
  openmeter/notification/consumer/balancetreshold.go
  openmeter/notification/eventhandler/handler.go
  openmeter/notification/repository/channel.go
  openmeter/notification/repository/event.go
  openmeter/notification/repository/rule.go
  openmeter/notification/webhook/webhook.go
  openmeter/productcatalog/plan/adapter/phase.go
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/sink/flushhandler/handler.go
  openmeter/sink/flushhandler/ingestnotification/handler.go
  openmeter/sink/sink.go
  pkg/kafka/topicprovisioner.go
Labels: release-note/ignore

#1845 refactor(framework): simplify logging handlers
  cmd/server/main.go
  openmeter/ingest/ingestdriver/http_transport_test.go
  openmeter/server/server_test.go
  pkg/errorsx/handler.go
Labels: release-note/ignore

#1846 chore: bump Dagger to v0.14.0
  .github/workflows/ci-exp.yaml
  .github/workflows/ci.yaml
  dagger.json
  flake.lock
Labels: release-note/ignore

#1847 chore(deps): bump Svix to v1.40.0
  .dagger/versions_pinned.go
  docker-compose.yaml
  go.mod
  go.sum
  openmeter/notification/webhook/svix.go
  openmeter/notification/webhook/webhook.go
Labels: release-note/dependency-update

#1849 ci: fix Dagger version for Snapshot and SDK workflows
  .github/workflows/sdk-node.yaml
  .github/workflows/sdk-python.yaml
  .github/workflows/sdk-web.yaml
  .github/workflows/snapshot.yaml
Labels: release-note/ignore

#1853 fix(serializer): allow cloudevents without data
  openmeter/ingest/kafkaingest/serializer/json.go
  openmeter/ingest/kafkaingest/serializer/serializer.go
  openmeter/ingest/kafkaingest/serializer/serializer_test.go
  openmeter/meter/validate.go
  openmeter/meter/validate_test.go
  openmeter/sink/namespaces.go
Labels: area/processor, release-note/bug-fix

#1856 feat(api): accept application/json content-type for ingest
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/web/src/client/openapi.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/events.tsp
  openmeter/ingest/ingestdriver/http_transport.go
Labels: area/api, release-note/feature

#1855 test(e2e): invalid events
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/web/src/client/openapi.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/events.tsp
  e2e/config.yaml
  e2e/e2e_test.go
  openmeter/streaming/clickhouse_connector/connector.go
Labels: area/processor, release-note/ignore

#1857 feat(events): only accept json object
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/clients/event.ts
  api/client/node/schemas/openapi.ts
  api/client/web/src/client/openapi.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/events.tsp
  e2e/e2e_test.go
Labels: area/ingest, release-note/breaking-change

#1858 fix(events): data type
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/web/src/client/openapi.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/events.tsp
Labels: area/api, release-note/ignore

#1869 fix: updating PlanPhase to have no RateCards
  openmeter/productcatalog/plan/adapter/phase.go
  openmeter/productcatalog/plan/service/service_test.go
Labels: release-note/bug-fix, area/product-catalog

#1873 fix: updating Plan to have no PlanPhases
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/service/service_test.go
Labels: release-note/bug-fix, area/product-catalog

#1874 fix(api): return empty array instead of null
  openmeter/productcatalog/plan/httpdriver/mapping.go
Labels: area/api, release-note/bug-fix, area/product-catalog

#1875 fix: Plan status check at PlanPhase operations
  openmeter/productcatalog/plan/adapter/phase.go
  openmeter/productcatalog/plan/assert.go
  openmeter/productcatalog/plan/service/phase.go
  openmeter/productcatalog/plan/service/service_test.go
Labels: release-note/bug-fix, area/product-catalog

#1876 refactor: rm unused hard delete option
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/service.go
Labels: release-note/ignore, kind/refactor

#1860 Update Plan API
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/web/src/client/openapi.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/plan.tsp
  api/spec/src/productcatalog/ratecards.tsp
  api/spec/src/productcatalog/routes.tsp
  api/spec/src/query.tsp
  api/spec/src/rest.tsp
  api/spec/src/types.tsp
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/plan/httpdriver/plan.go
  pkg/sortx/order.go
Labels: area/api, release-note/ignore

#1877 fix: Plan/Phase request mapping in HTTP driver
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/plan/service.go
Labels: area/api, release-note/bug-fix, area/product-catalog

#1878 fix(api): plan metadata & allow draft deletion
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/plan/service/plan.go
Labels: area/api, release-note/bug-fix

#1881 chore: remove stainless integration
  .dagger/snapshot.go
  .github/workflows/snapshot.yaml
  dagger.json
Labels: release-note/ignore

#1885 fix: Plan API implementation
  openmeter/productcatalog/plan/httpdriver/idorkey.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/plan/httpdriver/plan.go
  openmeter/productcatalog/plan/price.go
  openmeter/productcatalog/plan/service/plan.go
  openmeter/server/router/plan.go
Labels: release-note/bug-fix, area/product-catalog

#1886 fix: healthcheck for Postgres container
  docker-compose.yaml
Labels: release-note/ignore

#1887 fix: updating RateCards in PlanPhase
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/schema/productcatalog.go
  openmeter/productcatalog/plan/adapter/phase.go
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/assert.go
  openmeter/productcatalog/plan/service/phase.go
  openmeter/productcatalog/plan/service/service_test.go
  tools/migrate/migrations/20241119131528_plan.down.sql
  tools/migrate/migrations/20241119131528_plan.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/bug-fix, area/product-catalog

#1889 fix: listing deleted PlanPhases
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/schema/productcatalog.go
  openmeter/productcatalog/plan/adapter/plan.go
  tools/migrate/migrations/20241119154436_plan.down.sql
  tools/migrate/migrations/20241119154436_plan.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/bug-fix, area/product-catalog

#1891 chore(client): update Node and Web client dependencies
  api/client/node/.eslintignore
  api/client/node/.eslintrc.json
  api/client/node/eslint.config.js
  api/client/node/package.json
  api/client/node/pnpm-lock.yaml
  api/client/web/package.json
  api/client/web/pnpm-lock.yaml
Labels: release-note/dependency-update

#1893 fix: validate Plan before Publish
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/plan.go
  openmeter/productcatalog/plan/service.go
  openmeter/productcatalog/plan/service/plan.go
  openmeter/productcatalog/plan/service/service_test.go
Labels: release-note/bug-fix, area/product-catalog

#1894 fix: creating duplicated Plans
  openmeter/productcatalog/plan/service/plan.go
  openmeter/productcatalog/plan/service/service_test.go
Labels: release-note/bug-fix, area/product-catalog

#1888 fix(customer): delete customer subjects
  openmeter/customer/adapter/customer.go
  openmeter/ent/db/customersubjects.go
  openmeter/ent/db/customersubjects/customersubjects.go
  openmeter/ent/db/customersubjects/where.go
  openmeter/ent/db/customersubjects_create.go
  openmeter/ent/db/customersubjects_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/customer.go
  test/customer/customer.go
  tools/migrate/migrations/20241119181140_customer_subjects_soft_delete.down.sql
  tools/migrate/migrations/20241119181140_customer_subjects_soft_delete.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/bug-fix, area/billing

#1895 fix(node): client types
  api/client/node/schemas/openapi.ts
  api/client/node/test/agent.ts
  api/client/node/test/api.test.ts
  api/client/node/test/mocks.ts
Labels: area/api, release-note/ignore

#1897 fix(customer): api mapping
  openmeter/customer/entity/customer.go
Labels: release-note/bug-fix, area/billing

#1898 feat: add Discount support to Plan API
  openmeter/productcatalog/plan/adapter/mapping.go
  openmeter/productcatalog/plan/adapter/phase.go
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/plan/phase.go
  openmeter/productcatalog/plan/service.go
  openmeter/productcatalog/plan/service/service.go
  openmeter/productcatalog/plan/utils.go
  openmeter/productcatalog/plan/utils_test.go
Labels: release-note/feature, area/product-catalog

#1896 feat: totals calculations
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/invoicelinemapper.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/entity/invoice.go
  openmeter/billing/entity/invoiceline.go
  openmeter/billing/entity/totals.go
  openmeter/billing/invoice.go
  openmeter/billing/service/calculation/draftuntil.go
  openmeter/billing/service/calculation/totals.go
  openmeter/billing/service/invoicecalc.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/service/lineservice/feeline.go
  openmeter/billing/service/lineservice/linebase.go
  openmeter/billing/service/lineservice/service.go
  openmeter/billing/service/lineservice/usagebasedline.go
  openmeter/billing/service/lineservice/usagebasedline_test.go
  openmeter/ent/db/billinginvoice.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/billinginvoice/where.go
  openmeter/ent/db/billinginvoice_create.go
  openmeter/ent/db/billinginvoice_update.go
  openmeter/ent/db/billinginvoiceflatfeelineconfig.go
  openmeter/ent/db/billinginvoiceflatfeelineconfig/billinginvoiceflatfeelineconfig.go
  openmeter/ent/db/billinginvoiceflatfeelineconfig/where.go
  openmeter/ent/db/billinginvoiceflatfeelineconfig_create.go
  openmeter/ent/db/billinginvoiceflatfeelineconfig_update.go
  openmeter/ent/db/billinginvoiceline.go
  openmeter/ent/db/billinginvoiceline/billinginvoiceline.go
  openmeter/ent/db/billinginvoiceline/where.go
  openmeter/ent/db/billinginvoiceline_create.go
  openmeter/ent/db/billinginvoiceline_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/schema/billing.go
  pkg/currencyx/currency.go
  pkg/currencyx/currency_test.go
  test/billing/invoice_test.go
  tools/migrate/migrations/20241121145549_billing-totals.down.sql
  tools/migrate/migrations/20241121145549_billing-totals.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/billing

#1901 fix(api): discounts
  openmeter/productcatalog/plan/httpdriver/mapping.go
Labels: release-note/ignore

#1899 refactor: use samber mo
  go.mod
  go.sum
  openmeter/billing/adapter/invoicelinediff.go
  openmeter/billing/adapter/invoicelinediff_test.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/entity/invoiceline.go
  openmeter/billing/service/lineservice/feeline.go
  openmeter/billing/service/lineservice/linebase.go
  openmeter/billing/service/lineservice/usagebasedline.go
  pkg/models/optional.go
  pkg/slicesx/optional.go
  test/billing/adapter_test.go
  test/billing/invoice_test.go
Labels: release-note/ignore, area/billing

#1902 feat: implement billing api methods
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/billing/customeroverride.tsp
  api/spec/src/billing/invoices.tsp
  api/spec/src/billing/invoices/docref.tsp
  api/spec/src/billing/invoices/invoice.tsp
  api/spec/src/billing/invoices/org.tsp
  api/spec/src/billing/profile.tsp
  openmeter/billing/adapter.go
  openmeter/billing/adapter/customeroverride.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/entity/errors.go
  openmeter/billing/entity/invoiceline.go
  openmeter/billing/httpdriver/handler.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/httpdriver/profile.go
  openmeter/billing/invoice.go
  openmeter/billing/invoiceline.go
  openmeter/billing/service.go
  openmeter/billing/service/customer.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceline.go
  openmeter/server/router/billing.go
  test/billing/invoice_test.go
Labels: release-note/feature, area/billing

#1900 refactor: lockable set
  openmeter/billing/adapter/invoicelinediff.go
  openmeter/billing/adapter/invoicelines.go
  pkg/set/set.go
  pkg/set/set_test.go
Labels: release-note/ignore

#1918 Refactor Subscription Routes
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/productcatalog/routes.tsp
  api/spec/src/productcatalog/subscription.tsp
  api/spec/src/types.tsp
  openmeter/server/router/subscription.go
Labels: release-note/ignore

#1905 feat: line updating
  openmeter/app/sandbox/mock.go
  openmeter/billing/adapter.go
  openmeter/billing/adapter/adapter.go
  openmeter/billing/adapter/customeroverride.go
  openmeter/billing/adapter/errors.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/invoicelinediff.go
  openmeter/billing/adapter/invoicelinemapper.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/adapter/profile.go
  openmeter/billing/adapter/upsert.go
  openmeter/billing/adapter/validationissue.go
  openmeter/billing/entity/errors.go
  openmeter/billing/entity/invoice.go
  openmeter/billing/entity/invoiceline.go
  openmeter/billing/entity/validationissue.go
  openmeter/billing/entity/validationissue_test.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/invoiceline.go
  openmeter/billing/service.go
  openmeter/billing/service/calculation/draftuntil.go
  openmeter/billing/service/calculation/totals.go
  openmeter/billing/service/customeroverride.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoicecalc.go
  openmeter/billing/service/invoicecalc/calculator.go
  openmeter/billing/service/invoicecalc/details.go
  openmeter/billing/service/invoicecalc/draftuntil.go
  openmeter/billing/service/invoicecalc/mock.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/service/invoicestate.go
  openmeter/billing/service/lineservice/feeline.go
  openmeter/billing/service/lineservice/linebase.go
  openmeter/billing/service/lineservice/service.go
  openmeter/billing/service/lineservice/usagebasedline.go
  openmeter/billing/service/profile.go
  openmeter/billing/service/service.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/billinginvoiceusagebasedlineconfig.go
  openmeter/ent/db/billinginvoiceusagebasedlineconfig/billinginvoiceusagebasedlineconfig.go
  openmeter/ent/db/billinginvoiceusagebasedlineconfig/where.go
  openmeter/ent/db/billinginvoiceusagebasedlineconfig_create.go
  openmeter/ent/db/billinginvoiceusagebasedlineconfig_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  openmeter/entitlement/adapter/transaction.go
  openmeter/productcatalog/plan/price.go
  test/billing/adapter_test.go
  test/billing/invoice_test.go
  test/billing/profile_test.go
  test/billing/suite_test.go
  tools/migrate/migrations/20241126151128_billing-ubp-pre-qty-save.down.sql
  tools/migrate/migrations/20241126151128_billing-ubp-pre-qty-save.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/billing

#1921 feat: delete invoice
  openmeter/billing/adapter/invoice.go
  openmeter/billing/entity/errors.go
  openmeter/billing/entity/invoice.go
  openmeter/billing/invoice.go
  openmeter/billing/service.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoicestate.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/migrate/schema.go
  test/billing/invoice_test.go
Labels: release-note/feature, area/billing

#1720 feat(streaming): raw event connector
  app/common/openmeter.go
  app/common/wire.go
  app/config/aggregation.go
  app/config/config_test.go
  app/config/sink.go
  cmd/balance-worker/wire_gen.go
  cmd/jobs/entitlement/init.go
  cmd/notification-service/wire_gen.go
  cmd/server/main.go
  cmd/server/wire_gen.go
  cmd/sink-worker/main.go
  e2e/e2e_test.go
  openmeter/billing/service/lineservice/meters.go
  openmeter/credit/balance.go
  openmeter/credit/engine/engine_test.go
  openmeter/credit/grant.go
  openmeter/credit/grant/owner_connector.go
  openmeter/entitlement/metered/balance.go
  openmeter/entitlement/metered/grant_owner_adapter.go
  openmeter/meter/parse.go
  openmeter/meter/parse_test.go
  openmeter/meter/validate.go
  openmeter/meter/validate_test.go
  openmeter/server/router/meter_query.go
  openmeter/server/router/meter_subject.go
  openmeter/server/server_test.go
  openmeter/sink/namespaces.go
  openmeter/sink/storage.go
  openmeter/sink/storage_test.go
  openmeter/streaming/clickhouse/materialized_view/connector.go
  openmeter/streaming/clickhouse/materialized_view/meter_query.go
  openmeter/streaming/clickhouse/materialized_view/meter_query_test.go
  openmeter/streaming/clickhouse/raw_events/connector.go
  openmeter/streaming/clickhouse/raw_events/event_query.go
  openmeter/streaming/clickhouse/raw_events/event_query_test.go
  openmeter/streaming/clickhouse/raw_events/meter_query.go
  openmeter/streaming/clickhouse/raw_events/meter_query_test.go
  openmeter/streaming/clickhouse_connector/connector.go
  openmeter/streaming/clickhouse_connector/model.go
  openmeter/streaming/connector.go
  openmeter/streaming/query_params.go
  openmeter/streaming/testutils/streaming.go
  openmeter/streaming/testutils/streaming_test.go
Labels: area/ingest, release-note/feature
