Repository openmeterio/openmeter, pull requests merged in 2024-08, with the labels that each got.

#1283 refactor: event naming consistency
  internal/credit/events.go
  internal/entitlement/events.go
  internal/entitlement/metered/events.go
  internal/entitlement/metered/reset.go
  internal/entitlement/snapshot/event.go
  internal/event/spec/event_type.go
  internal/event/spec/parser.go
  internal/event/spec/parser_test.go
  internal/sink/flushhandler/ingestnotification/events.go
  internal/sink/flushhandler/ingestnotification/handler.go
  openmeter/credit/events.go
  openmeter/entitlement/events.go
  openmeter/entitlement/metered/events.go
  openmeter/sink/flushhandler/ingestnotification/ingestnotification.go
Labels: area/ingest, release-note/misc, area/sink-worker, area/balance-worker

#1276 feat: support entitlement, ingest events
  cmd/balance-worker/main.go
  internal/entitlement/balanceworker/entitlementhandler.go
  internal/entitlement/balanceworker/ingesthandler.go
  internal/entitlement/balanceworker/worker.go
Labels: release-note/feature, area/balance-worker

#1281 feat: notification-service
  .vscode/launch.json
  Dockerfile
  Makefile
  cmd/notification-service/.air.toml
  cmd/notification-service/main.go
  cmd/notification-service/version.go
  config/config.go
  config/config_test.go
  config/notificationservice.go
  internal/notification/consumer/consumer.go
  internal/watermill/nopublisher/nopublisher.go
Labels: release-note/ignore

#1285 fix: exclude deleted entitlements from autoreset
  internal/entitlement/postgresadapter/entitlement.go
Labels: release-note/bug-fix

#1284 refactor: rename poision queue to DLQ
  cmd/balance-worker/main.go
  cmd/notification-service/main.go
  config/balanceworker.go
  config/config_test.go
  config/events.go
  config/notificationservice.go
  internal/entitlement/balanceworker/worker.go
  internal/notification/consumer/consumer.go
Labels: release-note/misc

#1286 chore: expose balance and notification types
  cmd/balance-worker/main.go
  cmd/notification-service/main.go
  openmeter/entitlement/balanceworker/worker.go
  openmeter/event/publisher/publisher.go
  openmeter/notification/consumer/consumer.go
  openmeter/registry/entitlement.go
Labels: release-note/ignore

#1288 Pass a list of IDs for exact querying
  internal/productcatalog/feature_connector.go
  internal/productcatalog/postgresadapter/feature.go
Labels: release-note/misc

#1290 Expose missing getEntitlementById handler and types
  openmeter/entitlement/httpdriver/handlers.go
  openmeter/entitlement/httpdriver/types.go
Labels: release-note/misc

#1292 fix(examples): update vector example
  examples/ingest-logs/README.md
  examples/ingest-logs/docker-compose.yaml
  examples/ingest-logs/vector.yaml
  quickstart/config.yaml
Labels: release-note/misc, kind/refactor

#1280 Feat/batch ingest events for balance calculation
  cmd/balance-worker/main.go
  cmd/notification-service/main.go
  cmd/server/main.go
  cmd/sink-worker/main.go
  config/balanceworker.go
  config/config_test.go
  internal/entitlement/balanceworker/entitlementhandler.go
  internal/entitlement/balanceworker/ingesthandler.go
  internal/entitlement/balanceworker/repository.go
  internal/entitlement/balanceworker/worker.go
  internal/entitlement/postgresadapter/entitlement.go
  internal/event/spec/parser.go
  internal/event/spec/resourcepath.go
  internal/registry/builder/entitlement.go
  internal/registry/entitlement.go
  internal/sink/flushhandler/ingestnotification/events.go
  internal/sink/flushhandler/ingestnotification/handler.go
  internal/sink/namespaces.go
  openmeter/registry/entitlement.go
  openmeter/sink/flushhandler/ingestnotification/ingestnotification.go
  pkg/slicesx/chunk.go
  pkg/slicesx/chunk_test.go
Labels: release-note/misc

#1301 fix: go generate for ent schemas
  internal/ent/db/balancesnapshot_create.go
  internal/ent/db/balancesnapshot_query.go
  internal/ent/db/balancesnapshot_update.go
  internal/ent/db/ent.go
  internal/ent/db/entitlement_create.go
  internal/ent/db/entitlement_query.go
  internal/ent/db/entitlement_update.go
  internal/ent/db/feature_query.go
  internal/ent/db/grant_create.go
  internal/ent/db/grant_query.go
  internal/ent/db/grant_update.go
  internal/ent/db/runtime/runtime.go
  internal/ent/db/usagereset_create.go
  internal/ent/db/usagereset_query.go
  internal/ent/db/usagereset_update.go
  pkg/framework/entutils/testutils/ent1/db/ent.go
  pkg/framework/entutils/testutils/ent1/db/example1_query.go
  pkg/framework/entutils/testutils/ent1/db/runtime/runtime.go
  pkg/framework/entutils/testutils/ent2/db/ent.go
  pkg/framework/entutils/testutils/ent2/db/example2_query.go
  pkg/framework/entutils/testutils/ent2/db/runtime/runtime.go
Labels: release-note/misc

#1291 feat: use sarama lib for internal message publishing
  cmd/balance-worker/main.go
  cmd/notification-service/main.go
  cmd/server/main.go
  cmd/sink-worker/main.go
  internal/watermill/driver/kafka/marshaler.go
  internal/watermill/driver/kafka/metrics/README.md
  internal/watermill/driver/kafka/metrics/adapter.go
  internal/watermill/driver/kafka/publisher.go
  internal/watermill/driver/kafka/topic_provision.go
  openmeter/watermill/driver/kafka/driver.go
Labels: area/dependencies, area/api, release-note/dependency-update, area/sink-worker, area/balance-worker

#1302 refactor: Notification API spec
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
Labels: area/api, release-note/misc, kind/refactor

#1307 chore: update exports for openmeter
  cmd/sink-worker/main.go
  config/balanceworker.go
  config/config_test.go
  config/sink.go
  openmeter/sink/flushhandler/ingestnotification/ingestnotification.go
  openmeter/watermill/driver/kafka/driver.go
Labels: release-note/misc

#1308 Fix quickstart
  quickstart/quickstart_test.go
Labels: release-note/bug-fix

#1309 fix: confluent cloud connectivity issues
  cmd/balance-worker/main.go
  cmd/notification-service/main.go
  cmd/server/main.go
  cmd/sink-worker/main.go
  internal/watermill/driver/kafka/logger.go
  internal/watermill/driver/kafka/publisher.go
  internal/watermill/driver/kafka/topic_provision.go
  openmeter/watermill/driver/kafka/driver.go
Labels: release-note/bug-fix

#1315 fix: expose feature repo
  internal/registry/builder/entitlement.go
  internal/registry/entitlement.go
Labels: release-note/misc

#1314 refactor: use watermill event bus
  cmd/balance-worker/main.go
  cmd/notification-service/main.go
  cmd/server/main.go
  cmd/sink-worker/main.go
  internal/credit/connector.go
  internal/credit/grant.go
  internal/credit/grant/events.go
  internal/entitlement/balanceworker/entitlementhandler.go
  internal/entitlement/balanceworker/ingesthandler.go
  internal/entitlement/balanceworker/worker.go
  internal/entitlement/connector.go
  internal/entitlement/events.go
  internal/entitlement/metered/connector.go
  internal/entitlement/metered/events.go
  internal/entitlement/metered/reset.go
  internal/entitlement/metered/utils_test.go
  internal/entitlement/snapshot/event.go
  internal/event/metadata/event_type.go
  internal/event/metadata/resourcepath.go
  internal/event/publisher.go
  internal/event/publisher/publisher.go
  internal/event/publisher/transformer.go
  internal/event/spec/parser.go
  internal/event/spec/parser_test.go
  internal/notification/consumer/consumer.go
  internal/registry/entitlement.go
  internal/sink/flushhandler/ingestnotification/events/events.go
  internal/sink/flushhandler/ingestnotification/handler.go
  internal/watermill/driver/kafka/marshaler.go
  internal/watermill/driver/kafka/publisher.go
  internal/watermill/eventbus/eventbus.go
  openmeter/credit/adapters.go
  openmeter/entitlement/adapters.go
  openmeter/entitlement/metered/adapters.go
  openmeter/event/event.go
  openmeter/event/publisher/publisher.go
  openmeter/sink/flushhandler/ingestnotification/events/events.go
  openmeter/sink/flushhandler/ingestnotification/ingestnotification.go
  openmeter/watermill/eventbus/eventbus.go
  openmeter/watermill/marshaler/marshaler.go
  openmeter/watermill/marshaler/source.go
  openmeter/watermill/marshaler/source_test.go
  test/entitlement/regression/framework_test.go
Labels: release-note/misc, kind/refactor

#1318 chore: expose types for cloud usage
  openmeter/entitlement/snapshot/events.go
  openmeter/watermill/nopublisher/nopublisher.go
Labels: release-note/ignore

#1319 fix: subject ID resolving error
  internal/entitlement/balanceworker/entitlementhandler.go
  openmeter/entitlement/balanceworker/worker.go
Labels: release-note/bug-fix

#1320 ci: run ci pipeline on depot
  .github/workflows/ci.yaml
Labels: release-note/ignore

#1316 refactor: subscribers
  cmd/balance-worker/main.go
  cmd/notification-service/main.go
  cmd/server/main.go
  cmd/sink-worker/main.go
  internal/entitlement/balanceworker/entitlementhandler.go
  internal/entitlement/balanceworker/ingesthandler.go
  internal/entitlement/balanceworker/worker.go
  internal/entitlement/connector.go
  internal/event/publisher.go
  internal/notification/consumer/consumer.go
  internal/watermill/driver/kafka/broker.go
  internal/watermill/driver/kafka/publisher.go
  internal/watermill/driver/kafka/subscriber.go
  internal/watermill/eventbus/eventbus.go
  internal/watermill/grouphandler/grouphandler.go
  internal/watermill/router/router.go
  openmeter/entitlement/balanceworker/worker.go
  openmeter/event/event.go
  openmeter/notification/consumer/consumer.go
  openmeter/watermill/driver/kafka/driver.go
  openmeter/watermill/eventbus/eventbus.go
  openmeter/watermill/grouphandler/grouphandler.go
  openmeter/watermill/router/router.go
Labels: release-note/misc

#1321 ci: update kafka module
  ci/e2e.go
  dagger.json
Labels: release-note/ignore

#1325 fix: relax entitlement snapshot event validation
  internal/entitlement/balanceworker/entitlementhandler.go
  internal/entitlement/snapshot/event.go
  openmeter/entitlement/snapshot/events.go
Labels: release-note/bug-fix

#1324 Fail e2e tests for event ingest timeouts
  e2e/e2e_test.go
  internal/testutils/async.go
Labels: release-note/ignore

#1327 ci: run large pipelines on depot runners
  .github/actions/free-disk-space/action.yaml
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  ci/e2e.go
Labels: release-note/ignore

#1329 docs: tweak readme quickstart
  README.md
Labels: release-note/ignore

#1332 Test improvements
  ci/e2e.go
  ci/main.go
Labels: release-note/ignore

#1333 Add version update mechanism for ci dependencies
  ci/dev.go
  ci/go.mod
  ci/go.sum
  ci/main.go
  ci/versions.go
  ci/versions_pinned.go
  docker-compose.yaml
  justfile
Labels: release-note/ignore

#1323 feat: add command to recalculate balance snapshots
  .vscode/launch.json
  cmd/jobs/config/loader.go
  cmd/jobs/entitlement/init.go
  cmd/jobs/entitlement/recalculatesnapshots.go
  cmd/jobs/entitlement/root.go
  cmd/jobs/main.go
  cmd/jobs/service/otel.go
  cmd/jobs/version.go
  go.mod
  go.sum
  internal/entitlement/adapter/entitlement.go
  internal/entitlement/balanceworker/recalculate.go
  internal/entitlement/connector.go
  internal/entitlement/repository.go
  openmeter/entitlement/balanceworker/worker.go
Labels: release-note/feature, area/entitlements

#1344 Implement usage carryover
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/python/src/openmeter/_operations/_operations.py
  api/client/python/src/openmeter/aio/_operations/_operations.py
  api/client/web/src/client/openapi.ts
  api/openapi.yaml
  internal/credit/adapter/grant.go
  internal/credit/balance.go
  internal/credit/engine/engine.go
  internal/credit/grant/grant.go
  internal/ent/db/entitlement.go
  internal/ent/db/entitlement/entitlement.go
  internal/ent/db/entitlement/where.go
  internal/ent/db/entitlement_create.go
  internal/ent/db/entitlement_update.go
  internal/ent/db/migrate/schema.go
  internal/ent/db/mutation.go
  internal/ent/schema/entitlement.go
  internal/entitlement/adapter/entitlement.go
  internal/entitlement/driver/entitlement.go
  internal/entitlement/driver/metered.go
  internal/entitlement/driver/parser.go
  internal/entitlement/entitlement.go
  internal/entitlement/metered/connector.go
  internal/entitlement/metered/entitlement.go
  internal/entitlement/metered/reset.go
  internal/entitlement/metered/reset_test.go
  internal/entitlement/repository.go
Labels: release-note/feature

#1338 build: drop ubi and distroless builds
  .github/workflows/artifacts.yaml
  Dockerfile
Labels: release-note/breaking-change, area/distribution

#1348 build: add container scanning
  ci/generate.go
  ci/main.go
  dagger.json
Labels: release-note/ignore

#1337 build: update go version used to build the application
  Dockerfile
  ci/versions_pinned.go
Labels: release-note/dependency-update

#1349 fix: strip monotonic clock reading from time returned by clock
  pkg/clock/clock.go
Labels: release-note/misc

#1350 refactor: Notification API spec
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/server/router/notification.go
Labels: release-note/misc

#1354 feat: add Notification ent schema
  internal/ent/db/client.go
  internal/ent/db/ent.go
  internal/ent/db/expose.go
  internal/ent/db/hook/hook.go
  internal/ent/db/migrate/schema.go
  internal/ent/db/mutation.go
  internal/ent/db/notificationchannel.go
  internal/ent/db/notificationchannel/notificationchannel.go
  internal/ent/db/notificationchannel/where.go
  internal/ent/db/notificationchannel_create.go
  internal/ent/db/notificationchannel_delete.go
  internal/ent/db/notificationchannel_query.go
  internal/ent/db/notificationchannel_update.go
  internal/ent/db/notificationevent.go
  internal/ent/db/notificationevent/notificationevent.go
  internal/ent/db/notificationevent/where.go
  internal/ent/db/notificationevent_create.go
  internal/ent/db/notificationevent_delete.go
  internal/ent/db/notificationevent_query.go
  internal/ent/db/notificationevent_update.go
  internal/ent/db/notificationeventdeliverystatus.go
  internal/ent/db/notificationeventdeliverystatus/notificationeventdeliverystatus.go
  internal/ent/db/notificationeventdeliverystatus/where.go
  internal/ent/db/notificationeventdeliverystatus_create.go
  internal/ent/db/notificationeventdeliverystatus_delete.go
  internal/ent/db/notificationeventdeliverystatus_query.go
  internal/ent/db/notificationeventdeliverystatus_update.go
  internal/ent/db/notificationrule.go
  internal/ent/db/notificationrule/notificationrule.go
  internal/ent/db/notificationrule/where.go
  internal/ent/db/notificationrule_create.go
  internal/ent/db/notificationrule_delete.go
  internal/ent/db/notificationrule_query.go
  internal/ent/db/notificationrule_update.go
  internal/ent/db/paginate.go
  internal/ent/db/predicate/predicate.go
  internal/ent/db/runtime.go
  internal/ent/db/tx.go
  internal/ent/schema/notification.go
  internal/notification/channel.go
  internal/notification/event.go
  internal/notification/rule.go
Labels: release-note/feature

#1355 feat: add webhook provider to Notification
  go.mod
  go.sum
  internal/notification/webhook/events.go
  internal/notification/webhook/secret.go
  internal/notification/webhook/svix.go
  internal/notification/webhook/webhook.go
Labels: release-note/feature

#1356 feat: implement channels support
  internal/ent/db/notificationchannel_create.go
  internal/ent/db/notificationchannel_update.go
  internal/notification/channel.go
  internal/notification/defaults.go
  internal/notification/errors.go
  internal/notification/httpdriver/channel.go
  internal/notification/httpdriver/errors.go
  internal/notification/httpdriver/handler.go
  internal/notification/repository.go
  internal/notification/repository/entitymapping.go
  internal/notification/repository/repository.go
  internal/notification/service.go
  internal/notification/validator.go
Labels: kind/feature, release-note/feature

#1357 feat: implement rules for Notification API
  internal/notification/httpdriver/handler.go
  internal/notification/httpdriver/rule.go
  internal/notification/repository.go
  internal/notification/repository/entitymapping.go
  internal/notification/repository/repository.go
  internal/notification/rule.go
  internal/notification/service.go
Labels: kind/feature, area/api, release-note/feature

#1358 feat: implement events for Notification API
  internal/notification/event.go
  internal/notification/eventhandler.go
  internal/notification/httpdriver/event.go
  internal/notification/httpdriver/handler.go
  internal/notification/repository.go
  internal/notification/repository/entitymapping.go
  internal/notification/repository/repository.go
  internal/notification/service.go
Labels: kind/feature, area/api, release-note/feature

#1362 chore: update balance worker adapter
  go.mod
  openmeter/entitlement/adapter/adapters.go
Labels: release-note/misc

#1361 ci: add missing binary builds
  ci/build.go
Labels: release-note/ignore

#1360 test: add integration test suite for Notification API
  ci/e2e.go
  ci/main.go
  ci/versions_pinned.go
  internal/notification/eventhandler.go
  test/notification/channel.go
  test/notification/event.go
  test/notification/helpers.go
  test/notification/notification_test.go
  test/notification/rule.go
  test/notification/testenv.go
  test/notification/webhook.go
Labels: release-note/ignore

#1363 feat: resolve full subject entity
  internal/entitlement/balanceworker/entitlementhandler.go
  internal/entitlement/balanceworker/recalculate.go
  internal/entitlement/balanceworker/worker.go
  internal/entitlement/snapshot/event.go
  internal/event/models/models.go
  internal/event/models/subject.go
  openmeter/entitlement/balanceworker/worker.go
  openmeter/event/models/models.go
Labels: kind/feature, release-note/misc, area/notification

#1334 build: fix kafka linker errors
  cmd/balance-worker/.air.toml
  cmd/notification-service/.air.toml
  cmd/server/.air.toml
  cmd/sink-worker/.air.toml
  flake.nix
Labels: release-note/ignore

#1365 feat: add tx support to Notification API
  internal/notification/repository.go
  internal/notification/repository/repository.go
  internal/notification/service.go
Labels: release-note/misc

#1368 test: rm unnecessary envvar check
  test/notification/testenv.go
Labels: release-note/ignore

#1367 feat: enable Notification API in backend
  Makefile
  cmd/notification-service/main.go
  cmd/server/main.go
  config.example.yaml
  config/config.go
  config/config_test.go
  config/notification.go
  config/notificationservice.go
  config/svix.go
  config/testdata/complete.yaml
  docker-compose.yaml
  internal/server/router/notification.go
  internal/server/router/router.go
  internal/server/server_test.go
  openmeter/notification/alias.go
  openmeter/notification/httpdriver/alias.go
  openmeter/notification/repository/alias.go
  openmeter/notification/webhook/alias.go
Labels: release-note/ignore

#1371 refactor: rename Svix API key in config
  config.example.yaml
  config/config_test.go
  config/testdata/complete.yaml
  internal/notification/webhook/svix.go
  test/notification/testenv.go
Labels: release-note/ignore

#1366 Implement entitlement overrides OM738
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/clients/subject.ts
  api/client/node/schemas/openapi.ts
  api/client/python/src/openmeter/_operations/_operations.py
  api/client/python/src/openmeter/aio/_operations/_operations.py
  api/client/web/src/client/openapi.ts
  api/openapi.yaml
  e2e/e2e_test.go
  internal/entitlement/connector.go
  internal/entitlement/driver/entitlement.go
  internal/entitlement/driver/parser.go
  internal/server/router/entitlement.go
  openmeter/entitlement/driver/handlers.go
  openmeter/entitlement/driver/types.go
Labels: release-note/feature

#1372 Fix concurrent map writes
  internal/productcatalog/adapter/feature_test.go
Labels: release-note/ignore

#1322 ci: use depot for container image build
  .github/workflows/artifacts.yaml
Labels: release-note/ignore

#1375 fix: Notification API in backend
  cmd/server/main.go
  internal/notification/eventhandler.go
  internal/notification/service.go
Labels: kind/bug, release-note/bug-fix

#1369 feat: simplify dlq setup
  cmd/balance-worker/main.go
  cmd/notification-service/main.go
  config/balanceworker.go
  config/config_test.go
  config/events.go
  config/notification.go
  go.mod
  internal/entitlement/balanceworker/worker.go
  internal/notification/consumer/consumer.go
  internal/watermill/driver/kafka/topic_provision.go
  internal/watermill/router/context.go
  internal/watermill/router/router.go
  internal/watermill/router/router_test.go
  openmeter/watermill/router/router.go
Labels: release-note/feature

#1374 Docker cleanup
  .github/workflows/artifacts.yaml
Labels: release-note/ignore

#1376 refactor(api): notification events sending
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/ent/db/migrate/schema.go
  internal/ent/db/mutation.go
  internal/ent/db/notificationevent.go
  internal/ent/db/notificationevent/notificationevent.go
  internal/ent/db/notificationevent/where.go
  internal/ent/db/notificationevent_create.go
  internal/ent/db/notificationevent_update.go
  internal/ent/db/predicate/predicate.go
  internal/ent/db/runtime.go
  internal/ent/schema/notification.go
  internal/notification/annotations.go
  internal/notification/event.go
  internal/notification/httpdriver/event.go
  internal/notification/httpdriver/handler.go
  internal/notification/httpdriver/rule.go
  internal/notification/internal/rule.go
  internal/notification/repository/repository.go
  internal/server/router/notification.go
  openmeter/notification/httpdriver/alias.go
Labels: area/api, kind/refactor

#1379 fix: missing payload in notification event
  internal/notification/event.go
Labels: release-note/bug-fix

#1392 refactor: add utils for Notification API
  internal/notification/event.go
  internal/notification/eventhandler.go
  internal/notification/utils.go
Labels: release-note/misc

#1398 refactor: optimize usage reset queries
  internal/entitlement/adapter/entitlement.go
Labels: release-note/misc

#1397 refactor: postgres/ent driver initialization
  cmd/balance-worker/main.go
  cmd/jobs/entitlement/init.go
  cmd/notification-service/main.go
  cmd/server/main.go
  pkg/framework/entutils/database.go
  pkg/framework/entutils/driver/driver.go
  pkg/framework/pgdriver/driver.go
  test/notification/helpers.go
  test/notification/notification_test.go
  test/notification/testenv.go
Labels: release-note/misc, kind/refactor

#1401 fix: database error handling
  cmd/balance-worker/main.go
  cmd/notification-service/main.go
  cmd/server/main.go
  test/notification/testenv.go
Labels: release-note/bug-fix

#1380 feat: add subject and feature filters
  internal/ent/db/migrate/schema.go
  internal/ent/generate.go
  internal/ent/schema/notification.go
  internal/notification/annotations.go
  internal/notification/event.go
  internal/notification/repository/entitymapping.go
  internal/notification/repository/repository.go
  pkg/framework/entutils/pgjsonb.go
  test/notification/notification_test.go
  test/notification/repository.go
  test/notification/testenv.go
Labels: release-note/feature

#1359 feat: notification handler
  cmd/notification-service/main.go
  internal/event/models/subject.go
  internal/notification/consumer/balancethreshold_test.go
  internal/notification/consumer/balancetreshold.go
  internal/notification/consumer/consumer.go
  internal/notification/event.go
  internal/notification/repository/repository.go
  internal/notification/rule.go
  internal/productcatalog/driver/feature.go
  internal/productcatalog/driver/parser.go
  test/notification/consumer_balance.go
  test/notification/notification_test.go
Labels: release-note/feature, area/notification

#1403 feat: set max processing time for sarama consumers
  internal/watermill/driver/kafka/subscriber.go
Labels: release-note/misc

#1402 ci: separate build cache for quickstart
  ci/main.go
Labels: release-note/ignore

#1404 fix: infinite loop processing events
  cmd/balance-worker/main.go
  cmd/notification-service/main.go
  internal/entitlement/balanceworker/entitlementhandler.go
  internal/entitlement/balanceworker/ingesthandler.go
  internal/entitlement/balanceworker/worker.go
  internal/watermill/eventbus/eventbus.go
  internal/watermill/router/metrics.go
  internal/watermill/router/router.go
Labels: release-note/bug-fix, area/entitlements

#1405 fix: issues around balance snapshots
  internal/entitlement/entitlement.go
  internal/notification/consumer/balancetreshold.go
  internal/notification/consumer/consumer.go
Labels: release-note/bug-fix

#1406 fix: notification service startup issues
  internal/notification/consumer/consumer.go
Labels: release-note/bug-fix

#1408 Fix bug with recurrence
  internal/credit/engine/engine.go
  test/entitlement/regression/scenario_test.go
Labels: release-note/bug-fix

#1409 fix: Notification API
  internal/notification/channel.go
  internal/notification/repository/repository.go
  internal/notification/rule.go
  internal/notification/service.go
  internal/notification/webhook/svix.go
  internal/notification/webhook/webhook.go
Labels: release-note/bug-fix

#1410 feat: add filtering by rule and channel
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/notification/event.go
  internal/notification/httpdriver/event.go
  internal/notification/repository/repository.go
Labels: release-note/misc

#1413 refactor: annotations field for notification event
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/notification/event.go
  internal/notification/service.go
  internal/notification/utils.go
Labels: release-note/misc

#1417 feat: add support for dlq metrics
  internal/watermill/router/metrics.go
  internal/watermill/router/router.go
Labels: release-note/feature, area/balance-worker, area/notification

#1419 refactor: svix integration in Notification API
  internal/notification/httpdriver/errors.go
  internal/notification/webhook/errors.go
  internal/notification/webhook/svix.go
  internal/notification/webhook/webhook.go
Labels: release-note/misc

#1420 fix: update of channel assignment for rules
  internal/notification/repository/repository.go
  internal/notification/rule.go
  internal/notification/service.go
  internal/notification/utils.go
  internal/notification/utils_test.go
Labels: release-note/bug-fix

#1421 fix: annotation should contain subject ID
  internal/notification/consumer/balancetreshold.go
Labels: release-note/bug-fix, area/notification

#1422 Feat/node sdk notifications
  api/client/node/clients/notifications.ts
  api/client/node/index.ts
  api/client/node/package.json
  api/client/node/pnpm-lock.yaml
Labels: area/api, release-note/misc

#1424 fix: notification api
  internal/notification/httpdriver/event.go
  internal/notification/repository/entitymapping.go
  internal/notification/repository/repository.go
  internal/notification/service.go
  internal/notification/webhook/webhook.go
Labels: release-note/bug-fix

#1423 Add example seeders
  config.example.yaml
  docs/seeder.md
  etc/seed/observability.yaml
  etc/seed/streams/api-requests.yaml
  etc/seed/streams/prompt-tokens.yaml
  etc/seed/streams/workload-runtime.yaml
Labels: release-note/misc

#1434 fix: meter registration
  openmeter/watermill/driver/kafka/metrics/adapter.go
Labels: release-note/bug-fix, area/notification

#1418 Add test that go generate was run
  .golangci.yaml
  ci/generate.go
  ci/main.go
Labels: release-note/ignore

#1435 Update Dagger modules
  ci/e2e.go
  ci/go.sum
  ci/main.go
  dagger.json
  flake.lock
  flake.nix
Labels: release-note/ignore

#1433 fix: nil error on event creation
  cmd/notification-service/main.go
  cmd/server/main.go
  openmeter/notification/service.go
  test/notification/testenv.go
Labels: release-note/bug-fix, area/notification

#1437 refactor: notification
  cmd/notification-service/main.go
  cmd/server/main.go
  openmeter/notification/eventhandler.go
  openmeter/notification/eventhandler/handler.go
  openmeter/notification/repository/channel.go
  openmeter/notification/repository/event.go
  openmeter/notification/repository/repository.go
  openmeter/notification/repository/rule.go
  openmeter/notification/service.go
  openmeter/notification/service/channel.go
  openmeter/notification/service/event.go
  openmeter/notification/service/rule.go
  openmeter/notification/service/service.go
  test/notification/testenv.go
Labels: release-note/ignore

#1439 feat: add recalculation metrics
  cmd/jobs/entitlement/recalculatesnapshots.go
  openmeter/entitlement/balanceworker/recalculate.go
Labels: release-note/misc

#1441 refactor: allow recalculator reuse
  cmd/jobs/entitlement/recalculatesnapshots.go
  openmeter/entitlement/balanceworker/recalculate.go
Labels: release-note/misc

#1442 refactor: metrics
  openmeter/entitlement/balanceworker/recalculate.go
  openmeter/entitlement/balanceworker/worker.go
  openmeter/notification/consumer/consumer.go
  openmeter/sink/flushhandler/handler.go
  openmeter/sink/flushhandler/meters.go
  openmeter/watermill/driver/kafka/broker.go
  openmeter/watermill/grouphandler/grouphandler.go
  openmeter/watermill/router/metrics.go
Labels: release-note/misc

#1443 fix: remove explicit buckets
  openmeter/entitlement/balanceworker/recalculate.go
Labels: release-note/misc, area/entitlements

#1444 fix: rule assignements lost on channel update
  openmeter/notification/service/channel.go
Labels: release-note/bug-fix

#1313 Add versioned migrations
  .github/workflows/ci.yaml
  .vscode/settings.json
  Makefile
  atlas.hcl
  ci/e2e.go
  ci/migrate.go
  ci/versions_pinned.go
  cmd/balance-worker/main.go
  cmd/jobs/entitlement/init.go
  cmd/notification-service/main.go
  cmd/server/main.go
  config.example.yaml
  config/config.go
  config/config_test.go
  config/postgres.go
  dagger.json
  docker-compose.yaml
  docs/migration.md
  etc/postgres-init/svix.sql
  flake.nix
  go.mod
  go.sum
  openmeter/ent/db/runtime/runtime.go
  openmeter/entitlement/metered/utils_test.go
  openmeter/productcatalog/adapter/feature_test.go
  openmeter/registry/startup/db.go
  openmeter/testutils/pg_driver.go
  pkg/framework/entutils/database.go
  pkg/framework/entutils/entdriver/driver.go
  pkg/framework/entutils/paginate_test.go
  pkg/framework/entutils/testutils/ent1/db/runtime/runtime.go
  pkg/framework/entutils/testutils/ent2/db/runtime/runtime.go
  pkg/framework/entutils/transaction_test.go
  quickstart/config.yaml
  quickstart/docker-compose.yaml
  test/entitlement/regression/framework_test.go
  test/notification/testenv.go
  tools/migrate/migrate.go
  tools/migrate/migrate_test.go
  tools/migrate/migrations/20240826120919_init.down.sql
  tools/migrate/migrations/20240826120919_init.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/misc

#1445 refactor: balance worker metrics
  openmeter/entitlement/balanceworker/entitlementhandler.go
  openmeter/entitlement/balanceworker/recalculate.go
  openmeter/entitlement/balanceworker/worker.go
Labels: release-note/misc

#1447 refactor(api): pagination info
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  e2e/e2e_test.go
Labels: area/api, release-note/ignore
