Repository openmeterio/openmeter, pull requests merged in 2024-02, with the labels that each got.

#582 feat(subject): batch upsert
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/README.md
  api/client/node/clients/subject.ts
  api/client/node/index.ts
  api/client/node/schemas/openapi.ts
  api/client/node/test/agent.ts
  api/client/node/test/api.test.ts
  api/openapi.yaml
Labels: area/api, release-note/breaking-change, release-note/feature

#598 feat: update go to 1.22
  ci/main.go
  flake.lock
  flake.nix
  go.mod
Labels: area/dependencies

#599 chore: update oapi codegen
  api/api.gen.go
  api/client/go/client.gen.go
  go.mod
  go.sum
Labels: area/dependencies

#608 feat: update flake
  flake.lock
Labels: release-note/misc

#611 Add better error handling
  cmd/server/main.go
  go.mod
  go.sum
  internal/ingest/httpingest/httpingest.go
  internal/ingest/httpingest/httpingest_test.go
  internal/server/authenticator/authenticator.go
  internal/server/router/event.go
  internal/server/router/meter.go
  internal/server/router/meter_query.go
  internal/server/router/meter_subject.go
  internal/server/router/portal.go
  internal/server/router/router.go
  internal/server/router/subject.go
  internal/server/server.go
  internal/server/server_test.go
  pkg/contextx/attr.go
  pkg/contextx/log.go
  pkg/errorsx/handler.go
  pkg/models/problem.go
Labels: kind/refactor

#614 ci: add pipeline structure to dagger ci
  .github/workflows/release.yaml
  ci/main.go
  ci/release.go
  ci/utils.go
Labels: kind/refactor

#637 chore(meter): add more validation for the group by field
  pkg/models/meter.go
Labels: release-note/misc
