Repository openmeterio/openmeter, pull requests merged in 2024-07, with the labels that each got.

#1125 Correct Usage Period Calculations
  e2e/e2e_test.go
  internal/entitlement/boolean/connector.go
  internal/entitlement/connector.go
  internal/entitlement/entitlement.go
  internal/entitlement/entitlement_test.go
  internal/entitlement/entitlement_types.go
  internal/entitlement/metered/balance_test.go
  internal/entitlement/metered/connector.go
  internal/entitlement/metered/grant_owner_adapter.go
  internal/entitlement/static/connector.go
Labels: release-note/bug-fix

#1126 fix: remove redundant error check
  internal/sink/sink.go
Labels: release-note/ignore, kind/refactor

#1128 feat: fix issues when grant expires the same time when a reset happens
  internal/credit/balance_connector.go
  internal/credit/grant.go
  internal/credit/grant_connector.go
  internal/credit/postgresadapter/balance_snapshot.go
  internal/entitlement/boolean/connector.go
  internal/entitlement/connector.go
  internal/entitlement/httpdriver/entitlement.go
  internal/entitlement/httpdriver/metered.go
  internal/entitlement/metered/balance.go
  internal/entitlement/metered/balance_test.go
  internal/entitlement/metered/connector.go
  internal/entitlement/metered/entitlement_grant.go
  internal/entitlement/postgresadapter/entitlement.go
  internal/entitlement/static/connector.go
  internal/productcatalog/postgresadapter/feature.go
  pkg/clock/clock.go
  pkg/clock/clock_test.go
  pkg/framework/entutils/mixins.go
  test/entitlement/regression/framework_test.go
  test/entitlement/regression/scenario_test.go
Labels: area/api, release-note/bug-fix

#1131 fix: engine cannot query windowed data
  internal/entitlement/metered/grant_owner_adapter.go
Labels: release-note/bug-fix

#1133 fix(entitlement): pass config to static create
  internal/entitlement/static/connector.go
Labels: release-note/bug-fix

#1132 fix: query usage for same period as balance is queried for
  internal/entitlement/metered/balance.go
Labels: release-note/bug-fix

#1136 fix: meters weren't filtered by subject
  internal/credit/balance_connector.go
  internal/credit/owner_connector.go
  internal/entitlement/metered/grant_owner_adapter.go
Labels: area/api, release-note/bug-fix

#1137 fix: subject filtering for value endpoint
  internal/entitlement/metered/balance.go
Labels: area/api, release-note/bug-fix

#1138 refactor: split ingest and kafka specific config
  config/config_test.go
  config/ingest.go
  config/ingest_test.go
Labels: release-note/ignore, kind/refactor

#1140 fix: config validation for static entitlements
  internal/entitlement/entitlement.go
  internal/entitlement/httpdriver/entitlement.go
  internal/entitlement/httpdriver/parser.go
  internal/entitlement/postgresadapter/ent/db/entitlement.go
  internal/entitlement/postgresadapter/ent/db/entitlement_create.go
  internal/entitlement/postgresadapter/ent/db/entitlement_update.go
  internal/entitlement/postgresadapter/ent/db/migrate/schema.go
  internal/entitlement/postgresadapter/ent/db/mutation.go
  internal/entitlement/postgresadapter/ent/schema/entitlement.go
  internal/entitlement/postgresadapter/entitlement.go
  internal/entitlement/repository.go
  internal/entitlement/static/connector.go
  internal/entitlement/static/entitlement.go
Labels: kind/bug, release-note/bug-fix

#1141 fix(router): namespace driver default
  internal/server/router/router.go
Labels: area/api, release-note/bug-fix

#1142 feat: add support request in error encorder
  internal/credit/httpdriver/grant.go
  internal/entitlement/httpdriver/errors.go
  internal/ingest/ingestdriver/http_transport.go
  internal/productcatalog/httpdriver/errors.go
  pkg/framework/transport/httptransport/handler.go
Labels: release-note/ignore, kind/refactor

#1135 feat(server): return event count as prom metrics
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  cmd/server/main.go
  go.mod
  internal/debug/debug.go
  internal/debug/httpdriver/metrics.go
  internal/server/router/debug.go
  internal/server/router/router.go
  internal/server/server_test.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
  internal/streaming/connector.go
  internal/streaming/testutils/streaming.go
  pkg/framework/commonhttp/encoder.go
Labels: kind/feature, area/api, release-note/feature

#1148 feat(debug): exports
  internal/debug/httpdriver/metrics.go
  openmeter/debug/adapters.go
  openmeter/debug/httpdriver/handlers.go
  openmeter/debug/httpdriver/types.go
  openmeter/debug/types.go
Labels: area/api, release-note/ignore

#1143 Break up entitlement tests
  cmd/server/main.go
  internal/credit/balance_connector.go
  internal/credit/balancesnapshot_connector.go
  internal/credit/grant_connector.go
  internal/credit/postgresadapter/balance_snapshot.go
  internal/credit/postgresadapter/transaction.go
  internal/entitlement/metered/balance_test.go
  internal/entitlement/metered/reset_test.go
  internal/entitlement/metered/utils_test.go
  openmeter/credit/adapters.go
  openmeter/credit/postgresadapter/adapters.go
  openmeter/credit/types.go
  test/entitlement/regression/framework_test.go
  test/entitlement/regression/scenario_test.go
Labels: release-note/ignore, kind/refactor

#1150 chore: regen api
  api/client/node/schemas/openapi.ts
  api/client/python/src/openmeter/_operations/_operations.py
  api/client/python/src/openmeter/aio/_operations/_operations.py
  api/client/web/src/client/openapi.ts
Labels: release-note/ignore

#1151 feat: allow to list entitlements across namespaces
  internal/entitlement/connector.go
  internal/entitlement/httpdriver/entitlement.go
  internal/entitlement/postgresadapter/entitlement.go
Labels: kind/feature, release-note/misc, area/entitlements

#1134 Ignore irrelevant values for different entitlement types
  internal/entitlement/boolean/connector.go
  internal/entitlement/static/connector.go
Labels: release-note/bug-fix, kind/refactor

#1149 Add issueAfterResetPriority to entitlement API OM-721
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/web/src/client/openapi.ts
  api/openapi.yaml
  e2e/e2e_test.go
  internal/credit/grant.go
  internal/entitlement/entitlement.go
  internal/entitlement/httpdriver/entitlement.go
  internal/entitlement/httpdriver/parser.go
  internal/entitlement/metered/connector.go
  internal/entitlement/metered/entitlement.go
  internal/entitlement/postgresadapter/ent/db/entitlement.go
  internal/entitlement/postgresadapter/ent/db/entitlement/entitlement.go
  internal/entitlement/postgresadapter/ent/db/entitlement/where.go
  internal/entitlement/postgresadapter/ent/db/entitlement_create.go
  internal/entitlement/postgresadapter/ent/db/entitlement_update.go
  internal/entitlement/postgresadapter/ent/db/migrate/schema.go
  internal/entitlement/postgresadapter/ent/db/mutation.go
  internal/entitlement/postgresadapter/ent/schema/entitlement.go
  internal/entitlement/postgresadapter/entitlement.go
  internal/entitlement/repository.go
  pkg/convert/ptr.go
Labels: release-note/feature, area/entitlements

#1129 Use UTC in internal History APIs
  internal/credit/engine.go
  internal/credit/engine_test.go
Labels: release-note/feature

#1153 Refactor meter filtering on features
  Makefile
  internal/entitlement/metered/grant_owner_adapter.go
  internal/productcatalog/feature.go
  internal/productcatalog/feature_connector.go
  internal/productcatalog/httpdriver/feature.go
  internal/productcatalog/postgresadapter/feature.go
  pkg/convert/ptr.go
Labels: release-note/ignore

#1154 feat: add dedicated redis client package
  config/config_test.go
  config/dedupe.go
  pkg/redis/client.go
  pkg/redis/config.go
Labels: release-note/misc, area/dedupe

#1155 fix: dedup cleanup
  cmd/server/main.go
  config/dedupe.go
  internal/dedupe/dedupe.go
  internal/dedupe/memorydedupe/memorydedupe.go
  internal/dedupe/redisdedupe/redisdedupe.go
  internal/sink/sink.go
Labels: release-note/misc, area/dedupe

#1176 ci: add back git checkout step for Dagger
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .github/workflows/snapshot.yaml
Labels: release-note/ignore

#1178 feat: allow access to entitlement parser
  internal/entitlement/httpdriver/entitlement.go
  internal/entitlement/httpdriver/parser.go
  openmeter/entitlement/httpdriver/handlers.go
Labels: area/api, release-note/ignore

#1180 Hotfix for balance calculation after a grant is voided
  internal/credit/engine.go
  internal/credit/grant_connector.go
  internal/credit/postgresadapter/grant.go
  test/entitlement/regression/framework_test.go
  test/entitlement/regression/scenario_test.go
Labels: release-note/bug-fix

#1184 Only save balance for active grants during in-between snapshot saves
  internal/credit/balance_connector.go
  internal/credit/engine.go
  test/entitlement/regression/scenario_test.go
Labels: release-note/bug-fix

#1185 feat: allow searching by feature key
  internal/entitlement/connector.go
  internal/entitlement/postgresadapter/entitlement.go
Labels: area/api, release-note/ignore

#1183 Fix local Nix setup with VSCode
  flake.lock
Labels: release-note/ignore

#1186 Rename node client arguments to reflect OpenAPI OM-812
  api/client/node/clients/feature.ts
  api/client/node/clients/subject.ts
Labels: release-note/ignore

#1188 ci: upgrade Dagger
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .github/workflows/sdk-node.yaml
  .github/workflows/sdk-python.yaml
  .github/workflows/sdk-web.yaml
  .github/workflows/snapshot.yaml
  ci/build.go
  ci/e2e.go
  ci/generate.go
  ci/go.mod
  ci/go.sum
  ci/lint.go
  ci/main.go
  ci/release.go
  ci/snapshot.go
  ci/utils.go
  dagger.json
  flake.lock
  go.mod
Labels: release-note/ignore

#1199 feat(sink-worker): enable kafka client logging
  cmd/sink-worker/main.go
  config.example.yaml
  config/config_test.go
  config/ingest.go
  config/ingest_test.go
  config/testdata/complete.yaml
  internal/ingest/kafkaingest/collector.go
  pkg/kafka/config.go
Labels: area/ingest, release-note/misc

#1200 chore(deps): bump github.com/confluentinc/confluent-kafka-go to v2.5.0
  go.mod
  go.sum
Labels: area/dependencies, dependency/go, release-note/dependency-update

#1189 ci: dagger cache experiments
  ci/main.go
Labels: release-note/ignore

#1202 ci: update dagger dependencies
  ci/go.mod
  ci/go.sum
Labels: release-note/ignore

#1204 Lint improvements
  .golangci.yaml
  cmd/server/main.go
  config/ingest.go
  config/ingest_test.go
  internal/credit/balance_connector.go
  internal/credit/balance_test.go
  internal/credit/engine.go
  internal/credit/engine_test.go
  internal/credit/grant.go
  internal/credit/grant_connector.go
  internal/credit/httpdriver/grant.go
  internal/credit/owner_connector.go
  internal/credit/postgresadapter/grant.go
  internal/debug/httpdriver/metrics.go
  internal/entitlement/boolean/connector.go
  internal/entitlement/connector.go
  internal/entitlement/entitlement.go
  internal/entitlement/httpdriver/entitlement.go
  internal/entitlement/httpdriver/metered.go
  internal/entitlement/metered/balance.go
  internal/entitlement/metered/balance_test.go
  internal/entitlement/postgresadapter/entitlement.go
  internal/entitlement/repository.go
  internal/ingest/httpingest/httpingest_test.go
  internal/ingest/ingestdriver/http_transport_test.go
  internal/productcatalog/httpdriver/feature.go
  internal/productcatalog/postgresadapter/feature.go
  internal/productcatalog/postgresadapter/feature_test.go
  internal/server/authenticator/portal.go
  internal/server/router/event.go
  internal/server/router/product_catalog.go
  internal/sink/sink.go
  internal/sink/storage_test.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
  internal/streaming/testutils/streaming.go
  openmeter/credit/httpdriver/handlers.go
  openmeter/credit/httpdriver/types.go
  openmeter/credit/types.go
  openmeter/debug/httpdriver/handlers.go
  openmeter/entitlement/boolean/types.go
  openmeter/entitlement/httpdriver/handlers.go
  openmeter/entitlement/httpdriver/types.go
  openmeter/entitlement/metered/types.go
  openmeter/entitlement/static/types.go
  openmeter/entitlement/types.go
  openmeter/productcatalog/httpdriver/handlers.go
  openmeter/productcatalog/httpdriver/types.go
  openmeter/productcatalog/types.go
  openmeter/sink/sink.go
  pkg/clock/clock.go
  pkg/framework/entutils/transaction_test.go
  pkg/framework/transport/httptransport/argshandler.go
  pkg/kafka/config_test.go
  pkg/kafka/metrics/stats/stats_test.go
  pkg/numberx/number.go
  pkg/recurrence/recurrence_test.go
  test/entitlement/regression/framework_test.go
  test/entitlement/regression/scenario_test.go
Labels: release-note/ignore

#1205 ci: add bodyclose linter
  .golangci.yaml
  internal/ingest/httpingest/httpingest_test.go
  internal/ingest/ingestdriver/http_transport_test.go
  internal/server/server_test.go
Labels: release-note/ignore

#1206 chore(sdk): update Node.js dependencies
  api/client/node/package.json
  api/client/node/pnpm-lock.yaml
Labels: release-note/ignore

#1209 feat(config): validate meters config length
  config/config.go
Labels: area/api, release-note/feature

#1218 ci: run jobs on larger nodes
  .github/workflows/ci.yaml
Labels: release-note/ignore

#1219 Fix error on creating new entitlements by a key shared by active and inactive features OM-812
  internal/entitlement/connector.go
  internal/productcatalog/feature_connector.go
  internal/productcatalog/httpdriver/feature.go
  internal/productcatalog/postgresadapter/feature.go
  test/entitlement/regression/scenario_test.go
Labels: release-note/bug-fix

#1220 Allow usage granting and grant listing by feature key OM-812
  .vscode/settings.json
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/clients/subject.ts
  api/client/node/schemas/openapi.ts
  api/client/python/src/openmeter/_operations/_operations.py
  api/client/python/src/openmeter/aio/_operations/_operations.py
  api/client/web/src/client/openapi.ts
  api/openapi.yaml
  internal/entitlement/httpdriver/metered.go
  internal/entitlement/metered/connector.go
  internal/entitlement/metered/entitlement_grant.go
  internal/server/router/entitlement.go
Labels: release-note/feature

#1221 ci: disable stainless for now
  ci/snapshot.go
Labels: release-note/ignore

#1228 refactor: Notification API specification
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
Labels: area/api, release-note/misc, kind/refactor

#1233 ci: tune dagger cache
  .github/workflows/ci.yaml
  ci/build.go
  ci/generate.go
  ci/lint.go
  ci/main.go
  ci/release.go
  ci/utils.go
Labels: release-note/ignore

#1234 refactor(api): return meta object instead of id
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
Labels: area/api, release-note/misc, kind/refactor

#1239 refactor(api): notification event payload
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
Labels: kind/feature, area/api, release-note/misc

#1245 refactor(api): Notifications API
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
Labels: area/api, release-note/misc, kind/refactor

#1241 Adding a standardized pagination implementation to entitlement entities OM-779
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/clients/entitlement.ts
  api/client/node/clients/feature.ts
  api/client/node/clients/grant.ts
  api/client/node/clients/pagination.ts
  api/client/node/schemas/openapi.ts
  api/client/python/src/openmeter/_operations/_operations.py
  api/client/python/src/openmeter/aio/_operations/_operations.py
  api/client/web/src/client/openapi.ts
  api/openapi.yaml
  e2e/e2e_test.go
  internal/credit/grant_connector.go
  internal/credit/httpdriver/grant.go
  internal/credit/postgresadapter/grant.go
  internal/ent/db/paginate.go
  internal/ent/generate.go
  internal/entitlement/connector.go
  internal/entitlement/httpdriver/entitlement.go
  internal/entitlement/metered/entitlement_grant.go
  internal/entitlement/postgresadapter/entitlement.go
  internal/entitlement/repository.go
  internal/productcatalog/feature_connector.go
  internal/productcatalog/httpdriver/feature.go
  internal/productcatalog/httpdriver/parser.go
  internal/productcatalog/postgresadapter/feature.go
  internal/productcatalog/postgresadapter/feature_test.go
  pkg/framework/commonhttp/pagination.go
  pkg/framework/commonhttp/union.go
  pkg/framework/entutils/paginate.tpl
  pkg/framework/entutils/paginate_test.go
  pkg/framework/entutils/testutils/ent1/db/paginate.go
  pkg/framework/entutils/testutils/ent1/generate.go
  pkg/pagination/pagination.go
  pkg/pagination/pagination_test.go
  test/entitlement/regression/scenario_test.go
Labels: release-note/feature

#1249 feat: add event specifications
  internal/credit/events.go
  internal/entitlement/events.go
  internal/entitlement/metered/events.go
  internal/entitlement/snapshot/event.go
  internal/event/models/models.go
  internal/event/spec/event_type.go
  internal/event/spec/parser.go
  internal/event/spec/parser_test.go
  internal/event/spec/utils.go
  internal/sink/events.go
Labels: area/ingest, release-note/ignore, area/entitlements

#1253 chore: change grant ordering default to be EffectiveAt descending OM-840
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/python/src/openmeter/_operations/_operations.py
  api/client/python/src/openmeter/aio/_operations/_operations.py
  api/client/web/src/client/openapi.ts
  api/openapi.yaml
  internal/credit/grant_connector.go
  internal/credit/httpdriver/grant.go
  internal/credit/postgresadapter/grant.go
  pkg/framework/entutils/sort.go
  pkg/sortx/order.go
Labels: release-note/misc

#1250 feat: add entitlements events
  cmd/server/main.go
  config.example.yaml
  config/config.go
  config/config_test.go
  config/events.go
  go.mod
  go.sum
  internal/credit/events.go
  internal/credit/grant_connector.go
  internal/entitlement/connector.go
  internal/entitlement/entitlement.go
  internal/entitlement/metered/connector.go
  internal/entitlement/metered/events.go
  internal/entitlement/metered/reset.go
  internal/entitlement/metered/utils_test.go
  internal/event/publisher/publisher.go
  internal/event/publisher/transformer.go
  internal/event/spec/resourcepath.go
  internal/ingest/kafkaingest/namespace.go
  internal/watermill/driver/kafka/publisher.go
  internal/watermill/driver/noop/publisher.go
  openmeter/credit/adapters.go
  openmeter/entitlement/adapters.go
  openmeter/entitlement/metered/adapters.go
  openmeter/event/publisher/publisher.go
  pkg/kafka/provisiontopic.go
  test/entitlement/regression/framework_test.go
Labels: area/api, release-note/feature

#1258 chore: expose event subsystem for the cloud deployment
  cmd/server/main.go
  internal/watermill/driver/kafka/publisher.go
  openmeter/credit/events.go
  openmeter/entitlement/events.go
  openmeter/entitlement/metered/events.go
  openmeter/event/publisher/publisher.go
  openmeter/watermill/driver/kafka/driver.go
  openmeter/watermill/driver/noop/driver.go
Labels: release-note/ignore

#1257 Add filtering to entitlement entities OM-778 OM-736 OM-732
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/python/src/openmeter/_operations/_operations.py
  api/client/python/src/openmeter/aio/_operations/_operations.py
  api/client/web/src/client/openapi.ts
  api/openapi.yaml
  e2e/e2e_test.go
  internal/credit/grant_connector.go
  internal/credit/httpdriver/grant.go
  internal/credit/postgresadapter/grant.go
  internal/entitlement/connector.go
  internal/entitlement/httpdriver/entitlement.go
  internal/entitlement/postgresadapter/entitlement.go
  internal/productcatalog/feature_connector.go
  internal/productcatalog/httpdriver/feature.go
  internal/productcatalog/postgresadapter/feature.go
  pkg/framework/commonhttp/sort.go
  pkg/strcase/strcase.go
  pkg/strcase/strcase_test.go
Labels: release-note/feature

#1271 Expose methods for checking if a meter has entitlement entities associated
  internal/entitlement/postgresadapter/entitlement.go
  internal/entitlement/repository.go
  internal/productcatalog/feature_connector.go
  internal/productcatalog/postgresadapter/feature.go
Labels: release-note/misc

#1170 feat: add measureUsageFrom input OM-751
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/node/test/mocks.ts
  api/client/web/src/client/openapi.ts
  api/openapi.yaml
  e2e/e2e_test.go
  internal/entitlement/entitlement.go
  internal/entitlement/entitlement_test.go
  internal/entitlement/httpdriver/entitlement.go
  internal/entitlement/httpdriver/parser.go
  internal/entitlement/metered/connector.go
Labels: release-note/feature, area/entitlements

#1273 refactor: move sink models to a seperate package
  internal/sink/buffer.go
  internal/sink/buffer_test.go
  internal/sink/model.go
  internal/sink/models/models.go
  internal/sink/namespaces.go
  internal/sink/namespaces_test.go
  internal/sink/sink.go
  internal/sink/storage.go
  internal/sink/storage_test.go
  openmeter/sink/models/models.go
Labels: release-note/misc, area/sink-worker

#1256 feat: ingest events
  .vscode/launch.json
  cmd/sink-worker/main.go
  config.example.yaml
  config/config_test.go
  config/events.go
  internal/event/spec/resourcepath.go
  internal/sink/flushhandler/handler.go
  internal/sink/flushhandler/ingestnotification/events.go
  internal/sink/flushhandler/ingestnotification/handler.go
  internal/sink/flushhandler/meters.go
  internal/sink/flushhandler/mux.go
  internal/sink/flushhandler/types.go
  internal/sink/sink.go
  openmeter/sink/flushhandler/flushhandler.go
  openmeter/sink/flushhandler/ingestnotification/ingestnotification.go
  openmeter/sink/sink.go
Labels: area/ingest, release-note/feature

#1278 feat: add entitlements initialization - v2
  cmd/balance-worker/main.go
  cmd/server/main.go
  cmd/sink-worker/main.go
  config/aggregation.go
  internal/entitlement/balanceworker/worker.go
  internal/registry/entitlement.go
Labels: kind/refactor, area/entitlements
