Repository openmeterio/openmeter, pull requests merged in 2024-09, with the labels that each got.

#1451 feat(pagination): add helpers
  pkg/pagination/pagination.go
Labels: release-note/feature

#1436 feat(connector): add ingest timestamps
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  openmeter/ingest/kafkaingest/collector.go
  openmeter/sink/storage.go
  openmeter/sink/storage_test.go
  openmeter/streaming/clickhouse_connector/connector.go
  openmeter/streaming/clickhouse_connector/query.go
  openmeter/streaming/clickhouse_connector/query_test.go
Labels: area/api, area/processor, release-note/breaking-change, release-note/feature

#1467 fix: golangci-lint in local env
  flake.lock
  flake.nix
Labels: release-note/ignore

#1466 refactor(ingest): drop unused httpingest package
  openmeter/ingest/httpingest/httpingest.go
  openmeter/ingest/httpingest/httpingest_test.go
Labels: kind/refactor

#1468 refactor: collector meter
  cmd/server/main.go
  openmeter/ingest/ingestadapter/metrics.go
  openmeter/ingest/kafkaingest/collector.go
Labels: kind/refactor

#1471 feat(config): clickhouse connection settings
  config/aggregation.go
  config/config_test.go
Labels: area/dependencies, release-note/feature

#1469 feat: fetch expired entitlements for multiple namespaces
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/schema/entitlement.go
  openmeter/entitlement/adapter/entitlement.go
  openmeter/entitlement/metered/reset.go
  openmeter/entitlement/repository.go
  tools/migrate/migrations/20240903155435_entitlement-expired-index.down.sql
  tools/migrate/migrations/20240903155435_entitlement-expired-index.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/misc

#1474 feat: expose connection pool stats
  cmd/balance-worker/main.go
  cmd/notification-service/main.go
  cmd/server/main.go
  go.mod
  go.sum
  pkg/framework/pgdriver/driver.go
  pkg/pgxpoolobserver/observer.go
Labels: release-note/feature

#1475 refactor: kafka client configuration
  config.example.yaml
  config/config.go
  config/config_test.go
  config/kafka.go
  config/testdata/complete.yaml
  pkg/kafka/config.go
Labels: release-note/misc

#1485 fix: panic when no pool elements have been acquired
  pkg/pgxpoolobserver/observer.go
Labels: release-note/bug-fix

#1487 refactor: rm global Kafka configuration
  config.example.yaml
  config/config.go
  config/config_test.go
  config/helpers.go
  config/kafka.go
  config/sink.go
  config/testdata/complete.yaml
Labels: release-note/misc, kind/refactor

#1486 feat(api): event list
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  openmeter/server/router/event.go
  openmeter/streaming/clickhouse_connector/connector.go
  openmeter/streaming/clickhouse_connector/query.go
  openmeter/streaming/clickhouse_connector/query_test.go
  openmeter/streaming/connector.go
Labels: area/api, area/processor, release-note/feature

#1499 chore(nix): bump librdkafka to v2.5.3
  flake.nix
Labels: release-note/ignore

#1498 refactor: Kafka client setup for sink-worker
  cmd/sink-worker/main.go
  config/config_test.go
  config/sink.go
  config/testdata/complete.yaml
  e2e/config.yaml
  pkg/kafka/config.go
  quickstart/config.yaml
Labels: release-note/breaking-change, kind/refactor

#1497 Meter event validation
  openmeter/meter/meter.go
  openmeter/meter/validate.go
  openmeter/meter/validate_test.go
  openmeter/sink/namespaces.go
  openmeter/sink/namespaces_test.go
  pkg/models/meter.go
Labels: area/processor, kind/refactor

#1501 fix: Kafka consumer config
  pkg/kafka/config.go
  pkg/kafka/config_test.go
Labels: kind/bug, release-note/bug-fix

#1500 Initialize TypeSpec API
  api/spec/.gitignore
  api/spec/.npmrc
  api/spec/.prettierignore
  api/spec/.prettierrc.json
  api/spec/linter/index.js
  api/spec/linter/rules/casing.js
  api/spec/linter/rules/docs.js
  api/spec/linter/rules/utils.js
  api/spec/package.json
  api/spec/pnpm-lock.yaml
  api/spec/src/date.tsp
  api/spec/src/errors.tsp
  api/spec/src/events.tsp
  api/spec/src/key.tsp
  api/spec/src/main.tsp
  api/spec/src/metadata.tsp
  api/spec/src/pagination.tsp
  api/spec/src/types.tsp
  api/spec/tspconfig.yaml
Labels: area/api, release-note/ignore

#1502 fix: Kafka config defaults
  config/kafka.go
  config/sink.go
Labels: release-note/bug-fix

#1503 fix: defaults for Kafka broker address family
  config/kafka.go
Labels: release-note/bug-fix

#1506 fix: quickstart
  quickstart/README.md
Labels: release-note/ignore

#1508 feat(api): events subject filter full match
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  openmeter/streaming/clickhouse_connector/query.go
  openmeter/streaming/clickhouse_connector/query_test.go
Labels: area/api, release-note/bug-fix

#1504 Meter spec
  api/spec/linter/index.js
  api/spec/linter/rules/friendlyName.js
  api/spec/package.json
  api/spec/src/auth.tsp
  api/spec/src/cloud/auth.tsp
  api/spec/src/cloud/main.tsp
  api/spec/src/date.tsp
  api/spec/src/debug.tsp
  api/spec/src/errors.tsp
  api/spec/src/events.tsp
  api/spec/src/key.tsp
  api/spec/src/main.tsp
  api/spec/src/metadata.tsp
  api/spec/src/meters.tsp
  api/spec/src/portal.tsp
  api/spec/src/types.tsp
  ci/generate.go
  ci/main.go
  flake.nix
Labels: kind/feature, area/api

#1524 build: upgrade dagger modules
  dagger.json
Labels: release-note/ignore

#1525 chore(api): support style on query params in spec
  api/spec/package.json
  api/spec/patches/@typespec__http.patch
  api/spec/patches/@typespec__openapi3.patch
  api/spec/pnpm-lock.yaml
  api/spec/src/meters.tsp
Labels: release-note/ignore

#1521 TypeSpec fixes
  api/spec/src/cloud/main.tsp
  api/spec/src/cloud/subjects.tsp
  api/spec/src/entitlements.tsp
  api/spec/src/errors.tsp
  api/spec/src/main.tsp
  api/spec/src/notification.tsp
  ci/dev.go
  ci/generate.go
  dagger.json
Labels: kind/feature, area/api

#1526 fix: reduce the number of sarma metrics
  openmeter/watermill/driver/kafka/broker.go
  openmeter/watermill/driver/kafka/metrics.go
  openmeter/watermill/driver/kafka/metrics/adapter.go
Labels: release-note/misc

#1528 fix: use aggregate metrics
  openmeter/watermill/driver/kafka/metrics.go
Labels: release-note/misc

#1523 feat: add invoicing database structure
  openmeter/billing/config.go
  openmeter/billing/invoice/status.go
  openmeter/billing/invoice/tax.go
  openmeter/billing/provider/config.go
  openmeter/billing/provider/reference.go
  openmeter/ent/db/billinginvoice.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/billinginvoice/where.go
  openmeter/ent/db/billinginvoice_create.go
  openmeter/ent/db/billinginvoice_delete.go
  openmeter/ent/db/billinginvoice_query.go
  openmeter/ent/db/billinginvoice_update.go
  openmeter/ent/db/billinginvoiceitem.go
  openmeter/ent/db/billinginvoiceitem/billinginvoiceitem.go
  openmeter/ent/db/billinginvoiceitem/where.go
  openmeter/ent/db/billinginvoiceitem_create.go
  openmeter/ent/db/billinginvoiceitem_delete.go
  openmeter/ent/db/billinginvoiceitem_query.go
  openmeter/ent/db/billinginvoiceitem_update.go
  openmeter/ent/db/billingprofile.go
  openmeter/ent/db/billingprofile/billingprofile.go
  openmeter/ent/db/billingprofile/where.go
  openmeter/ent/db/billingprofile_create.go
  openmeter/ent/db/billingprofile_delete.go
  openmeter/ent/db/billingprofile_query.go
  openmeter/ent/db/billingprofile_update.go
  openmeter/ent/db/billingworkflowconfig.go
  openmeter/ent/db/billingworkflowconfig/billingworkflowconfig.go
  openmeter/ent/db/billingworkflowconfig/where.go
  openmeter/ent/db/billingworkflowconfig_create.go
  openmeter/ent/db/billingworkflowconfig_delete.go
  openmeter/ent/db/billingworkflowconfig_query.go
  openmeter/ent/db/billingworkflowconfig_update.go
  openmeter/ent/db/client.go
  openmeter/ent/db/ent.go
  openmeter/ent/db/expose.go
  openmeter/ent/db/hook/hook.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/paginate.go
  openmeter/ent/db/predicate/predicate.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/tx.go
  openmeter/ent/schema/billing.go
  tools/migrate/migrations/20240917172257_billing-entities.down.sql
  tools/migrate/migrations/20240917172257_billing-entities.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/billing

#1530 chore(api): add plan types to the spec
  api/spec/linter/rules/friendlyName.js
  api/spec/src/billing.tsp
  api/spec/src/discounts.tsp
  api/spec/src/entitlements.tsp
  api/spec/src/plan.tsp
  api/spec/src/prices.tsp
  api/spec/src/ratecards.tsp
  api/spec/src/types.tsp
Labels: release-note/ignore

#1533 build: rename dagger module following official conventions
  .dagger/.gitattributes
  .dagger/.gitignore
  .dagger/build.go
  .dagger/dev.go
  .dagger/e2e.go
  .dagger/generate.go
  .dagger/go.mod
  .dagger/go.sum
  .dagger/lint.go
  .dagger/main.go
  .dagger/migrate.go
  .dagger/release.go
  .dagger/snapshot.go
  .dagger/utils.go
  .dagger/versions.go
  .dagger/versions_pinned.go
  .fossa.yaml
  .golangci.yaml
  dagger.json
Labels: release-note/ignore

#1535 chore(api): add tspMain to spec's package.json
  api/spec/lib/index.js
  api/spec/lib/rules/casing.js
  api/spec/lib/rules/docs.js
  api/spec/lib/rules/friendlyName.js
  api/spec/lib/rules/utils.js
  api/spec/package.json
Labels: release-note/ignore

#1538 Upgrade dagger
  .dagger/go.mod
  .dagger/go.sum
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .github/workflows/sdk-node.yaml
  .github/workflows/sdk-python.yaml
  .github/workflows/sdk-web.yaml
  .github/workflows/snapshot.yaml
  dagger.json
  flake.lock
  flake.nix
Labels: release-note/ignore

#1536 feat(customer): add
  api/spec/src/billing.tsp
  api/spec/src/customer.tsp
  api/spec/src/types.tsp
  openmeter/customer/customer.go
  openmeter/customer/errors.go
  openmeter/customer/repository.go
  openmeter/customer/repository/customer.go
  openmeter/customer/repository/entitymapping.go
  openmeter/customer/repository/repository.go
  openmeter/customer/service.go
  openmeter/ent/client.go
  openmeter/ent/db/client.go
  openmeter/ent/db/customer.go
  openmeter/ent/db/customer/customer.go
  openmeter/ent/db/customer/where.go
  openmeter/ent/db/customer_create.go
  openmeter/ent/db/customer_delete.go
  openmeter/ent/db/customer_query.go
  openmeter/ent/db/customer_update.go
  openmeter/ent/db/customersubjects.go
  openmeter/ent/db/customersubjects/customersubjects.go
  openmeter/ent/db/customersubjects/where.go
  openmeter/ent/db/customersubjects_create.go
  openmeter/ent/db/customersubjects_delete.go
  openmeter/ent/db/customersubjects_query.go
  openmeter/ent/db/customersubjects_update.go
  openmeter/ent/db/ent.go
  openmeter/ent/db/expose.go
  openmeter/ent/db/hook/hook.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/paginate.go
  openmeter/ent/db/predicate/predicate.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/tx.go
  openmeter/ent/schema/customer.go
  pkg/framework/entutils/mixins.go
  pkg/models/model.go
  tools/migrate/migrations/20240918204720_customer.down.sql
  tools/migrate/migrations/20240918204720_customer.up.sql
  tools/migrate/migrations/atlas.sum
Labels: area/api, release-note/feature, area/billing

#1539 Dagger updates
  .dagger/ci.go
  .dagger/lint.go
  .dagger/main.go
  .dagger/migrate.go
  .dagger/test.go
  .dagger/test_e2e.go
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .github/workflows/sdk-node.yaml
  .github/workflows/sdk-python.yaml
  .github/workflows/sdk-web.yaml
  .github/workflows/snapshot.yaml
  Makefile
  dagger.json
Labels: release-note/ignore

#1542 refactor: customer features for invoicing
  openmeter/customer/customer.go
  openmeter/customer/errors.go
  openmeter/customer/repository.go
  openmeter/customer/repository/customer.go
  openmeter/customer/service.go
  openmeter/ent/db/customer.go
  openmeter/ent/db/customer/customer.go
  openmeter/ent/db/customer/where.go
  openmeter/ent/db/customer_create.go
  openmeter/ent/db/customer_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/schema/customer.go
  pkg/framework/entutils/mixins.go
  pkg/models/model.go
  pkg/timezone/tz.go
  tools/migrate/migrations/20240919144910_customer-timezone.down.sql
  tools/migrate/migrations/20240919144910_customer-timezone.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/misc, area/billing

#1543 refactor: restore dedicated param types
  openmeter/customer/customer.go
  openmeter/customer/repository.go
  openmeter/customer/repository/customer.go
  openmeter/customer/service.go
Labels: release-note/misc

#1540 feat: add diff util
  pkg/slicesx/diff.go
  pkg/slicesx/diff_test.go
Labels: release-note/misc

#1545 fix: mixin indexing tweaks
  openmeter/ent/db/migrate/schema.go
  pkg/framework/entutils/mixins.go
  tools/migrate/migrations/20240920070940_indexing-fixes.down.sql
  tools/migrate/migrations/20240920070940_indexing-fixes.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/misc

#1548 refactor: helper for provisioning Kafka topics
  openmeter/ingest/kafkaingest/namespace.go
  openmeter/watermill/driver/kafka/topic_provision.go
  pkg/kafka/provisiontopic.go
Labels: release-note/misc, kind/refactor

#1537 Add entitlements APIs and resources to TypeSpec
  .editorconfig
  .vscode/default.code-workspace
  .vscode/settings.json
  api/spec/src/cloud/main.tsp
  api/spec/src/customer.tsp
  api/spec/src/entitlements.tsp
  api/spec/src/entitlements/entitlements.tsp
  api/spec/src/entitlements/feature.tsp
  api/spec/src/entitlements/grant.tsp
  api/spec/src/entitlements/main.tsp
  api/spec/src/entitlements/subjects.tsp
  api/spec/src/main.tsp
  api/spec/src/meters.tsp
  api/spec/src/pagination.tsp
  api/spec/src/query.tsp
  api/spec/src/ratecards.tsp
  api/spec/src/types.tsp
Labels: area/api, release-note/misc

#1547 Move Features under separate package
  openmeter/entitlement/balanceworker/entitlementhandler.go
  openmeter/entitlement/balanceworker/ingesthandler.go
  openmeter/entitlement/balanceworker/recalculate.go
  openmeter/entitlement/boolean/connector.go
  openmeter/entitlement/connector.go
  openmeter/entitlement/driver/errors.go
  openmeter/entitlement/entitlement_types.go
  openmeter/entitlement/metered/balance_test.go
  openmeter/entitlement/metered/connector.go
  openmeter/entitlement/metered/grant_owner_adapter.go
  openmeter/entitlement/metered/reset_test.go
  openmeter/entitlement/metered/utils_test.go
  openmeter/entitlement/snapshot/event.go
  openmeter/entitlement/static/connector.go
  openmeter/notification/httpdriver/errors.go
  openmeter/notification/service.go
  openmeter/notification/service/service.go
  openmeter/productcatalog/adapter/feature.go
  openmeter/productcatalog/adapter/feature_test.go
  openmeter/productcatalog/adapter/transaction.go
  openmeter/productcatalog/driver/errors.go
  openmeter/productcatalog/driver/feature.go
  openmeter/productcatalog/driver/parser.go
  openmeter/productcatalog/feature/connector.go
  openmeter/productcatalog/feature/feature.go
  openmeter/productcatalog/feature/repository.go
  openmeter/registry/builder/entitlement.go
  openmeter/registry/entitlement.go
  openmeter/server/router/router.go
  openmeter/server/server_test.go
  test/entitlement/regression/framework_test.go
  test/entitlement/regression/scenario_test.go
  test/notification/consumer_balance.go
  test/notification/event.go
  test/notification/rule.go
  test/notification/testenv.go
Labels: release-note/misc

#1560 chore: update build dependencies
  .dagger/versions.go
  .dagger/versions_pinned.go
  flake.lock
  flake.nix
  justfile
Labels: release-note/ignore

#1529 Adds improved transaction handling
  openmeter/credit/adapter/transaction.go
  openmeter/credit/balance.go
  openmeter/credit/connector.go
  openmeter/credit/grant.go
  openmeter/credit/grant/owner_connector.go
  openmeter/ent/db/client.go
  openmeter/ent/db/expose.go
  openmeter/ent/db/tx.go
  openmeter/ent/entc.go
  openmeter/ent/tx/enttx.go
  openmeter/entitlement/adapter/entitlement.go
  openmeter/entitlement/adapter/transaction.go
  openmeter/entitlement/adapter/usage_reset.go
  openmeter/entitlement/connector.go
  openmeter/entitlement/metered/grant_owner_adapter.go
  openmeter/entitlement/metered/repository.go
  openmeter/entitlement/metered/reset.go
  openmeter/entitlement/metered/utils_test.go
  openmeter/entitlement/repository.go
  openmeter/productcatalog/adapter/transaction.go
  openmeter/registry/builder/entitlement.go
  pkg/framework/entutils/entexpose/expose.tpl
  pkg/framework/entutils/testutils/ent1/db/client.go
  pkg/framework/entutils/testutils/ent1/db/expose.go
  pkg/framework/entutils/testutils/ent1/db/tx.go
  pkg/framework/entutils/testutils/ent1/entc.go
  pkg/framework/entutils/testutils/ent2/db/client.go
  pkg/framework/entutils/testutils/ent2/db/expose.go
  pkg/framework/entutils/testutils/ent2/db/tx.go
  pkg/framework/entutils/testutils/ent2/entc.go
  pkg/framework/entutils/transaction.go
  pkg/framework/entutils/transaction_test.go
  pkg/framework/transaction/context.go
  pkg/framework/transaction/transaction.go
  test/entitlement/regression/framework_test.go
Labels: release-note/misc

#1544 feat(customer): crud api
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  api/spec/src/billing.tsp
  api/spec/src/customer.tsp
  api/spec/src/main.tsp
  api/spec/src/plan.tsp
  api/spec/src/types.tsp
  api/spec/tspconfig.yaml
  cmd/server/main.go
  openmeter/customer/customer.go
  openmeter/customer/defaults.go
  openmeter/customer/errors.go
  openmeter/customer/httpdriver/apimapping.go
  openmeter/customer/httpdriver/customer.go
  openmeter/customer/httpdriver/errors.go
  openmeter/customer/httpdriver/handler.go
  openmeter/customer/repository/customer.go
  openmeter/customer/repository/entitymapping.go
  openmeter/customer/service.go
  openmeter/ent/db/customer.go
  openmeter/ent/db/customer/customer.go
  openmeter/ent/db/customer/where.go
  openmeter/ent/db/customer_create.go
  openmeter/ent/db/customer_query.go
  openmeter/ent/db/customer_update.go
  openmeter/ent/db/customersubjects.go
  openmeter/ent/db/customersubjects/customersubjects.go
  openmeter/ent/db/customersubjects/where.go
  openmeter/ent/db/customersubjects_create.go
  openmeter/ent/db/customersubjects_query.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/schema/customer.go
  openmeter/server/router/customer.go
  openmeter/server/router/router.go
  pkg/framework/entutils/mixins.go
  pkg/models/model.go
  test/customer/customer.go
  test/customer/customer_test.go
  test/customer/testenv.go
  test/notification/notification_test.go
  test/notification/testenv.go
  tools/migrate/migrations/20240923170525_customer_drop_providers.down.sql
  tools/migrate/migrations/20240923170525_customer_drop_providers.up.sql
  tools/migrate/migrations/20240923180033_customer_drop_key.down.sql
  tools/migrate/migrations/20240923180033_customer_drop_key.up.sql
  tools/migrate/migrations/atlas.sum
Labels: area/api, release-note/feature

#1566 feat: billing profile
  .vscode/settings.json
  openmeter/billing/adapter.go
  openmeter/billing/adapter/adapter.go
  openmeter/billing/adapter/errors.go
  openmeter/billing/adapter/profile.go
  openmeter/billing/config.go
  openmeter/billing/errors.go
  openmeter/billing/profile.go
  openmeter/billing/provider/config.go
  openmeter/billing/provider/openmetersandbox/provider.go
  openmeter/billing/provider/reference.go
  openmeter/billing/provider/stripe/provider.go
  openmeter/billing/service.go
  openmeter/billing/service/profile.go
  openmeter/billing/service/service.go
  openmeter/ent/db/billinginvoice.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/billinginvoice/where.go
  openmeter/ent/db/billinginvoice_create.go
  openmeter/ent/db/billinginvoice_query.go
  openmeter/ent/db/billinginvoice_update.go
  openmeter/ent/db/billingprofile.go
  openmeter/ent/db/billingprofile/billingprofile.go
  openmeter/ent/db/billingprofile/where.go
  openmeter/ent/db/billingprofile_create.go
  openmeter/ent/db/billingprofile_query.go
  openmeter/ent/db/billingprofile_update.go
  openmeter/ent/db/billingworkflowconfig.go
  openmeter/ent/db/billingworkflowconfig/billingworkflowconfig.go
  openmeter/ent/db/billingworkflowconfig/where.go
  openmeter/ent/db/billingworkflowconfig_create.go
  openmeter/ent/db/billingworkflowconfig_query.go
  openmeter/ent/db/billingworkflowconfig_update.go
  openmeter/ent/db/client.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/predicate/predicate.go
  openmeter/ent/db/runtime.go
  openmeter/ent/schema/billing.go
  pkg/models/model.go
  test/billing/profile_test.go
  test/billing/suite_test.go
  test/customer/customer.go
  tools/migrate/migrations/20240917172257_billing-entities.down.sql
  tools/migrate/migrations/20240923180033_customer_drop_key.down.sql
  tools/migrate/migrations/20240924164504_billing-profile.down.sql
  tools/migrate/migrations/20240924164504_billing-profile.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/billing

#1572 feat: billing customer overrides
  .vscode/settings.json
  openmeter/billing/adapter.go
  openmeter/billing/adapter/customeroverride.go
  openmeter/billing/adapter/profile.go
  openmeter/billing/customeroverride.go
  openmeter/billing/errors.go
  openmeter/billing/profile.go
  openmeter/billing/service.go
  openmeter/billing/service/customeroverride.go
  openmeter/billing/service/profile.go
  openmeter/billing/service/service.go
  openmeter/customer/repository/entitymapping.go
  openmeter/ent/db/billingcustomeroverride.go
  openmeter/ent/db/billingcustomeroverride/billingcustomeroverride.go
  openmeter/ent/db/billingcustomeroverride/where.go
  openmeter/ent/db/billingcustomeroverride_create.go
  openmeter/ent/db/billingcustomeroverride_delete.go
  openmeter/ent/db/billingcustomeroverride_query.go
  openmeter/ent/db/billingcustomeroverride_update.go
  openmeter/ent/db/billingprofile.go
  openmeter/ent/db/billingprofile/billingprofile.go
  openmeter/ent/db/billingprofile/where.go
  openmeter/ent/db/billingprofile_create.go
  openmeter/ent/db/billingprofile_query.go
  openmeter/ent/db/billingprofile_update.go
  openmeter/ent/db/client.go
  openmeter/ent/db/customer.go
  openmeter/ent/db/customer/customer.go
  openmeter/ent/db/customer/where.go
  openmeter/ent/db/customer_create.go
  openmeter/ent/db/customer_query.go
  openmeter/ent/db/customer_update.go
  openmeter/ent/db/ent.go
  openmeter/ent/db/expose.go
  openmeter/ent/db/hook/hook.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/paginate.go
  openmeter/ent/db/predicate/predicate.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/tx.go
  openmeter/ent/schema/billing.go
  openmeter/ent/schema/customer.go
  test/billing/customeroverride_test.go
  test/billing/profile_test.go
  test/billing/suite_test.go
  tools/migrate/migrations/20240924220843_billing-customer-override.down.sql
  tools/migrate/migrations/20240924220843_billing-customer-override.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/billing

#1568 Remove unnecessary pointer return from transaction.Run
  pkg/framework/transaction/transaction.go
Labels: release-note/misc

#1567 feat(api): add Notification API to TypeSpec
  api/spec/src/cloud/main.tsp
  api/spec/src/main.tsp
  api/spec/src/notification.tsp
  api/spec/src/notification/channel.tsp
  api/spec/src/notification/event.tsp
  api/spec/src/notification/main.tsp
  api/spec/src/notification/rule.tsp
  api/spec/src/notification/svix.tsp
  api/spec/src/types.tsp
Labels: release-note/misc, kind/refactor

#1575 refactor(api): Notification API in TypeSepc
  api/spec/src/notification/channel.tsp
  api/spec/src/notification/event.tsp
  api/spec/src/notification/rule.tsp
  api/spec/src/notification/svix.tsp
  api/spec/src/types.tsp
Labels: area/api, release-note/misc

#1577 Add lint job for TypeSpec
  .dagger/generate.go
  .dagger/lint.go
  api/spec/package.json
Labels: release-note/ignore

#1578 fix(api): query explode
  api/spec/src/entitlements/entitlements.tsp
  api/spec/src/entitlements/grant.tsp
  api/spec/src/notification/event.tsp
  api/spec/src/notification/rule.tsp
Labels: area/api, release-note/misc

#1580 fix: typespec formatting
  api/spec/src/entitlements/entitlements.tsp
  api/spec/src/entitlements/grant.tsp
  api/spec/src/notification/event.tsp
  api/spec/src/notification/rule.tsp
Labels: area/api, release-note/misc

#1579 feat: bump github.com/svix/svix-webhooks to v1.36.0
  go.mod
  go.sum
  openmeter/notification/webhook/svix.go
Labels: release-note/dependency-update

#1576 feat: add pending invoice listing API
  go.mod
  go.sum
  openmeter/billing/adapter.go
  openmeter/billing/adapter/customeroverride.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/invoiceitems.go
  openmeter/billing/errors.go
  openmeter/billing/gobldriver/errors.go
  openmeter/billing/gobldriver/invoice.go
  openmeter/billing/gobldriver/invoice_test.go
  openmeter/billing/gobldriver/metadata.go
  openmeter/billing/gobldriver/validationcomplement.go
  openmeter/billing/invoice.go
  openmeter/billing/invoice/status.go
  openmeter/billing/invoiceitem.go
  openmeter/billing/provider/api/api.go
  openmeter/billing/service.go
  openmeter/billing/service/customeroverride.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceitem.go
  openmeter/billing/tax.go
  openmeter/customer/customer.go
  openmeter/customer/httpdriver/apimapping.go
  openmeter/ent/db/billinginvoice.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/billinginvoice/where.go
  openmeter/ent/db/billinginvoice_create.go
  openmeter/ent/db/billinginvoice_query.go
  openmeter/ent/db/billinginvoice_update.go
  openmeter/ent/db/billinginvoiceitem.go
  openmeter/ent/db/billinginvoiceitem/billinginvoiceitem.go
  openmeter/ent/db/billinginvoiceitem/where.go
  openmeter/ent/db/billinginvoiceitem_create.go
  openmeter/ent/db/billinginvoiceitem_query.go
  openmeter/ent/db/billinginvoiceitem_update.go
  openmeter/ent/db/customer.go
  openmeter/ent/db/customer/where.go
  openmeter/ent/db/customer_create.go
  openmeter/ent/db/customer_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  openmeter/ent/schema/customer.go
  pkg/currencyx/currency.go
  pkg/gobl/convert.go
  pkg/gobl/validation/error.go
  pkg/models/model.go
  pkg/timezone/tz.go
  test/billing/invoice_test.go
  test/customer/customer.go
  tools/migrate/migrations/20240917172257_billing-entities.down.sql
  tools/migrate/migrations/20240926164233_pending-invoice-items.down.sql
  tools/migrate/migrations/20240926164233_pending-invoice-items.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/billing

#1582 ci: use trivy db mirror to avoid rate limit
  .dagger/ci.go
  .github/workflows/artifacts.yaml
Labels: release-note/ignore

#1581 fix: required and readonly fields be optional
  api/api.gen.go
  api/codegen.yaml
  openmeter/customer/customer.go
  openmeter/entitlement/driver/metered.go
  openmeter/entitlement/driver/parser.go
  openmeter/entitlement/snapshot/event.go
  openmeter/notification/internal/rule.go
  openmeter/productcatalog/driver/parser.go
  test/notification/consumer_balance.go
  test/notification/event.go
Labels: area/api, release-note/misc

#1583 fix(api): update endpoints for Notification API
  api/spec/src/notification/channel.tsp
  api/spec/src/notification/rule.tsp
Labels: area/api, release-note/misc

#1584 TypeSpec fixes
  api/spec/src/cloud/main.tsp
  api/spec/src/cloud/subjects.tsp
  api/spec/src/entitlements/subjects.tsp
  api/spec/src/events.tsp
  api/spec/src/notification/rule.tsp
  api/spec/src/portal.tsp
Labels: kind/bug

#1588 chore(api): update Node client dependencies
  api/client/node/package-lock.json
  api/client/node/package.json
  api/client/node/pnpm-lock.yaml
Labels: release-note/dependency-update

#1589 chore(api): update web client dependencies
  api/client/web/package.json
  api/client/web/pnpm-lock.yaml
  api/client/web/src/client/openapi.ts
Labels: release-note/ignore

#1587 feat: add Kafka topic name resolver
  cmd/server/main.go
  cmd/sink-worker/main.go
  openmeter/ingest/kafkaingest/collector.go
  openmeter/ingest/kafkaingest/namespace.go
  openmeter/ingest/kafkaingest/topicresolver/namespacedtopic.go
  openmeter/ingest/kafkaingest/topicresolver/resolver.go
  openmeter/sink/sink.go
Labels: release-note/misc
