Repository openmeterio/openmeter, pull requests merged in 2024-06, with the labels that each got.

#978 Update viper
  config/viper.go
  go.mod
  go.sum
Labels: area/dependencies

#977 fix(sink-worker): prevent closing during flush operation
  internal/sink/sink.go
Labels: area/ingest, release-note/bug-fix, area/sink-worker

#991 ci: update go version
  benthos-collector.Dockerfile
  ci/main.go
  go.mod
Labels: area/dependencies, release-note/ignore

#995 Update Web SDK to include file extensions for imports
  api/client/web/.eslintrc.json
  api/client/web/package.json
  api/client/web/pnpm-lock.yaml
  api/client/web/src/client/index.ts
  api/client/web/src/index.ts
  api/client/web/src/react/hooks.ts
  api/client/web/src/react/index.ts
  api/client/web/src/react/provider.tsx
  api/client/web/tsconfig.json
Labels: area/api, release-note/bug-fix

#997 ci: add engine log export
  .github/workflows/ci.yaml
Labels: release-note/ignore

#1001 ci: fix engine log export
  .github/workflows/ci.yaml
Labels: release-note/ignore

#1003 ci: update dagger
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .github/workflows/sdk-node.yaml
  .github/workflows/sdk-python.yaml
  .github/workflows/sdk-web.yaml
  .github/workflows/snapshot.yaml
  ci/go.mod
  ci/go.sum
  dagger.json
  flake.lock
Labels: release-note/ignore

#1007 refactor: mk Kafka metrics pkg public
  cmd/server/main.go
  internal/ingest/kafkaingest/collector.go
  internal/sink/sink.go
  openmeter/ingest/kafkaingest/collector.go
  pkg/kafka/metrics/broker.go
  pkg/kafka/metrics/consumergroup.go
  pkg/kafka/metrics/metrics.go
  pkg/kafka/metrics/stats/broker.go
  pkg/kafka/metrics/stats/consumergroup.go
  pkg/kafka/metrics/stats/stats.go
  pkg/kafka/metrics/stats/stats_test.go
  pkg/kafka/metrics/stats/testdata/stats.json
  pkg/kafka/metrics/stats/topic.go
  pkg/kafka/metrics/topic.go
Labels: area/ingest, release-note/misc, area/sink-worker

#1008 chore: add go config to editorconfig
  .editorconfig
Labels: release-note/ignore

#1010 feat: add Kafka client configs
  config.example.yaml
  config/config_test.go
  config/ingest.go
  config/ingest_test.go
  config/testdata/complete.yaml
  pkg/kafka/config.go
  pkg/kafka/config_test.go
Labels: area/ingest, release-note/misc, area/sink-worker

#1011 refactor(sink-worker): add improvements
  cmd/sink-worker/main.go
  internal/sink/sink.go
Labels: release-note/misc, kind/refactor, area/sink-worker

#1012 refactor: log Kafka local errors on warn level
  internal/sink/sink.go
Labels: release-note/misc, kind/refactor, area/sink-worker

#1029 refactor(sink-worker): event parsing and validation
  internal/sink/model.go
  internal/sink/namespaces.go
  internal/sink/namespaces_test.go
  internal/sink/sink.go
  internal/sink/storage.go
  internal/sink/storage_test.go
Labels: release-note/ignore, kind/refactor, area/sink-worker

#1031 build: update dagger
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .github/workflows/sdk-node.yaml
  .github/workflows/sdk-python.yaml
  .github/workflows/sdk-web.yaml
  .github/workflows/snapshot.yaml
  ci/go.mod
  ci/go.sum
  dagger.json
  flake.lock
Labels: release-note/ignore

#1030 Move examples
  README.md
  examples/customer-dashboard-nextjs/.env.example
  examples/customer-dashboard-nextjs/.eslintrc.json
  examples/customer-dashboard-nextjs/.gitignore
  examples/customer-dashboard-nextjs/.npmrc
  examples/customer-dashboard-nextjs/.prettierignore
  examples/customer-dashboard-nextjs/.prettierrc.json
  examples/customer-dashboard-nextjs/README.md
  examples/customer-dashboard-nextjs/environment.d.ts
  examples/customer-dashboard-nextjs/next.config.js
  examples/customer-dashboard-nextjs/package.json
  examples/customer-dashboard-nextjs/pnpm-lock.yaml
  examples/customer-dashboard-nextjs/postcss.config.js
  examples/customer-dashboard-nextjs/public/next.svg
  examples/customer-dashboard-nextjs/public/vercel.svg
  examples/customer-dashboard-nextjs/src/app/Query.client.tsx
  examples/customer-dashboard-nextjs/src/app/api/token/route.ts
  examples/customer-dashboard-nextjs/src/app/favicon.ico
  examples/customer-dashboard-nextjs/src/app/globals.css
  examples/customer-dashboard-nextjs/src/app/layout.tsx
  examples/customer-dashboard-nextjs/src/app/page.tsx
  examples/customer-dashboard-nextjs/tailwind.config.ts
  examples/customer-dashboard-nextjs/tsconfig.json
  examples/export-stripe-go/README.md
  examples/export-stripe-go/go.mod
  examples/export-stripe-go/go.sum
  examples/export-stripe-go/main.go
  examples/export-stripe-go/report.go
  examples/export-stripe-go/setup.go
  examples/export-stripe-node/.gitignore
  examples/export-stripe-node/.prettierrc.json
  examples/export-stripe-node/README.md
  examples/export-stripe-node/app.ts
  examples/export-stripe-node/package-lock.json
  examples/export-stripe-node/package.json
  examples/export-stripe-node/setup.ts
  examples/export-stripe-node/tsconfig.json
  examples/ingest-fastify-node/.gitignore
  examples/ingest-fastify-node/.prettierrc.json
  examples/ingest-fastify-node/README.md
  examples/ingest-fastify-node/app.ts
  examples/ingest-fastify-node/package-lock.json
  examples/ingest-fastify-node/package.json
  examples/ingest-fastify-node/tsconfig.json
  examples/ingest-kubernetes-pod-time-go/README.md
Labels: release-note/ignore

#1033 chore: update nix flake
  flake.lock
Labels: release-note/ignore

#1035 ci: update Dagger dependencies
  ci/go.mod
  ci/go.sum
Labels: area/dependencies

#1036 feat(benthos): add tracing to openmeter output
  Makefile
  collector/benthos/output/openmeter.go
  etc/seed/seed.yaml
  go.mod
  go.sum
Labels: kind/feature, release-note/misc, kind/refactor, area/collectors

#1037 chore: fix copy paste
  collector/benthos/input/otel_log.go
Labels: release-note/misc, area/collectors

#1038 Fix panic in e2e tests
  e2e/e2e_test.go
Labels: release-note/misc

#976 feat: add callbacks support for ingested batches
  internal/sink/namespaces.go
  internal/sink/namespaces_test.go
  internal/sink/sink.go
  openmeter/sink/sink.go
Labels: kind/feature, area/ingest, kind/refactor, area/sink-worker

#1050 refactor: rename recurrnace values
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  api/types/entitlement.go
  e2e/e2e_test.go
  internal/credit/engine_test.go
  internal/credit/postgresadapter/ent/db/grant/grant.go
  internal/credit/postgresadapter/ent/db/migrate/schema.go
  internal/credit/recurrence.go
  internal/credit/recurrence_test.go
Labels: area/api, kind/refactor

#1051 feat: entitlements list API
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/entitlement/db_connector.go
  internal/entitlement/entitlement_connector.go
  internal/entitlement/httpdriver/entitlement.go
  internal/entitlement/postgresadapter/entitlement.go
  internal/server/router/entitlement.go
  internal/server/router/noop.go
  openmeter/entitlement/httpdriver/handlers.go
  openmeter/entitlement/httpdriver/types.go
  pkg/models/model.go
Labels: kind/feature, area/api, release-note/feature, area/entitlements

#1059 chore: add command to gen sdks
  Makefile
Labels: release-note/misc

#1061 chore: update viper
  go.mod
  go.sum
Labels: area/dependencies

#1068 Storing Usage Period
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/web/src/client/openapi.ts
  api/openapi.yaml
  api/types/entitlement.go
  e2e/e2e_test.go
  internal/credit/recurrence.go
  internal/entitlement/connector.go
  internal/entitlement/entitlement.go
  internal/entitlement/httpdriver/entitlement.go
  internal/entitlement/httpdriver/parser.go
  internal/entitlement/metered/balance_test.go
  internal/entitlement/metered/grant_owner_adapter.go
  internal/entitlement/postgresadapter/entitlement.go
  internal/entitlement/repository.go
  internal/entitlement/static/connector.go
  internal/productcatalog/feature_connector.go
  internal/productcatalog/httpdriver/feature.go
  internal/productcatalog/postgresadapter/feature.go
  internal/productcatalog/postgresadapter/feature_test.go
  internal/server/router/entitlement.go
Labels: release-note/feature, area/entitlements

#1067 feat: entitlement auto reset support pt1
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/python/src/openmeter/_operations/_operations.py
  api/client/python/src/openmeter/aio/_operations/_operations.py
  api/client/web/src/client/openapi.ts
  api/openapi.yaml
  internal/credit/balance_connector.go
  internal/credit/engine.go
  internal/credit/engine_test.go
  internal/credit/grant.go
  internal/credit/grant_connector.go
  internal/credit/history.go
  internal/credit/owner_connector.go
  internal/credit/period.go
  internal/credit/postgresadapter/ent/db/grant.go
  internal/credit/postgresadapter/ent/db/grant/grant.go
  internal/credit/postgresadapter/ent/db/grant/where.go
  internal/credit/postgresadapter/ent/db/grant_create.go
  internal/credit/postgresadapter/ent/db/mutation.go
  internal/credit/postgresadapter/ent/schema/grant.go
  internal/credit/postgresadapter/grant.go
  internal/entitlement/connector.go
  internal/entitlement/entitlement.go
  internal/entitlement/httpdriver/entitlement.go
  internal/entitlement/httpdriver/metered.go
  internal/entitlement/httpdriver/parser.go
  internal/entitlement/metered/balance.go
  internal/entitlement/metered/balance_test.go
  internal/entitlement/metered/connector.go
  internal/entitlement/metered/entitlement.go
  internal/entitlement/metered/grant_owner_adapter.go
  internal/entitlement/postgresadapter/ent/db/entitlement.go
  internal/entitlement/postgresadapter/ent/db/entitlement/entitlement.go
  internal/entitlement/postgresadapter/ent/db/entitlement/where.go
  internal/entitlement/postgresadapter/ent/db/entitlement_create.go
  internal/entitlement/postgresadapter/ent/db/entitlement_update.go
  internal/entitlement/postgresadapter/ent/db/migrate/schema.go
  internal/entitlement/postgresadapter/ent/db/mutation.go
  internal/entitlement/postgresadapter/ent/schema/entitlement.go
  internal/entitlement/postgresadapter/entitlement.go
  internal/entitlement/repository.go
  openmeter/credit/types.go
  pkg/recurrence/period.go
  pkg/recurrence/recurrence.go
  pkg/recurrence/recurrence_test.go
Labels: kind/feature, area/api, release-note/feature

#1076 Unify error handling for entitlements
  internal/entitlement/httpdriver/entitlement.go
  internal/entitlement/httpdriver/errors.go
  internal/entitlement/httpdriver/metered.go
Labels: release-note/bug-fix, area/entitlements

#1077 feat: implement get and delete
  internal/entitlement/connector.go
  internal/entitlement/httpdriver/entitlement.go
  internal/entitlement/postgresadapter/entitlement.go
  internal/entitlement/repository.go
  internal/server/router/entitlement.go
  internal/server/router/noop.go
  openmeter/entitlement/httpdriver/handlers.go
  openmeter/entitlement/httpdriver/types.go
Labels: kind/feature, release-note/feature, area/entitlements

#1074 fix: make sure we are handling nil maps
  internal/entitlement/httpdriver/parser.go
  pkg/convert/ptr.go
Labels: area/api, release-note/ignore

#1078 fix: expose deletion handlers
  openmeter/entitlement/httpdriver/handlers.go
Labels: area/api, release-note/ignore

#1080 Feat/automatic grant issuing
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  e2e/e2e_test.go
  internal/credit/grant.go
  internal/credit/grant_connector.go
  internal/credit/postgresadapter/ent/db/grant.go
  internal/credit/postgresadapter/ent/db/grant/grant.go
  internal/credit/postgresadapter/ent/db/grant/where.go
  internal/credit/postgresadapter/ent/db/grant_create.go
  internal/credit/postgresadapter/ent/db/migrate/schema.go
  internal/credit/postgresadapter/ent/db/mutation.go
  internal/credit/postgresadapter/ent/schema/grant.go
  internal/credit/postgresadapter/grant.go
  internal/entitlement/boolean/connector.go
  internal/entitlement/connector.go
  internal/entitlement/entitlement_types.go
  internal/entitlement/httpdriver/metered.go
  internal/entitlement/metered/balance.go
  internal/entitlement/metered/connector.go
  internal/entitlement/metered/entitlement.go
  internal/entitlement/metered/entitlement_grant.go
  internal/entitlement/metered/reset.go
  internal/entitlement/static/connector.go
Labels: kind/feature, area/entitlements

#1079 feat: return history from last reset
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/python/src/openmeter/_operations/_operations.py
  api/client/python/src/openmeter/aio/_operations/_operations.py
  api/client/web/src/client/openapi.ts
  api/openapi.yaml
  internal/entitlement/httpdriver/metered.go
  internal/entitlement/metered/balance.go
  internal/entitlement/metered/balance_test.go
Labels: area/api, release-note/feature

#1084 feat: access entitlement value via featureKey
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/python/src/openmeter/_operations/_operations.py
  api/client/python/src/openmeter/aio/_operations/_operations.py
  api/client/web/src/client/openapi.ts
  api/openapi.yaml
  e2e/e2e_test.go
  internal/entitlement/connector.go
  internal/entitlement/entitlement.go
  internal/entitlement/httpdriver/entitlement.go
  internal/entitlement/httpdriver/parser.go
  internal/entitlement/metered/balance_test.go
  internal/entitlement/postgresadapter/ent/db/entitlement.go
  internal/entitlement/postgresadapter/ent/db/entitlement/entitlement.go
  internal/entitlement/postgresadapter/ent/db/entitlement/where.go
  internal/entitlement/postgresadapter/ent/db/entitlement_create.go
  internal/entitlement/postgresadapter/ent/db/migrate/schema.go
  internal/entitlement/postgresadapter/ent/db/mutation.go
  internal/entitlement/postgresadapter/ent/db/runtime.go
  internal/entitlement/postgresadapter/ent/schema/entitlement.go
  internal/entitlement/postgresadapter/entitlement.go
  internal/entitlement/repository.go
Labels: kind/feature

#1091 feat: add type alias for MeteredEntitlementValue
  openmeter/entitlement/metered/types.go
Labels: area/api, release-note/ignore

#1092 feat: add subjectKey to entitlement list params
  internal/entitlement/connector.go
  internal/entitlement/postgresadapter/entitlement.go
  openmeter/entitlement/types.go
Labels: area/api, release-note/misc

#1093 feat(api): allow filtering entitlements by feature IDs
  internal/entitlement/connector.go
  internal/entitlement/postgresadapter/entitlement.go
Labels: area/api, release-note/misc

#1094 feat(api): allow filtering features by meterslug
  internal/productcatalog/feature_connector.go
  internal/productcatalog/postgresadapter/feature.go
Labels: area/api, release-note/misc

#1095 fix(api): query used for filtering entitlements
  internal/entitlement/postgresadapter/entitlement.go
Labels: kind/bug, area/api, release-note/misc

#1096 fix: expose delete handler params
  openmeter/entitlement/httpdriver/handlers.go
  openmeter/entitlement/httpdriver/types.go
Labels: release-note/bug-fix

#1097 fix: fetch query params of archived features
  internal/entitlement/metered/grant_owner_adapter.go
Labels: release-note/bug-fix

#1098 feat: add encoding errors for feature API
  internal/productcatalog/httpdriver/errors.go
  internal/productcatalog/httpdriver/feature.go
Labels: area/api, release-note/misc

#1099 feat: expose entitlement response object
  openmeter/entitlement/metered/types.go
Labels: area/api, release-note/ignore

#1102 chore(direnv): upgrade to 3.0.5
  .envrc
Labels: area/dependencies, release-note/ignore

#1103 fix(api): feature times
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/clients/feature.ts
  api/client/node/package-lock.json
  api/openapi.yaml
  internal/productcatalog/feature.go
Labels: area/api, release-note/bug-fix

#1104 feat(api): add feature and entitlement to node api
  api/client/node/README.md
  api/client/node/clients/client.ts
  api/client/node/clients/entitlement.ts
  api/client/node/clients/feature.ts
  api/client/node/clients/grant.ts
  api/client/node/clients/subject.ts
  api/client/node/index.ts
  api/client/node/schemas/openapi.ts
  api/client/node/test/agent.ts
  api/client/node/test/api.test.ts
  api/client/node/test/mocks.ts
Labels: area/api, release-note/feature

#1106 feat: add support for 1d meters
  cmd/server/main.go
  internal/credit/balance_connector.go
  internal/credit/engine.go
  internal/credit/engine_test.go
  internal/credit/owner_connector.go
  internal/entitlement/connector.go
  internal/entitlement/metered/balance.go
  internal/entitlement/metered/balance_test.go
  internal/entitlement/metered/grant_owner_adapter.go
  openmeter/entitlement/adapters.go
Labels: area/api, release-note/bug-fix

#1105 feat: include entitlement creation in a single transaction
  internal/credit/grant_connector.go
  internal/entitlement/boolean/connector.go
  internal/entitlement/connector.go
  internal/entitlement/entitlement_types.go
  internal/entitlement/metered/connector.go
  internal/entitlement/metered/grant_owner_adapter.go
  internal/entitlement/static/connector.go
  pkg/framework/entutils/transaction.go
Labels: release-note/bug-fix

#1100 refactor: store feature config field as byte slice
  internal/entitlement/entitlement.go
  internal/entitlement/httpdriver/entitlement.go
  internal/entitlement/httpdriver/parser.go
  internal/entitlement/postgresadapter/ent/db/entitlement.go
  internal/entitlement/postgresadapter/ent/db/entitlement_create.go
  internal/entitlement/postgresadapter/ent/db/entitlement_update.go
  internal/entitlement/postgresadapter/ent/db/migrate/schema.go
  internal/entitlement/postgresadapter/ent/db/mutation.go
  internal/entitlement/postgresadapter/ent/schema/entitlement.go
  internal/entitlement/postgresadapter/entitlement.go
  internal/entitlement/repository.go
  internal/entitlement/static/connector.go
  internal/entitlement/static/entitlement.go
Labels: area/api, release-note/misc, kind/refactor

#1101 fix: give proper error response if the errors are wrapped
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/python/src/openmeter/_operations/_operations.py
  api/client/python/src/openmeter/aio/_operations/_operations.py
  api/client/web/src/client/openapi.ts
  api/openapi.yaml
  internal/entitlement/httpdriver/errors.go
  internal/productcatalog/httpdriver/errors.go
  pkg/errorsx/convert.go
  pkg/framework/commonhttp/errors.go
Labels: area/api, release-note/bug-fix

#1110 Validate entitlement exists for grant create and deletion
  internal/entitlement/metered/entitlement_grant.go
  internal/entitlement/postgresadapter/entitlement.go
Labels: release-note/bug-fix

#1111 Return isSoftLimit on EntitlementMetered API
  internal/entitlement/httpdriver/parser.go
Labels: release-note/bug-fix

#1113 feat: grants take effect at start of current window, not at end
  internal/credit/grant_connector.go
Labels: release-note/feature

#1114 Revert "refactor: store feature config field as byte slice"
  internal/entitlement/entitlement.go
  internal/entitlement/httpdriver/entitlement.go
  internal/entitlement/httpdriver/parser.go
  internal/entitlement/postgresadapter/ent/db/entitlement.go
  internal/entitlement/postgresadapter/ent/db/entitlement_create.go
  internal/entitlement/postgresadapter/ent/db/entitlement_update.go
  internal/entitlement/postgresadapter/ent/db/migrate/schema.go
  internal/entitlement/postgresadapter/ent/db/mutation.go
  internal/entitlement/postgresadapter/ent/schema/entitlement.go
  internal/entitlement/postgresadapter/entitlement.go
  internal/entitlement/repository.go
  internal/entitlement/static/connector.go
  internal/entitlement/static/entitlement.go
Labels: release-note/bug-fix
