Repository openmeterio/openmeter, pull requests merged in 2024-03, with the labels that each got.

#653 Add OTEL log ingestion
  .golangci.yaml
  collector/benthos/input/otel_log.go
  collector/benthos/internal/LICENSE
  collector/benthos/internal/message/batch.go
  collector/benthos/internal/message/transaction.go
  collector/benthos/internal/shutdown/signaler.go
  collector/benthos/output/otel_log.go
  examples/collectors/README.md
  examples/collectors/otel-log/.env.dist
  examples/collectors/otel-log/README.md
  examples/collectors/otel-log/config.yaml
  examples/collectors/otel-log/docker-compose.yaml
  examples/collectors/otel-log/seed/config.yaml
  go.mod
Labels: kind/feature, area/collectors

#654 fix: status code returned by ingest on invalid event
  internal/ingest/httpingest/httpingest.go
  internal/ingest/httpingest/httpingest_test.go
Labels: kind/bug

#652 feat(quickstart): use unified meters
  config.example.yaml
  examples/ingest-logs/README.md
  quickstart/README.md
  quickstart/config.yaml
  quickstart/docker-compose.yaml
  quickstart/ingest.sh
  quickstart/verify.sh
Labels: kind/documentation, release-note/ignore

#659 Fix benthos collector
  benthos-collector.Dockerfile
  deploy/charts/benthos-collector/templates/_helpers.tpl
  deploy/charts/benthos-collector/templates/deployment.yaml
  examples/collectors/database/docker-compose.common.yaml
  examples/collectors/http-server/docker-compose.yaml
Labels: kind/bug

#662 ci: free up some space on GHA
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
Labels: release-note/ignore

#663 fix(quickstart): docker compose extends
  quickstart/docker-compose.yaml
Labels: kind/bug

#664 fix(examples/otel): docker compose command
  examples/collectors/otel-log/docker-compose.yaml
Labels: kind/bug

#665 fix(meter): validate group by key
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  pkg/models/meter.go
  pkg/models/meter_test.go
Labels: kind/bug, area/api

#674 docs(client): add version to go client
  api/client/go/README.md
Labels: release-note/ignore

#679 Update openmeter.io links
  api/client/web/README.md
  examples/collectors/README.md
  examples/collectors/http-server/README.md
  examples/customer-dashboard-nextjs/README.md
Labels: release-note/ignore

#684 ci: bump dagger cache
  ci/build.go
Labels: release-note/misc

#685 ci: increase lint timeout
  .golangci.yaml
Labels: release-note/ignore

#698 chore: update broken link to nextjs example
  api/client/web/README.md
Labels: kind/documentation, release-note/ignore

#681 feat(query): filter by group by
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/server/router/meter_query.go
  internal/server/server.go
  internal/server/server_test.go
  internal/streaming/clickhouse_connector/connector.go
  internal/streaming/clickhouse_connector/query.go
  internal/streaming/clickhouse_connector/query_test.go
  internal/streaming/query_params.go
Labels: area/api, release-note/feature

#713 fix(python): client generate
  .github/actions/free-disk-space/action.yaml
  .github/workflows/ci.yaml
  api/client/python/Dockerfile
  api/client/python/Makefile
  api/client/python/config.yaml
  api/client/python/src/openmeter/__init__.py
  api/client/python/src/openmeter/_client.py
  api/client/python/src/openmeter/_configuration.py
  api/client/python/src/openmeter/_operations/__init__.py
  api/client/python/src/openmeter/_operations/_operations.py
  api/client/python/src/openmeter/_serialization.py
  api/client/python/src/openmeter/_vendor.py
  api/client/python/src/openmeter/aio/__init__.py
  api/client/python/src/openmeter/aio/_client.py
  api/client/python/src/openmeter/aio/_configuration.py
  api/client/python/src/openmeter/aio/_operations/__init__.py
  api/client/python/src/openmeter/aio/_operations/_operations.py
  api/client/python/src/openmeter/aio/_vendor.py
Labels: area/api, release-note/dependency-update

#714 fix(ci): access python generator image
  .github/workflows/generate-client-python.yaml
Labels: release-note/ignore

#715 chore(api): update python client makefile
  api/client/python/Makefile
Labels: release-note/ignore

#722 fix(api): python client dict query serialization (filterGroupBy)
  api/client/python/examples/async/ingest.py
  api/client/python/examples/async/poetry.lock
  api/client/python/examples/async/pyproject.toml
  api/client/python/examples/async/query.py
  api/client/python/src/openmeter/_operations/_patch.py
Labels: kind/bug, area/api, release-note/bug-fix

#708 chore(api): update OpenAPI
  .spectral.yaml
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.yaml
  internal/server/authenticator/authenticator.go
  internal/server/server_test.go
Labels: area/api, release-note/misc, kind/refactor

#727 fix(api): python generator
  api/client/python/config.yaml
  api/client/python/poetry.lock
  api/client/python/pyproject.toml
  api/client/python/src/openmeter/_client.py
  api/client/python/src/openmeter/_operations/_operations.py
  api/client/python/src/openmeter/aio/_client.py
  api/client/python/src/openmeter/aio/_operations/_operations.py
Labels: release-note/ignore

#733 chore: upgrade dagger
  .github/workflows/ci.yaml
  Makefile
  ci/.gitattributes
  ci/.gitignore
  ci/dagger.json
  ci/e2e.go
  ci/go.mod
  ci/go.sum
  ci/main.go
  ci/release.go
  ci/utils.go
  dagger.json
  flake.lock
  flake.nix
Labels: kind/refactor

#734 fix: ci release
  .github/workflows/release.yaml
Labels: release-note/ignore

#710 refactor: new framework
  cmd/server/main.go
  internal/ingest/ingestdriver/http_transport.go
  internal/ingest/ingestdriver/http_transport_test.go
  internal/ingest/service.go
  internal/server/router/event.go
  internal/server/router/router.go
  internal/server/server_test.go
  openmeter/ingest/ingestdriver/http_transport.go
  openmeter/ingest/service.go
  pkg/errorsx/handler.go
  pkg/framework/README.md
  pkg/framework/internal/operation/name.go
  pkg/framework/operation/log.go
  pkg/framework/operation/middleware.go
  pkg/framework/operation/middleware_test.go
  pkg/framework/operation/name.go
  pkg/framework/operation/name_test.go
  pkg/framework/operation/operation.go
  pkg/framework/operation/operation_test.go
  pkg/framework/transport/httptransport/handler.go
  pkg/framework/transport/httptransport/options.go
Labels: kind/refactor
