Repository openmeterio/openmeter, pull requests merged in 2025-04, with the labels that each got.

#2540 feat: plan rate card discount support
  e2e/productcatalog_test.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/planphase.go
  openmeter/ent/db/planphase/planphase.go
  openmeter/ent/db/planphase_create.go
  openmeter/ent/db/planphase_update.go
  openmeter/ent/db/planratecard.go
  openmeter/ent/db/planratecard/planratecard.go
  openmeter/ent/db/planratecard/where.go
  openmeter/ent/db/planratecard_create.go
  openmeter/ent/db/planratecard_update.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/productcatalog.go
  openmeter/productcatalog/discount.go
  openmeter/productcatalog/discount_test.go
  openmeter/productcatalog/plan/adapter/mapping.go
  openmeter/productcatalog/plan/adapter/phase.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/plan/ratecard_test.go
  openmeter/productcatalog/ratecard.go
  openmeter/productcatalog/ratecard_test.go
  pkg/models/percentage.go
  tools/migrate/migrations/20250331141703_plan-rc-discounts.down.sql
  tools/migrate/migrations/20250331141703_plan-rc-discounts.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/product-catalog

#2571 fix: subject provisioning was borken
  openmeter/sink/flushhandler/ingestnotification/events/events.go
  openmeter/sink/flushhandler/ingestnotification/handler.go
Labels: release-note/bug-fix

#2573 fix: reenable affected meter reporting
  app/config/config_test.go
  app/config/sink.go
  cmd/sink-worker/main.go
  cmd/sink-worker/wire.go
  cmd/sink-worker/wire_gen.go
  openmeter/meter/adapter/meter.go
  openmeter/meter/httphandler/meter.go
  openmeter/meter/service.go
  openmeter/sink/flushhandler/ingestnotification/handler.go
  openmeter/sink/meters.go
  openmeter/sink/models/models.go
  openmeter/sink/sink.go
Labels: release-note/bug-fix, area/notification

#2575 fix(meter): respect meter event from
  openmeter/streaming/clickhouse/meter_query.go
Labels: release-note/bug-fix

#2574 feat(meter): order in listing
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/go/client_test.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/entitlements/feature.tsp
  api/spec/src/meters.tsp
  openmeter/meter/adapter/meter.go
  openmeter/meter/httphandler/meter.go
  openmeter/meter/meter.go
  openmeter/meter/service.go
  openmeter/productcatalog/adapter/feature.go
  openmeter/productcatalog/driver/feature.go
  openmeter/productcatalog/feature/connector.go
  openmeter/server/router/meter.go
Labels: area/api, release-note/feature

#2577 feat(collector): filter out run-ai resources
  collector/benthos/input/runai/pods.go
  collector/benthos/input/runai/workloads.go
Labels: release-note/feature

#2579 feat(otel): enable parent based sampling
  app/config/telemetry.go
Labels: release-note/ignore

#2581 fix: flat fee validation
  openmeter/billing/invoiceline.go
Labels: release-note/bug-fix, area/billing

#2580 chore: bump golangci-lint
  .golangci.yaml
  flake.lock
Labels: release-note/ignore

#2583 chore: fix dynamic pricing naming
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/prices.tsp
  openmeter/billing/service/lineservice/usagebasedline.go
  openmeter/billing/service/lineservice/usagebasedline_test.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/price.go
  openmeter/productcatalog/ratecard_test.go
Labels: release-note/breaking-change, area/product-catalog

#2582 chore: otelsql disable unnecessary spans
  app/common/database.go
  pkg/framework/pgdriver/driver.go
Labels: release-note/ignore

#2585 fix: stripe invoice setting
  openmeter/app/stripe/client/invoice.go
Labels: release-note/bug-fix, area/billing

#2576 feat: invoice discounts api v2
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices/discounts.tsp
  api/spec/src/billing/invoices/invoice.tsp
  api/spec/src/billing/invoices/main.tsp
  openmeter/billing/httpdriver/deprecations.go
  openmeter/billing/httpdriver/deprecations_test.go
  openmeter/billing/httpdriver/invoiceline.go
Labels: release-note/deprecation, area/billing

#2586 revert: remove invoice discounts
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/invoicediscounts.go
  openmeter/billing/invoice.go
  openmeter/billing/invoicediscount.go
  openmeter/ent/db/billinginvoice.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/billinginvoice/where.go
  openmeter/ent/db/billinginvoice_create.go
  openmeter/ent/db/billinginvoice_query.go
  openmeter/ent/db/billinginvoice_update.go
  openmeter/ent/db/billinginvoicediscount.go
  openmeter/ent/db/billinginvoicediscount/billinginvoicediscount.go
  openmeter/ent/db/billinginvoicediscount/where.go
  openmeter/ent/db/billinginvoicediscount_create.go
  openmeter/ent/db/billinginvoicediscount_query.go
  openmeter/ent/db/billinginvoicediscount_update.go
  openmeter/ent/db/billinginvoiceline.go
  openmeter/ent/db/billinginvoiceline/billinginvoiceline.go
  openmeter/ent/db/billinginvoiceline/where.go
  openmeter/ent/db/billinginvoiceline_create.go
  openmeter/ent/db/billinginvoiceline_query.go
  openmeter/ent/db/billinginvoiceline_update.go
  openmeter/ent/db/client.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  test/billing/invoice_test.go
  test/billing/invoicediscount_test.go
  tools/migrate/migrations/20250403195308_deprecate-invoice-discounts.down.sql
  tools/migrate/migrations/20250403195308_deprecate-invoice-discounts.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/ignore, area/billing

#2584 feat: add clickhouse tracing
  app/common/clickhouse.go
  app/config/aggregation.go
  cmd/balance-worker/wire_gen.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/internal/wire_gen.go
  cmd/notification-service/wire_gen.go
  cmd/server/wire_gen.go
  cmd/sink-worker/wire_gen.go
  pkg/framework/clickhouseotel/otel.go
Labels: release-note/ignore

#2592 Don't return deleted subscriptions in customer.currentSubscriptionId
  openmeter/customer/adapter/customer.go
Labels: release-note/bug-fix

#2589 galexi/refactor/subscription
  app/common/subscription.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/productcatalog/subscription/http/change.go
  openmeter/productcatalog/subscription/http/create.go
  openmeter/productcatalog/subscription/http/errors.go
  openmeter/productcatalog/subscription/http/handler.go
  openmeter/productcatalog/subscription/service.go
  openmeter/productcatalog/subscription/service/change_test.go
  openmeter/productcatalog/subscription/service/migrate.go
  openmeter/productcatalog/subscription/service/migrate_test.go
  openmeter/productcatalog/subscription/service/plan_test.go
  openmeter/productcatalog/subscription/service/service.go
  openmeter/server/router/router.go
  openmeter/server/server_test.go
  openmeter/subscription/entitlement/adapter.go
  openmeter/subscription/entitlement/errors.go
  openmeter/subscription/service.go
  openmeter/subscription/subscriptionspec.go
  openmeter/subscription/testutils/mock.go
  openmeter/subscription/testutils/service.go
  openmeter/subscription/workflow/errors.go
  openmeter/subscription/workflow/service.go
  openmeter/subscription/workflow/service/service.go
  openmeter/subscription/workflow/service/subscription.go
  openmeter/subscription/workflow/service/subscription_test.go
  test/billing/subscription_suite.go
  test/billing/subscription_test.go
  test/subscription/framework_test.go
  test/subscription/scenario_editaligned_test.go
  test/subscription/scenario_editcancel_test.go
Labels: release-note/ignore, kind/refactor

#2594 refactor(events): use error join
  openmeter/app/stripe/event.go
  openmeter/customer/event.go
  openmeter/meter/event.go
  openmeter/productcatalog/plan/event.go
Labels: release-note/ignore

#2593 refactor: productcatalog types
  openmeter/billing/httpdriver/deprecations.go
  openmeter/billing/httpdriver/deprecations_test.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/productcatalog/addon.go
  openmeter/productcatalog/addon/adapter/adapter_test.go
  openmeter/productcatalog/addon/adapter/mapping.go
  openmeter/productcatalog/addon/httpdriver/addon.go
  openmeter/productcatalog/addon/httpdriver/mapping.go
  openmeter/productcatalog/addon/service.go
  openmeter/productcatalog/addon/service/addon.go
  openmeter/productcatalog/addon/service/service_test.go
  openmeter/productcatalog/effectiveperiod.go
  openmeter/productcatalog/effectiveperiod_test.go
  openmeter/productcatalog/http/mapping.go
  openmeter/productcatalog/plan.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/plan/service/plan.go
  openmeter/productcatalog/plan_test.go
  openmeter/productcatalog/subscription/http/mapping.go
Labels: release-note/misc

#2546 Customer Access API
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/cloud/main.tsp
  api/spec/src/customer.tsp
  api/spec/src/entitlements/customer.tsp
  api/spec/src/entitlements/main.tsp
  e2e/productcatalog_test.go
  openmeter/customer/httpdriver/apimapping.go
  openmeter/customer/httpdriver/customer.go
  openmeter/customer/httpdriver/handler.go
  openmeter/customer/service.go
  openmeter/customer/service/customer.go
  openmeter/entitlement/access.go
  openmeter/entitlement/access_test.go
  openmeter/entitlement/connector.go
  openmeter/entitlement/utils_test.go
  openmeter/server/router/customer.go
  openmeter/server/router/entitlement.go
  openmeter/server/server_test.go
Labels: release-note/feature

#2588 feat: persist rate card discounts
  openmeter/billing/adapter/invoicelinemapper.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/httpdriver/deprecations.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/invoiceline.go
  openmeter/ent/db/billinginvoiceline.go
  openmeter/ent/db/billinginvoiceline/billinginvoiceline.go
  openmeter/ent/db/billinginvoiceline/where.go
  openmeter/ent/db/billinginvoiceline_create.go
  openmeter/ent/db/billinginvoiceline_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/predicate/predicate.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  openmeter/productcatalog/discount.go
  openmeter/productcatalog/http/mapping.go
  pkg/models/clonable.go
  tools/migrate/migrations/20250404145234_billing-line-ratecard-discounts.down.sql
  tools/migrate/migrations/20250404145234_billing-line-ratecard-discounts.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/billing

#2595 refactor: plan status type
  openmeter/productcatalog/plan.go
  openmeter/productcatalog/plan/adapter/adapter_test.go
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/plan/service/plan.go
  openmeter/productcatalog/plan/service/service_test.go
  openmeter/productcatalog/plan_test.go
  openmeter/productcatalog/subscription/service/change.go
Labels: release-note/ignore

#2597 fix: ratecard http mapping
  openmeter/productcatalog/http/mapping.go
Labels: release-note/bug-fix

#2598 fix(api): add-ons http API
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/routes.tsp
  openmeter/server/router/addon.go
Labels: release-note/bug-fix, release-note/ignore

#2600 fix(otel): nil ptr deref
  pkg/framework/clickhouseotel/otel.go
Labels: release-note/bug-fix

#2601 fix: nil ptr deref in billing worker
  openmeter/billing/worker/subscription/sync.go
Labels: release-note/bug-fix

#2603 fix: assume that non-flat prices are UBP
  openmeter/billing/worker/subscription/sync.go
Labels: release-note/bug-fix

#2602 fix: addon var name
  openmeter/productcatalog/addon/event.go
Labels: release-note/ignore

#2599 refactor: simplify discount handling
  openmeter/app/stripe/entity/app/invoice.go
  openmeter/billing/adapter/invoicelinediff.go
  openmeter/billing/adapter/invoicelinediff_test.go
  openmeter/billing/adapter/invoicelinemapper.go
  openmeter/billing/app.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/invoiceline.go
  openmeter/billing/service/lineservice/feeline.go
  openmeter/billing/service/lineservice/usagebasedline.go
  pkg/slicesx/empty.go
  test/app/stripe/invoice_test.go
  test/billing/adapter_test.go
  test/billing/invoice_test.go
Labels: release-note/ignore, area/billing

#2604 feat(addon): add instance type
  openmeter/ent/db/addon.go
  openmeter/ent/db/addon/addon.go
  openmeter/ent/db/addon/where.go
  openmeter/ent/db/addon_create.go
  openmeter/ent/db/addon_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/schema/addon.go
  openmeter/productcatalog/addon.go
  openmeter/productcatalog/addon/adapter/adapter_test.go
  openmeter/productcatalog/addon/adapter/addon.go
  openmeter/productcatalog/addon/adapter/mapping.go
  openmeter/productcatalog/addon/httpdriver/mapping.go
  openmeter/productcatalog/addon/service.go
  openmeter/productcatalog/addon/service/service_test.go
  tools/migrate/migrations/20250405193107_addon-instance-type.down.sql
  tools/migrate/migrations/20250405193107_addon-instance-type.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature

#2605 fix(addon): allow removing rate cards
  openmeter/productcatalog/addon/httpdriver/mapping.go
Labels: release-note/bug-fix

#2607 refactor: ratecards in productcatalog
  openmeter/productcatalog/addon/adapter/addon.go
  openmeter/productcatalog/addon/adapter/mapping.go
  openmeter/productcatalog/addon/assert.go
  openmeter/productcatalog/addon/httpdriver/mapping.go
  openmeter/productcatalog/addon/ratecard.go
  openmeter/productcatalog/addon/ratecard_test.go
  openmeter/productcatalog/plan/adapter/adapter_test.go
  openmeter/productcatalog/plan/adapter/mapping.go
  openmeter/productcatalog/plan/assert.go
  openmeter/productcatalog/plan/event.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/plan/ratecard.go
  openmeter/productcatalog/plan/ratecard_test.go
  openmeter/productcatalog/plan/service/plan.go
  openmeter/productcatalog/plan/service/service_test.go
Labels: release-note/ignore, kind/refactor

#2606 feat: add discount reason
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices/discounts.tsp
  openmeter/billing/adapter/invoicelinemapper.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/invoiceline.go
  openmeter/billing/service/lineservice/usagebasedline.go
  openmeter/billing/service/lineservice/usagebasedline_test.go
  openmeter/ent/db/billinginvoicelinediscount.go
  openmeter/ent/db/billinginvoicelinediscount/billinginvoicelinediscount.go
  openmeter/ent/db/billinginvoicelinediscount/where.go
  openmeter/ent/db/billinginvoicelinediscount_create.go
  openmeter/ent/db/billinginvoicelinediscount_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/schema/billing.go
  test/billing/adapter_test.go
  tools/migrate/migrations/20250406215430_billing-line-discount-reason.down.sql
  tools/migrate/migrations/20250406215430_billing-line-discount-reason.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/misc, area/billing

#2616 feat: add ratecards type to add-on pkg
  openmeter/productcatalog/addon/adapter/mapping.go
  openmeter/productcatalog/addon/addon.go
  openmeter/productcatalog/addon/assert.go
  openmeter/productcatalog/addon/httpdriver/mapping.go
  openmeter/productcatalog/addon/ratecard.go
  openmeter/productcatalog/addon/service.go
  openmeter/productcatalog/addon/service/addon.go
  openmeter/productcatalog/addon/service/service_test.go
  openmeter/productcatalog/plan/ratecard.go
Labels: release-note/misc, area/product-catalog

#2618 fix: panic in clickhouse otel wrapper
  pkg/framework/clickhouseotel/otel.go
Labels: release-note/bug-fix, release-note/ignore

#2620 feat: collector http server
  collector/benthos/presets/http-server/config.yaml
  collector/benthos/presets/http-server/input.yaml
  collector/benthos/presets/http-server/output.yaml
  deploy/charts/benthos-collector/README.md
  deploy/charts/benthos-collector/templates/service.yaml
  deploy/charts/benthos-collector/templates/statefulset.yaml
  deploy/charts/benthos-collector/values.yaml
Labels: release-note/feature

#2596 feat: add amount discount support
  openmeter/app/stripe/entity/app/invoice.go
  openmeter/billing/adapter/invoicelinediff.go
  openmeter/billing/adapter/invoicelinediff_test.go
  openmeter/billing/adapter/invoicelinemapper.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/app.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/invoiceline.go
  openmeter/billing/invoicelinediscount.go
  openmeter/billing/service/lineservice/feeline.go
  openmeter/billing/service/lineservice/usagebasedline.go
  openmeter/billing/service/lineservice/usagebasedline_test.go
  openmeter/ent/db/billinginvoicediscount.go
  openmeter/ent/db/billinginvoicediscount/billinginvoicediscount.go
  openmeter/ent/db/billinginvoicediscount/where.go
  openmeter/ent/db/billinginvoicediscount_create.go
  openmeter/ent/db/billinginvoicediscount_update.go
  openmeter/ent/db/billinginvoicelinediscount.go
  openmeter/ent/db/billinginvoicelinediscount/billinginvoicelinediscount.go
  openmeter/ent/db/billinginvoicelinediscount/where.go
  openmeter/ent/db/billinginvoicelinediscount_create.go
  openmeter/ent/db/billinginvoicelinediscount_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/predicate/predicate.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  openmeter/ent/schema/productcatalog.go
  openmeter/productcatalog/discount.go
  pkg/equal/equal.go
  pkg/models/model.go
  test/app/stripe/invoice_test.go
  test/billing/adapter_test.go
  test/billing/invoice_test.go
  tools/migrate/migrations/20250407191828_billing-line-discount-unit-support.down.sql
  tools/migrate/migrations/20250407191828_billing-line-discount-unit-support.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/misc, area/billing

#2623 refactor: productcatalog
  openmeter/productcatalog/addon/ratecard.go
  openmeter/productcatalog/addon/service/addon.go
  openmeter/productcatalog/plan/service/plan.go
  openmeter/productcatalog/ratecard.go
  openmeter/productcatalog/ratecard_test.go
Labels: release-note/misc

#2536 SubscriptionAddon API
  Makefile
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/cloud/main.tsp
  api/spec/src/productcatalog/routes.tsp
  api/spec/src/productcatalog/subscriptionaddon.tsp
  openmeter/server/router/subscriptionaddon.go
Labels: release-note/misc

#2625 refactor(api): subscription add-on API
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/subscriptionaddon.tsp
Labels: release-note/misc

#2624 refactor: billing pricer interface
  openmeter/billing/errors.go
  openmeter/billing/service/lineservice/pricedynamic.go
  openmeter/billing/service/lineservice/pricedynamic_test.go
  openmeter/billing/service/lineservice/priceflat.go
  openmeter/billing/service/lineservice/priceflat_test.go
  openmeter/billing/service/lineservice/pricegraduatedtiered.go
  openmeter/billing/service/lineservice/pricegraduatedtiered_test.go
  openmeter/billing/service/lineservice/pricepackage.go
  openmeter/billing/service/lineservice/pricepackage_test.go
  openmeter/billing/service/lineservice/pricer.go
  openmeter/billing/service/lineservice/pricetiered.go
  openmeter/billing/service/lineservice/priceunit.go
  openmeter/billing/service/lineservice/priceunit_test.go
  openmeter/billing/service/lineservice/pricevolumetiered.go
  openmeter/billing/service/lineservice/pricevolumetiered_test.go
  openmeter/billing/service/lineservice/usagebasedline.go
  openmeter/billing/service/lineservice/usagebasedline_test.go
  test/billing/invoice_test.go
Labels: release-note/bug-fix, area/billing

#2627 refactor: reimplement min max commitments
  openmeter/app/sandbox/mock.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/invoicelineprogressive.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/invoice.go
  openmeter/billing/invoiceline.go
  openmeter/billing/invoicelinediscount.go
  openmeter/billing/invoicelineprogressive.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoicestate.go
  openmeter/billing/service/lineservice/commitments.go
  openmeter/billing/service/lineservice/pricedynamic.go
  openmeter/billing/service/lineservice/pricedynamic_test.go
  openmeter/billing/service/lineservice/pricegraduatedtiered.go
  openmeter/billing/service/lineservice/pricegraduatedtiered_test.go
  openmeter/billing/service/lineservice/pricemutate.go
  openmeter/billing/service/lineservice/pricepackage.go
  openmeter/billing/service/lineservice/pricepackage_test.go
  openmeter/billing/service/lineservice/priceunit.go
  openmeter/billing/service/lineservice/priceunit_test.go
  openmeter/billing/service/lineservice/pricevolumetiered.go
  openmeter/billing/service/lineservice/pricevolumetiered_test.go
  openmeter/billing/service/lineservice/usagebasedline.go
  openmeter/billing/service/lineservice/usagebasedline_test.go
  openmeter/productcatalog/price.go
  test/billing/invoice_test.go
  tools/migrate/migrations/20250408162413_child-uniq-id-rename.down.sql
  tools/migrate/migrations/20250408162413_child-uniq-id-rename.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/bug-fix

#2631 fix(helm): http-server collector preset
  deploy/charts/benthos-collector/templates/_helpers.tpl
  examples/collectors/http-server/README.md
  examples/collectors/http-server/docker-compose.yaml
Labels: release-note/misc

#2632 feat: implement percentage discounts
  openmeter/app/stripe/entity/app/invoice.go
  openmeter/billing/invoicelinediscount.go
  openmeter/billing/service/lineservice/discountpercentage.go
  openmeter/billing/service/lineservice/feeline.go
  openmeter/billing/service/lineservice/feeline_test.go
  openmeter/billing/service/lineservice/priceunit_test.go
  openmeter/billing/service/lineservice/usagebasedline.go
  openmeter/billing/service/lineservice/usagebasedline_test.go
Labels: release-note/feature, area/billing

#2633 feat: introduce custom validator for addon
  openmeter/productcatalog/addon.go
  openmeter/productcatalog/addon/addon.go
  openmeter/productcatalog/addon/service/addon.go
  openmeter/productcatalog/plan/service/plan.go
  pkg/models/validator.go
Labels: release-note/ignore, release-note/misc

#2637 Remove feature.Feature from productcatalog.RateCard
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/productcatalog/addon/adapter/adapter_test.go
  openmeter/productcatalog/addon/adapter/mapping.go
  openmeter/productcatalog/addon/assert.go
  openmeter/productcatalog/addon/ratecard_test.go
  openmeter/productcatalog/addon/service/addon.go
  openmeter/productcatalog/http/mapping.go
  openmeter/productcatalog/plan/adapter/adapter_test.go
  openmeter/productcatalog/plan/adapter/mapping.go
  openmeter/productcatalog/plan/assert.go
  openmeter/productcatalog/plan/ratecard_test.go
  openmeter/productcatalog/plan/serializer.go
  openmeter/productcatalog/plan/serializer_test.go
  openmeter/productcatalog/plan/service/plan.go
  openmeter/productcatalog/plan/service/service_test.go
  openmeter/productcatalog/ratecard.go
  openmeter/productcatalog/ratecard_test.go
  openmeter/productcatalog/subscription/plan.go
  openmeter/subscription/aligment_test.go
  openmeter/subscription/testutils/ratecard.go
  openmeter/subscription/workflow/service/subscription_test.go
  test/subscription/scenario_editaligned_test.go
  test/subscription/scenario_editcancel_test.go
Labels: release-note/ignore

#2636 feat: discount correlation ID
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/convert.gen.go
  api/convert.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices/discounts.tsp
  api/spec/src/billing/invoices/invoice.tsp
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/discount.go
  openmeter/billing/httpdriver/deprecations.go
  openmeter/billing/httpdriver/discounts.go
  openmeter/billing/invoiceline.go
  openmeter/billing/invoicelinediscount.go
  openmeter/billing/service/discounts.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/service/lineservice/discountpercentage.go
  openmeter/billing/service/lineservice/feeline_test.go
  openmeter/billing/service/lineservice/priceunit_test.go
  openmeter/billing/service/lineservice/usagebasedline.go
  openmeter/billing/service/lineservice/usagebasedline_test.go
  openmeter/ent/db/billinginvoiceline.go
  openmeter/ent/db/billinginvoiceline/billinginvoiceline.go
  openmeter/ent/db/billinginvoiceline_create.go
  openmeter/ent/db/billinginvoiceline_update.go
  openmeter/ent/db/billinginvoicelinediscount.go
  openmeter/ent/db/billinginvoicelinediscount/billinginvoicelinediscount.go
  openmeter/ent/db/billinginvoicelinediscount_create.go
  openmeter/ent/db/billinginvoicelinediscount_update.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  openmeter/productcatalog/http/mapping.go
  test/billing/adapter_test.go
  test/billing/discount_test.go
Labels: release-note/feature, area/billing

#2638 Remove subscription.RateCard
  openmeter/billing/validators/subscription/validator.go
  openmeter/billing/worker/subscription/phaseiterator.go
  openmeter/billing/worker/subscription/phaseiterator_test.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/productcatalog/ratecard.go
  openmeter/productcatalog/subscription/http/mapping.go
  openmeter/productcatalog/subscription/plan.go
  openmeter/productcatalog/subscription/service/plan_test.go
  openmeter/subscription/item.go
  openmeter/subscription/patch.go
  openmeter/subscription/patch/additem_test.go
  openmeter/subscription/patch/patch_test.go
  openmeter/subscription/patch/serialization.go
  openmeter/subscription/patch/serialization_test.go
  openmeter/subscription/ratecard.go
  openmeter/subscription/repo/mapping.go
  openmeter/subscription/repo/subscriptionitemrepo.go
  openmeter/subscription/repository.go
  openmeter/subscription/service/service.go
  openmeter/subscription/service/sync_test.go
  openmeter/subscription/subscriptionspec.go
  openmeter/subscription/subscriptionview.go
  openmeter/subscription/testutils/compare.go
  openmeter/subscription/workflow/service/subscription_test.go
  test/subscription/scenario_editaligned_test.go
  test/subscription/scenario_editcancel_test.go
Labels: release-note/ignore

#2641 fix(client): JS exports
  api/client/javascript/package.json
Labels: release-note/bug-fix

#2643 fix(client): JS client query return type
  api/client/javascript/src/client/meters.ts
  api/client/javascript/src/portal/index.ts
Labels: release-note/bug-fix

#2635 feat: add plan-addon compatibility
  openmeter/productcatalog/assignment.go
  openmeter/productcatalog/entitlement.go
  openmeter/productcatalog/plan.go
  openmeter/productcatalog/ratecard.go
  openmeter/productcatalog/ratecard_test.go
Labels: release-note/feature

#2644 Fix RC serialization in events
  openmeter/productcatalog/ratecard.go
  openmeter/subscription/serialize_test.go
  openmeter/subscription/subscriptionspec.go
Labels: release-note/bug-fix

#2645 chore: fix lo.FromPtrOr usages
  openmeter/app/httpdriver/marketplace.go
  openmeter/app/stripe/entity/app/invoice.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/invoicelinemapper.go
  openmeter/billing/adapter/validationissue.go
  openmeter/billing/httpdriver/discounts.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/httpdriver/profile.go
  openmeter/billing/service/invoice.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/entitlement/adapter/entitlement.go
  openmeter/productcatalog/addon.go
  openmeter/productcatalog/addon/adapter/mapping.go
  openmeter/productcatalog/addon/assert.go
  openmeter/productcatalog/addon/httpdriver/addon.go
  openmeter/productcatalog/addon/service.go
  openmeter/productcatalog/effectiveperiod.go
  openmeter/productcatalog/http/mapping.go
  openmeter/productcatalog/plan.go
  openmeter/productcatalog/plan/adapter/mapping.go
  openmeter/productcatalog/plan/assert.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/plan/httpdriver/plan.go
  openmeter/productcatalog/plan/service.go
  openmeter/productcatalog/price.go
  openmeter/productcatalog/subscription/http/change.go
  openmeter/productcatalog/subscription/http/create.go
  openmeter/productcatalog/subscription/http/mapping.go
  openmeter/productcatalog/subscription/plan.go
  openmeter/server/router/billing.go
  openmeter/subscription/repo/mapping.go
  test/app/stripe/invoice_test.go
  test/billing/invoice_test.go
Labels: release-note/ignore

#2646 chore: schema fixes
  openmeter/ent/schema/billing.go
Labels: release-note/ignore

#2647 feat: record pre line metered quantity
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices/invoice.tsp
  openmeter/billing/adapter/invoicelinemapper.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/invoiceline.go
  openmeter/billing/service/lineservice/usagebasedline.go
  openmeter/billing/service/lineservice/usagebasedline_test.go
  openmeter/ent/db/billinginvoiceusagebasedlineconfig.go
  openmeter/ent/db/billinginvoiceusagebasedlineconfig/billinginvoiceusagebasedlineconfig.go
  openmeter/ent/db/billinginvoiceusagebasedlineconfig/where.go
  openmeter/ent/db/billinginvoiceusagebasedlineconfig_create.go
  openmeter/ent/db/billinginvoiceusagebasedlineconfig_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  tools/migrate/migrations/20250411132453_billing-metered-pre-line-period-quantity.down.sql
  tools/migrate/migrations/20250411132453_billing-metered-pre-line-period-quantity.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/billing

#2648 feat: subscription <-> billing sync should syncornize discounts
  openmeter/billing/worker/subscription/sync.go
Labels: release-note/ignore, area/billing, area/product-catalog

#2649 fix(subs): item serialization
  openmeter/subscription/item.go
  openmeter/subscription/serialize_test.go
Labels: release-note/ignore

#2658 feat(api): add add-on assignments
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/productcatalog/main.tsp
  api/spec/src/productcatalog/planaddon.tsp
  api/spec/src/productcatalog/routes.tsp
  openmeter/server/router/planaddon.go
Labels: area/api, release-note/feature

#2661 feat(api): add plan add-ons to cloud API
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/spec/src/cloud/main.tsp
Labels: area/api, release-note/ignore

#2660 fix(db): fix unique key constraint of meters
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/schema/meter.go
  tools/migrate/migrations/20250414082312_meter-unique-key.down.sql
  tools/migrate/migrations/20250414082312_meter-unique-key.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/bug-fix

#2642 Refactor Periods
  openmeter/billing/worker/subscription/phaseiterator.go
  openmeter/credit/balance.go
  openmeter/credit/balance/service.go
  openmeter/credit/balance/service_test.go
  openmeter/credit/balance/usage.go
  openmeter/credit/engine/burnphase.go
  openmeter/credit/engine/grant.go
  openmeter/credit/engine/history.go
  openmeter/credit/engine/run.go
  openmeter/credit/engine/run_test.go
  openmeter/credit/grant/grant.go
  openmeter/credit/grant/owner_connector.go
  openmeter/credit/helper.go
  openmeter/credit/trace.go
  openmeter/entitlement/adapter/entitlement.go
  openmeter/entitlement/adapter/entitlement_test.go
  openmeter/entitlement/adapter/usage_reset.go
  openmeter/entitlement/boolean/connector.go
  openmeter/entitlement/driver/parser.go
  openmeter/entitlement/entitlement.go
  openmeter/entitlement/metered/balance.go
  openmeter/entitlement/metered/entitlement.go
  openmeter/entitlement/metered/grant_owner_adapter.go
  openmeter/entitlement/metered/grant_owner_adapter_test.go
  openmeter/entitlement/metered/lateevents_test.go
  openmeter/entitlement/metered/repository.go
  openmeter/entitlement/metered/reset_test.go
  openmeter/entitlement/metered/trace.go
  openmeter/entitlement/repository.go
  openmeter/entitlement/snapshot/event.go
  openmeter/entitlement/static/connector.go
  openmeter/notification/consumer/balancetreshold.go
  openmeter/subscription/subscriptionspec.go
  pkg/models/cadence.go
  pkg/timeutil/closedperiod.go
  pkg/timeutil/closedperiod_test.go
  pkg/timeutil/openperiod.go
  pkg/timeutil/openperiod_test.go
  pkg/timeutil/period.go
  pkg/timeutil/recurrence.go
  pkg/timeutil/recurrence_test.go
  pkg/timeutil/timeline.go
  test/notification/consumer_balance.go
Labels: release-note/ignore

#2664 fix(pc): fix rc comparison
  openmeter/productcatalog/ratecard.go
Labels: release-note/bug-fix

#2665 fix(collector): run-ai metric timestamps
  collector/benthos/input/run_ai.go
  collector/benthos/input/runai/metrics.go
Labels: release-note/bug-fix

#2666 feat(collector): add run_ai_resource_count metric and status code to run_ai_http_request_ns
  collector/benthos/input/run_ai.go
  collector/benthos/input/runai/pods.go
  collector/benthos/input/runai/service.go
  collector/benthos/input/runai/workloads.go
Labels: release-note/feature

#2663 feat: add db schema for plan add-on assignments
  openmeter/ent/db/addon.go
  openmeter/ent/db/addon/addon.go
  openmeter/ent/db/addon/where.go
  openmeter/ent/db/addon_create.go
  openmeter/ent/db/addon_query.go
  openmeter/ent/db/addon_update.go
  openmeter/ent/db/client.go
  openmeter/ent/db/ent.go
  openmeter/ent/db/expose.go
  openmeter/ent/db/hook/hook.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/paginate.go
  openmeter/ent/db/plan.go
  openmeter/ent/db/plan/plan.go
  openmeter/ent/db/plan/where.go
  openmeter/ent/db/plan_create.go
  openmeter/ent/db/plan_query.go
  openmeter/ent/db/plan_update.go
  openmeter/ent/db/planaddon.go
  openmeter/ent/db/planaddon/planaddon.go
  openmeter/ent/db/planaddon/where.go
  openmeter/ent/db/planaddon_create.go
  openmeter/ent/db/planaddon_delete.go
  openmeter/ent/db/planaddon_query.go
  openmeter/ent/db/planaddon_update.go
  openmeter/ent/db/predicate/predicate.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/db/tx.go
  openmeter/ent/schema/addon.go
  openmeter/ent/schema/planaddon.go
  openmeter/ent/schema/productcatalog.go
  pkg/framework/entutils/mixins.go
  tools/migrate/migrations/20250415105134_plan_addons.down.sql
  tools/migrate/migrations/20250415105134_plan_addons.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/ignore

#2634 feat: usage discounts
  openmeter/billing/errors.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/invoicelinediscount.go
  openmeter/billing/invoicelineprogressive.go
  openmeter/billing/service/lineservice/commitments.go
  openmeter/billing/service/lineservice/discountusage.go
  openmeter/billing/service/lineservice/meteredquantity.go
  openmeter/billing/service/lineservice/pricedynamic.go
  openmeter/billing/service/lineservice/pricegraduatedtiered.go
  openmeter/billing/service/lineservice/pricemutate.go
  openmeter/billing/service/lineservice/pricepackage.go
  openmeter/billing/service/lineservice/pricer.go
  openmeter/billing/service/lineservice/priceunit.go
  openmeter/billing/service/lineservice/pricevolumetiered.go
  openmeter/billing/service/lineservice/usagebasedline.go
  test/billing/discount_test.go
Labels: release-note/feature, area/billing

#2667 SubscriptionAddons II - Refactors
  openmeter/credit/engine/run.go
  openmeter/entitlement/metered/grant_owner_adapter.go
  openmeter/entitlement/metered/grant_owner_adapter_test.go
  openmeter/productcatalog/effectiveperiod.go
  openmeter/productcatalog/price.go
  openmeter/productcatalog/ratecard.go
  openmeter/subscription/apply.go
  openmeter/subscription/patch.go
  openmeter/subscription/patch/additem.go
  openmeter/subscription/patch/addphase.go
  openmeter/subscription/patch/patch_test.go
  openmeter/subscription/patch/removeitem.go
  openmeter/subscription/patch/removephase.go
  openmeter/subscription/patch/stretchphase.go
  openmeter/subscription/patch/unscheduleedit.go
  openmeter/subscription/patch_test.go
  openmeter/subscription/service/sync.go
  openmeter/subscription/specpath.go
  openmeter/subscription/subscriptionspec.go
  openmeter/subscription/testutils/patch.go
  openmeter/subscription/workflow/service/subscription.go
  pkg/models/cadence.go
  pkg/timeutil/openperiod.go
  pkg/timeutil/openperiod_test.go
  pkg/timeutil/timeline.go
  pkg/timeutil/timeline_test.go
Labels: release-note/feature

#2674 fix: map validation error for plan create request
  openmeter/productcatalog/plan/httpdriver/plan.go
Labels: release-note/bug-fix

#2672 feat: allow installing apps without API keys
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/app/marketplace.tsp
  api/spec/src/app/stripe.tsp
  openmeter/app/adapter.go
  openmeter/app/adapter/marketplace.go
  openmeter/app/httpdriver/handler.go
  openmeter/app/httpdriver/marketplace.go
  openmeter/app/marketplace.go
  openmeter/app/registry.go
  openmeter/app/sandbox/marketplace.go
  openmeter/app/service.go
  openmeter/app/service/marketplace.go
  openmeter/app/stripe/entity/marketplace.go
  openmeter/server/router/marketplace.go
  openmeter/server/server_test.go
  test/app/stripe/appstripe.go
  test/app/stripe/fixture.go
Labels: release-note/feature, area/apps

#2675 feat: add adapter for planaddon service
  openmeter/productcatalog/plan/adapter/mapping.go
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/plan.go
  openmeter/productcatalog/planaddon.go
  openmeter/productcatalog/planaddon/adapter/adapter.go
  openmeter/productcatalog/planaddon/adapter/adapter_test.go
  openmeter/productcatalog/planaddon/adapter/mapping.go
  openmeter/productcatalog/planaddon/adapter/planaddon.go
  openmeter/productcatalog/planaddon/assert.go
  openmeter/productcatalog/planaddon/errors.go
  openmeter/productcatalog/planaddon/errors_test.go
  openmeter/productcatalog/planaddon/event.go
  openmeter/productcatalog/planaddon/planaddon.go
  openmeter/productcatalog/planaddon/repository.go
  openmeter/productcatalog/planaddon/service.go
  openmeter/productcatalog/planaddon/testutils/addon.go
  openmeter/productcatalog/planaddon/testutils/env.go
  openmeter/productcatalog/planaddon/testutils/feature.go
  openmeter/productcatalog/planaddon/testutils/meters.go
  openmeter/productcatalog/planaddon/testutils/namespace.go
  openmeter/productcatalog/planaddon/testutils/plan.go
  openmeter/testutils/logger.go
Labels: release-note/feature

#2676 fix(api): add rest utility for nested visibility models for plan addons
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/app/app.tsp
  api/spec/src/app/stripe.tsp
  api/spec/src/billing/invoices.tsp
  api/spec/src/billing/invoices/invoice.tsp
  api/spec/src/billing/profile.tsp
  api/spec/src/customer.tsp
  api/spec/src/debug.tsp
  api/spec/src/meters.tsp
  api/spec/src/notification/channel.tsp
  api/spec/src/productcatalog/planaddon.tsp
  api/spec/src/productcatalog/routes.tsp
  api/spec/src/rest.tsp
Labels: release-note/bug-fix

#2668 SubscriptionAddons II - Diff Apply
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/db/subscriptionitem.go
  openmeter/ent/db/subscriptionitem/subscriptionitem.go
  openmeter/ent/db/subscriptionitem/where.go
  openmeter/ent/db/subscriptionitem_create.go
  openmeter/ent/db/subscriptionitem_update.go
  openmeter/ent/schema/subscription.go
  openmeter/subscription/addon/addon.go
  openmeter/subscription/addon/addon_test.go
  openmeter/subscription/addon/addonratecard.go
  openmeter/subscription/addon/diff/README.md
  openmeter/subscription/addon/diff/addon.go
  openmeter/subscription/addon/diff/apply.go
  openmeter/subscription/addon/diff/apply_test.go
  openmeter/subscription/addon/diff/diff.go
  openmeter/subscription/addon/extend.go
  openmeter/subscription/addon/instance.go
  openmeter/subscription/addon/service/change_test.go
  openmeter/subscription/addon/service/create_test.go
  openmeter/subscription/addon/service/list_test.go
  openmeter/subscription/annotations.go
  openmeter/subscription/item.go
  openmeter/subscription/repo/mapping.go
  openmeter/subscription/repo/subscriptionitemrepo.go
  openmeter/subscription/repository.go
  openmeter/subscription/subscriptionspec.go
  openmeter/subscription/subscriptionview.go
  openmeter/subscription/testutils/addon.go
  openmeter/subscription/testutils/plan.go
  openmeter/subscription/workflow/service/subscription.go
  openmeter/subscription/workflow/service/subscription_test.go
  tools/migrate/migrations/20250415143130_subs-annotations.down.sql
  tools/migrate/migrations/20250415143130_subs-annotations.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/misc

#2681 feat: add planaddon service implementation
  openmeter/productcatalog/planaddon/adapter/planaddon.go
  openmeter/productcatalog/planaddon/service/planaddon.go
  openmeter/productcatalog/planaddon/service/service.go
  openmeter/productcatalog/planaddon/service/service_test.go
Labels: release-note/feature

#2679 feat: custominvoicing db struct
  openmeter/ent/db/appcustominvoicing.go
  openmeter/ent/db/appcustominvoicing/appcustominvoicing.go
  openmeter/ent/db/appcustominvoicing/where.go
  openmeter/ent/db/appcustominvoicing_create.go
  openmeter/ent/db/appcustominvoicing_delete.go
  openmeter/ent/db/appcustominvoicing_query.go
  openmeter/ent/db/appcustominvoicing_update.go
  openmeter/ent/db/appcustominvoicingcustomer.go
  openmeter/ent/db/appcustominvoicingcustomer/appcustominvoicingcustomer.go
  openmeter/ent/db/appcustominvoicingcustomer/where.go
  openmeter/ent/db/appcustominvoicingcustomer_create.go
  openmeter/ent/db/appcustominvoicingcustomer_delete.go
  openmeter/ent/db/appcustominvoicingcustomer_query.go
  openmeter/ent/db/appcustominvoicingcustomer_update.go
  openmeter/ent/db/client.go
  openmeter/ent/db/ent.go
  openmeter/ent/db/expose.go
  openmeter/ent/db/hook/hook.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/paginate.go
  openmeter/ent/db/predicate/predicate.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/db/tx.go
  openmeter/ent/schema/appcustominvoicing.go
  tools/migrate/migrations/20250416191201_app-custominvoicing.down.sql
  tools/migrate/migrations/20250416191201_app-custominvoicing.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/ignore

#2685 fix(api): planaddon spec
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/planaddon.tsp
  api/spec/src/productcatalog/routes.tsp
  openmeter/productcatalog/planaddon/httpdriver/mapping.go
  openmeter/productcatalog/planaddon/httpdriver/planaddon.go
Labels: release-note/ignore

#2687 Use TransactingRepo
  openmeter/subscription/addon/repo/subscriptionaddon.go
Labels: release-note/bug-fix

#2669 feat(customer): return subscriptions in api with expand
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/customer.tsp
  openmeter/billing/httpdriver/customeroverride.go
  openmeter/customer/adapter/entitymapping.go
  openmeter/customer/customer.go
  openmeter/customer/httpdriver/apimapping.go
  openmeter/customer/httpdriver/customer.go
  openmeter/customer/httpdriver/handler.go
  openmeter/server/router/customer.go
  openmeter/server/router/router.go
  openmeter/subscription/repo/subscriptionrepo.go
Labels: area/api, release-note/feature

#2688 Validation for start time
  openmeter/subscription/workflow/service/addon.go
Labels: release-note/bug-fix

#2689 fix: allow add-on for draft plan
  openmeter/productcatalog/planaddon.go
  openmeter/productcatalog/planaddon/adapter/adapter_test.go
  openmeter/productcatalog/planaddon/service/service_test.go
Labels: release-note/ignore

#2690 fix: panic
  openmeter/subscription/workflow/service/addon.go
Labels: release-note/bug-fix

#2692 feat: check add-on compatibilty on plan publish
  .golangci.yaml
  openmeter/productcatalog/plan/adapter/adapter_test.go
  openmeter/productcatalog/plan/adapter/mapping.go
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/addon.go
  openmeter/productcatalog/plan/plan.go
  openmeter/productcatalog/plan/service.go
  openmeter/productcatalog/plan/service/plan.go
  openmeter/productcatalog/plan/service/service_test.go
  openmeter/productcatalog/testutils/addon.go
  openmeter/productcatalog/testutils/env.go
  openmeter/productcatalog/testutils/feature.go
  openmeter/productcatalog/testutils/meters.go
  openmeter/productcatalog/testutils/namespace.go
  openmeter/productcatalog/testutils/plan.go
Labels: release-note/feature

#2694 refactor: AsProductCatalogPlan type mapper function
  openmeter/productcatalog/plan/plan.go
  openmeter/productcatalog/plan/service/plan.go
  openmeter/productcatalog/planaddon/planaddon.go
  openmeter/productcatalog/planaddon/service/planaddon.go
  openmeter/productcatalog/subscription/service/change.go
  openmeter/productcatalog/subscription/service/create.go
  openmeter/productcatalog/subscription/service/migrate.go
  openmeter/productcatalog/subscription/service/plan.go
  openmeter/productcatalog/subscription/testutils/adapter.go
  openmeter/subscription/testutils/plan.go
Labels: release-note/ignore

#2699 refactor: use testutils in productcatalog
  openmeter/productcatalog/addon/adapter/adapter_test.go
  openmeter/productcatalog/addon/service/service_test.go
  openmeter/productcatalog/planaddon/adapter/adapter_test.go
  openmeter/productcatalog/planaddon/service/service_test.go
  openmeter/productcatalog/planaddon/testutils/addon.go
  openmeter/productcatalog/planaddon/testutils/env.go
  openmeter/productcatalog/planaddon/testutils/feature.go
  openmeter/productcatalog/planaddon/testutils/meters.go
  openmeter/productcatalog/planaddon/testutils/namespace.go
  openmeter/productcatalog/planaddon/testutils/plan.go
  openmeter/productcatalog/testutils/addon.go
Labels: release-note/ignore

#2700 feat(collector): improve run.ai metrics collection resilience
  collector/benthos/input/runai/metrics.go
Labels: release-note/feature

#2701 chore(deps): update librdkafka in nix
  flake.nix
Labels: release-note/dependency-update, release-note/ignore

#2702 fix: plan add-on assignments
  openmeter/productcatalog/addon/addon.go
  openmeter/productcatalog/addon/validators.go
  openmeter/productcatalog/plan/plan.go
  openmeter/productcatalog/plan/validators.go
  openmeter/productcatalog/planaddon.go
  openmeter/productcatalog/planaddon/service/planaddon.go
Labels: release-note/bug-fix

#2703 fix: flat fee discount idempotency
  openmeter/billing/service/lineservice/feeline.go
  openmeter/billing/worker/subscription/sync_test.go
  test/billing/discount_test.go
Labels: release-note/bug-fix, area/billing

#2704 fix: plan add-on assignment service
  openmeter/productcatalog/addon/adapter/mapping.go
  openmeter/productcatalog/plan/adapter/mapping.go
  openmeter/productcatalog/planaddon/adapter/mapping.go
  openmeter/productcatalog/planaddon/service/planaddon.go
Labels: release-note/bug-fix

#2678 feat: skaffold custom invoicing
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/apps.ts
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/app/app.tsp
  api/spec/src/app/customer.tsp
  api/spec/src/app/custominvoicing.tsp
  api/spec/src/app/main.tsp
  api/spec/src/app/stripe.tsp
  api/spec/src/productcatalog/tax.tsp
  app/common/app.go
  cmd/billing-worker/main.go
  cmd/billing-worker/wire.go
  cmd/billing-worker/wire_gen.go
  cmd/server/main.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  docker-compose.yaml
  openmeter/app/adapter/marketplace.go
  openmeter/app/app.go
  openmeter/app/appbase.go
  openmeter/app/custominvoicing/adapter.go
  openmeter/app/custominvoicing/adapter/adapter.go
  openmeter/app/custominvoicing/adapter/appconfig.go
  openmeter/app/custominvoicing/adapter/customerdata.go
  openmeter/app/custominvoicing/app.go
  openmeter/app/custominvoicing/customerdata.go
  openmeter/app/custominvoicing/factory.go
  openmeter/app/custominvoicing/service.go
  openmeter/app/custominvoicing/service/customerdata.go
  openmeter/app/custominvoicing/service/factory.go
  openmeter/app/custominvoicing/service/service.go
  openmeter/app/httpdriver/app.go
  openmeter/app/httpdriver/customer.go
  openmeter/app/httpdriver/handler.go
  openmeter/app/httpdriver/mapper.go
  openmeter/app/httpdriver/marketplace.go
  openmeter/app/registry.go
  openmeter/app/sandbox/app.go
  openmeter/app/sandbox/config.go
  openmeter/app/sandbox/mock.go
  openmeter/app/service/app.go
  openmeter/app/stripe/entity/app/config.go
  openmeter/billing/httpdriver/handler.go
  openmeter/billing/httpdriver/profile.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/schema/appcustominvoicing.go
  tools/migrate/migrations/20250417145207_app-custominvoicing.down.sql
  tools/migrate/migrations/20250417145207_app-custominvoicing.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/apps

#2710 fix(collector): runai scheduler shutdown
  collector/benthos/input/run_ai.go
Labels: release-note/misc

#2711 chore(client): update javascript dependencies
  api/client/javascript/package.json
  api/client/javascript/pnpm-lock.yaml
Labels: release-note/dependency-update

#2713 fix: filtering customers subscriptions by plan key
  openmeter/customer/adapter/customer.go
Labels: release-note/misc

#2715 fix: maxQuantity in API request mapper
  openmeter/productcatalog/planaddon/httpdriver/mapping.go
Labels: release-note/bug-fix

#2705 feat: custom invocing app
  api/spec/src/billing/invoices.tsp
  app/common/app.go
  openmeter/app/custominvoicing/app.go
  openmeter/app/custominvoicing/factory.go
  openmeter/app/custominvoicing/service.go
  openmeter/app/custominvoicing/service/service.go
  openmeter/app/custominvoicing/service/sync.go
  openmeter/app/custominvoicing/sync.go
  openmeter/billing/app.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/invoice.go
  openmeter/billing/service.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceapp.go
  openmeter/billing/service/invoicestate.go
  openmeter/server/server_test.go
  test/app/custominvoicing/invocing_test.go
  test/app/stripe/invoice_test.go
  test/billing/invoice_test.go
Labels: release-note/feature, area/billing, area/apps

#2714 refactor: invoice number generation
  openmeter/app/custominvoicing/app.go
  openmeter/app/sandbox/app.go
  openmeter/billing/seq.go
  openmeter/billing/service/seq.go
Labels: release-note/ignore, area/billing

#2712 feat: custom invoicing api
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/app/custominvoicing.tsp
  cmd/server/main.go
  openmeter/app/custominvoicing/httpdriver/custominvoicing.go
  openmeter/app/custominvoicing/httpdriver/errors.go
  openmeter/app/custominvoicing/httpdriver/handler.go
  openmeter/app/custominvoicing/httpdriver/mapper.go
  openmeter/app/custominvoicing/service/sync.go
  openmeter/billing/README.md
  openmeter/billing/adapter.go
  openmeter/billing/app.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/httpdriver/profile.go
  openmeter/billing/worker/subscription/handlers.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/server/router/appcustominvoicing.go
  openmeter/server/router/router.go
  openmeter/server/server_test.go
Labels: release-note/feature, area/billing

#2717 chore(api): remove x-internal from /api/v2/events
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/events.tsp
Labels: release-note/feature

#2720 chore: add error wrapping
  openmeter/subscription/subscriptionspec.go
Labels: release-note/bug-fix

#2708 Plan-Addon RateCard Compatibility adjustments
  openmeter/productcatalog/addon.go
  openmeter/productcatalog/planaddon.go
  openmeter/productcatalog/ratecard.go
  pkg/slicesx/iteratee.go
Labels: release-note/misc

#2725 chore(client): add methods to javascript SDK
  api/client/javascript/src/client/apps.ts
  api/client/javascript/src/client/billing.ts
  api/client/javascript/src/client/debug.ts
  api/client/javascript/src/client/entitlements.ts
  api/client/javascript/src/client/index.ts
  api/client/javascript/src/client/info.ts
Labels: release-note/feature

#2723 feat(wire): app and namespace
  app/common/app.go
  app/common/kafka.go
  app/common/namespace.go
  app/common/streaming.go
  cmd/balance-worker/wire.go
  cmd/balance-worker/wire_gen.go
  cmd/billing-worker/main.go
  cmd/billing-worker/wire.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/internal/wire.go
  cmd/jobs/internal/wire_gen.go
  cmd/notification-service/wire.go
  cmd/notification-service/wire_gen.go
  cmd/server/main.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  cmd/sink-worker/wire.go
  cmd/sink-worker/wire_gen.go
  openmeter/billing/service/invoice.go
Labels: release-note/ignore, area/apps

#2724 fix: invoice app serialization
  openmeter/billing/events.go
  openmeter/billing/worker/subscription/handlers.go
  test/billing/event_test.go
Labels: release-note/ignore, area/billing

#2706 Addon Purchase Validations
  app/common/subscription.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/internal/wire_gen.go
  cmd/server/wire_gen.go
  openmeter/subscription/addon/diff/apply_test.go
  openmeter/subscription/addon/service/change_test.go
  openmeter/subscription/addon/service/create_test.go
  openmeter/subscription/addon/service/list_test.go
  openmeter/subscription/addon/service/service.go
  openmeter/subscription/testutils/addon.go
  openmeter/subscription/testutils/helpers.go
  openmeter/subscription/testutils/service.go
  openmeter/subscription/workflow/service/addon_test.go
  openmeter/subscription/workflow/service/subscription_test.go
  test/billing/subscription_suite.go
Labels: release-note/misc

#2734 feat: add raw events
  app/config/config_test.go
  app/config/sink.go
  openmeter/sink/flushhandler/ingestnotification/events/events.go
  openmeter/sink/flushhandler/ingestnotification/handler.go
Labels: release-note/feature

#2722 fix: allow empty description for apps
  openmeter/app/adapter/app.go
  openmeter/app/app.go
  test/app/stripe/appstripe.go
Labels: release-note/bug-fix

#2735 refactor: balance worker
  app/common/openmeter_balanceworker.go
  openmeter/entitlement/balanceworker/cachehandler.go
  openmeter/entitlement/balanceworker/entitlementhandler.go
  openmeter/entitlement/balanceworker/ingesthandler.go
  openmeter/entitlement/balanceworker/worker.go
  openmeter/entitlement/edge/event.go
Labels: release-note/ignore

#2738 feat(client): add generated zod schema to JS client
  api/client/javascript/orval.config.ts
  api/client/javascript/package.json
  api/client/javascript/pnpm-lock.yaml
  api/client/javascript/src/zod/index.ts
Labels: release-note/feature

#2739 chore: remove taxid validation
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/types.tsp
Labels: release-note/misc

#2740 feat(client): add meter update method to javascript SDK
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/meters.ts
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/meters.tsp
Labels: release-note/feature

#2743 fix: pin entitlement test to a specific time
  openmeter/entitlement/metered/balance_test.go
Labels: release-note/ignore

#2742 refactor: improve notification
  app/common/notification.go
  openmeter/notification/adapter/channel.go
  openmeter/notification/adapter/entitymapping.go
  openmeter/notification/adapter/event.go
  openmeter/notification/adapter/repository.go
  openmeter/notification/adapter/rule.go
  openmeter/notification/channel.go
  openmeter/notification/consumer/balancethreshold_test.go
  openmeter/notification/consumer/balancetreshold.go
  openmeter/notification/event.go
  openmeter/notification/eventhandler/handler.go
  openmeter/notification/eventpayload.go
  openmeter/notification/httpdriver/channel.go
  openmeter/notification/httpdriver/event.go
  openmeter/notification/httpdriver/mapping.go
  openmeter/notification/httpdriver/rule.go
  openmeter/notification/internal/rule.go
  openmeter/notification/rule.go
  openmeter/notification/service.go
  openmeter/notification/service/channel.go
  openmeter/notification/webhook/svix.go
  test/notification/consumer_balance.go
  test/notification/testenv.go
Labels: release-note/ignore

#2719 Subscription Addon Restore
  openmeter/productcatalog/addon.go
  openmeter/server/router/subscriptionaddon.go
  openmeter/server/server_test.go
  openmeter/subscription/addon/diff/addon.go
  openmeter/subscription/addon/diff/affected.go
  openmeter/subscription/addon/diff/apply.go
  openmeter/subscription/addon/diff/apply_test.go
  openmeter/subscription/addon/diff/restore.go
  openmeter/subscription/addon/diff/restore_test.go
  openmeter/subscription/addon/diff/zeroratecard.go
  openmeter/subscription/addon/extend.go
  openmeter/subscription/addon/extend_test.go
  openmeter/subscription/addon/http/create.go
  openmeter/subscription/addon/http/handler.go
  openmeter/subscription/addon/http/mapping.go
  openmeter/subscription/addon/http/update.go
  openmeter/subscription/annotations.go
  openmeter/subscription/apply.go
  openmeter/subscription/patch/patch_test.go
  openmeter/subscription/subscriptionspec.go
  openmeter/subscription/testutils/addon.go
  openmeter/subscription/testutils/compare.go
  openmeter/subscription/testutils/ratecard.go
  openmeter/subscription/workflow/annotations.go
  openmeter/subscription/workflow/service.go
  openmeter/subscription/workflow/service/addon.go
  openmeter/subscription/workflow/service/addon_test.go
  openmeter/subscription/workflow/service/subscription.go
  openmeter/subscription/workflow/service/subscription_test.go
  tools/migrate/entitlement_test.go
  tools/migrate/migrations/20250424160933_boolean-entitlement-count-annotation.down.sql
  tools/migrate/migrations/20250424160933_boolean-entitlement-count-annotation.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature

#2744 feat(client): remove crypto hard dependency from Node SDK
  api/client/javascript/src/client/events.ts
Labels: release-note/feature

#2746 refactor: improve notification
  openmeter/ent/db/mutation.go
  openmeter/ent/db/notificationrule.go
  openmeter/ent/db/notificationrule/notificationrule.go
  openmeter/ent/db/notificationrule/where.go
  openmeter/ent/db/notificationrule_create.go
  openmeter/ent/schema/notification.go
  openmeter/notification/adapter/adapter.go
  openmeter/notification/adapter/channel.go
  openmeter/notification/adapter/deliverystatus.go
  openmeter/notification/adapter/event.go
  openmeter/notification/adapter/repository.go
  openmeter/notification/adapter/rule.go
  openmeter/notification/consumer/balancetreshold.go
  openmeter/notification/deliverystatus.go
  openmeter/notification/event.go
  openmeter/notification/httpdriver/mapping.go
  openmeter/notification/httpdriver/rule.go
  openmeter/notification/repository.go
  openmeter/notification/rule.go
  openmeter/notification/service/channel.go
  openmeter/notification/service/deliverystatus.go
  openmeter/notification/service/event.go
  openmeter/notification/service/rule.go
  openmeter/notification/service/service.go
  openmeter/notification/webhook/svix.go
  test/notification/repository.go
  test/notification/rule.go
Labels: release-note/ignore

#2747 refactor: notification
  api/spec/src/notification/balancethreshold.tsp
  api/spec/src/notification/event.tsp
  api/spec/src/notification/main.tsp
  api/spec/src/notification/rule.tsp
  openmeter/ent/schema/notification.go
  openmeter/notification/balancethreshold.go
  openmeter/notification/consumer/balancetreshold.go
  openmeter/notification/event.go
  openmeter/notification/eventpayload.go
  openmeter/notification/httpdriver/mapping.go
  openmeter/notification/internal/rule.go
  openmeter/notification/rule.go
  test/notification/event.go
  test/notification/rule.go
Labels: release-note/ignore

#2736 Feature Validation
  openmeter/productcatalog/addon.go
  openmeter/productcatalog/addon/httpdriver/addon.go
  openmeter/productcatalog/plan.go
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/httpdriver/plan.go
  openmeter/productcatalog/plan_test.go
  openmeter/productcatalog/planaddon/adapter/planaddon.go
  openmeter/productcatalog/ratecard.go
  openmeter/productcatalog/subscription/service/change.go
  openmeter/productcatalog/subscription/service/change_test.go
  openmeter/productcatalog/subscription/service/create.go
  openmeter/productcatalog/subscription/service/migrate.go
  openmeter/subscription/addon/diff/apply_test.go
  openmeter/subscription/subscriptionspec.go
  openmeter/subscription/testutils/addon.go
  openmeter/subscription/testutils/feature.go
Labels: release-note/bug-fix

#2748 feat(notification): invoice events
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/notification/balancethreshold.tsp
  api/spec/src/notification/event.tsp
  api/spec/src/notification/invoice.tsp
  api/spec/src/notification/main.tsp
  api/spec/src/notification/rule.tsp
  cmd/notification-service/main.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/notificationevent/notificationevent.go
  openmeter/ent/db/notificationrule/notificationrule.go
  openmeter/ent/schema/notification.go
  openmeter/notification/annotations.go
  openmeter/notification/consumer/balancetreshold.go
  openmeter/notification/consumer/consumer.go
  openmeter/notification/consumer/invoice.go
  openmeter/notification/event.go
  openmeter/notification/eventpayload.go
  openmeter/notification/httpdriver/mapping.go
  openmeter/notification/httpdriver/rule.go
  openmeter/notification/internal/rule.go
  openmeter/notification/invoice.go
  openmeter/notification/rule.go
  test/notification/event.go
Labels: release-note/feature

#2751 feat: reset notifications
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/notification/entitlements.tsp
  api/spec/src/notification/event.tsp
  api/spec/src/notification/main.tsp
  api/spec/src/notification/rule.tsp
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/notificationevent/notificationevent.go
  openmeter/ent/db/notificationrule/notificationrule.go
  openmeter/notification/adapter/event.go
  openmeter/notification/annotations.go
  openmeter/notification/consumer/consumer.go
  openmeter/notification/consumer/entitlementbalancethreshold.go
  openmeter/notification/consumer/entitlementreset.go
  openmeter/notification/consumer/entitlementsnapshot.go
  openmeter/notification/entitlements.go
  openmeter/notification/event.go
  openmeter/notification/eventpayload.go
  openmeter/notification/httpdriver/mapping.go
  openmeter/notification/httpdriver/rule.go
  openmeter/notification/internal/rule.go
  openmeter/notification/invoice.go
  openmeter/notification/rule.go
  test/notification/consumer_balance.go
  test/notification/event.go
Labels: release-note/feature, area/notification

#2755 fix: entitlement resets
  openmeter/notification/consumer/entitlementreset.go
Labels: release-note/ignore
