Repository openmeterio/openmeter, pull requests merged in 2025-06, with the labels that each got.

#2931 fix: allow adding flat fees lines without features
  openmeter/billing/httpdriver/deprecations.go
Labels: release-note/bug-fix, area/billing

#2928 chore: only execute balance worker for namespaces with active notifications
  app/common/notification.go
  app/common/openmeter_balanceworker.go
  cmd/balance-worker/wire.go
  cmd/balance-worker/wire_gen.go
  cmd/jobs/entitlement/recalculatesnapshots.go
  cmd/jobs/internal/wire.go
  cmd/jobs/internal/wire_gen.go
  openmeter/entitlement/balanceworker/entitlementhandler.go
  openmeter/entitlement/balanceworker/filters.go
  openmeter/entitlement/balanceworker/filters/filter.go
  openmeter/entitlement/balanceworker/filters/notifications.go
  openmeter/entitlement/balanceworker/recalculate.go
  openmeter/entitlement/balanceworker/worker.go
  pkg/lrux/lruitemttl.go
  pkg/lrux/lruitemttl_test.go
  pkg/models/key.go
Labels: release-note/misc, area/entitlements, area/notification

#2932 fix: invoice line updates
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/lineservice/usagebasedlineflat.go
  openmeter/productcatalog/price.go
Labels: area/api, release-note/bug-fix, area/billing

#2934 chore: expose keyhash function
  openmeter/dedupe/redisdedupe/keyhash.go
  openmeter/dedupe/redisdedupe/redisdedupe.go
Labels: release-note/ignore

#2937 fix: decrease hash size by removing padding
  openmeter/dedupe/redisdedupe/keyhash.go
Labels: release-note/breaking-change

#2927 feat: test prorating
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/subscription/sync_test.go
Labels: release-note/ignore

#2939 fix(streaming): cache materialize without group by
  openmeter/streaming/clickhouse/cachematerialize.go
  openmeter/streaming/clickhouse/cachematerialize_test.go
Labels: area/processor, release-note/bug-fix

#2938 chore: log sink-worker race condition if happens
  openmeter/dedupe/dedupe.go
  openmeter/dedupe/memorydedupe/memorydedupe.go
  openmeter/dedupe/memorydedupe/memorydedupe_test.go
  openmeter/dedupe/redisdedupe/redisdedupe.go
  openmeter/sink/sink.go
Labels: release-note/ignore, area/dedupe

#2941 fix: flat price term defaulting
  openmeter/billing/service/lineservice/priceflat.go
Labels: area/api, release-note/bug-fix, area/billing

#2942 fix: only return customer address if fields are set
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/httpdriver/invoice_test.go
Labels: release-note/bug-fix, area/billing

#2940 refactor(cache): filter out rows
  openmeter/streaming/clickhouse/cache.go
  openmeter/streaming/clickhouse/cache_util.go
  openmeter/streaming/clickhouse/cache_util_test.go
Labels: release-note/ignore

#2944 fix: ingested event key assignment
  openmeter/ingest/kafkaingest/collector.go
  openmeter/ingest/kafkaingest/serializer/json.go
  openmeter/ingest/kafkaingest/serializer/serializer.go
  openmeter/ingest/kafkaingest/serializer/serializer_test.go
Labels: release-note/bug-fix, area/dedupe, area/sink-worker

#2946 feat(db): add cascading for subscriptions
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/schema/entitlement.go
  openmeter/ent/schema/subscription.go
  openmeter/subscription/testutils/db.go
  openmeter/subscription/workflow/service/subscription_test.go
  tools/migrate/migrations/20250605102416_subscription-cascade.down.sql
  tools/migrate/migrations/20250605102416_subscription-cascade.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/misc

#2950 feat(customer): metadata
  openmeter/customer/adapter/customer.go
  openmeter/customer/adapter/entitymapping.go
  openmeter/customer/customer.go
  openmeter/customer/httpdriver/apimapping.go
  openmeter/customer/httpdriver/customer.go
  pkg/models/metadata.go
  test/customer/customer.go
Labels: release-note/bug-fix

#2958 fix: change subject metadata type
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/subjects.tsp
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/db/subject.go
  openmeter/ent/db/subject/subject.go
  openmeter/ent/db/subject/where.go
  openmeter/ent/db/subject_create.go
  openmeter/ent/db/subject_update.go
  openmeter/ent/schema/subject.go
  openmeter/notification/internal/rule.go
  openmeter/subject/adapter/subject.go
  openmeter/subject/httphandler/subject.go
  openmeter/subject/service.go
  openmeter/subject/subject.go
Labels: release-note/bug-fix

#2959 fix(cache): no to
  openmeter/streaming/clickhouse/cache.go
Labels: release-note/bug-fix

#2957 refactor: subject fixes
  app/common/subject.go
  cmd/balance-worker/wire_gen.go
  cmd/server/wire_gen.go
  openmeter/entitlement/balanceworker/entitlementhandler.go
  openmeter/entitlement/balanceworker/recalculate.go
  openmeter/entitlement/balanceworker/subject.go
  openmeter/server/server_test.go
  openmeter/subject/adapter.go
  openmeter/subject/adapter/adapter.go
  openmeter/subject/adapter/subject.go
  openmeter/subject/httphandler/subject.go
  openmeter/subject/service.go
  openmeter/subject/service/service.go
Labels: release-note/ignore

#2960 feat(meter): add subject display name to csv export
  openmeter/meter/httphandler/handler.go
  openmeter/meter/httphandler/query.go
  openmeter/meter/httphandler/query_csv.go
  openmeter/server/router/router.go
Labels: release-note/feature

#2963 feat(meter): do not include subject in csv export when not returned
  openmeter/meter/httphandler/query_csv.go
  openmeter/server/server_test.go
Labels: release-note/feature

#2965 fix(subject): ent deprecate
  openmeter/ent/db/subject.go
  openmeter/ent/db/subject/subject.go
  openmeter/ent/schema/subject.go
Labels: release-note/bug-fix

#2961 refactor: split lines
  openmeter/billing/adapter.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/invoicelinemapper.go
  openmeter/billing/adapter/invoicelineprogressive.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/adapter/invoicelinesplitgroup.go
  openmeter/billing/discount.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/invoice.go
  openmeter/billing/invoiceline.go
  openmeter/billing/invoicelineprogressive.go
  openmeter/billing/invoicelinesplitgroup.go
  openmeter/billing/service.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoicecalc/details.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/service/invoicelinesplitgroup.go
  openmeter/billing/service/lineservice/commitments.go
  openmeter/billing/service/lineservice/discountusage.go
  openmeter/billing/service/lineservice/linebase.go
  openmeter/billing/service/lineservice/meters.go
  openmeter/billing/service/lineservice/pricer.go
  openmeter/billing/service/lineservice/usagebasedline.go
  openmeter/billing/service/lineservice/usagebasedline_test.go
  openmeter/billing/worker/subscription/feehelper.go
  openmeter/billing/worker/subscription/invoiceupdate.go
  openmeter/billing/worker/subscription/patch.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/ent/db/billinginvoiceline/billinginvoiceline.go
  openmeter/ent/db/billinginvoicesplitlinegroup_create.go
  openmeter/ent/db/billinginvoicesplitlinegroup_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  openmeter/productcatalog/tax.go
  openmeter/server/server_test.go
  test/billing/adapter_test.go
  test/billing/discount_test.go
  test/billing/invoice_test.go
  test/billing/tax_test.go
  tools/migrate/billing_test.go
  tools/migrate/migrations/20250609204117_billing-migrate-split-line-groups.down.sql
  tools/migrate/migrations/20250609204117_billing-migrate-split-line-groups.up.sql
  tools/migrate/migrations/atlas.sum
  tools/migrate/testdata/billing/README.md
  tools/migrate/testdata/billing/removesplitlines/db/db.go
  tools/migrate/testdata/billing/removesplitlines/db/models.go
  tools/migrate/testdata/billing/removesplitlines/db/queries.sql.go
  tools/migrate/testdata/billing/removesplitlines/fixture.sql
  tools/migrate/testdata/billing/removesplitlines/sqlc.yaml
  tools/migrate/testdata/billing/removesplitlines/sqlc/db-schema.sql
  tools/migrate/testdata/billing/removesplitlines/sqlc/queries.sql
Labels: release-note/misc, area/billing

#2912 refactor: simplify invoicing api
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices.tsp
  api/spec/src/billing/invoices/docref.tsp
  api/spec/src/billing/invoices/invoice.tsp
  openmeter/billing/httpdriver/deprecations.go
  openmeter/billing/httpdriver/deprecations_test.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/httpdriver/invoiceline.go
Labels: area/api, release-note/deprecation, area/billing

#2983 fix(http): fix mapping of new fields on view response
  openmeter/productcatalog/subscription/http/mapping.go
Labels: release-note/bug-fix

#2984 fix(pc): fix alignment related validations
  openmeter/productcatalog/addon.go
  openmeter/productcatalog/addon/ratecard.go
  openmeter/productcatalog/errors.go
  openmeter/productcatalog/phase.go
  openmeter/productcatalog/plan.go
  openmeter/productcatalog/plan_test.go
  openmeter/productcatalog/planaddon.go
  openmeter/productcatalog/planaddon_test.go
  openmeter/productcatalog/ratecard.go
  openmeter/productcatalog/ratecard_test.go
Labels: release-note/bug-fix

#2985 fix(subs): serialization
  openmeter/subscription/subscriptionspec.go
  openmeter/subscription/workflow/service/subscription_test.go
Labels: release-note/bug-fix

#2986 fix(subs): fix cadence validations
  openmeter/subscription/subscriptionspec.go
  openmeter/subscription/workflow/service/subscription.go
Labels: release-note/bug-fix

#2988 fix(billing): fix billing period calculation so it doesnt fail
  openmeter/billing/worker/subscription/phaseiterator.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/productcatalog/subscription/http/mapping.go
  openmeter/subscription/subscriptionspec.go
  openmeter/subscription/timing.go
Labels: release-note/bug-fix

#2990 fix(billing): fetch invoice split line hierarchy
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/service/lineservice/linebase.go
Labels: release-note/bug-fix

#2995 feat(subscription): addon events
  app/common/subscription.go
  openmeter/event/metadata/resourcepath.go
  openmeter/subscription/addon/events.go
  openmeter/subscription/addon/events_test.go
  openmeter/subscription/addon/service/service.go
  openmeter/subscription/testutils/service.go
  test/billing/subscription_suite.go
Labels: release-note/feature, area/billing

#2999 feat(api): remove beta badges
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/cloud/main.tsp
  api/spec/src/main.tsp
Labels: area/api, release-note/feature

#2930 feat(subs): add BillingAnchor
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/subscription.tsp
  e2e/productcatalog_test.go
  openmeter/billing/worker/subscription/phaseiterator.go
  openmeter/billing/worker/subscription/phaseiterator_test.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/subscription.go
  openmeter/ent/db/subscription/subscription.go
  openmeter/ent/db/subscription/where.go
  openmeter/ent/db/subscription_create.go
  openmeter/ent/db/subscription_update.go
  openmeter/ent/schema/subscription.go
  openmeter/productcatalog/subscription/http/create.go
  openmeter/productcatalog/subscription/http/mapping.go
  openmeter/subscription/addon/service/change_test.go
  openmeter/subscription/addon/service/create_test.go
  openmeter/subscription/addon/service/list_test.go
  openmeter/subscription/patch/patch_test.go
  openmeter/subscription/repo/mapping.go
  openmeter/subscription/repo/subscriptionrepo.go
  openmeter/subscription/repository.go
  openmeter/subscription/service/service_test.go
  openmeter/subscription/service/sync_test.go
  openmeter/subscription/service/synchelpers.go
  openmeter/subscription/subscription.go
  openmeter/subscription/subscriptionspec.go
  openmeter/subscription/subscriptionview.go
  openmeter/subscription/testutils/compare.go
  openmeter/subscription/testutils/service.go
  openmeter/subscription/workflow/service.go
  openmeter/subscription/workflow/service/subscription.go
  openmeter/subscription/workflow/service/subscription_test.go
  pkg/timeutil/recurrence.go
  test/customer/customer.go
  test/subscription/framework_test.go
  test/subscription/scenario_editaligned_test.go
  test/subscription/scenario_firstofmonth_test.go
  tools/migrate/migrations/20250610125104_subs-billing-anchor.down.sql
  tools/migrate/migrations/20250610125104_subs-billing-anchor.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature

#3006 fix(api): subscription mapping for billing anchor
  openmeter/subscription/subscription.go
Labels: release-note/bug-fix

#3008 refactor(notification): error handling
  openmeter/notification/eventhandler/dispatch.go
  openmeter/notification/eventhandler/reconcile.go
  openmeter/notification/httpdriver/errors.go
  openmeter/notification/webhook/errors.go
  openmeter/notification/webhook/handler.go
  openmeter/notification/webhook/secret.go
  openmeter/notification/webhook/svix/application.go
  openmeter/notification/webhook/svix/event.go
  openmeter/notification/webhook/svix/internal/error.go
  openmeter/notification/webhook/svix/message.go
  openmeter/notification/webhook/svix/svix.go
  openmeter/notification/webhook/svix/webhook.go
Labels: release-note/bug-fix, kind/refactor

#3015 refactor(billing-sync): generate lines for first cadence for future s…
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/subscription/errors.go
  openmeter/subscription/subscriptionspec.go
Labels: release-note/misc

#3016 fix(ratecard): compatibility validation
  openmeter/productcatalog/ratecard.go
  openmeter/productcatalog/ratecard_test.go
  openmeter/subscription/addon/extend_test.go
Labels: release-note/bug-fix

#3020 chore: remove query cache
  app/common/streaming.go
  app/config/aggregation.go
  app/config/config_test.go
  openmeter/meter/httphandler/query.go
  openmeter/streaming/clickhouse/cache.go
  openmeter/streaming/clickhouse/cache_test.go
  openmeter/streaming/clickhouse/cache_util.go
  openmeter/streaming/clickhouse/cache_util_test.go
  openmeter/streaming/clickhouse/cachematerialize.go
  openmeter/streaming/clickhouse/cachematerialize_test.go
  openmeter/streaming/clickhouse/cachemerge.go
  openmeter/streaming/clickhouse/cachemerge_test.go
  openmeter/streaming/clickhouse/cachequery.go
  openmeter/streaming/clickhouse/cachequery_test.go
  openmeter/streaming/clickhouse/connector.go
  openmeter/streaming/clickhouse/connector_test.go
  openmeter/streaming/query_params.go
Labels: release-note/misc

#3021 chore: remove deprecated windowSize from meters
  app/config/config.go
  app/config/config_test.go
  openmeter/credit/balance.go
  openmeter/credit/engine/engine.go
  openmeter/credit/engine/engine_test.go
  openmeter/credit/engine/grant.go
  openmeter/credit/engine/reset_test.go
  openmeter/credit/engine/run_test.go
  openmeter/credit/grant.go
  openmeter/credit/helper.go
  openmeter/entitlement/metered/balance.go
  openmeter/entitlement/metered/lateevents_test.go
  openmeter/meter/adapter/meter.go
  openmeter/meter/meter.go
  openmeter/meter/meter_test.go
  openmeter/meter/mockadapter/adapter.go
  openmeter/meter/mockadapter/manage.go
  openmeter/streaming/testutils/streaming.go
Labels: release-note/misc

#3023 feat: add monthly query aggregation
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/meters.tsp
  openmeter/meter/meter.go
  openmeter/streaming/clickhouse/meter_query.go
Labels: release-note/feature

#3026 fix: field name in validation error
  openmeter/productcatalog/errors.go
Labels: release-note/ignore

#3018 feat: add billing anchor [OM-1428]
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/routes.tsp
  api/spec/src/productcatalog/subscription.tsp
  e2e/productcatalog_test.go
  openmeter/productcatalog/subscription/http/change.go
  openmeter/productcatalog/subscription/http/migrate.go
  openmeter/productcatalog/subscription/service.go
  openmeter/productcatalog/subscription/service/migrate.go
  openmeter/subscription/testutils/compare.go
  openmeter/subscription/workflow/service.go
  openmeter/subscription/workflow/service/subscription.go
  openmeter/subscription/workflow/service/subscription_test.go
Labels: release-note/feature

#2987 feat(helm): add support for external PostgreSQL and Redis in Svix
  deploy/charts/openmeter/Chart.yaml
  deploy/charts/openmeter/templates/svix.yaml
  deploy/charts/openmeter/values.yaml
Labels: release-note/misc

#3034 fix: snapshot invoice quantities in parallel
  app/common/billing.go
  app/config/billing.go
  app/config/config_test.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/internal/wire_gen.go
  cmd/server/wire_gen.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/service/invoicestate.go
  openmeter/billing/service/lineservice/feeline.go
  openmeter/billing/service/lineservice/service.go
  openmeter/billing/service/lineservice/usagebasedline.go
  openmeter/billing/service/lineservice/usagebasedlineflat.go
  openmeter/billing/service/service.go
  test/app/testenv.go
  test/billing/suite.go
  test/subscription/framework_test.go
Labels: release-note/feature, area/billing

#3037 feat(collector): include all kubernetes phase pods in run.ai result
  collector/benthos/input/runai/pods.go
  collector/benthos/input/runai/workloads.go
Labels: kind/feature

#3036 refactor: high watermark cache to filter framework
  cmd/jobs/entitlement/recalculatesnapshots.go
  openmeter/entitlement/balanceworker/entitlementhandler.go
  openmeter/entitlement/balanceworker/filters.go
  openmeter/entitlement/balanceworker/filters/filter.go
  openmeter/entitlement/balanceworker/filters/highwatermark.go
  openmeter/entitlement/balanceworker/filters/notifications.go
  openmeter/entitlement/balanceworker/ingesthandler.go
  openmeter/entitlement/balanceworker/recalculate.go
  openmeter/entitlement/balanceworker/worker.go
Labels: release-note/ignore, area/entitlements, area/notification

#3038 feat: redis high watermark cache
  app/common/openmeter_balanceworker.go
  app/config/balanceworker.go
  app/config/config_test.go
  app/config/testdata/complete.yaml
  cmd/balance-worker/wire_gen.go
  cmd/jobs/entitlement/recalculatesnapshots.go
  openmeter/entitlement/balanceworker/filters.go
  openmeter/entitlement/balanceworker/filters/highwatermark.go
  openmeter/entitlement/balanceworker/filterstate.go
  openmeter/entitlement/balanceworker/recalculate.go
  openmeter/entitlement/balanceworker/worker.go
Labels: release-note/feature, area/entitlements, area/notification

#3052 refactor(meter): reduce cross dependencies
  app/common/meter.go
  cmd/server/wire_gen.go
  openmeter/meter/adapter/manage.go
  openmeter/meter/service/manage.go
  openmeter/productcatalog/adapter/feature.go
Labels: release-note/misc

#3056 fix(stripe): resolving app id from billing profile
  openmeter/app/stripe/httpdriver/checkout_session.go
Labels: release-note/bug-fix

#3057 fix(app): resolving app id from customer billing profile
  openmeter/app/httpdriver/customer.go
Labels: release-note/bug-fix
