Repository openmeterio/openmeter, pull requests merged in 2025-03, with the labels that each got.

#2368 Entitlement History Fix
  openmeter/credit/helper.go
  openmeter/entitlement/metered/balance.go
Labels: release-note/bug-fix

#2370 chore(deps): bump cloud.google.com/go/storage to v1.50.0
  go.mod
  go.sum
Labels: release-note/dependency-update

#2373 Fix History Windowing
  openmeter/entitlement/metered/balance.go
  openmeter/entitlement/metered/balance_test.go
  openmeter/meter/meter.go
  openmeter/streaming/testutils/streaming.go
  openmeter/streaming/testutils/streaming_test.go
Labels: release-note/bug-fix

#2374 chore(collector): disable setting timezone
  collector/benthos/input/run_ai.go
Labels: release-note/ignore

#2375 fix: delete multiple customers with the same key
  openmeter/customer/adapter/customer.go
  openmeter/ent/db/customer.go
  openmeter/ent/db/customer/customer.go
  openmeter/ent/db/customer/where.go
  openmeter/ent/db/customer_create.go
  openmeter/ent/db/customer_update.go
  openmeter/ent/db/customersubjects.go
  openmeter/ent/db/customersubjects/customersubjects.go
  openmeter/ent/db/customersubjects/where.go
  openmeter/ent/db/customersubjects_create.go
  openmeter/ent/db/customersubjects_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/schema/customer.go
  tools/migrate/migrations/20250304071554_customer-remove-is-deleted.down.sql
  tools/migrate/migrations/20250304071554_customer-remove-is-deleted.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/bug-fix

#2379 fix: remove feature cache temporarily
  openmeter/billing/service/lineservice/service.go
Labels: release-note/bug-fix

#2381 feat: add meta to collector pod env
  deploy/charts/benthos-collector/templates/statefulset.yaml
Labels: release-note/ignore

#2382 feat: support ignoring migrations
  tools/migrate/fs.go
  tools/migrate/fs_test.go
  tools/migrate/migrate.go
  tools/migrate/testdata/ignore/20240826120919_init.down.sql
  tools/migrate/testdata/ignore/20240826120919_init.up.sql
  tools/migrate/testdata/ignore/20240903155435_entitlement-expired-index.down.sql
  tools/migrate/testdata/ignore/20240903155435_entitlement-expired-index.up.sql
  tools/migrate/testdata/ignore/20240917172257_billing-entities.down.sql
  tools/migrate/testdata/ignore/20240917172257_billing-entities.up.sql
  tools/migrate/testdata/noignore/20240826120919_init.down.sql
  tools/migrate/testdata/noignore/20240826120919_init.up.sql
  tools/migrate/testdata/noignore/20240903155435_entitlement-expired-index.down.sql
  tools/migrate/testdata/noignore/20240903155435_entitlement-expired-index.up.sql
  tools/migrate/testdata/noignore/20240917172257_billing-entities.down.sql
  tools/migrate/testdata/noignore/20240917172257_billing-entities.up.sql
Labels: release-note/misc

#2369 Credit API Refactors (History Rewrite Part I)
  openmeter/credit/adapter/balance_snapshot.go
  openmeter/credit/adapter/grant.go
  openmeter/credit/balance.go
  openmeter/credit/balance/repository.go
  openmeter/credit/grant.go
  openmeter/credit/grant/events.go
  openmeter/credit/grant/grant.go
  openmeter/credit/grant/owner_connector.go
  openmeter/credit/grant/repo.go
  openmeter/credit/helper.go
  openmeter/entitlement/balanceworker/worker.go
  openmeter/entitlement/metered/balance.go
  openmeter/entitlement/metered/balance_test.go
  openmeter/entitlement/metered/connector.go
  openmeter/entitlement/metered/entitlement_grant.go
  openmeter/entitlement/metered/grant_owner_adapter.go
  openmeter/entitlement/metered/grant_owner_adapter_test.go
  openmeter/entitlement/metered/reset.go
  openmeter/entitlement/metered/reset_test.go
  openmeter/server/server_test.go
  test/entitlement/regression/scenario_test.go
Labels: release-note/misc

#2384 chore: fix ingest event partition assignment
  openmeter/entitlement/balanceworker/ingesthandler.go
  openmeter/sink/flushhandler/ingestnotification/events/events.go
  openmeter/sink/flushhandler/ingestnotification/handler.go
  openmeter/subscription/validators/customer/validator.go
Labels: release-note/misc, area/entitlements

#2186 feat(streaming): query progress
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/pnpm-lock.yaml
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/cloud/main.tsp
  api/spec/src/events.tsp
  api/spec/src/info/main.tsp
  api/spec/src/info/progress.tsp
  api/spec/src/meters.tsp
  app/common/config.go
  app/common/progressmanager.go
  app/common/streaming.go
  app/config/config.go
  app/config/config_test.go
  app/config/dedupe.go
  app/config/progressmanager.go
  cmd/balance-worker/wire.go
  cmd/balance-worker/wire_gen.go
  cmd/billing-worker/wire.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/internal/wire.go
  cmd/jobs/internal/wire_gen.go
  cmd/notification-service/wire.go
  cmd/notification-service/wire_gen.go
  cmd/server/main.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  cmd/sink-worker/wire.go
  cmd/sink-worker/wire_gen.go
  config.example.yaml
  openmeter/meter/httphandler/mapping.go
  openmeter/meterevent/adapter/event.go
  openmeter/meterevent/httphandler/event.go
  openmeter/meterevent/meterevent.go
  openmeter/progressmanager/adapter.go
  openmeter/progressmanager/adapter/adapter.go
  openmeter/progressmanager/adapter/noop.go
  openmeter/progressmanager/adapter/progress.go
  openmeter/progressmanager/entity/progressmanager.go
  openmeter/progressmanager/httpdriver/handler.go
  openmeter/progressmanager/httpdriver/progress.go
  openmeter/progressmanager/service.go
  openmeter/server/router/info.go
  openmeter/server/router/router.go
  openmeter/server/server_test.go
  openmeter/streaming/clickhouse/materialized_view/connector.go
  openmeter/streaming/clickhouse/raw_events/connector.go
  openmeter/streaming/clickhouse/raw_events/event_query.go
  openmeter/streaming/clickhouse/raw_events/event_query_test.go
  openmeter/streaming/clickhouse/raw_events/meter_query.go
  openmeter/streaming/connector.go
  openmeter/streaming/query_params.go
  pkg/redis/config.go
Labels: area/processor, release-note/feature

#2387 feat(collector): extend kubernetes collector
  collector/benthos/input/kubernetes.go
  collector/benthos/input/run_ai.go
Labels: release-note/feature

#2388 chore: use random partitions
  openmeter/sink/flushhandler/ingestnotification/events/events.go
Labels: release-note/ignore

#2390 fix: high watermark cache
  openmeter/entitlement/balanceworker/entitlementhandler.go
  openmeter/entitlement/balanceworker/ingesthandler.go
  openmeter/entitlement/balanceworker/worker.go
  openmeter/entitlement/metered/events.go
  openmeter/entitlement/metered/reset.go
  openmeter/sink/flushhandler/ingestnotification/events/events.go
  openmeter/sink/flushhandler/ingestnotification/handler.go
Labels: release-note/bug-fix, area/notification

#2386 chore: add highwatermark cache status
  openmeter/entitlement/balanceworker/entitlementhandler.go
  openmeter/entitlement/balanceworker/recalculate.go
  openmeter/entitlement/balanceworker/worker.go
Labels: release-note/misc, area/billing

#2393 feat: add cursor pagination type
  pkg/pagination/v2/cursor.go
  pkg/pagination/v2/cursor_test.go
  pkg/pagination/v2/pagination.go
  pkg/pagination/v2/pagination_test.go
Labels: release-note/misc

#2391 feat(meter): edit
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/meters.tsp
  app/config/config.go
  openmeter/meter/adapter/adapter.go
  openmeter/meter/adapter/manage.go
  openmeter/meter/httphandler/handler.go
  openmeter/meter/httphandler/meter.go
  openmeter/meter/meter.go
  openmeter/meter/meter_test.go
  openmeter/meter/mockadapter/manage.go
  openmeter/meter/service.go
  openmeter/server/router/meter.go
  openmeter/server/server_test.go
  openmeter/streaming/clickhouse/materialized_view/connector.go
  openmeter/streaming/clickhouse/raw_events/connector.go
  openmeter/streaming/connector.go
  openmeter/streaming/testutils/streaming.go
Labels: release-note/feature

#2408 feat: small pagination change
  pkg/pagination/v2/pagination.go
  pkg/pagination/v2/pagination_test.go
Labels: release-note/ignore

#2410 feat(pkg): add time filter
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/filter.tsp
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: release-note/ignore

#2412 Don't create Transactions for Everything
  openmeter/app/adapter/adapter.go
  openmeter/app/adapter/app.go
  openmeter/app/adapter/customer.go
  openmeter/app/adapter/marketplace.go
  openmeter/app/stripe/adapter/adapter.go
  openmeter/app/stripe/adapter/customer.go
  openmeter/app/stripe/adapter/stripe.go
  openmeter/billing/adapter/adapter.go
  openmeter/credit/adapter/transaction.go
  openmeter/customer/adapter/adapter.go
  openmeter/customer/adapter/customer.go
  openmeter/entitlement/adapter/transaction.go
  openmeter/meter/adapter/adapter.go
  openmeter/meter/adapter/manage.go
  openmeter/productcatalog/adapter/transaction.go
  openmeter/productcatalog/plan/adapter/adapter.go
  openmeter/subscription/repo/transaction.go
  pkg/framework/entutils/transaction.go
  pkg/framework/entutils/transaction_test.go
Labels: release-note/misc

#2415 chore: remove totalCount from cursor paginated results
  pkg/pagination/v2/pagination.go
  pkg/pagination/v2/pagination_test.go
Labels: release-note/ignore

#2383 Balance & Usage Consistency (History Rewrite Part II)
  openmeter/credit/adapter/grant.go
  openmeter/credit/balance.go
  openmeter/credit/engine/engine.go
  openmeter/credit/engine/history.go
  openmeter/credit/engine/reset_test.go
  openmeter/credit/engine/run.go
  openmeter/credit/engine/run_test.go
  openmeter/credit/helper.go
  openmeter/entitlement/metered/balance.go
  openmeter/entitlement/metered/grant_owner_adapter.go
  openmeter/entitlement/metered/lateevents_test.go
  openmeter/entitlement/metered/reset_test.go
  openmeter/entitlement/metered/utils_test.go
  test/entitlement/regression/scenario_test.go
Labels: release-note/bug-fix

#2406 Persisting Usage in Snapshots (History Rewrite Part III)
  app/common/entitlement.go
  app/config/config.go
  app/config/config_test.go
  app/config/entitlements.go
  cmd/balance-worker/wire_gen.go
  config.example.yaml
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/credit/adapter/balance_snapshot.go
  openmeter/credit/adapter/transaction.go
  openmeter/credit/balance.go
  openmeter/credit/balance/balance.go
  openmeter/credit/balance/repository.go
  openmeter/credit/balance/service.go
  openmeter/credit/balance/service_test.go
  openmeter/credit/balance/usage.go
  openmeter/credit/connector.go
  openmeter/credit/engine/history.go
  openmeter/credit/engine/reset_test.go
  openmeter/credit/engine/run.go
  openmeter/credit/engine/run_test.go
  openmeter/credit/grant.go
  openmeter/credit/helper.go
  openmeter/ent/db/balancesnapshot.go
  openmeter/ent/db/balancesnapshot/balancesnapshot.go
  openmeter/ent/db/balancesnapshot/where.go
  openmeter/ent/db/balancesnapshot_create.go
  openmeter/ent/db/balancesnapshot_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/schema/balance_snapshot.go
  openmeter/entitlement/metered/balance.go
  openmeter/entitlement/metered/balance_test.go
  openmeter/entitlement/metered/lateevents_test.go
  openmeter/entitlement/metered/reset_test.go
  openmeter/entitlement/metered/utils_test.go
  openmeter/registry/builder/entitlement.go
  openmeter/subscription/testutils/customer.go
  openmeter/subscription/testutils/service.go
  test/app/stripe/testenv.go
  test/app/testenv.go
  test/billing/suite.go
  test/customer/testenv.go
  test/entitlement/regression/framework_test.go
  tools/migrate/migrations/20250307151454_balance-snapshot-usage.down.sql
  tools/migrate/migrations/20250307151454_balance-snapshot-usage.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/misc

#2407 Entitlement Waterfall Optimizations (History Rewrite Part IV)
  app/common/entitlement.go
  cmd/balance-worker/wire_gen.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/internal/wire_gen.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/credit/balance.go
  openmeter/credit/connector.go
  openmeter/credit/grant.go
  openmeter/credit/helper.go
  openmeter/credit/trace.go
  openmeter/entitlement/metered/balance.go
  openmeter/entitlement/metered/connector.go
  openmeter/entitlement/metered/grant_owner_adapter.go
  openmeter/entitlement/metered/lateevents_test.go
  openmeter/entitlement/metered/reset.go
  openmeter/entitlement/metered/trace.go
  openmeter/entitlement/metered/utils_test.go
  openmeter/registry/builder/entitlement.go
  openmeter/subscription/testutils/service.go
  test/entitlement/regression/framework_test.go
Labels: release-note/misc

#2416 Use a single method in all setup to avoid wire collisions
  app/common/openmeter_balanceworker.go
  cmd/balance-worker/wire_gen.go
Labels: release-note/misc

#2418 fix: balance snapshot indexes
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/schema/balance_snapshot.go
  tools/migrate/migrations/20250311193204_balance-snapshot-indexes.down.sql
  tools/migrate/migrations/20250311193204_balance-snapshot-indexes.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/misc, area/entitlements

#2385 Fix customer subject validation
  app/common/subscription.go
  openmeter/subscription/service/service.go
  openmeter/subscription/subscriptionspec.go
  openmeter/subscription/validators/customer/validator.go
Labels: release-note/bug-fix

#2425 feat(collector): prometheus input
  collector/benthos/input/prometheus.go
  collector/benthos/input/run_ai.go
Labels: release-note/feature

#2423 fix: invoice deletion throws an error (OM-1251) but completes
  openmeter/billing/service/invoice.go
Labels: release-note/bug-fix, area/billing

#2380 refactor: rely on FromEntities where it makes sense
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/service/lineservice/linebase.go
Labels: release-note/misc, area/billing

#2426 Add Restore Functionality
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/routes.tsp
  openmeter/productcatalog/subscription/http/cancel.go
  openmeter/productcatalog/subscription/http/handler.go
  openmeter/server/router/subscription.go
  openmeter/subscription/repo/subscriptionrepo.go
  openmeter/subscription/service.go
  openmeter/subscription/service/service.go
  openmeter/subscription/service/workflowservice.go
  openmeter/subscription/service/workflowservice_test.go
  openmeter/subscription/testutils/mock.go
Labels: release-note/feature

#2371 feat: openmeter customer override api
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/billing.ts
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/customeroverride.tsp
  api/spec/src/billing/invoices.tsp
  api/spec/src/billing/profile.tsp
  openmeter/app/stripe/adapter/stripe.go
  openmeter/billing/adapter.go
  openmeter/billing/adapter/customeroverride.go
  openmeter/billing/customeroverride.go
  openmeter/billing/httpdriver/customeroverride.go
  openmeter/billing/httpdriver/handler.go
  openmeter/billing/invoice.go
  openmeter/billing/profile.go
  openmeter/billing/service.go
  openmeter/billing/service/customeroverride.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/validators/subscription/validator.go
  openmeter/billing/worker/collect/collect.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/customer/adapter.go
  openmeter/customer/adapter/customer.go
  openmeter/customer/customer.go
  openmeter/customer/httpdriver/apimapping.go
  openmeter/customer/httpdriver/customer.go
  openmeter/customer/service.go
  openmeter/customer/service/customer.go
  openmeter/productcatalog/subscription/service/create.go
  openmeter/server/router/billing.go
  openmeter/server/server_test.go
  test/billing/customeroverride_test.go
  test/billing/tax_test.go
Labels: release-note/feature, area/billing

#2424 Fix validations on Continuing Subscriptions
  openmeter/subscription/service/service.go
  openmeter/subscription/service/service_test.go
  openmeter/subscription/service/servicevalidation.go
Labels: release-note/bug-fix

#2429 List Customer Subscriptions
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/customers.ts
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/customer.tsp
  e2e/productcatalog_test.go
  openmeter/productcatalog/subscription/http/get.go
  openmeter/productcatalog/subscription/http/handler.go
  openmeter/server/router/customer.go
  openmeter/subscription/repo/subscriptionrepo.go
Labels: release-note/feature

#2431 feat(collector): timestamps and offset fields
  collector/benthos/input/prometheus.go
  collector/benthos/input/run_ai.go
  collector/benthos/input/runai/metrics.go
  collector/benthos/input/schedule.go
Labels: release-note/feature

#2432 refactor: appstripe transaction handling
  openmeter/app/httpdriver/app.go
  openmeter/app/httpdriver/customer.go
  openmeter/app/httpdriver/mapper.go
  openmeter/app/httpdriver/marketplace.go
  openmeter/app/stripe/adapter.go
  openmeter/app/stripe/adapter/stripe.go
  openmeter/app/stripe/service.go
  openmeter/app/stripe/service/app.go
  openmeter/billing/httpdriver/customeroverride.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/httpdriver/profile.go
  openmeter/server/server_test.go
Labels: release-note/ignore

#2421 feat: pin customers to billing profiles on default profile change
  openmeter/app/sandbox/mock.go
  openmeter/billing/adapter.go
  openmeter/billing/adapter/customeroverride.go
  openmeter/billing/adapter/profile.go
  openmeter/billing/customeroverride.go
  openmeter/billing/profile.go
  openmeter/billing/service/profile.go
  openmeter/billing/worker/subscription/sync_test.go
  test/billing/subscription_suite.go
  test/billing/subscription_test.go
  test/billing/suite.go
Labels: release-note/feature, area/billing

#2434 refactor: use validator pattern for input validation
  openmeter/billing/service/profile.go
Labels: release-note/misc

#2435 chore: fix profile override not working
  openmeter/billing/adapter/customeroverride.go
Labels: release-note/bug-fix, area/billing

#2436 feat: allow additional handlers in billing worker
  openmeter/billing/worker/worker.go
Labels: release-note/misc, area/billing

#2438 fix: customeroverride doesn't pin to billing profile
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/customeroverride.tsp
  openmeter/billing/httpdriver/customeroverride.go
Labels: release-note/bug-fix, area/billing

#2439 Subs Listing
  openmeter/subscription/repo/subscriptionrepo.go
  openmeter/subscription/subscription.go
  openmeter/subscription/subscription_test.go
Labels: release-note/bug-fix

#2441 chore: fix checkout session status code
  openmeter/app/stripe/httpdriver/checkout_session.go
Labels: release-note/bug-fix, area/billing

#2437 feat(billing): enable by default
  app/common/app.go
  app/common/billing.go
  app/common/productcatalog.go
  app/common/subscription.go
  app/config/apps.go
  app/config/billing.go
  app/config/config_test.go
  app/config/productcatalog.go
  cmd/billing-worker/main.go
  cmd/server/main.go
  config.example.yaml
  e2e/config.yaml
  openmeter/server/router/app.go
  openmeter/server/router/appstripe.go
  openmeter/server/router/billing.go
  openmeter/server/router/customer.go
  openmeter/server/router/plan.go
  openmeter/server/router/router.go
  openmeter/server/router/subscription.go
  openmeter/server/server_test.go
  pkg/log/mock.go
Labels: release-note/feature

#2444 feat(stripe): return more properties in create checkout session
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/app/stripe.tsp
  openmeter/app/stripe/adapter/stripe.go
  openmeter/app/stripe/client/checkout.go
  openmeter/app/stripe/client/client.go
  openmeter/app/stripe/entity/input.go
  openmeter/app/stripe/httpdriver/checkout_session.go
  test/app/stripe/appstripe.go
Labels: release-note/feature

#2445 fix: checkout session event serialization
  openmeter/app/events.go
  openmeter/app/stripe/entity/events.go
  openmeter/app/stripe/service/app.go
  pkg/models/model.go
Labels: release-note/misc, area/billing

#2446 chore: nix update devenv
  flake.lock
Labels: release-note/misc

#2447 feat: allow listing only active plans
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/plan.tsp
  api/spec/src/productcatalog/routes.tsp
  openmeter/productcatalog/plan/adapter/adapter_test.go
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/httpdriver/plan.go
  openmeter/productcatalog/plan/service.go
Labels: release-note/feature, area/product-catalog

#2448 fix(subscription): error handling
  openmeter/productcatalog/subscription/http/errors.go
  openmeter/productcatalog/subscription/service/plan.go
  openmeter/productcatalog/subscription/testutils/adapter.go
  openmeter/subscription/errors.go
  openmeter/subscription/plan.go
  openmeter/subscription/repo/subscriptionitemrepo.go
  openmeter/subscription/repo/subscriptionphaserepo.go
  openmeter/subscription/repo/subscriptionrepo.go
  openmeter/subscription/service/workflowservice_test.go
  openmeter/subscription/state.go
Labels: release-note/bug-fix

#2449 fix(stripe): create checkout session customer
  openmeter/app/stripe/client/checkout.go
  openmeter/app/stripe/entity/input.go
  openmeter/app/stripe/httpdriver/checkout_session.go
Labels: release-note/bug-fix

#2450 fix: plan status listing
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/productcatalog/plan.tsp
  api/spec/src/productcatalog/routes.tsp
  openmeter/productcatalog/plan/adapter/adapter_test.go
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/httpdriver/plan.go
  openmeter/productcatalog/plan/service.go
Labels: release-note/bug-fix, area/product-catalog

#2451 fix: plan listing invalid filter
  openmeter/productcatalog/plan/adapter/plan.go
Labels: release-note/bug-fix, release-note/ignore

#2452 chore: regenerate cloud api + go client
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
Labels: release-note/ignore

#2466 fix: plan list documentation
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/routes.tsp
Labels: release-note/misc, area/product-catalog

#2467 fix: add precondition failed to errors
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/errors.tsp
Labels: release-note/bug-fix

#2468 Add missing status values
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/subscription.tsp
Labels: release-note/bug-fix

#2469 fix: app deletion check should return proper error messages
  openmeter/app/httpdriver/app.go
  openmeter/billing/adapter.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/profile.go
  openmeter/billing/errors.go
  openmeter/billing/httpdriver/errors.go
  openmeter/billing/service.go
  openmeter/billing/service/profile.go
  openmeter/server/server_test.go
  test/billing/profile_test.go
Labels: release-note/bug-fix, area/billing

#2470 feat: invoice in advance flat fees on subs creation
  openmeter/billing/worker/subscription/handlers.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/billing/worker/worker.go
Labels: release-note/feature, area/billing

#2473 fix: allow zero prices
  openmeter/billing/invoiceline.go
  test/billing/invoice_test.go
Labels: release-note/bug-fix, area/billing

#2471 Fill in Feature for SubscriptionExpanded
  app/common/subscription.go
  e2e/productcatalog_test.go
  openmeter/productcatalog/subscription/http/mapping.go
  openmeter/subscription/service/service.go
  openmeter/subscription/subscriptionview.go
  openmeter/subscription/testutils/service.go
  test/billing/subscription_suite.go
Labels: release-note/feature

#2475 fix: store masked api key in db
  openmeter/app/httpdriver/app.go
  openmeter/app/httpdriver/customer.go
  openmeter/app/httpdriver/mapper.go
  openmeter/app/httpdriver/marketplace.go
  openmeter/app/stripe/adapter.go
  openmeter/app/stripe/adapter/stripe.go
  openmeter/app/stripe/entity/input.go
  openmeter/app/stripe/service.go
  openmeter/app/stripe/service/app.go
  openmeter/app/stripe/service/factory.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/httpdriver/profile.go
  openmeter/ent/db/appstripe.go
  openmeter/ent/db/appstripe/appstripe.go
  openmeter/ent/db/appstripe/where.go
  openmeter/ent/db/appstripe_create.go
  openmeter/ent/db/appstripe_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/schema/app_stripe.go
  tools/migrate/migrations/20250318123842_app-stripe-store-masked-key.down.sql
  tools/migrate/migrations/20250318123842_app-stripe-store-masked-key.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/bug-fix, area/apps

#2477 fix: do not reset key on subscription starting
  openmeter/customer/adapter/customer.go
  openmeter/subscription/service/service.go
Labels: release-note/bug-fix, area/subscriptions

#2476 fix: allow deleting manual approval invoices
  openmeter/billing/service/invoicestate.go
  test/billing/invoice_test.go
Labels: release-note/bug-fix, area/billing

#2472 Use discriminated union on item price
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/subscription.tsp
  openmeter/productcatalog/subscription/http/mapping.go
Labels: release-note/feature

#2479 chore: fix postgresql docker
  docker-compose.yaml
Labels: release-note/ignore

#2482 fix: app stripe support empty invoices
  openmeter/app/stripe/entity/app/invoice.go
  test/app/stripe/appstripe.go
  test/app/stripe/fixture.go
  test/app/stripe/invoice_test.go
Labels: release-note/bug-fix, area/billing, area/apps

#2474 refactor: meter events service
  e2e/e2e_test.go
  openmeter/meter/parse.go
  openmeter/meter/parse_test.go
  openmeter/meterevent/adapter/event.go
  openmeter/meterevent/httphandler/event.go
  openmeter/meterevent/httphandler/mapping.go
  openmeter/meterevent/service.go
  openmeter/server/server_test.go
  openmeter/streaming/clickhouse/connector.go
  openmeter/streaming/clickhouse/event_query.go
  openmeter/streaming/clickhouse/event_query_test.go
  openmeter/streaming/clickhouse/meter_query.go
  openmeter/streaming/clickhouse/meter_query_test.go
  openmeter/streaming/clickhouse/utils_query.go
  openmeter/streaming/connector.go
  openmeter/streaming/testutils/streaming.go
Labels: release-note/misc

#2484 fix: let's have a unified percentage representation
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/discounts.tsp
  api/spec/src/types.tsp
  openmeter/productcatalog/discount.go
  openmeter/productcatalog/discount_test.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  pkg/models/percentage.go
  pkg/models/percentage_test.go
Labels: area/api, release-note/feature

#2487 feat(collector): add container ports in helm chart
  deploy/charts/benthos-collector/templates/statefulset.yaml
Labels: release-note/misc

#2489 Fix entitlement alignment on aligned edits
  openmeter/subscription/service/sync.go
  openmeter/subscription/service/synchelpers.go
  openmeter/subscription/subscriptionspec.go
  test/subscription/scenario_editaligned_test.go
Labels: release-note/bug-fix

#2491 feat(collector): rename container port in helm chart
  deploy/charts/benthos-collector/templates/statefulset.yaml
Labels: release-note/ignore

#2480 refactor: update default billing profile
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/profile.tsp
  openmeter/billing/defaults.go
Labels: release-note/misc, area/billing

#2486 refactor: unify price mapping code (billing, subs, plan)
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/subscription.tsp
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/subscription/http/mapping.go
Labels: release-note/misc, area/product-catalog

#2492 feat: subscription sync job
  app/common/billing.go
  cmd/jobs/billing/billing.go
  cmd/jobs/billing/subscriptionsync/sync.go
  cmd/jobs/internal/wire.go
  cmd/jobs/internal/wire_gen.go
  openmeter/billing/worker/subscription/reconciler.go
  openmeter/billing/worker/worker.go
Labels: release-note/misc, area/product-catalog

#2496 chore: subscription -> billing tweaks
  openmeter/billing/worker/subscription/reconciler.go
  openmeter/subscription/list.go
  openmeter/subscription/repo/subscriptionrepo.go
Labels: release-note/misc, area/billing

#2498 fix: gathering invoice deletion from sync
  openmeter/billing/service/invoice.go
  openmeter/billing/worker/subscription/sync.go
Labels: release-note/bug-fix, area/billing

#2499 fix: gathering invoice deletion from sync
  app/common/billing.go
  app/common/subscription.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/internal/wire_gen.go
  cmd/server/wire_gen.go
  openmeter/billing/validators/customer/customer.go
  openmeter/server/server_test.go
  openmeter/subscription/service.go
  openmeter/subscription/service/service.go
  openmeter/subscription/testutils/mock.go
Labels: release-note/bug-fix

#2502 chore: do not sync subscriptions without billble items
  openmeter/billing/worker/subscription/sync.go
Labels: release-note/misc, area/billing

#2495 feat(api): events v2 API
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/codegen.yaml
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/app/app.tsp
  api/spec/src/app/marketplace.tsp
  api/spec/src/app/stripe.tsp
  api/spec/src/cloud/main.tsp
  api/spec/src/customer.tsp
  api/spec/src/events.tsp
  api/spec/src/pagination.tsp
  api/spec/src/query.tsp
  go.mod
  go.sum
  openmeter/apiconverter/cursor.go
  openmeter/apiconverter/filter.gen.go
  openmeter/apiconverter/filter.go
  openmeter/app/httpdriver/app.go
  openmeter/app/httpdriver/marketplace.go
  openmeter/meterevent/adapter/event.go
  openmeter/meterevent/httphandler/event.go
  openmeter/meterevent/httphandler/event_v2.go
  openmeter/meterevent/httphandler/handler.go
  openmeter/meterevent/httphandler/mapping.gen.go
  openmeter/meterevent/httphandler/mapping.go
  openmeter/meterevent/service.go
  openmeter/server/router/event.go
  openmeter/server/server_test.go
  openmeter/streaming/clickhouse/connector.go
  openmeter/streaming/clickhouse/event_query_v2.go
  openmeter/streaming/clickhouse/event_query_v2_test.go
  openmeter/streaming/connector.go
  openmeter/streaming/testutils/streaming.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/pagination/v2/cursor.go
  pkg/pagination/v2/cursor_test.go
  tools.go
Labels: release-note/feature

#2503 feat(collector): require subject in cloudevents.spec.json
  cloudevents.spec.json
Labels: release-note/misc

#2507 fix(pkg): Set.IsEmpty should check for emptiness
  pkg/set/set.go
  pkg/set/set_test.go
Labels: release-note/ignore

#2510 docs(api): meter query
  api/api.gen.go
  api/openapi.yaml
  api/spec/lib/rules/operationSummary.js
  api/spec/src/meters.tsp
Labels: area/api, release-note/ignore

#2524 fix(api): generate spec
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
Labels: release-note/ignore

#2526 chore: filter deleted customers
  app/common/billing.go
  cmd/jobs/internal/wire_gen.go
  openmeter/billing/worker/subscription/reconciler.go
Labels: release-note/bug-fix, area/billing

#2527 fix: list active subscriptions by time
  openmeter/subscription/repo/subscriptionrepo.go
Labels: release-note/bug-fix

#2523 Better name for shared Metadata model
  openmeter/ent/schema/billing.go
  openmeter/ent/schema/entitlement.go
  openmeter/ent/schema/feature.go
  openmeter/ent/schema/grant.go
  openmeter/ent/schema/notification.go
  openmeter/ent/schema/subscription.go
  openmeter/entitlement/adapter/entitlement.go
  openmeter/entitlement/entitlement.go
  openmeter/notification/annotations.go
  openmeter/notification/consumer/balancetreshold.go
  openmeter/notification/event.go
  openmeter/notification/httpdriver/rule.go
  openmeter/productcatalog/subscription/http/change.go
  openmeter/productcatalog/subscription/http/create.go
  openmeter/productcatalog/subscription/http/mapping.go
  openmeter/productcatalog/subscription/service/migrate.go
  openmeter/subscription/item.go
  openmeter/subscription/phase.go
  openmeter/subscription/repo/mapping.go
  openmeter/subscription/repository.go
  openmeter/subscription/service.go
  openmeter/subscription/service/workflowservice.go
  openmeter/subscription/service/workflowservice_test.go
  openmeter/subscription/subscription.go
  openmeter/subscription/subscriptionspec.go
  openmeter/subscription/subscriptionview.go
  pkg/framework/entutils/mixins.go
  pkg/models/annotation.go
  pkg/models/metadata.go
  pkg/models/model.go
Labels: release-note/misc

#2528 fix: subscription reconciler init
  openmeter/billing/worker/subscription/reconciler.go
Labels: release-note/bug-fix

#2522 feat(api): add initial support for Addons
  .spectral.yaml
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/addon.tsp
  api/spec/src/productcatalog/main.tsp
  api/spec/src/productcatalog/plan.tsp
  api/spec/src/productcatalog/routes.tsp
  openmeter/server/router/addon.go
  openmeter/server/router/router.go
Labels: release-note/ignore, release-note/feature

#2530 refactor: terminating services
  app/common/runner.go
  cmd/notification-service/main.go
  cmd/sink-worker/main.go
Labels: release-note/ignore

#2532 chore(api): rm unused types from Plan API
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/productcatalog/plan.tsp
Labels: release-note/ignore

#2497 refactor: price commitments
  openmeter/billing/service/lineservice/usagebasedline_test.go
  openmeter/productcatalog/plan/adapter/adapter_test.go
  openmeter/productcatalog/plan/ratecard_test.go
  openmeter/productcatalog/plan/service/service_test.go
  openmeter/productcatalog/price.go
  openmeter/productcatalog/price_test.go
  openmeter/productcatalog/ratecard_test.go
  pkg/equal/equal.go
  test/app/stripe/invoice_test.go
  test/billing/invoice_test.go
  test/billing/tax_test.go
Labels: release-note/misc, kind/refactor

#2533 refactor(api): plan API
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/routes.tsp
Labels: release-note/deprecation, release-note/misc

#2535 feat(api): addons spec
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/cloud/main.tsp
  api/spec/src/productcatalog/addon.tsp
Labels: area/api, release-note/ignore

#2261 Map subscription errors in workflow service
  openmeter/subscription/service/errors.go
  openmeter/subscription/service/workflowservice.go
Labels: release-note/bug-fix

#2537 Validate customer relations before delete and update
  app/common/customer.go
  openmeter/customer/adapter/customer.go
  openmeter/entitlement/validators/customer/validator.go
  test/customer/customer.go
  test/customer/testenv.go
Labels: release-note/bug-fix

#2430 Subscription Deletion
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/routes.tsp
  openmeter/productcatalog/subscription/http/delete.go
  openmeter/productcatalog/subscription/http/handler.go
  openmeter/server/router/subscription.go
Labels: release-note/feature

#2478 Entitlement Batch Update methods
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/schema/entitlement.go
  openmeter/entitlement/adapter/entitlement.go
  openmeter/entitlement/adapter/entitlement_test.go
  openmeter/entitlement/metered/reset.go
  openmeter/entitlement/repository.go
  tools/migrate/migrations/20250327123818_entitlement-cursor.down.sql
  tools/migrate/migrations/20250327123818_entitlement-cursor.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/misc

#2539 refactor!: Go SDK
  api/client/go/client.gen.go
  api/client/go/codegen.yaml
  e2e/e2e_test.go
  e2e/entitlement_test.go
  e2e/productcatalog_test.go
Labels: release-note/breaking-change

#2525 feat(customers): get by key
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/customer.tsp
  openmeter/app/httpdriver/customer.go
  openmeter/app/httpdriver/handler.go
  openmeter/app/stripe/adapter/stripe.go
  openmeter/billing/service/customer.go
  openmeter/billing/service/customeroverride.go
  openmeter/billing/service/service.go
  openmeter/billing/worker/subscription/reconciler.go
  openmeter/customer/adapter/customer.go
  openmeter/customer/customer.go
  openmeter/customer/errors.go
  openmeter/customer/httpdriver/customer.go
  openmeter/customer/service/customer.go
  openmeter/entitlement/validators/customer/validator.go
  openmeter/productcatalog/subscription/http/create.go
  openmeter/productcatalog/subscription/http/get.go
  openmeter/productcatalog/subscription/service.go
  openmeter/productcatalog/subscription/service/create.go
  openmeter/server/router/customer.go
  openmeter/server/router/router.go
  openmeter/subscription/service/service.go
  openmeter/subscription/service/service_test.go
  openmeter/subscription/service/servicevalidation.go
  openmeter/subscription/service/workflowservice.go
  openmeter/subscription/service/workflowservice_test.go
  openmeter/subscription/validators/customer/validator.go
  test/app/stripe/appstripe.go
  test/billing/customeroverride_test.go
  test/customer/customer.go
Labels: area/api, release-note/feature

#2541 fix(customer): api for id or key
  api/client/go/client.gen.go
  api/client/javascript/src/client/customers.ts
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  openmeter/customer/adapter/customer.go
Labels: area/api, release-note/bug-fix

#2542 refactor!: subscription status API type
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/subscription.tsp
  e2e/productcatalog_test.go
Labels: release-note/breaking-change

#2543 chore(spec): update typespec
  .dagger/generate.go
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/customers.ts
  api/client/javascript/src/client/portal.ts
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/package.json
  api/spec/patches/@typespec__http.patch
  api/spec/patches/@typespec__openapi.patch
  api/spec/patches/@typespec__openapi3.patch
  api/spec/pnpm-lock.yaml
  api/spec/src/app/app.tsp
  api/spec/src/app/customer.tsp
  api/spec/src/billing/invoices.tsp
  api/spec/src/billing/invoices/invoice.tsp
  api/spec/src/billing/profile.tsp
  api/spec/src/cloud/main.tsp
  api/spec/src/entitlements/entitlements.tsp
  api/spec/src/errors.tsp
  api/spec/src/events.tsp
  api/spec/src/main.tsp
  api/spec/src/meters.tsp
  api/spec/src/notification/channel.tsp
  api/spec/src/notification/event.tsp
  api/spec/src/notification/rule.tsp
  api/spec/src/productcatalog/discounts.tsp
  api/spec/src/productcatalog/prices.tsp
  api/spec/src/productcatalog/ratecards.tsp
  api/spec/src/productcatalog/routes.tsp
  api/spec/src/productcatalog/subscription.tsp
  api/spec/src/rest.tsp
Labels: release-note/ignore

#2483 feat: add new price types
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/prices.tsp
  api/spec/src/productcatalog/ratecards.tsp
  openmeter/billing/service/lineservice/usagebasedline.go
  openmeter/billing/service/lineservice/usagebasedline_test.go
  openmeter/ent/db/billinginvoiceusagebasedlineconfig/billinginvoiceusagebasedlineconfig.go
  openmeter/ent/db/migrate/schema.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/price.go
  pkg/convert/ptr.go
Labels: release-note/feature, area/billing, area/product-catalog

#2545 fix(api): typespec types
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices/pay.tsp
  api/spec/src/notification/rule.tsp
Labels: release-note/ignore

#2509 feat(api): JSON encoded filter param
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/patches/@typespec__openapi3.patch
  api/spec/pnpm-lock.yaml
  api/spec/src/events.tsp
  openmeter/meterevent/httphandler/mapping.gen.go
  openmeter/meterevent/httphandler/mapping.go
  openmeter/meterevent/service.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: release-note/ignore

#2558 chore: update add-ons spec descriptions
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/addon.tsp
  api/spec/src/productcatalog/routes.tsp
Labels: release-note/ignore

#2544 feat(events): entity mutation events
  app/common/app.go
  app/common/customer.go
  app/common/meter.go
  app/common/productcatalog.go
  cmd/balance-worker/wire_gen.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/internal/wire_gen.go
  cmd/notification-service/wire_gen.go
  cmd/server/wire_gen.go
  openmeter/app/adapter.go
  openmeter/app/adapter/app.go
  openmeter/app/event.go
  openmeter/app/service/app.go
  openmeter/app/service/service.go
  openmeter/app/stripe/adapter/stripe.go
  openmeter/app/stripe/entity/input.go
  openmeter/app/stripe/event.go
  openmeter/app/stripe/service/app.go
  openmeter/customer/adapter/customer.go
  openmeter/customer/event.go
  openmeter/customer/service/customer.go
  openmeter/customer/service/service.go
  openmeter/event/metadata/resourcepath.go
  openmeter/meter/adapter/adapter.go
  openmeter/meter/adapter/manage.go
  openmeter/meter/adapter/meter.go
  openmeter/meter/event.go
  openmeter/meter/service/manage.go
  openmeter/meter/service/service.go
  openmeter/productcatalog/adapter/feature_test.go
  openmeter/productcatalog/feature/connector.go
  openmeter/productcatalog/feature/event.go
  openmeter/productcatalog/feature/feature.go
  openmeter/productcatalog/plan/event.go
  openmeter/productcatalog/plan/serializer.go
  openmeter/productcatalog/plan/serializer_test.go
  openmeter/productcatalog/plan/service/plan.go
  openmeter/productcatalog/plan/service/service.go
  openmeter/productcatalog/plan/service/service_test.go
  openmeter/registry/builder/entitlement.go
  openmeter/session/session.go
  openmeter/subscription/events.go
  openmeter/subscription/service/service.go
  openmeter/subscription/testutils/customer.go
  openmeter/subscription/testutils/service.go
  test/app/stripe/appstripe.go
  test/app/stripe/testenv.go
  test/app/testenv.go
  test/billing/subscription_suite.go
  test/billing/suite.go
  test/customer/testenv.go
  test/entitlement/regression/framework_test.go
  test/notification/testenv.go
Labels: release-note/feature

#2559 chore: bump nix env
  flake.lock
Labels: release-note/ignore

#2562 Require all reviewers
  .github/workflows/require-all-reviewers.yml
  CONTRIBUTING.md
Labels: release-note/ignore, require-all-reviewers

#2563 chore: bump golnagci-lint configuration to v2
  .dagger/versions.go
  .golangci.yaml
  app/config/postgres.go
  openmeter/app/adapter/adapter.go
  openmeter/app/stripe/adapter/adapter.go
  openmeter/app/stripe/entity/app/invoice.go
  openmeter/billing/adapter/adapter.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/credit/balance/usage.go
  openmeter/customer/adapter/adapter.go
  openmeter/entitlement/connector.go
  openmeter/entitlement/scheduling.go
  openmeter/entitlement/scheduling_test.go
  openmeter/meter/httphandler/mapping.go
  openmeter/productcatalog/subscription/http/mapping.go
  openmeter/productcatalog/subscription/service/migrate.go
  openmeter/streaming/clickhouse/meter_query.go
  openmeter/subscription/patch/additem.go
  openmeter/subscription/patch/removephase.go
  pkg/timeutil/period.go
  pkg/timeutil/period_test.go
  test/app/stripe/fixture.go
  test/billing/invoice_test.go
Labels: release-note/ignore

#2565 refactor: add-ons api
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/addon.tsp
Labels: area/api, release-note/ignore

#2538 refactor: make discounts rate card level
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/discounts.tsp
  api/spec/src/productcatalog/plan.tsp
  api/spec/src/productcatalog/ratecards.tsp
  openmeter/ent/db/planphase.go
  openmeter/ent/db/planphase/planphase.go
  openmeter/ent/schema/productcatalog.go
  openmeter/productcatalog/phase.go
  openmeter/productcatalog/plan/adapter/adapter_test.go
  openmeter/productcatalog/plan/adapter/mapping.go
  openmeter/productcatalog/plan/adapter/phase.go
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
Labels: area/api, release-note/feature, area/product-catalog

#2568 fix: use invoice's workflow settings
  openmeter/app/stripe/entity/app/invoice.go
Labels: release-note/misc

#2567 fix(stripeapp): handle send invoice collection method correctly
  openmeter/app/stripe/client/appclient.go
  openmeter/app/stripe/client/invoice.go
  openmeter/app/stripe/client/stripe.go
  openmeter/app/stripe/entity/app/app.go
  openmeter/app/stripe/entity/app/customer.go
  openmeter/app/stripe/entity/app/invoice.go
  openmeter/app/stripe/service/factory.go
  openmeter/billing/service/invoice.go
  test/app/stripe/appstripe.go
  test/app/stripe/invoice_test.go
  test/app/stripe/testenv.go
Labels: release-note/bug-fix, area/billing
