Repository openmeterio/openmeter, pull requests merged in 2025-02, with the labels that each got.

#2181 fix(sdk): force response type
  api/client/javascript/src/client/common.ts
  api/client/javascript/src/client/entitlements.ts
  api/client/javascript/src/client/features.ts
Labels: release-note/ignore

#2188 refactor: rm unnecessary pagination
  openmeter/productcatalog/plan/service/plan.go
Labels: release-note/ignore

#2189 feat: support listing plans by currency
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/routes.tsp
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/httpdriver/plan.go
  openmeter/productcatalog/plan/service.go
Labels: release-note/ignore

#2191 fix(billing): asOf calculation for invoicing
  openmeter/billing/worker/collect/collect.go
Labels: release-note/bug-fix

#2187 fix(deploy): helm chart
  deploy/charts/openmeter/values.example.yaml
Labels: release-note/ignore

#2192 fix(billing): skip invoices with no billable lines
  openmeter/billing/worker/collect/collect.go
Labels: release-note/bug-fix

#2199 fix: corepack pkg manager install
  .dagger/generate.go
  .dagger/release.go
  .dagger/versions.go
Labels: release-note/ignore

#2200 chore: make invoice action api more descriptive
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices.tsp
  openmeter/billing/httpdriver/invoice.go
Labels: area/api, release-note/misc

#2183 feat: support payment states
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices/invoice.tsp
  openmeter/app/sandbox/app.go
  openmeter/app/sandbox/errors.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/app.go
  openmeter/billing/invoice.go
  openmeter/billing/invoicestate.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoicestate.go
  openmeter/billing/validationissue.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/migrate/schema.go
  test/billing/invoice_test.go
Labels: release-note/feature, area/billing

#2204 refactor(billing): mk invoice collection asOf aligned
  openmeter/billing/service/collectionat.go
  openmeter/billing/worker/collect/collect.go
Labels: release-note/misc

#2163 Possibility to enforce billing alignment for plans
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/lib/rules/casing.js
  api/spec/src/productcatalog/alignment.tsp
  api/spec/src/productcatalog/main.tsp
  api/spec/src/productcatalog/plan.tsp
  e2e/productcatalog_test.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/plan.go
  openmeter/ent/db/plan/plan.go
  openmeter/ent/db/plan/where.go
  openmeter/ent/db/plan_create.go
  openmeter/ent/db/plan_update.go
  openmeter/ent/db/runtime.go
  openmeter/ent/schema/productcatalog.go
  openmeter/entitlement/driver/parser.go
  openmeter/productcatalog/alignment.go
  openmeter/productcatalog/plan.go
  openmeter/productcatalog/plan/adapter/mapping.go
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/plan/service.go
  openmeter/productcatalog/plan/service/plan.go
  openmeter/productcatalog/plan/service/service_test.go
  openmeter/productcatalog/plan_test.go
  openmeter/productcatalog/ratecard.go
  pkg/datex/date.go
  tools/migrate/migrations/20250203131553_plan-alignment.down.sql
  tools/migrate/migrations/20250203131553_plan-alignment.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature

#2171 feat: support stripe webhooks for payment statuses
  .vscode/launch.json
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/app/stripe.tsp
  api/spec/src/billing/invoices/invoice.tsp
  api/spec/src/productcatalog/subscription.tsp
  app/common/app.go
  app/config/apps.go
  app/config/config.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/internal/wire_gen.go
  cmd/server/wire_gen.go
  docs/stripe-dev.md
  openmeter/app/stripe/adapter.go
  openmeter/app/stripe/adapter/stripe.go
  openmeter/app/stripe/client/appclient.go
  openmeter/app/stripe/client/invoice.go
  openmeter/app/stripe/entity/input.go
  openmeter/app/stripe/httpdriver/const.go
  openmeter/app/stripe/httpdriver/webhook.go
  openmeter/app/stripe/service.go
  openmeter/app/stripe/service/app.go
  openmeter/app/stripe/service/billing.go
  openmeter/app/stripe/service/const.go
  openmeter/app/stripe/service/factory.go
  openmeter/app/stripe/service/service.go
  openmeter/billing/adapter.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/invoiceapp.go
  openmeter/billing/invoice.go
  openmeter/billing/invoicestate.go
  openmeter/billing/service.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceapp.go
  openmeter/billing/service/invoicestate.go
  openmeter/ent/db/billinginvoice.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/billinginvoice/where.go
  openmeter/ent/db/billinginvoice_create.go
  openmeter/ent/db/billinginvoice_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  openmeter/server/server_test.go
  test/app/stripe/invoice_test.go
  test/app/stripe/stripe_mock.go
  test/app/stripe/testenv.go
  test/app/testenv.go
  tools/migrate/migrations/20250203165324_billing-tax-external-id.down.sql
  tools/migrate/migrations/20250203165324_billing-tax-external-id.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/billing

#2206 chore: bump atlas to v0.30.0
  .dagger/migrate.go
  .dagger/versions.go
  .dagger/versions_pinned.go
  flake.nix
Labels: release-note/dependency-update

#2207 fix(stripe): checkout session input validation
  openmeter/app/stripe/entity/input.go
Labels: release-note/bug-fix, area/billing

#2208 fix(stripe): checkout session input validation
  openmeter/app/stripe/httpdriver/checkout_session.go
Labels: release-note/bug-fix, area/billing

#2211 feat: add support for background invoice progressing
  .vscode/launch.json
  app/common/billing.go
  app/common/config.go
  app/config/billing.go
  app/config/config.go
  app/config/config_test.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/internal/wire_gen.go
  cmd/server/wire_gen.go
  config.example.yaml
  openmeter/billing/events.go
  openmeter/billing/service.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/service.go
  openmeter/billing/serviceconfig.go
  openmeter/billing/worker/asyncadvance/asyncadvance.go
  openmeter/billing/worker/worker.go
  test/app/testenv.go
  test/billing/suite.go
Labels: release-note/feature, area/billing

#2212 feat: canceled subscription should invoke invoice now
  openmeter/billing/worker/subscription/handlers.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/worker.go
Labels: release-note/misc, area/billing

#2213 fix: billing error reporting
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/profile.go
  openmeter/billing/errors.go
  openmeter/billing/invoiceline.go
  openmeter/billing/service/profile.go
  openmeter/billing/service/service.go
  openmeter/customer/errors.go
Labels: area/api, release-note/bug-fix, area/billing

#2217 fix: empty Plan Phase validation
  openmeter/productcatalog/plan.go
Labels: release-note/bug-fix

#2220 fix: reuse gathering invoices
  openmeter/billing/service/invoiceline.go
  test/billing/invoice_test.go
Labels: release-note/ignore

#2219 fix: improve stripe logging
  app/common/app.go
  openmeter/app/stripe/adapter/adapter.go
  openmeter/app/stripe/adapter/customer.go
  openmeter/app/stripe/adapter/stripe.go
  openmeter/app/stripe/client/appclient.go
  openmeter/app/stripe/client/client.go
  openmeter/app/stripe/client/logger.go
  openmeter/app/stripe/entity/app/app.go
  openmeter/app/stripe/entity/app/client.go
  openmeter/app/stripe/entity/app/customer.go
  openmeter/app/stripe/entity/app/invoice.go
  openmeter/app/stripe/service/factory.go
  openmeter/billing/invoice.go
  test/app/stripe/invoice_test.go
  test/app/stripe/testenv.go
  test/app/testenv.go
Labels: release-note/bug-fix, area/apps

#2216 Fix Nil-ish Time Comparison
  openmeter/subscription/subscriptionview.go
Labels: release-note/bug-fix

#2176 Test without nix cache
  .github/workflows/ci.yaml
Labels: release-note/misc

#2226 Fix one-time lines in aligned subs
  openmeter/billing/worker/subscription/phaseiterator.go
  openmeter/billing/worker/subscription/phaseiterator_test.go
Labels: release-note/bug-fix

#2227 chore: change API tags from private preview to beta
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/app/app.tsp
  api/spec/src/app/marketplace.tsp
  api/spec/src/app/stripe.tsp
  api/spec/src/billing/customeroverride.tsp
  api/spec/src/billing/invoices.tsp
  api/spec/src/billing/profile.tsp
  api/spec/src/cloud/main.tsp
  api/spec/src/customer.tsp
  api/spec/src/main.tsp
  api/spec/src/productcatalog/routes.tsp
Labels: release-note/misc

#2228 fix: make sure we are propagating non not found errors
  openmeter/entitlement/metered/grant_owner_adapter.go
Labels: release-note/misc, area/entitlements

#2229 chore: use lo for error casting
  openmeter/notification/webhook/svix.go
  pkg/errorsx/convert.go
  pkg/errorsx/handler.go
  pkg/framework/commonhttp/errors.go
  pkg/framework/transaction/transaction.go
  test/notification/event.go
  test/notification/rule.go
Labels: release-note/misc

#2230 chore(api): update JavaScript SDK dependencies
  api/client/javascript/package.json
  api/client/javascript/pnpm-lock.yaml
Labels: release-note/ignore

#2221 feat: store status details in DB
  openmeter/billing/adapter/invoice.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/invoice.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoicestate.go
  openmeter/ent/db/billinginvoice.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/billinginvoice/where.go
  openmeter/ent/db/billinginvoice_create.go
  openmeter/ent/db/billinginvoice_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  test/billing/invoice_test.go
  tools/migrate/migrations/20250207101313_billing-store-status-details.down.sql
  tools/migrate/migrations/20250207101313_billing-store-status-details.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/misc, area/billing

#2241 feat: always persist the calculated taxconfig into the lines
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/profile.tsp
  openmeter/billing/service/invoicecalc/calculator.go
  openmeter/billing/service/invoicecalc/taxconfig.go
  openmeter/productcatalog/tax.go
Labels: area/api, release-note/misc, area/billing

#2242 chore(api): disable python sdk publishing
  .dagger/release.go
  .github/workflows/ci-exp.yaml
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .github/workflows/sdk-javascript-release.yaml
  .github/workflows/sdk-javascript.yaml
  .github/workflows/sdk-python.yaml
  dagger.json
Labels: release-note/ignore

#2243 fix(sink): deadlock in flushhandler
  openmeter/sink/flushhandler/handler.go
  openmeter/sink/flushhandler/mux.go
  openmeter/sink/flushhandler/types.go
  openmeter/sink/sink.go
Labels: release-note/bug-fix

#2244 chore(deps): bump github.com/oklog/run to v1.1.1-0.20240127200640-eee6e044b77c
  go.mod
  go.sum
Labels: release-note/dependency-update

#2247 chore: update dagger to v0.15.3
  flake.lock
Labels: release-note/misc

#2246 feat: log panics with stack trace
  cmd/balance-worker/main.go
  cmd/benthos-collector/main.go
  cmd/billing-worker/main.go
  cmd/jobs/main.go
  cmd/notification-service/main.go
  cmd/server/main.go
  cmd/sink-worker/main.go
  pkg/paniclogger/paniclogger.go
Labels: release-note/misc

#2248 refactor: panic logger v2
  cmd/balance-worker/main.go
  cmd/benthos-collector/main.go
  cmd/billing-worker/main.go
  cmd/jobs/main.go
  cmd/notification-service/main.go
  cmd/server/main.go
  cmd/sink-worker/main.go
  pkg/log/panic.go
  pkg/paniclogger/paniclogger.go
Labels: release-note/misc

#2251 fix: sarama debug log
  app/common/watermill.go
  cmd/balance-worker/wire_gen.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/internal/wire_gen.go
  cmd/notification-service/wire_gen.go
  cmd/server/wire_gen.go
  cmd/sink-worker/wire_gen.go
  openmeter/watermill/driver/kafka/broker.go
Labels: release-note/bug-fix, release-note/ignore

#2250 fix(meter): validate value prop with count
  pkg/models/meter.go
  pkg/models/meter_test.go
Labels: area/ingest, release-note/bug-fix

#2252 Fix mapping typo
  openmeter/productcatalog/plan/httpdriver/mapping.go
Labels: release-note/bug-fix

#2253 feat: add otel scope to sarama logger
  openmeter/watermill/driver/kafka/broker.go
Labels: release-note/ignore

#2254 Use UsagePeriod defaulting as written in docs
  openmeter/productcatalog/plan/httpdriver/mapping.go
Labels: release-note/bug-fix

#2256 Revert "fix: only publish events after successful commits (#2218)"
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/credit/grant.go
  openmeter/entitlement/connector.go
  openmeter/entitlement/metered/reset.go
  openmeter/entitlement/scheduling.go
  openmeter/subscription/service/service.go
  pkg/framework/entutils/transaction_test.go
  pkg/framework/transaction/hookmanager.go
  pkg/framework/transaction/transaction.go
Labels: release-note/bug-fix

#2258 feat: add otel stacktrace to paniclogger
  pkg/log/panic.go
Labels: release-note/ignore

#2260 fix: panic on shutdown
  app/common/runner.go
  cmd/notification-service/main.go
  cmd/server/main.go
  cmd/sink-worker/main.go
Labels: release-note/bug-fix, release-note/ignore

#2259 feat(collector): update kubernetes collector
  cmd/benthos-collector/main.go
  collector/benthos/bloblang/parse_resource.go
  collector/benthos/input/kubernetes.go
  collector/benthos/output/openmeter.go
  collector/benthos/presets/kubernetes-pod-exec-time/config.yaml
  examples/collectors/kubernetes-pod-exec-time/seed/pod.yaml
  go.mod
  go.sum
Labels: release-note/misc

#2263 fix(collector): permissions
  deploy/charts/benthos-collector/templates/rbac.yaml
Labels: release-note/ignore

#2265 feat(stripe): webhook handle multiple apps
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/app/stripe.tsp
  openmeter/app/stripe/httpdriver/webhook.go
Labels: release-note/feature, area/billing

#2266 feat(streaming): null if no value
  openmeter/streaming/clickhouse/raw_events/meter_query.go
  openmeter/streaming/clickhouse/raw_events/meter_query_test.go
Labels: area/processor, release-note/feature

#2267 fix(streaming): raw event connector with null query
  openmeter/streaming/clickhouse/raw_events/connector.go
Labels: area/processor, release-note/bug-fix

#2268 fix(billing): dedupe invoice validation issues
  openmeter/billing/adapter/validationissue.go
Labels: release-note/bug-fix, area/billing

#2269 fix(streaming): raw query count
  openmeter/streaming/clickhouse/raw_events/meter_query.go
Labels: area/processor, release-note/bug-fix

#2270 fix(streaming): unique count casting
  openmeter/streaming/clickhouse/raw_events/meter_query.go
Labels: area/processor, release-note/bug-fix

#2271 fix(invoice): validation issue deduping
  openmeter/billing/adapter/validationissue.go
Labels: release-note/bug-fix, area/billing

#2273 chore: cannot advance logging
  openmeter/billing/worker/advance/advance.go
Labels: release-note/misc, area/billing

#2272 fix(streaming): aggregation condition for count
  openmeter/streaming/clickhouse/materialized_view/meter_query.go
  openmeter/streaming/clickhouse/raw_events/meter_query.go
  openmeter/streaming/clickhouse/raw_events/meter_query_test.go
Labels: area/processor, release-note/ignore

#2275 Hotfix sync exclusion rules
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/subscription/sync_test.go
Labels: release-note/bug-fix

#2257 feat: cancel namespace setting
  openmeter/billing/worker/subscription/handlers.go
Labels: release-note/misc

#2276 ci: add codeowners
  .github/CODEOWNERS
Labels: release-note/ignore

#2290 fix(streaming): clickhouse row close
  openmeter/streaming/clickhouse/materialized_view/connector.go
  openmeter/streaming/clickhouse/raw_events/connector.go
Labels: area/processor, release-note/bug-fix

#2305 Collect runtime metrics
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  app/common/telemetry.go
  cmd/balance-worker/wire_gen.go
  cmd/billing-worker/wire_gen.go
  cmd/notification-service/wire_gen.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  cmd/sink-worker/wire_gen.go
  go.mod
  go.sum
Labels: release-note/misc

#2304 fix: shutdown procedure in server
  app/common/config.go
  app/common/termination.go
  app/config/config.go
  app/config/config_test.go
  app/config/telemetry.go
  app/config/termination.go
  app/config/testdata/complete.yaml
  cmd/server/.air.toml
  cmd/server/main.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  config.example.yaml
  go.mod
  go.sum
  openmeter/ingest/kafkaingest/collector.go
  pkg/gosundheit/logger.go
Labels: release-note/bug-fix

#2249 Add current cycle info to subs response
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/subscription.tsp
  e2e/productcatalog_test.go
  openmeter/productcatalog/subscription/http/get.go
  openmeter/productcatalog/subscription/http/mapping.go
  openmeter/subscription/subscriptionview.go
Labels: release-note/misc

#2306 Fix "phase xy has no billables" errors
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/routes.tsp
  e2e/productcatalog_test.go
  openmeter/productcatalog/subscription/http/mapping.go
  openmeter/productcatalog/subscription/service/migrate.go
  openmeter/subscription/service/workflowservice.go
  openmeter/subscription/subscriptionspec.go
  openmeter/subscription/timing.go
Labels: release-note/bug-fix

#2308 fix: billing profile unique indexes
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/schema/app_stripe.go
  openmeter/ent/schema/billing.go
  openmeter/ent/schema/feature.go
  openmeter/ent/schema/productcatalog.go
  tools/migrate/migrations/20250218103055_fix-unique-indexes.down.sql
  tools/migrate/migrations/20250218103055_fix-unique-indexes.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/bug-fix, area/billing

#2311 fix: regression on default billing profile promotion
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/schema/billing.go
  test/billing/invoice_test.go
  tools/migrate/migrations/20250218161614_billing-profile-fix-constraint.down.sql
  tools/migrate/migrations/20250218161614_billing-profile-fix-constraint.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/bug-fix, area/billing

#2307 feat(collector): run-ai collector
  collector/benthos/bloblang/parse_resource.go
  collector/benthos/input/run_ai.go
  collector/benthos/input/runai/metrics.go
  collector/benthos/input/runai/service.go
  collector/benthos/input/runai/token.go
  collector/benthos/input/runai/workloads.go
  go.mod
  go.sum
Labels: release-note/misc

#2313 refactor: Dockerfile
  Dockerfile
Labels: release-note/ignore

#2314 refactor: Dockerfiles
  Dockerfile
  benthos-collector.Dockerfile
Labels: release-note/ignore

#2310 Alignment API touches
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/subscription.tsp
  e2e/productcatalog_test.go
  openmeter/productcatalog/subscription/http/mapping.go
  openmeter/subscription/patch.go
  openmeter/subscription/patch/patch_test.go
  openmeter/subscription/patch/removeitem.go
  openmeter/subscription/patch/serialization.go
  openmeter/subscription/patch/unscheduleedit.go
  openmeter/subscription/patch/unscheduleedit_test.go
Labels: release-note/feature

#2264 chore: replace with `github.com/sagikazarmark/slog-shim` with `log/slog`
  cmd/sink-worker/main.go
  go.mod
  go.sum
Labels: release-note/ignore

#2316 fix: interval parsing
  openmeter/entitlement/driver/parser.go
Labels: release-note/bug-fix

#2317 chore: bump Svix to v1.59.1
  go.mod
  go.sum
  openmeter/notification/webhook/svix.go
Labels: release-note/dependency-update

#2318 chore(deps): bump entgo.io/ent from 0.14.1 to 0.14.2
  go.mod
  go.sum
  openmeter/ent/db/runtime/runtime.go
  pkg/framework/entutils/testutils/ent1/db/runtime/runtime.go
  pkg/framework/entutils/testutils/ent2/db/runtime/runtime.go
Labels: release-note/dependency-update

#2319 feat: add entrypoint script
  Dockerfile
  benthos-collector.Dockerfile
  entrypoint.sh
Labels: release-note/ignore

#2321 feat(helm): add support for injecting CA certs
  deploy/charts/benthos-collector/README.md
  deploy/charts/benthos-collector/templates/configmap.yaml
  deploy/charts/benthos-collector/templates/deployment.yaml
  deploy/charts/benthos-collector/values.yaml
  deploy/charts/openmeter/README.md
  deploy/charts/openmeter/templates/configmap.yaml
  deploy/charts/openmeter/templates/deployment.yaml
  deploy/charts/openmeter/values.yaml
Labels: release-note/misc

#2323 fix: disable stats for Kafka admin client
  app/common/kafka.go
Labels: release-note/bug-fix

#2324 feat(collector): openmeter output errors
  collector/benthos/input/run_ai.go
  collector/benthos/input/runai/workloads.go
  collector/benthos/output/openmeter.go
Labels: release-note/misc, area/collectors

#2320 refactor(portal): service with httphandler
  api/api.gen.go
  api/client/javascript/src/client/portal.ts
  api/openapi.yaml
  api/spec/src/cloud/main.tsp
  api/spec/src/portal.tsp
  app/common/config.go
  app/common/portal.go
  cmd/server/main.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  openmeter/portal/adapter/adapter.go
  openmeter/portal/adapter/noop.go
  openmeter/portal/adapter/token.go
  openmeter/portal/authenticator/authenticator.go
  openmeter/portal/errors.go
  openmeter/portal/httphandler/errors.go
  openmeter/portal/httphandler/handler.go
  openmeter/portal/httphandler/mapping.go
  openmeter/portal/httphandler/portal.go
  openmeter/portal/service.go
  openmeter/server/authenticator/portal.go
  openmeter/server/router/portal.go
  openmeter/server/router/router.go
  openmeter/server/server.go
  openmeter/server/server_test.go
Labels: release-note/ignore

#2337 Expose logs of E2E tests
  .dagger/test_e2e.go
  .gitignore
  app/config/telemetry.go
  config.example.yaml
  e2e/config.yaml
Labels: release-note/misc

#2341 fix(portal): meter not found
  openmeter/portal/httphandler/errors.go
Labels: release-note/bug-fix

#2343 fix: customer delete with active subscription
  app/common/billing.go
  app/common/subscription.go
  openmeter/billing/invoice.go
  openmeter/billing/service/service.go
  openmeter/billing/validators/customer/customer.go
  openmeter/billing/validators/subscription/validator.go
  openmeter/customer/requestvalidator.go
  openmeter/customer/service.go
  openmeter/customer/service/customer.go
  openmeter/customer/service/requestvalidator.go
  openmeter/customer/service/service.go
  openmeter/server/server_test.go
  openmeter/subscription/list.go
  openmeter/subscription/repo/subscriptionrepo.go
  openmeter/subscription/repository.go
  openmeter/subscription/service.go
  openmeter/subscription/service/service.go
  openmeter/subscription/testutils/mock.go
  openmeter/subscription/validators/customer/validator.go
Labels: release-note/bug-fix

#2344 feat(collector): run.ai pod metrics and token expiration check
  collector/benthos/input/run_ai.go
  collector/benthos/input/runai/metrics.go
  collector/benthos/input/runai/pods.go
  collector/benthos/input/runai/token.go
  collector/benthos/input/runai/workloads.go
Labels: release-note/misc

#2346 fix(entitlement): sum same period
  openmeter/credit/helper.go
Labels: release-note/bug-fix, area/entitlements

#2348 chore: fix 500 on meter validation errors
  openmeter/customer/httpdriver/errors.go
  openmeter/entitlement/driver/errors.go
Labels: release-note/bug-fix

#2339 Refactor Credit API (Entitlement Reset Part I)
  openmeter/credit/balance.go
  openmeter/credit/balance/balance.go
  openmeter/credit/engine/burnphase.go
  openmeter/credit/engine/engine.go
  openmeter/credit/engine/engine_test.go
  openmeter/credit/engine/grant.go
  openmeter/credit/engine/history.go
  openmeter/credit/engine/run.go
  openmeter/credit/engine/run_test.go
  openmeter/credit/grant/grant.go
  openmeter/credit/helper.go
Labels: release-note/misc, kind/refactor

#2349 feat(errors): generic http error handler
  openmeter/app/httpdriver/errors.go
  openmeter/app/stripe/httpdriver/errors.go
  openmeter/billing/httpdriver/errors.go
  openmeter/billing/validators/subscription/validator.go
  openmeter/credit/balance.go
  openmeter/credit/driver/grant.go
  openmeter/credit/grant.go
  openmeter/customer/httpdriver/errors.go
  openmeter/customer/service/customer.go
  openmeter/debug/httpdriver/metrics.go
  openmeter/entitlement/connector.go
  openmeter/entitlement/driver/entitlement.go
  openmeter/entitlement/driver/errors.go
  openmeter/entitlement/driver/metered.go
  openmeter/entitlement/metered/balance.go
  openmeter/entitlement/metered/grant_owner_adapter.go
  openmeter/entitlement/scheduling.go
  openmeter/entitlement/scheduling_test.go
  openmeter/info/httpdriver/currencies.go
  openmeter/info/httpdriver/errors.go
  openmeter/ingest/ingestdriver/http_transport.go
  openmeter/meter/errors.go
  openmeter/meter/httphandler/errors.go
  openmeter/meter/httphandler/meter.go
  openmeter/meter/httphandler/query.go
  openmeter/notification/httpdriver/errors.go
  openmeter/portal/httphandler/errors.go
  openmeter/productcatalog/driver/errors.go
  openmeter/productcatalog/feature/connector.go
  openmeter/productcatalog/plan/httpdriver/errors.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/subscription/http/cancel.go
  openmeter/productcatalog/subscription/http/create.go
  openmeter/productcatalog/subscription/http/errors.go
  openmeter/productcatalog/subscription/service/change.go
  openmeter/productcatalog/subscription/service/change_test.go
  openmeter/productcatalog/subscription/service/create.go
  openmeter/productcatalog/subscription/service/migrate.go
  openmeter/productcatalog/subscription/service/migrate_test.go
  openmeter/productcatalog/subscription/service/plan.go
  openmeter/streaming/clickhouse/raw_events/connector.go
  openmeter/subscription/service/service.go
  openmeter/subscription/service/service_test.go
  openmeter/subscription/service/workflowservice.go
  openmeter/subscription/service/workflowservice_test.go
  openmeter/subscription/timing.go
  pkg/framework/commonhttp/encoder.go
  pkg/framework/transport/httptransport/argshandler.go
  pkg/framework/transport/httptransport/encoder/encoder.go
  pkg/framework/transport/httptransport/handler.go
  pkg/framework/transport/httptransport/options.go
  pkg/models/error.go
Labels: release-note/feature

#2345 refactor(event): httphandler
  app/common/meterevent.go
  cmd/server/main.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  openmeter/meterevent/adapter/adapter.go
  openmeter/meterevent/adapter/event.go
  openmeter/meterevent/httphandler/errors.go
  openmeter/meterevent/httphandler/event.go
  openmeter/meterevent/httphandler/handler.go
  openmeter/meterevent/meterevent.go
  openmeter/server/router/event.go
  openmeter/server/router/router.go
  openmeter/server/server_test.go
Labels: release-note/ignore

#2351 fix(event): error handler
  openmeter/meterevent/httphandler/errors.go
  openmeter/meterevent/httphandler/event.go
Labels: release-note/ignore

#2312 Entitlement Reset Calculation (Entitlement Reset Part II)
  .dagger/test_e2e.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/credit/balance.go
  openmeter/credit/connector.go
  openmeter/credit/engine/burnphase.go
  openmeter/credit/engine/engine.go
  openmeter/credit/engine/grant.go
  openmeter/credit/engine/reset.go
  openmeter/credit/engine/reset_test.go
  openmeter/credit/engine/run.go
  openmeter/credit/engine/run_test.go
  openmeter/credit/grant.go
  openmeter/credit/grant/grant.go
  openmeter/credit/grant/grant_test.go
  openmeter/credit/grant/owner_connector.go
  openmeter/credit/helper.go
  openmeter/ent/db/entitlement.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/usagereset.go
  openmeter/ent/db/usagereset/usagereset.go
  openmeter/ent/db/usagereset/where.go
  openmeter/ent/db/usagereset_create.go
  openmeter/ent/schema/entitlement.go
  openmeter/ent/schema/usage_reset.go
  openmeter/entitlement/adapter/entitlement.go
  openmeter/entitlement/adapter/usage_reset.go
  openmeter/entitlement/entitlement.go
  openmeter/entitlement/metered/balance.go
  openmeter/entitlement/metered/balance_test.go
  openmeter/entitlement/metered/connector.go
  openmeter/entitlement/metered/entitlement.go
  openmeter/entitlement/metered/grant_owner_adapter.go
  openmeter/entitlement/metered/grant_owner_adapter_test.go
  openmeter/entitlement/metered/repository.go
  openmeter/entitlement/metered/reset_test.go
  openmeter/entitlement/metered/utils_test.go
  openmeter/entitlement/repository.go
  openmeter/registry/builder/entitlement.go
  pkg/timeutil/period.go
  pkg/timeutil/period_test.go
  pkg/timeutil/recurrence.go
  pkg/timeutil/timeline.go
  test/entitlement/regression/framework_test.go
  test/entitlement/regression/scenario_test.go
  test/notification/consumer_balance.go
  tools/migrate/entitlement_test.go
  tools/migrate/migrations/20250220150245_usage-reset-anchor-times.down.sql
  tools/migrate/migrations/20250220150245_usage-reset-anchor-times.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature

#2353 Leep current UsagePeriod up to date for programmatic resets
  openmeter/entitlement/adapter/entitlement.go
  openmeter/entitlement/entitlement.go
  openmeter/entitlement/metered/grant_owner_adapter.go
Labels: release-note/bug-fix

#2354 refactor(collector): better unions
  collector/benthos/input/run_ai.go
  collector/benthos/input/runai/metrics.go
Labels: release-note/ignore

#2355 feat(deploy): use a StatefulSet and provide storage option for collector helm chart
  deploy/charts/benthos-collector/README.md
  deploy/charts/benthos-collector/templates/_helpers.tpl
  deploy/charts/benthos-collector/templates/statefulset.yaml
  deploy/charts/benthos-collector/values.yaml
Labels: release-note/misc

#2356 Enable immediate cancel for aligned subs
  openmeter/subscription/timing.go
Labels: release-note/misc
