Repository openmeterio/openmeter, pull requests merged in 2025-10, with the labels that each got.

#3451 fix: store metadata in metadata
  openmeter/entitlement/driver/metered.go
Labels: release-note/bug-fix

#3442 refactor(subs): subscription validations
  app/common/subscription.go
  openmeter/billing/validators/customer/customer.go
  openmeter/billing/validators/subscription/validator.go
  openmeter/billing/worker/subscription/reconciler.go
  openmeter/customer/httpdriver/customer.go
  openmeter/productcatalog/subscription/http/get.go
  openmeter/server/server_test.go
  openmeter/subscription/entitlement.go
  openmeter/subscription/entitlement/adapter.go
  openmeter/subscription/list.go
  openmeter/subscription/repo/subscriptionitemrepo.go
  openmeter/subscription/repo/subscriptionphaserepo.go
  openmeter/subscription/repo/subscriptionrepo.go
  openmeter/subscription/repo/utils.go
  openmeter/subscription/repository.go
  openmeter/subscription/service.go
  openmeter/subscription/service/service.go
  openmeter/subscription/service/servicevalidation.go
  openmeter/subscription/subscriptionvalidator.go
  openmeter/subscription/testutils/mock.go
  openmeter/subscription/testutils/service.go
  openmeter/subscription/uniqueness.go
  openmeter/subscription/validator.go
  openmeter/subscription/validators/customer/validator.go
  openmeter/subscription/validators/subscription/components.go
  openmeter/subscription/validators/subscription/validator.go
  openmeter/subscription/workflow/service/subscription.go
  pkg/timeutil/boundedperiod.go
  test/billing/subscription_suite.go
Labels: release-note/feature

#3461 chore(api): move features under Product Catalog
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/cloud/main.tsp
  api/spec/src/entitlements/main.tsp
  api/spec/src/notification/entitlements.tsp
  api/spec/src/productcatalog/features.tsp
  api/spec/src/productcatalog/routes.tsp
  api/spec/src/productcatalog/subscription.tsp
Labels: release-note/misc

#3460 fix: ffx hook was registered too early
  app/common/ffx.go
  app/common/server.go
  cmd/server/main.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  openmeter/server/server.go
Labels: release-note/bug-fix

#3455 feat(subs): unique constraints
  openmeter/entitlement/entitlement.go
  openmeter/entitlement/uniqueness.go
  openmeter/productcatalog/subscription/http/errors.go
  openmeter/subscription/addon/diff/apply_test.go
  openmeter/subscription/addon/diff/restore_test.go
  openmeter/subscription/errors.go
  openmeter/subscription/plan.go
  openmeter/subscription/service/service.go
  openmeter/subscription/service/service_test.go
  openmeter/subscription/subscriptionspec.go
  openmeter/subscription/testutils/builder.go
  openmeter/subscription/testutils/plan.go
  openmeter/subscription/uniqueness.go
  openmeter/subscription/uniqueness_test.go
  openmeter/subscription/validator.go
  openmeter/subscription/validators/subscription/validator.go
  openmeter/subscription/workflow/service/addon_test.go
  openmeter/subscription/workflow/service/subscription_test.go
  pkg/models/cadence.go
  pkg/models/cadence_test.go
  pkg/models/cadencelist.go
Labels: kind/feature

#3477 feat(meter): list subject period params
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/meters.tsp
  openmeter/meter/httphandler/query.go
  openmeter/server/router/meter.go
Labels: area/api, release-note/feature

#3478 feat(api): add meter group by values endpoint
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/meters.tsp
  openmeter/meter/httphandler/handler.go
  openmeter/meter/httphandler/query.go
  openmeter/server/router/meter.go
  openmeter/server/server_test.go
  openmeter/streaming/clickhouse/connector.go
  openmeter/streaming/clickhouse/group_by_values_query.go
  openmeter/streaming/clickhouse/group_by_values_query_test.go
  openmeter/streaming/connector.go
  openmeter/streaming/testutils/streaming.go
Labels: release-note/feature
