Repository openmeterio/openmeter, pull requests merged in 2025-01, with the labels that each got.

#2001 fix(invoice): stripe sync quantity
  openmeter/app/stripe/client/invoice.go
  openmeter/app/stripe/entity/app/calculator.go
  openmeter/app/stripe/entity/app/invoice.go
  test/app/stripe/invoice_test.go
Labels: release-note/bug-fix, area/billing

#2002 chore: bump dagger version to 0.15.1
  .dagger/go.mod
  .dagger/go.sum
  .dagger/test_e2e.go
  .github/workflows/ci-exp.yaml
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .github/workflows/sdk-node.yaml
  .github/workflows/sdk-python.yaml
  .github/workflows/sdk-web.yaml
  dagger.json
  flake.lock
Labels: release-note/ignore

#1997 Simplify plan API
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/cloud/main.tsp
  api/spec/src/productcatalog/routes.tsp
  openmeter/productcatalog/plan/adapter/adapter_test.go
  openmeter/productcatalog/plan/adapter/assert.go
  openmeter/productcatalog/plan/adapter/phase.go
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/assert.go
  openmeter/productcatalog/plan/httpdriver/driver.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/plan/httpdriver/phase.go
  openmeter/productcatalog/plan/repository.go
  openmeter/productcatalog/plan/service.go
  openmeter/productcatalog/plan/service/phase.go
  openmeter/productcatalog/plan/service/service_test.go
  openmeter/server/router/plan.go
Labels: release-note/ignore

#2003 chore: bump Svix to 1.44
  .dagger/versions_pinned.go
  docker-compose.yaml
  go.mod
  go.sum
  openmeter/notification/webhook/svix.go
  openmeter/notification/webhook/webhook.go
Labels: release-note/dependency-update

#2004 chore: bump build/ci dependencies
  .dagger/versions.go
  .dagger/versions_pinned.go
  Dockerfile
  benthos-collector.Dockerfile
Labels: release-note/ignore

#2007 refactor: disable Sarama metric collection
  openmeter/watermill/driver/kafka/broker.go
Labels: release-note/ignore

#2009 Revert "refactor: disable Sarama metric collection"
  openmeter/watermill/driver/kafka/broker.go
Labels: release-note/ignore

#2008 feat(billing): profile default update
  openmeter/app/httpdriver/marketplace.go
  openmeter/billing/adapter/profile.go
  openmeter/billing/errors.go
  openmeter/billing/profile.go
  openmeter/billing/service/profile.go
  test/billing/profile_test.go
Labels: release-note/feature, area/billing

#2010 feat: use plan phase duration and index instead of start after
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/plan.tsp
  e2e/productcatalog_test.go
  openmeter/billing/worker/subscription/scanario_test.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/planphase.go
  openmeter/ent/db/planphase/planphase.go
  openmeter/ent/db/planphase/where.go
  openmeter/ent/db/planphase_create.go
  openmeter/ent/db/planphase_update.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/productcatalog.go
  openmeter/productcatalog/phase.go
  openmeter/productcatalog/phase_test.go
  openmeter/productcatalog/plan.go
  openmeter/productcatalog/plan/adapter/adapter_test.go
  openmeter/productcatalog/plan/adapter/assert.go
  openmeter/productcatalog/plan/adapter/mapping.go
  openmeter/productcatalog/plan/adapter/phase.go
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/assert.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/plan/phase.go
  openmeter/productcatalog/plan/plan.go
  openmeter/productcatalog/plan/service.go
  openmeter/productcatalog/plan/service/service_test.go
  openmeter/productcatalog/subscription/plan.go
  openmeter/productcatalog/subscription/service/change_test.go
  openmeter/subscription/service/workflowservice_test.go
  openmeter/subscription/testutils/plan.go
  pkg/datex/date.go
  tools/migrate/migrations/20250103121359_plan-phase-duration.down.sql
  tools/migrate/migrations/20250103121359_plan-phase-duration.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature

#2019 Add missing assertions in Subscription tests
  openmeter/subscription/testutils/compare.go
Labels: release-note/misc

#2020 Use error wrapping for generic errors
  openmeter/credit/balance.go
  openmeter/credit/grant.go
  openmeter/entitlement/connector.go
  openmeter/entitlement/driver/entitlement.go
  openmeter/entitlement/driver/metered.go
  openmeter/entitlement/metered/balance.go
  openmeter/entitlement/metered/grant_owner_adapter.go
  openmeter/entitlement/scheduling.go
  openmeter/productcatalog/feature/connector.go
  openmeter/productcatalog/plan/service/plan.go
  openmeter/productcatalog/subscription/service/change.go
  openmeter/productcatalog/subscription/service/create.go
  openmeter/productcatalog/subscription/service/migrate.go
  openmeter/productcatalog/subscription/service/plan.go
  openmeter/subscription/service/service.go
  openmeter/subscription/service/workflowservice.go
  pkg/models/error.go
Labels: release-note/misc

#2021 fix: billing updated-at schemantics
  openmeter/billing/adapter.go
  openmeter/billing/adapter/profile.go
  openmeter/billing/customeroverride.go
  openmeter/billing/httpdriver/profile.go
  openmeter/billing/profile.go
  openmeter/billing/service/profile.go
  test/billing/profile_test.go
Labels: area/api, release-note/misc, area/billing

#2023 chore(api): update typespec to 0.63.0
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/README.md
  api/spec/package.json
  api/spec/patches/@typespec__http.patch
  api/spec/patches/@typespec__openapi.patch
  api/spec/patches/@typespec__openapi3.patch
  api/spec/pnpm-lock.yaml
  api/spec/src/app/app.tsp
  api/spec/src/app/customer.tsp
  api/spec/src/billing/customeroverride.tsp
  api/spec/src/billing/invoices.tsp
  api/spec/src/billing/invoices/docref.tsp
  api/spec/src/billing/invoices/invoice.tsp
  api/spec/src/billing/invoices/org.tsp
  api/spec/src/billing/invoices/pay.tsp
  api/spec/src/billing/invoices/tax.tsp
  api/spec/src/billing/profile.tsp
  api/spec/src/customer.tsp
  api/spec/src/entitlements/entitlements.tsp
  api/spec/src/entitlements/feature.tsp
  api/spec/src/entitlements/grant.tsp
  api/spec/src/entitlements/subjects.tsp
  api/spec/src/meters.tsp
  api/spec/src/notification/channel.tsp
  api/spec/src/notification/event.tsp
  api/spec/src/notification/rule.tsp
  api/spec/src/portal.tsp
  api/spec/src/productcatalog/discounts.tsp
  api/spec/src/productcatalog/plan.tsp
  api/spec/src/productcatalog/prices.tsp
  api/spec/src/productcatalog/ratecards.tsp
  api/spec/src/productcatalog/subscription.tsp
  api/spec/src/subjects.tsp
  api/spec/src/types.tsp
Labels: release-note/dependency-update

#1981 Add checks for Subscription dependencies so they cannot be updated inconsistently
  openmeter/customer/adapter/customer.go
  openmeter/customer/entity/errors.go
  openmeter/customer/httpdriver/errors.go
  openmeter/productcatalog/adapter/feature.go
  openmeter/productcatalog/driver/errors.go
  openmeter/productcatalog/feature/feature.go
  openmeter/productcatalog/subscription/service/change_test.go
  openmeter/productcatalog/subscription/service/migrate_test.go
  openmeter/subscription/repo/subscriptionrepo.go
  openmeter/subscription/repo/utils.go
  openmeter/subscription/service/service_test.go
  openmeter/subscription/service/update_test.go
  openmeter/subscription/service/workflowservice_test.go
  openmeter/subscription/testutils/customer.go
  openmeter/subscription/testutils/db.go
  openmeter/subscription/testutils/repository.go
  openmeter/subscription/testutils/service.go
  test/customer/customer.go
  test/customer/customer_test.go
  test/customer/testenv.go
Labels: release-note/misc

#2026 Fix Subscription Status mapping
  e2e/productcatalog_test.go
  openmeter/productcatalog/subscription/http/mapping.go
Labels: area/api, release-note/bug-fix

#2030 feat: make progressive billing optional
  api/api.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/profile.tsp
  openmeter/billing/adapter/customeroverride.go
  openmeter/billing/adapter/profile.go
  openmeter/billing/customeroverride.go
  openmeter/billing/defaults.go
  openmeter/billing/httpdriver/profile.go
  openmeter/billing/profile.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/service/lineservice/feeline.go
  openmeter/billing/service/lineservice/service.go
  openmeter/billing/service/lineservice/usagebasedline.go
  openmeter/billing/worker/subscription/scanario_test.go
  openmeter/ent/db/billingcustomeroverride.go
  openmeter/ent/db/billingcustomeroverride/billingcustomeroverride.go
  openmeter/ent/db/billingcustomeroverride/where.go
  openmeter/ent/db/billingcustomeroverride_create.go
  openmeter/ent/db/billingcustomeroverride_update.go
  openmeter/ent/db/billingworkflowconfig.go
  openmeter/ent/db/billingworkflowconfig/billingworkflowconfig.go
  openmeter/ent/db/billingworkflowconfig/where.go
  openmeter/ent/db/billingworkflowconfig_create.go
  openmeter/ent/db/billingworkflowconfig_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  test/billing/invoice_test.go
  tools/migrate/migrations/20250108103427_billing-profile-progressive-billing-flag.down.sql
  tools/migrate/migrations/20250108103427_billing-profile-progressive-billing-flag.up.sql
  tools/migrate/migrations/atlas.sum
Labels: area/api, release-note/feature, area/billing

#2029 Test Subscription Sync
  openmeter/subscription/patch.go
  openmeter/subscription/patch_test.go
  openmeter/subscription/service/sync.go
  openmeter/subscription/service/sync_test.go
  openmeter/subscription/service/synchelpers.go
  openmeter/subscription/service/update_test.go
  openmeter/subscription/subscriptionspec.go
  openmeter/subscription/subscriptionview.go
Labels: release-note/ignore

#2032 fix: correct subscription event publishing
  openmeter/subscription/events.go
  openmeter/subscription/service/service.go
Labels: release-note/misc, area/subscriptions

#2034 chore: regenerate go client
  api/client/go/client.gen.go
Labels: release-note/ignore

#2035 fix: body returned for billing delete calls
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/httpdriver/profile.go
Labels: release-note/ignore

#2033 feat: add validate billing stack before creating a paid subscription
  app/common/billing.go
  app/common/subscription.go
  cmd/server/wire_gen.go
  openmeter/billing/subscription/validator.go
  openmeter/productcatalog/subscription/http/errors.go
  openmeter/subscription/service/service.go
  openmeter/subscription/subscriptionvalidator.go
Labels: area/api, release-note/feature, area/billing, area/subscriptions

#2038 refactor: productcatalog errors
  openmeter/productcatalog/discount.go
  openmeter/productcatalog/entitlement.go
  openmeter/productcatalog/errors.go
  openmeter/productcatalog/phase.go
  openmeter/productcatalog/plan.go
  openmeter/productcatalog/plan/adapter/plan.go
  openmeter/productcatalog/plan/errors.go
  openmeter/productcatalog/plan/errors_test.go
  openmeter/productcatalog/plan/httpdriver/errors.go
  openmeter/productcatalog/plan/phase.go
  openmeter/productcatalog/plan/plan.go
  openmeter/productcatalog/plan/ratecard.go
  openmeter/productcatalog/price.go
  openmeter/productcatalog/ratecard.go
  openmeter/productcatalog/subscription/http/errors.go
  openmeter/productcatalog/subscription/service/plan.go
  openmeter/productcatalog/subscription/testutils/adapter.go
  openmeter/productcatalog/tax.go
  openmeter/productcatalog/tax_test.go
Labels: release-note/ignore

#2037 Test Subscription Edits
  .dagger/test.go
  go.mod
  go.sum
  openmeter/productcatalog/ratecard.go
  openmeter/subscription/patch/additem.go
  openmeter/subscription/patch/additem_test.go
  openmeter/subscription/patch/addphase.go
  openmeter/subscription/patch/patch_test.go
  openmeter/subscription/patch/removeitem.go
  openmeter/subscription/patch/removeitem_test.go
  openmeter/subscription/patch/removephase.go
  openmeter/subscription/patch/stretchphase.go
  openmeter/subscription/service/sync.go
  openmeter/subscription/service/sync_test.go
  openmeter/subscription/service/synchelpers.go
  openmeter/subscription/service/workflowservice.go
  openmeter/subscription/service/workflowservice_test.go
  openmeter/subscription/subscriptionspec.go
  openmeter/subscription/subscriptionview.go
  tools.go
Labels: release-note/misc

#2039 feat: support listing invoices across namespaces
  openmeter/billing/adapter/invoice.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/invoice.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/worker/subscription/scanario_test.go
  test/billing/invoice_test.go
Labels: release-note/misc

#2042 Add missing errors to HTTP mappings
  openmeter/productcatalog/subscription/http/errors.go
  openmeter/subscription/service/workflowservice.go
Labels: release-note/misc

#2041 feat(balance-worker): add additional handlers
  openmeter/billing/worker/worker.go
  openmeter/entitlement/balanceworker/worker.go
  openmeter/notification/consumer/consumer.go
  openmeter/watermill/grouphandler/grouphandler.go
Labels: release-note/ignore, area/balance-worker

#2046 feat(balance-worker): add additional handlers
  openmeter/billing/worker/worker.go
  openmeter/entitlement/balanceworker/worker.go
  openmeter/notification/consumer/consumer.go
  openmeter/watermill/grouphandler/grouphandler.go
Labels: release-note/ignore, area/balance-worker

#2044 Testing data-migrations
  atlas.hcl
  docs/migration.md
  openmeter/testutils/pg_driver.go
  tools/migrate/migrate_test.go
  tools/migrate/productcatalog_test.go
Labels: release-note/misc

#2043 Simplify SubscriptionView
  openmeter/subscription/subscriptionspec.go
  openmeter/subscription/subscriptionview.go
Labels: release-note/ignore

#2045 Entitlements ISO support
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/types.tsp
  e2e/e2e_test.go
  e2e/entitlement_test.go
  openmeter/credit/adapter/grant.go
  openmeter/ent/db/entitlement.go
  openmeter/ent/db/entitlement/entitlement.go
  openmeter/ent/db/entitlement/where.go
  openmeter/ent/db/entitlement_create.go
  openmeter/ent/db/entitlement_update.go
  openmeter/ent/db/grant.go
  openmeter/ent/db/grant/grant.go
  openmeter/ent/db/grant/where.go
  openmeter/ent/db/grant_create.go
  openmeter/ent/db/grant_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/schema/entitlement.go
  openmeter/ent/schema/grant.go
  openmeter/entitlement/adapter/entitlement.go
  openmeter/entitlement/driver/metered.go
  openmeter/entitlement/driver/parser.go
  openmeter/notification/internal/rule.go
  pkg/datex/date.go
  pkg/recurrence/recurrence.go
  test/notification/event.go
  tools/migrate/migrate_test.go
  tools/migrate/migrations/20250109231835_entitlements-usage-period-iso.down.sql
  tools/migrate/migrations/20250109231835_entitlements-usage-period-iso.up.sql
  tools/migrate/migrations/atlas.sum
  tools/migrate/productcatalog_test.go
Labels: release-note/feature

#2047 fix(app): masked api key in http handler
  openmeter/app/httpdriver/app.go
  openmeter/app/httpdriver/customer.go
  openmeter/app/httpdriver/handler.go
  openmeter/app/httpdriver/mapper.go
  openmeter/app/httpdriver/marketplace.go
  openmeter/app/stripe/adapter.go
  openmeter/app/stripe/adapter/stripe.go
  openmeter/app/stripe/service.go
  openmeter/app/stripe/service/app.go
  openmeter/billing/httpdriver/handler.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/httpdriver/profile.go
  openmeter/server/router/router.go
  openmeter/server/server_test.go
Labels: area/api, release-note/bug-fix

#2053 fix: watermill retry logic and error reporting
  app/config/config_test.go
  app/config/events.go
  openmeter/watermill/router/logger.go
  openmeter/watermill/router/router.go
Labels: release-note/misc, area/balance-worker

#2052 Small api type fixes
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/subscription.tsp
  openmeter/productcatalog/subscription/http/mapping.go
Labels: release-note/misc

#2055 feat: remove TZ from customers and billing
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices/invoice.tsp
  api/spec/src/customer.tsp
  e2e/productcatalog_test.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/invoice.go
  openmeter/billing/profile.go
  openmeter/billing/service/customeroverride.go
  openmeter/customer/adapter/customer.go
  openmeter/customer/adapter/entitymapping.go
  openmeter/customer/entity/customer.go
  openmeter/customer/httpdriver/apimapping.go
  openmeter/customer/httpdriver/customer.go
  openmeter/ent/db/billinginvoice.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/billinginvoice/where.go
  openmeter/ent/db/billinginvoice_create.go
  openmeter/ent/db/billinginvoice_update.go
  openmeter/ent/db/customer.go
  openmeter/ent/db/customer/customer.go
  openmeter/ent/db/customer/where.go
  openmeter/ent/db/customer_create.go
  openmeter/ent/db/customer_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  openmeter/ent/schema/customer.go
  openmeter/subscription/testutils/customer.go
  pkg/timezone/tz.go
  test/billing/customeroverride_test.go
  test/billing/invoice_test.go
  test/customer/customer.go
  tools/migrate/migrations/20250110164610_customer-remove-tz.down.sql
  tools/migrate/migrations/20250110164610_customer-remove-tz.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/deprecation, release-note/misc, area/billing

#2051 fix(app): stripe uninstall with invalid api key
  openmeter/app/adapter/app.go
  openmeter/app/adapter/customer.go
  openmeter/app/entity/app.go
  openmeter/app/httpdriver/app.go
  openmeter/app/httpdriver/customer.go
  openmeter/app/httpdriver/mapper.go
  openmeter/app/input.go
  openmeter/app/stripe/adapter.go
  openmeter/app/stripe/adapter/customer.go
  openmeter/app/stripe/adapter/stripe.go
  openmeter/app/stripe/entity/app/customer.go
  openmeter/app/stripe/entity/input.go
  openmeter/app/stripe/service/factory.go
  openmeter/billing/adapter.go
  openmeter/billing/adapter/profile.go
  openmeter/billing/service.go
  openmeter/billing/service/profile.go
  openmeter/secret/entity/errors.go
  openmeter/secret/entity/input.go
  openmeter/secret/entity/secret.go
  openmeter/secret/service/secret.go
  test/app/stripe/secret_mock.go
Labels: release-note/bug-fix, area/billing

#2060 feat(api): improve tagging
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/app/app.tsp
  api/spec/src/app/marketplace.tsp
  api/spec/src/app/stripe.tsp
  api/spec/src/billing/customeroverride.tsp
  api/spec/src/billing/invoices.tsp
  api/spec/src/billing/profile.tsp
  api/spec/src/cloud/main.tsp
  api/spec/src/customer.tsp
  api/spec/src/main.tsp
  api/spec/src/notification/channel.tsp
  api/spec/src/notification/event.tsp
  api/spec/src/notification/rule.tsp
  api/spec/src/notification/svix.tsp
  api/spec/src/productcatalog/routes.tsp
Labels: release-note/ignore

#2059 feat(billing): app used check invoice states
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/profile.go
  test/billing/profile_test.go
Labels: release-note/ignore, area/billing

#2054 feat(api): add dedicated field to recurring intervals thats always ISO format
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/types.tsp
  e2e/e2e_test.go
  openmeter/entitlement/driver/metered.go
  openmeter/entitlement/driver/parser.go
  openmeter/notification/internal/rule.go
  test/notification/event.go
Labels: release-note/misc

#2069 feat: disallow durations less than an hour
  openmeter/entitlement/entitlement.go
  openmeter/entitlement/scheduling.go
  openmeter/productcatalog/phase.go
  openmeter/productcatalog/ratecard.go
Labels: release-note/misc

#2074 fix(api): mk query params non-required
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices.tsp
  openmeter/billing/httpdriver/invoice.go
  openmeter/server/router/billing.go
Labels: release-note/misc

#2075 Fix Subscription Managed Entitlements
  openmeter/entitlement/boolean/connector.go
  openmeter/entitlement/metered/connector.go
  openmeter/entitlement/static/connector.go
  openmeter/subscription/testutils/compare.go
Labels: release-note/bug-fix

#2036 feat: create database sturcture and entities for invoice discounts
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/invoicediscounts.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/errors.go
  openmeter/billing/invoice.go
  openmeter/billing/invoicediscount.go
  openmeter/billing/invoiceline.go
  openmeter/billing/service.go
  openmeter/billing/service/invoice.go
  openmeter/ent/db/billinginvoice.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/billinginvoice/where.go
  openmeter/ent/db/billinginvoice_create.go
  openmeter/ent/db/billinginvoice_query.go
  openmeter/ent/db/billinginvoice_update.go
  openmeter/ent/db/billinginvoicediscount.go
  openmeter/ent/db/billinginvoicediscount/billinginvoicediscount.go
  openmeter/ent/db/billinginvoicediscount/where.go
  openmeter/ent/db/billinginvoicediscount_create.go
  openmeter/ent/db/billinginvoicediscount_delete.go
  openmeter/ent/db/billinginvoicediscount_query.go
  openmeter/ent/db/billinginvoicediscount_update.go
  openmeter/ent/db/billinginvoiceline.go
  openmeter/ent/db/billinginvoiceline/billinginvoiceline.go
  openmeter/ent/db/billinginvoiceline/where.go
  openmeter/ent/db/billinginvoiceline_create.go
  openmeter/ent/db/billinginvoiceline_query.go
  openmeter/ent/db/billinginvoiceline_update.go
  openmeter/ent/db/client.go
  openmeter/ent/db/ent.go
  openmeter/ent/db/expose.go
  openmeter/ent/db/hook/hook.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/paginate.go
  openmeter/ent/db/predicate/predicate.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/db/tx.go
  openmeter/ent/schema/billing.go
  test/billing/invoice_test.go
  test/billing/invoicediscount_test.go
  test/billing/suite.go
  tools/migrate/migrations/20250114104811_billing-invoice-discounts.down.sql
  tools/migrate/migrations/20250114104811_billing-invoice-discounts.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/billing

#2076 BillingValidation Error Mapping
  openmeter/billing/subscription/validator.go
Labels: release-note/bug-fix

#2071 fix(app): default
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/node/test/mocks.ts
  api/client/web/src/client/openapi.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/app/app.tsp
  api/spec/src/app/stripe.tsp
  openmeter/app/adapter.go
  openmeter/app/adapter/app.go
  openmeter/app/entity/app.go
  openmeter/app/entity/base/app.go
  openmeter/app/httpdriver/app.go
  openmeter/app/httpdriver/handler.go
  openmeter/app/httpdriver/mapper.go
  openmeter/app/service.go
  openmeter/app/service/app.go
  openmeter/app/stripe/httpdriver/errors.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/schema/app.go
  openmeter/server/router/app.go
  openmeter/server/server_test.go
  test/app/stripe/app_test.go
  test/app/stripe/appstripe.go
  tools/migrate/migrations/20250113222737_app_default_with_deleted.down.sql
  tools/migrate/migrations/20250113222737_app_default_with_deleted.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/bug-fix, area/billing

#2078 fix(stripe): webhook setup url
  openmeter/app/stripe/client/client.go
Labels: release-note/bug-fix, area/billing

#2079 feat(stripe): webhook no auth
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/app/stripe.tsp
Labels: release-note/feature, area/billing

#2080 fix(stripe): set webhook api version
  openmeter/app/stripe/client/client.go
Labels: release-note/bug-fix, area/billing

#2082 chore: bump Dagger to v0.15.2
  .dagger/go.mod
  .dagger/go.sum
  .github/workflows/ci-exp.yaml
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .github/workflows/sdk-node.yaml
  .github/workflows/sdk-python.yaml
  .github/workflows/sdk-web.yaml
  dagger.json
  flake.lock
Labels: release-note/ignore

#2073 feat: add invoice advance job
  Makefile
  cmd/jobs/billing/advance/advance.go
  cmd/jobs/billing/billing.go
  cmd/jobs/main.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/invoice.go
  openmeter/billing/worker/advance/advance.go
Labels: release-note/misc

#2083 fix(e2e): increase timeout
  e2e/entitlement_test.go
Labels: release-note/bug-fix

#2085 ci: rm unused Nix module
  dagger.json
Labels: release-note/ignore

#2084 fix(app): handle customer data deleted at
  openmeter/app/adapter/app.go
  openmeter/app/adapter/customer.go
  test/app/stripe/appstripe.go
Labels: release-note/bug-fix, area/billing

#2086 Expose entitlement schedule cadence
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/entitlements/entitlements.tsp
  openmeter/entitlement/driver/parser.go
  openmeter/entitlement/entitlement.go
Labels: release-note/misc

#2087 refactor: use plurar for category names in billing API
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/customeroverride.tsp
  api/spec/src/billing/invoices.tsp
  api/spec/src/billing/profile.tsp
Labels: area/api, release-note/feature

#2089 refactor: fix cloud urls
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/spec/src/cloud/main.tsp
Labels: release-note/ignore

#2090 chore: bump confluent-kafka-go to v.2.8.0
  flake.nix
  go.mod
  go.sum
Labels: release-note/dependency-update

#2091 feat: add invoice simulation endpoint
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices.tsp
  api/spec/src/cloud/main.tsp
  openmeter/billing/httpdriver/handler.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/invoice.go
  openmeter/billing/service.go
  openmeter/billing/service/invoice.go
  openmeter/server/router/billing.go
Labels: area/api, release-note/ignore, area/billing

#2092 fix: tiered price upToAmount type
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/prices.tsp
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/subscription/http/mapping.go
Labels: area/api, release-note/bug-fix, area/product-catalog

#2088 Expose API to exclude inactive entitlements
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/entitlements/entitlements.tsp
  openmeter/entitlement/adapter/entitlement.go
  openmeter/entitlement/connector.go
  openmeter/entitlement/driver/entitlement.go
Labels: release-note/feature

#2093 Entitlement API adjustments and fixes
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/subscription.tsp
  e2e/productcatalog_test.go
  openmeter/productcatalog/subscription/http/change.go
  openmeter/productcatalog/subscription/http/create.go
  openmeter/productcatalog/subscription/http/get.go
  openmeter/productcatalog/subscription/http/mapping.go
  openmeter/productcatalog/subscription/service/plan.go
  openmeter/subscription/subscriptionview.go
  test/customer/customer.go
Labels: release-note/misc

#2077 feat: support subscription edit syncronization
  openmeter/billing/errors.go
  openmeter/billing/invoice.go
  openmeter/billing/invoiceline.go
  openmeter/billing/service.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/worker/subscription/patch.go
  openmeter/billing/worker/subscription/scanario_test.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/subscription/sync_test.go
Labels: release-note/feature, area/billing, area/subscriptions

#2095 Add currency checks on Subs creation
  openmeter/subscription/service/service.go
  openmeter/subscription/service/service_test.go
Labels: release-note/misc

#2097 fix: wrapping validation errors properly
  openmeter/productcatalog/plan.go
  openmeter/productcatalog/plan/service/plan.go
Labels: release-note/bug-fix

#2096 feat(app): pass down customer currency to create checkout session
  openmeter/app/stripe/adapter/stripe.go
  openmeter/app/stripe/client/client.go
  test/app/stripe/appstripe.go
Labels: release-note/feature, area/billing

#2098 fix: number schema
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/prices.tsp
Labels: area/api, release-note/bug-fix

#2099 Add missing items
  openmeter/subscription/subscriptionview.go
Labels: release-note/bug-fix

#2102 fix: disable pro rating
  openmeter/billing/worker/subscription/phaseiterator.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/subscription/sync_test.go
Labels: release-note/breaking-change, area/billing

#2094 Fix Phase Stretching
  openmeter/subscription/patch/patch_test.go
  openmeter/subscription/patch/stretchphase.go
  openmeter/subscription/patch/stretchphase_test.go
  openmeter/subscription/testutils/compare.go
Labels: release-note/bug-fix

#2100 feat: Invoice update api endpoint
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices.tsp
  api/spec/src/billing/invoices/invoice.tsp
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/invoicelinemapper.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/httpdriver/handler.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/invoice.go
  openmeter/billing/invoiceline.go
  openmeter/billing/service/invoice.go
  openmeter/customer/httpdriver/apimapping.go
  openmeter/customer/httpdriver/customer.go
  openmeter/ent/db/billinginvoiceflatfeelineconfig.go
  openmeter/ent/db/billinginvoiceflatfeelineconfig/billinginvoiceflatfeelineconfig.go
  openmeter/ent/db/billinginvoiceflatfeelineconfig/where.go
  openmeter/ent/db/billinginvoiceflatfeelineconfig_create.go
  openmeter/ent/db/billinginvoiceflatfeelineconfig_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/schema/billing.go
  openmeter/productcatalog/price.go
  openmeter/server/router/billing.go
  test/app/stripe/invoice_test.go
  test/billing/adapter_test.go
  test/billing/invoice_test.go
  test/billing/invoicediscount_test.go
  tools/migrate/migrations/20250117120943_billing-fee-payment-term.down.sql
  tools/migrate/migrations/20250117120943_billing-fee-payment-term.up.sql
  tools/migrate/migrations/atlas.sum
Labels: area/api, release-note/feature, area/billing

#2105 feat: implement subscription line adding on invoice creation
  app/common/billing.go
  app/common/openmeter_billingworker.go
  app/common/openmeter_server.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/billing/advance/advance.go
  cmd/server/wire_gen.go
  openmeter/app/entity/base/app.go
  openmeter/billing/adapter/validationissue.go
  openmeter/billing/events.go
  openmeter/billing/profile.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/service/service.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/billing/worker/worker.go
  openmeter/customer/entity/customer.go
  openmeter/event/metadata/resourcepath.go
  test/billing/suite.go
Labels: release-note/feature, area/billing

#2104 Add Customer filtering by subscription plan key
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/customer.tsp
  e2e/productcatalog_test.go
  openmeter/customer/adapter/customer.go
  openmeter/customer/entity/customer.go
  openmeter/customer/httpdriver/customer.go
Labels: release-note/feature

#2115 chore(api): update typespec
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/package.json
  api/spec/patches/@typespec__http.patch
  api/spec/patches/@typespec__openapi.patch
  api/spec/patches/@typespec__openapi3.patch
  api/spec/pnpm-lock.yaml
Labels: release-note/dependency-update

#2122 chore(api): fix dagger generate
  .dagger/generate.go
  .dagger/release.go
Labels: release-note/ignore

#2121 Add more Tests for Subscription Edit
  openmeter/entitlement/adapter/entitlement.go
  openmeter/subscription/repo/subscriptionphaserepo.go
  openmeter/subscription/service/sync.go
  openmeter/subscription/service/workflowservice_test.go
  openmeter/subscription/testutils/service.go
  openmeter/testutils/time.go
  test/subscription/framework_test.go
  test/subscription/scenario_editcancel_test.go
Labels: release-note/misc

#2123 chore(api): patch typescript generator
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/package.json
  api/client/node/patches/openapi-typescript.patch
  api/client/node/pnpm-lock.yaml
  api/client/node/schemas/openapi.ts
  api/client/web/src/client/openapi.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/lib/index.js
  api/spec/lib/rules/discriminatedUnions.js
  api/spec/lib/rules/docs.js
  api/spec/src/billing/customeroverride.tsp
  api/spec/src/billing/profile.tsp
  api/spec/src/events.tsp
  api/spec/src/notification/event.tsp
  api/spec/src/productcatalog/plan.tsp
  api/spec/src/productcatalog/ratecards.tsp
  api/spec/src/productcatalog/subscription.tsp
Labels: release-note/ignore

#2117 fix: remove workflow ID and timestamps
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/web/src/client/openapi.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices/invoice.tsp
  api/spec/src/billing/profile.tsp
  openmeter/billing/adapter.go
  openmeter/billing/adapter/customeroverride.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/profile.go
  openmeter/billing/httpdriver/profile.go
  openmeter/billing/profile.go
  openmeter/billing/service/customeroverride.go
  openmeter/billing/service/profile.go
  test/billing/customeroverride_test.go
  test/billing/invoice_test.go
  test/billing/profile_test.go
Labels: area/api, release-note/deprecation, area/billing

#2120 fix: ListInvoices fixes
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/web/src/client/openapi.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices.tsp
  openmeter/billing/adapter/invoice.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/invoice.go
Labels: area/api, release-note/bug-fix, area/billing

#2125 feat: implement period value calculation of the invoice
  openmeter/billing/service/invoicecalc/calculator.go
  openmeter/billing/service/invoicecalc/period.go
Labels: area/api, release-note/misc, area/billing

#2124 fix: split lines should not be returned for gathering invoices
  openmeter/billing/service/invoice.go
Labels: area/api, release-note/bug-fix, area/billing

#2126 feat: currencies endpoint
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/cloud/main.tsp
  api/spec/src/main.tsp
  api/spec/src/static/currencies.tsp
  api/spec/src/static/main.tsp
  api/spec/src/static/routes.tsp
  openmeter/server/router/router.go
  openmeter/server/router/static.go
  openmeter/static/httpdriver/currencies.go
  openmeter/static/httpdriver/driver.go
  openmeter/static/httpdriver/errors.go
Labels: release-note/misc

#2127 feat: currencies endpoint v2
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/web/src/client/openapi.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/cloud/main.tsp
  api/spec/src/info/currencies.tsp
  api/spec/src/info/main.tsp
  api/spec/src/info/routes.tsp
  api/spec/src/main.tsp
  openmeter/info/httpdriver/currencies.go
  openmeter/info/httpdriver/driver.go
  openmeter/info/httpdriver/errors.go
  openmeter/server/router/info.go
  openmeter/server/router/router.go
Labels: area/api, release-note/misc

#2131 fix: filter non-iso currencies from currency output
  openmeter/info/httpdriver/currencies.go
Labels: area/api, release-note/misc

#2128 fix: invoice action on gathering invoices
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoicestate.go
Labels: area/api, release-note/bug-fix, area/billing

#2133 Entitlement Value check for Customer
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/web/src/client/openapi.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/customer.tsp
  api/spec/src/entitlements/subjects.tsp
  app/common/customer.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/billing/advance/advance.go
  cmd/server/wire_gen.go
  e2e/productcatalog_test.go
  openmeter/customer/entity/customer.go
  openmeter/customer/httpdriver/customer.go
  openmeter/customer/httpdriver/errors.go
  openmeter/customer/httpdriver/handler.go
  openmeter/customer/service.go
  openmeter/customer/service/customer.go
  openmeter/customer/service/service.go
  openmeter/server/router/customer.go
  openmeter/server/server_test.go
  openmeter/subscription/testutils/customer.go
  test/app/stripe/testenv.go
  test/app/testenv.go
  test/billing/suite.go
  test/customer/testenv.go
Labels: release-note/feature

#2137 Hide inactive Items from current Phase of Subscription response
  openmeter/productcatalog/subscription/http/get.go
  openmeter/subscription/subscriptionview.go
Labels: release-note/misc

#2118 feat: add collector to quickstart
  collector/quickstart/collector/config.yaml
  collector/quickstart/collector/resources/dedupe-cache.yaml
  collector/quickstart/collector/streams/input.yaml
  collector/quickstart/collector/streams/output.yaml
  collector/quickstart/docker-compose.yaml
  collector/quickstart/seeder/config.yaml
  quickstart/config.yaml
  quickstart/docker-compose.yaml
Labels: release-note/misc

#2135 feat(stripe): subscribe to invoice webhooks
  openmeter/app/stripe/client/appclient.go
  openmeter/app/stripe/client/client.go
  openmeter/app/stripe/client/invoice.go
  openmeter/app/stripe/entity/app/invoice.go
  openmeter/app/stripe/httpdriver/webhook.go
  openmeter/billing/app.go
  openmeter/billing/service/invoicestate.go
  test/app/stripe/invoice_test.go
Labels: release-note/feature, area/billing

#2139 chore: bump benthos version to 4.45.1
  cmd/benthos-collector/main.go
  collector/benthos/input/kubernetes.go
  collector/benthos/input/otel_log.go
  collector/benthos/input/schedule.go
  collector/benthos/internal/message/batch.go
  collector/benthos/output/openmeter.go
  collector/benthos/output/otel_log.go
  go.mod
  go.sum
Labels: release-note/dependency-update

#2138 fix(api): use explode=true for array query params
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/customeroverride.tsp
  api/spec/src/billing/invoices.tsp
  api/spec/src/billing/profile.tsp
  api/spec/src/entitlements/subjects.tsp
  api/spec/src/events.tsp
  api/spec/src/meters.tsp
  api/spec/src/productcatalog/routes.tsp
Labels: release-note/ignore

#2132 fix: manually deleted lines should no be synced back by subscription
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/web/src/client/openapi.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices/invoice.tsp
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/invoicediscounts.go
  openmeter/billing/adapter/invoicelinemapper.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/adapter/upsert.go
  openmeter/billing/errors.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/invoice.go
  openmeter/billing/invoiceline.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/lineservice/usagebasedline.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/ent/db/billinginvoiceline.go
  openmeter/ent/db/billinginvoiceline/billinginvoiceline.go
  openmeter/ent/db/billinginvoiceline/where.go
  openmeter/ent/db/billinginvoiceline_create.go
  openmeter/ent/db/billinginvoiceline_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/schema/billing.go
  test/app/stripe/invoice_test.go
  test/billing/adapter_test.go
  test/billing/invoice_test.go
  test/billing/invoicediscount_test.go
  tools/migrate/migrations/20250121141512_billing-managed-by.down.sql
  tools/migrate/migrations/20250121141512_billing-managed-by.up.sql
  tools/migrate/migrations/atlas.sum
Labels: area/api, release-note/bug-fix, area/billing

#2141 chore: bump nix
  .envrc
  flake.lock
Labels: release-note/ignore

#2140 refactor: remove per line edit endpoints from invoicing
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/web/src/client/openapi.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices.tsp
  openmeter/billing/adapter.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/errors.go
  openmeter/billing/httpdriver/handler.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/service.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceline.go
  openmeter/server/router/billing.go
  test/billing/invoice_test.go
  test/billing/invoicediscount_test.go
Labels: area/api, release-note/deprecation, area/billing

#2142 feat: implement invoice number generation
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/web/src/client/openapi.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices/invoice.tsp
  app/common/app.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/billing/advance/advance.go
  cmd/server/wire_gen.go
  openmeter/app/sandbox/app.go
  openmeter/app/sandbox/mock.go
  openmeter/billing/adapter.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/adapter/seq.go
  openmeter/billing/app.go
  openmeter/billing/invoice.go
  openmeter/billing/seq.go
  openmeter/billing/service.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/service/invoicestate.go
  openmeter/billing/service/seq.go
  openmeter/billing/service/seq_test.go
  openmeter/ent/db/billinginvoice.go
  openmeter/ent/db/billinginvoice/where.go
  openmeter/ent/db/billinginvoice_create.go
  openmeter/ent/db/billinginvoice_update.go
  openmeter/ent/db/billingsequencenumbers.go
  openmeter/ent/db/billingsequencenumbers/billingsequencenumbers.go
  openmeter/ent/db/billingsequencenumbers/where.go
  openmeter/ent/db/billingsequencenumbers_create.go
  openmeter/ent/db/billingsequencenumbers_delete.go
  openmeter/ent/db/billingsequencenumbers_query.go
  openmeter/ent/db/billingsequencenumbers_update.go
  openmeter/ent/db/client.go
  openmeter/ent/db/ent.go
  openmeter/ent/db/expose.go
  openmeter/ent/db/hook/hook.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/paginate.go
  openmeter/ent/db/predicate/predicate.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/db/tx.go
  openmeter/ent/schema/billing.go
  test/billing/adapter_test.go
  test/billing/invoice_test.go
  test/billing/suite.go
  tools/migrate/migrations/20250123130012_billing-sequence-numbers.down.sql
  tools/migrate/migrations/20250123130012_billing-sequence-numbers.up.sql
  tools/migrate/migrations/atlas.sum
Labels: area/api, release-note/misc, area/billing

#2144 feat(app): reuse app error codes in stripe app
  openmeter/app/stripe/adapter/customer.go
  openmeter/app/stripe/adapter/stripe.go
  openmeter/app/stripe/errors.go
  openmeter/app/stripe/httpdriver/checkout_session.go
  openmeter/app/stripe/httpdriver/errors.go
  openmeter/app/stripe/httpdriver/webhook.go
  test/app/stripe/appstripe.go
Labels: release-note/feature, area/billing

#2146 feat: configure tax included excluded on lines
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/node/schemas/openapi.ts
  api/client/web/src/client/openapi.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/profile.tsp
  api/spec/src/productcatalog/tax.tsp
  openmeter/billing/adapter/customeroverride.go
  openmeter/billing/adapter/profile.go
  openmeter/billing/customeroverride.go
  openmeter/billing/defaults.go
  openmeter/billing/httpdriver/profile.go
  openmeter/billing/profile.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/ent/db/billingcustomeroverride.go
  openmeter/ent/db/billingcustomeroverride/billingcustomeroverride.go
  openmeter/ent/db/billingcustomeroverride/where.go
  openmeter/ent/db/billingcustomeroverride_create.go
  openmeter/ent/db/billingcustomeroverride_update.go
  openmeter/ent/db/billingworkflowconfig.go
  openmeter/ent/db/billingworkflowconfig/billingworkflowconfig.go
  openmeter/ent/db/billingworkflowconfig/where.go
  openmeter/ent/db/billingworkflowconfig_create.go
  openmeter/ent/db/billingworkflowconfig_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/tax.go
  openmeter/productcatalog/tax_test.go
  test/billing/tax_test.go
  tools/migrate/migrations/20250124114836_billing-tax-behavior.down.sql
  tools/migrate/migrations/20250124114836_billing-tax-behavior.up.sql
  tools/migrate/migrations/atlas.sum
Labels: area/api, release-note/feature, area/billing

#2145 feat: only syncronize lines that have changed
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/subscription/sync_test.go
Labels: release-note/bug-fix, area/billing

#2149 feat(stripe): fix response with embedded
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/app/stripe.tsp
  openmeter/app/stripe/client/appclient.go
  openmeter/app/stripe/client/stripe.go
  openmeter/app/stripe/entity/input.go
  openmeter/app/stripe/httpdriver/checkout_session.go
  test/app/stripe/appstripe.go
Labels: area/api, release-note/bug-fix

#2148 feat: add support for tax included and tax code settings on invoices
  openmeter/app/stripe/client/appclient.go
  openmeter/app/stripe/client/invoice_line.go
  openmeter/app/stripe/entity/app/invoice.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/invoice.go
  test/app/stripe/invoice_test.go
  test/app/stripe/stripe_mock.go
Labels: release-note/bug-fix, area/billing

#2155 fix(ci): npm package publish
  .dagger/release.go
  .github/workflows/sdk-javascript-release.yaml
  api/client/javascript/.npmignore
Labels: release-note/ignore

#2156 feat: make tax codes and inclusion configurable in billing profiles
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.d.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/profile.tsp
  openmeter/billing/adapter/customeroverride.go
  openmeter/billing/adapter/profile.go
  openmeter/billing/customeroverride.go
  openmeter/billing/defaults.go
  openmeter/billing/httpdriver/profile.go
  openmeter/billing/invoice.go
  openmeter/billing/profile.go
  openmeter/ent/db/billingcustomeroverride.go
  openmeter/ent/db/billingcustomeroverride/billingcustomeroverride.go
  openmeter/ent/db/billingcustomeroverride/where.go
  openmeter/ent/db/billingcustomeroverride_create.go
  openmeter/ent/db/billingcustomeroverride_update.go
  openmeter/ent/db/billingworkflowconfig.go
  openmeter/ent/db/billingworkflowconfig/billingworkflowconfig.go
  openmeter/ent/db/billingworkflowconfig/where.go
  openmeter/ent/db/billingworkflowconfig_create.go
  openmeter/ent/db/billingworkflowconfig_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  openmeter/productcatalog/tax.go
  openmeter/productcatalog/tax_test.go
  test/billing/tax_test.go
  tools/migrate/migrations/20250127132300_billing-tax-behavior-to-config.down.sql
  tools/migrate/migrations/20250127132300_billing-tax-behavior-to-config.up.sql
  tools/migrate/migrations/atlas.sum
Labels: area/api, release-note/feature

#2157 fix: invoice updates should allow adding new lines without IDs
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.d.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices/invoice.tsp
  openmeter/billing/httpdriver/invoiceline.go
Labels: area/api, release-note/bug-fix

#2158 feat(app): stripe app validate customer data
  openmeter/app/stripe/adapter/customer.go
  openmeter/app/stripe/adapter/stripe.go
  openmeter/app/stripe/client/appclient.go
  openmeter/app/stripe/client/stripe.go
  test/app/stripe/appstripe.go
  test/app/stripe/fixture.go
  test/app/stripe/invoice_test.go
  test/app/stripe/testenv.go
Labels: release-note/feature, area/billing

#2161 fix: uppercase names
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.d.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/app/app.tsp
  api/spec/src/billing/customeroverride.tsp
  api/spec/src/billing/invoices.tsp
  api/spec/src/billing/invoices/docref.tsp
  api/spec/src/billing/invoices/invoice.tsp
  api/spec/src/billing/profile.tsp
  api/spec/src/productcatalog/plan.tsp
  api/spec/src/productcatalog/prices.tsp
  api/spec/src/types.tsp
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/httpdriver/invoiceline.go
Labels: area/api, release-note/breaking-change, release-note/bug-fix

#2159 fix: stripe sync issues
  openmeter/app/stripe/client/appclient.go
  openmeter/app/stripe/client/invoice_line.go
  openmeter/app/stripe/entity/app/invoice.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/service/invoice.go
  openmeter/billing/worker/subscription/sync_test.go
  test/app/stripe/invoice_test.go
  test/app/stripe/stripe_mock.go
  test/billing/invoice_test.go
Labels: release-note/bug-fix, area/billing

#2162 fix: invoice event unmarshaling
  openmeter/billing/events.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/worker.go
Labels: release-note/bug-fix, area/billing

#2164 feat(app): pass email in stripe checkout session customer create
  openmeter/app/stripe/adapter/customer.go
  openmeter/app/stripe/adapter/stripe.go
  openmeter/app/stripe/client/appclient.go
  openmeter/app/stripe/client/stripe.go
  openmeter/app/stripe/entity/input.go
Labels: release-note/feature, area/billing

#2160 Fix entitlement history bugs
  openmeter/credit/balance.go
  openmeter/entitlement/metered/balance.go
  openmeter/entitlement/metered/balance_test.go
  pkg/slicesx/first.go
  pkg/slicesx/last.go
Labels: release-note/bug-fix

#2166 Fix recurrence
  pkg/recurrence/recurrence.go
  pkg/recurrence/recurrence_test.go
Labels: release-note/misc

#2167 Fix Feature Archivation Checks
  openmeter/productcatalog/adapter/feature.go
  openmeter/productcatalog/adapter/feature_test.go
Labels: release-note/bug-fix

#2168 Disallow items with periods less than 1 hour
  openmeter/entitlement/boolean/connector.go
  openmeter/entitlement/entitlement.go
  openmeter/entitlement/metered/connector.go
  openmeter/entitlement/static/connector.go
  openmeter/productcatalog/entitlement.go
  pkg/recurrence/recurrence.go
  tools/migrate/migrations/20250129143720_minimum-entitlement-usageperiod.down.sql
  tools/migrate/migrations/20250129143720_minimum-entitlement-usageperiod.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/misc

#2170 test(api): add tests to JavaScript SDK
  api/client/javascript/package.json
  api/client/javascript/pnpm-lock.yaml
  api/client/javascript/scripts/generate.ts
  api/client/javascript/src/client/events.spec.ts
  api/client/javascript/src/client/events.ts
  api/client/javascript/src/client/index.ts
  api/client/javascript/src/client/placeholder.spec.ts
  api/client/javascript/src/client/schemas.d.ts
Labels: release-note/misc

#2175 feat(billing): add collectionAt to invoices
  openmeter/billing/adapter/invoice.go
  openmeter/billing/invoice.go
  openmeter/billing/service/collectionat.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceline.go
  openmeter/ent/db/billinginvoice.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/billinginvoice/where.go
  openmeter/ent/db/billinginvoice_create.go
  openmeter/ent/db/billinginvoice_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  test/billing/invoice_test.go
  tools/migrate/migrations/20250130104722_billing-collection-at.down.sql
  tools/migrate/migrations/20250130104722_billing-collection-at.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/ignore

#2169 feat(app): stripe checkout session params
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/app/stripe.tsp
  openmeter/app/stripe/client/appclient.go
  openmeter/app/stripe/client/checkout.go
  openmeter/app/stripe/client/stripe.go
  openmeter/app/stripe/entity/input.go
  openmeter/app/stripe/httpdriver/checkout_session.go
  test/app/stripe/appstripe.go
Labels: release-note/feature, area/billing

#2172 feat(customer): add optional key
  api/api.gen.go
  api/openapi.yaml
  api/spec/src/app/stripe.tsp
  api/spec/src/customer.tsp
  openmeter/app/stripe/adapter/stripe.go
  openmeter/app/stripe/entity/input.go
  openmeter/app/stripe/httpdriver/checkout_session.go
  openmeter/customer/adapter/customer.go
  openmeter/customer/adapter/entitymapping.go
  openmeter/customer/entity/customer.go
  openmeter/customer/entity/errors.go
  openmeter/customer/httpdriver/apimapping.go
  openmeter/customer/httpdriver/customer.go
  openmeter/customer/httpdriver/errors.go
  openmeter/ent/db/customer.go
  openmeter/ent/db/customer/customer.go
  openmeter/ent/db/customer/where.go
  openmeter/ent/db/customer_create.go
  openmeter/ent/db/customer_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/customer.go
  test/customer/customer.go
  tools/migrate/migrations/20250130034713_customer_key.down.sql
  tools/migrate/migrations/20250130034713_customer_key.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/billing

#2177 refactor: use wire for jobs service
  app/common/billing.go
  app/common/telemetry.go
  cmd/jobs/billing/advance/advance.go
  cmd/jobs/config/loader.go
  cmd/jobs/entitlement/init.go
  cmd/jobs/entitlement/recalculatesnapshots.go
  cmd/jobs/internal/app.go
  cmd/jobs/internal/config.go
  cmd/jobs/internal/globals.go
  cmd/jobs/internal/version.go
  cmd/jobs/internal/wire.go
  cmd/jobs/internal/wire_gen.go
  cmd/jobs/main.go
  cmd/jobs/service/otel.go
  cmd/jobs/version.go
Labels: release-note/ignore

#2178 chore(api): generate cloud
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.d.ts
  api/openapi.cloud.yaml
Labels: area/api, release-note/ignore

#2180 feat(sdk): throw on error and export types in JavaScript SDK
  api/client/javascript/package.json
  api/client/javascript/scripts/generate.ts
  api/client/javascript/src/client/apps.ts
  api/client/javascript/src/client/billing.ts
  api/client/javascript/src/client/common.ts
  api/client/javascript/src/client/customers.ts
  api/client/javascript/src/client/entitlements.ts
  api/client/javascript/src/client/events.spec.ts
  api/client/javascript/src/client/events.ts
  api/client/javascript/src/client/features.ts
  api/client/javascript/src/client/index.ts
  api/client/javascript/src/client/meters.ts
  api/client/javascript/src/client/notifications.ts
  api/client/javascript/src/client/plans.ts
  api/client/javascript/src/client/portal.ts
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/client/subjects.ts
  api/client/javascript/src/client/subscriptions.ts
  api/client/javascript/src/client/utils.ts
  api/client/javascript/src/portal/index.ts
Labels: release-note/misc

#2179 feat(billing): implement invoice collector
  app/common/billing.go
  cmd/jobs/billing/billing.go
  cmd/jobs/billing/collect/collect.go
  cmd/jobs/internal/wire.go
  cmd/jobs/internal/wire_gen.go
  openmeter/billing/service/collectionat.go
  openmeter/billing/service/invoice.go
  openmeter/billing/worker/collect/collect.go
Labels: release-note/feature

#2182 feat: sent to customer at field
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices/invoice.tsp
  openmeter/app/sandbox/app.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/app.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/invoice.go
  openmeter/billing/service/invoicestate.go
  openmeter/ent/db/billinginvoice.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/billinginvoice/where.go
  openmeter/ent/db/billinginvoice_create.go
  openmeter/ent/db/billinginvoice_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  tools/migrate/migrations/20250131125127_billing-sent-to-customer-at.down.sql
  tools/migrate/migrations/20250131125127_billing-sent-to-customer-at.up.sql
  tools/migrate/migrations/atlas.sum
Labels: area/api, release-note/feature, area/billing

#2184 fix: billing dependency cleanup
  app/common/billing.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/internal/wire_gen.go
  cmd/server/wire_gen.go
Labels: release-note/ignore

#2185 Exclude deleted plan contents from GET response
  openmeter/productcatalog/plan/adapter/plan.go
Labels: release-note/bug-fix
