Repository openmeterio/openmeter, pull requests merged in 2025-07, with the labels that each got.

#3058 refactor(subs): use validationissues
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/errors.tsp
  api/spec/src/productcatalog/errors.tsp
  api/spec/src/productcatalog/routes.tsp
  e2e/productcatalog_test.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/productcatalog/subscription/http/errors.go
  openmeter/subscription/apply.go
  openmeter/subscription/errors.go
  openmeter/subscription/errors_test.go
  openmeter/subscription/fieldselectormapper.go
  openmeter/subscription/patch/additem.go
  openmeter/subscription/specpath.go
  openmeter/subscription/subscriptionspec.go
  openmeter/subscription/subscriptionview.go
  openmeter/subscription/workflow/service/subscription.go
  pkg/models/fieldselector.go
  pkg/models/fieldselector_test.go
Labels: release-note/misc

#3060 chore: allow setting postgres settings by field
  app/common/database.go
  app/config/config_test.go
  app/config/postgres.go
Labels: release-note/misc

#3064 feat(entitlement): changing UsagePeriod duration
  .dagger/migrate.go
  Makefile
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/usagereset.go
  openmeter/ent/db/usagereset/usagereset.go
  openmeter/ent/db/usagereset/where.go
  openmeter/ent/db/usagereset_create.go
  openmeter/ent/schema/usage_reset.go
  openmeter/entitlement/adapter/entitlement.go
  openmeter/entitlement/adapter/usage_reset.go
  openmeter/entitlement/metered/grant_owner_adapter.go
  openmeter/entitlement/metered/grant_owner_adapter_test.go
  openmeter/entitlement/metered/repository.go
  openmeter/entitlement/metered/reset_test.go
  openmeter/entitlement/metered/utils_test.go
  tools/migrate/billing_test.go
  tools/migrate/entitlement_test.go
  tools/migrate/migrations/20250703081943_entitlement-usageperiod-interval-change.down.sql
  tools/migrate/migrations/20250703081943_entitlement-usageperiod-interval-change.up.sql
  tools/migrate/migrations/atlas.sum
  tools/migrate/testdata/billing/README.md
  tools/migrate/testdata/sqlcgen/20250605102416/db/db.go
  tools/migrate/testdata/sqlcgen/20250605102416/db/helpers.go
  tools/migrate/testdata/sqlcgen/20250605102416/db/models.go
  tools/migrate/testdata/sqlcgen/20250605102416/db/queries.sql.go
  tools/migrate/testdata/sqlcgen/20250605102416/fixture.sql
  tools/migrate/testdata/sqlcgen/20250605102416/sqlc.yaml
  tools/migrate/testdata/sqlcgen/20250605102416/sqlc/db-schema.sql
  tools/migrate/testdata/sqlcgen/20250605102416/sqlc/queries.sql
  tools/migrate/testdata/sqlcgen/20250609172811/db/db.go
  tools/migrate/testdata/sqlcgen/20250609172811/db/models.go
  tools/migrate/testdata/sqlcgen/20250609172811/db/queries.sql.go
  tools/migrate/testdata/sqlcgen/20250609172811/fixture.sql
  tools/migrate/testdata/sqlcgen/20250609172811/sqlc.yaml
  tools/migrate/testdata/sqlcgen/20250609172811/sqlc/db-schema.sql
  tools/migrate/testdata/sqlcgen/20250609172811/sqlc/queries.sql
  tools/migrate/testdata/sqlcgen/20250624115812/db/db.go
  tools/migrate/testdata/sqlcgen/20250624115812/db/models.go
  tools/migrate/testdata/sqlcgen/20250624115812/db/queries.sql.go
  tools/migrate/testdata/sqlcgen/20250624115812/sqlc.yaml
  tools/migrate/testdata/sqlcgen/20250624115812/sqlc/db-schema.sql
  tools/migrate/testdata/sqlcgen/20250624115812/sqlc/queries.sql
  tools/migrate/testdata/sqlcgen/20250703081943/db/db.go
  tools/migrate/testdata/sqlcgen/20250703081943/db/models.go
  tools/migrate/testdata/sqlcgen/20250703081943/db/queries.sql.go
  tools/migrate/testdata/sqlcgen/20250703081943/sqlc.yaml
  tools/migrate/testdata/sqlcgen/20250703081943/sqlc/db-schema.sql
  tools/migrate/testdata/sqlcgen/20250703081943/sqlc/queries.sql
  tools/migrate/testdata/sqlcgen/README.md
Labels: release-note/feature

#3075 fix: main
  openmeter/ent/db/mutation.go
  openmeter/ent/db/usagereset.go
  openmeter/ent/db/usagereset/where.go
  openmeter/ent/db/usagereset_create.go
  openmeter/ent/schema/usage_reset.go
  openmeter/entitlement/metered/grant_owner_adapter_test.go
  openmeter/entitlement/metered/repository.go
Labels: release-note/ignore

#3073 feat(billing): ignore sync annotation
  openmeter/billing/adapter/invoicelinemapper.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/annotations.go
  openmeter/billing/invoiceline.go
  openmeter/billing/worker/subscription/patch.go
  openmeter/billing/worker/subscription/phaseiterator.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/ent/db/billinginvoiceline.go
  openmeter/ent/db/billinginvoiceline/billinginvoiceline.go
  openmeter/ent/db/billinginvoiceline/where.go
  openmeter/ent/db/billinginvoiceline_create.go
  openmeter/ent/db/billinginvoiceline_query.go
  openmeter/ent/db/billinginvoiceline_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  openmeter/subscription/subscriptionspec.go
  pkg/timeutil/openperiod_test.go
  test/billing/invoice_test.go
  tools/migrate/migrations/20250707075725_billingline-annotations.down.sql
  tools/migrate/migrations/20250707075725_billingline-annotations.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/ignore

#3083 refactor(wire): ingest init
  app/common/config.go
  app/common/kafka.go
  app/common/openmeter_server.go
  cmd/jobs/internal/wire_gen.go
  cmd/server/main.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
Labels: release-note/ignore

#3082 feat(customer): get by usage attribution
  openmeter/customer/adapter.go
  openmeter/customer/adapter/customer.go
  openmeter/customer/customer.go
  openmeter/customer/service.go
  openmeter/customer/service/customer.go
  openmeter/server/server_test.go
  test/customer/customer.go
  test/customer/customer_test.go
Labels: release-note/ignore, area/billing

#3090 fix: namespace for Subject
  openmeter/notification/consumer/entitlementbalancethreshold.go
  openmeter/notification/consumer/entitlementreset.go
  openmeter/subject/adapter/subject.go
  openmeter/subject/httphandler/mapping.go
  openmeter/subject/httphandler/subject.go
  openmeter/subject/subject.go
Labels: release-note/ignore

#3093 fix(api): customerIdOrKey entitlement param type
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/entitlements/customer.tsp
Labels: area/api, release-note/bug-fix

#3106 feat: add customer subject service hook
  app/common/billing.go
  app/common/config.go
  app/common/customer.go
  app/config/config.go
  app/config/config_test.go
  app/config/customer.go
  app/config/testdata/complete.yaml
  cmd/server/wire.go
  cmd/server/wire_gen.go
  openmeter/customer/service/hooks/subject.go
  openmeter/customer/service/hooks/subject_test.go
  openmeter/server/server_test.go
  openmeter/subject/service.go
  openmeter/subject/service/service.go
  pkg/models/metadata.go
  pkg/models/servicehook.go
Labels: release-note/misc

#3107 chore: update oapi-codegen to 2.5.0
  api/api.gen.go
  api/client/go/client.gen.go
  api/codegen.yaml
  go.mod
  go.sum
Labels: release-note/misc

#3108 feat: add ignore errors config option
  app/common/customer.go
  app/config/config_test.go
  app/config/customer.go
  app/config/testdata/complete.yaml
  openmeter/customer/service/hooks/subject.go
Labels: release-note/ignore

#3114 fix(customer): subject service hook
  openmeter/customer/adapter/customer.go
  openmeter/customer/service/hooks/subject.go
  openmeter/customer/service/hooks/subject_test.go
Labels: release-note/misc

#3116 fix(sub): setting Customer metadata/annotations
  openmeter/subscription/service/service.go
Labels: release-note/bug-fix

#3121 chore: fix test notification event
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/notification/internal/rule.go
Labels: release-note/misc, area/notification, area/billing

#3115 feat(streaming): query by customer
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/meters.tsp
  openmeter/meter/httphandler/handler.go
  openmeter/meter/httphandler/mapping.go
  openmeter/meter/httphandler/query.go
  openmeter/meter/httphandler/query_csv.go
  openmeter/meter/meter.go
  openmeter/server/router/router.go
  openmeter/streaming/clickhouse/connector.go
  openmeter/streaming/clickhouse/connector_test.go
  openmeter/streaming/clickhouse/meter_query.go
  openmeter/streaming/clickhouse/meter_query_test.go
  openmeter/streaming/query_params.go
Labels: area/api, area/processor, release-note/feature

#3123 chore(client): regen
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
Labels: area/api, release-note/ignore

#3124 refactor(streaming): meter query customer filter
  openmeter/streaming/clickhouse/meter_query.go
Labels: area/processor, release-note/ignore

#3130 chore(sink-worker): log out dropped events
  app/config/sink.go
  cmd/sink-worker/main.go
  config.example.yaml
  openmeter/sink/sink.go
Labels: release-note/misc

#3131 fix: allow creating invoice for customers already deleted
  openmeter/billing/service/customer.go
  openmeter/billing/service/customeroverride.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/service/service.go
  openmeter/customer/customer.go
  openmeter/customer/httpdriver/customer.go
  openmeter/entitlement/validators/customer/validator.go
  test/billing/invoice_test.go
  test/customer/customer.go
Labels: release-note/bug-fix, area/billing

#3136 chore: add json tags to RawEvent struct
  openmeter/streaming/connector.go
Labels: release-note/misc

#3140 fix: omit deleted when listing channels
  openmeter/notification/adapter/channel.go
Labels: release-note/bug-fix

#3142 fix: decrease subs sync noise
  openmeter/billing/worker/subscription/sync.go
Labels: release-note/ignore, area/billing

#3144 feat(api): cutomer stripe apis
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/app/app.tsp
  api/spec/src/app/customer.tsp
  api/spec/src/app/stripe.tsp
  api/spec/src/billing/customeroverride.tsp
  api/spec/src/billing/invoices/org.tsp
  api/spec/src/cloud/main.tsp
  api/spec/src/customer/app.tsp
  api/spec/src/customer/customer.tsp
  api/spec/src/customer/main.tsp
  api/spec/src/customer/stripe.tsp
  api/spec/src/main.tsp
  openmeter/app/adapter/app.go
  openmeter/app/adapter/customer.go
  openmeter/app/app.go
  openmeter/app/httpdriver/customer.go
  openmeter/app/httpdriver/mapper.go
  openmeter/app/input.go
  openmeter/app/stripe/adapter.go
  openmeter/app/stripe/adapter/stripe.go
  openmeter/app/stripe/client/appclient.go
  openmeter/app/stripe/client/portal.go
  openmeter/app/stripe/entity/portal.go
  openmeter/app/stripe/httpdriver/customer.go
  openmeter/app/stripe/httpdriver/handler.go
  openmeter/app/stripe/httpdriver/mapping.go
  openmeter/app/stripe/service.go
  openmeter/app/stripe/service/app.go
  openmeter/billing/customeroverride.go
  openmeter/billing/service.go
  openmeter/billing/service/customeroverride.go
  openmeter/server/router/customerstripe.go
  openmeter/server/server_test.go
  test/app/stripe/app_test.go
  test/app/stripe/appstripe.go
  test/app/stripe/stripe_mock.go
  test/billing/customeroverride_test.go
Labels: area/api, release-note/feature, area/apps

#3143 fix: update/maintain dueAt on invoices [OM-1376]
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoicecalc/calculator.go
  openmeter/billing/service/invoicecalc/collectionat.go
  openmeter/billing/service/invoicecalc/discounts.go
  openmeter/billing/service/invoicecalc/draftuntil.go
  openmeter/billing/service/invoicecalc/dueat.go
  openmeter/billing/service/invoicestate.go
  test/billing/invoice_test.go
Labels: release-note/bug-fix, area/billing

#3153 fix(stripe): customer portal create status code
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/customer/stripe.tsp
Labels: area/api, release-note/bug-fix, area/apps

#3158 refactor: ignore/log payment app type mismatch
  openmeter/customer/service/hooks/subject.go
  openmeter/customer/service/hooks/subject_test.go
Labels: release-note/misc

#3160 fix: do not hardcode schema in migrations
  tools/migrate/migrations/20250609204117_billing-migrate-split-line-groups.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/bug-fix

#3161 fix: error mapping
  openmeter/productcatalog/addon/service/addon.go
  openmeter/productcatalog/errors.go
  openmeter/productcatalog/plan/service/plan.go
Labels: release-note/bug-fix

#3149 feat: billing use streaming specified minimum resolution [OM-1469]
  openmeter/billing/defaults.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/invoiceline.go
  openmeter/billing/service/lineservice/service.go
  openmeter/billing/service/lineservice/usagebasedline.go
  openmeter/billing/service/lineservice/usagebasedlineflat.go
  openmeter/billing/worker/subscription/invoiceupdate.go
  openmeter/billing/worker/subscription/phaseiterator.go
  openmeter/billing/worker/subscription/phaseiterator_test.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/streaming/defaults.go
  openmeter/streaming/testutils/streaming.go
  openmeter/subscription/subscriptionspec.go
  test/app/stripe/invoice_test.go
  test/billing/invoice_test.go
  tools/migrate/migrations/20250731160524_billing-second-resolution.down.sql
  tools/migrate/migrations/20250731160524_billing-second-resolution.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/bug-fix, release-note/feature, area/billing
