Repository openmeterio/openmeter, pull requests merged in 2025-09, with the labels that each got.

#3301 fix: breaking down migration
  tools/migrate/migrations/20250821121421_entitlement-customer-link.down.sql
Labels: release-note/bug-fix

#3310 chore: fix meter query validation errors
  openmeter/streaming/clickhouse/connector.go
  openmeter/streaming/clickhouse/meter_query.go
Labels: area/api, release-note/bug-fix

#3311 fix: subscription sync should save deleted invoices
  openmeter/billing/errors.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/service.go
  openmeter/billing/service/invoice.go
  openmeter/billing/worker/subscription/invoiceupdate.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/server/server_test.go
  test/billing/discount_test.go
  test/billing/invoice_test.go
Labels: release-note/bug-fix, area/billing, area/subscriptions

#3313 fix: support time zoned monthly metered queries
  openmeter/streaming/clickhouse/meter_query.go
Labels: area/api, release-note/bug-fix

#3318 fix(logger): log with context
  openmeter/app/stripe/service/billing.go
  openmeter/customer/adapter/customer.go
  openmeter/customer/service/hooks/subjectcustomer.go
  openmeter/entitlement/balanceworker/filters/highwatermark.go
  openmeter/notification/consumer/entitlementbalancethreshold.go
  openmeter/sink/meters.go
Labels: release-note/ignore

#3321 chore: fix missing nil check
  openmeter/notification/httpdriver/mapping.go
Labels: release-note/bug-fix

#3322 fix(notification): fix payload type
  openmeter/notification/httpdriver/mapping.go
Labels: release-note/bug-fix

#3323 chore: log transaction rollbacks
  pkg/framework/transaction/transaction.go
Labels: release-note/ignore

#3325 feat: add trancing to service hooks
  app/common/customer.go
  app/common/subject.go
  cmd/server/wire_gen.go
  openmeter/customer/service/hooks/subjectcustomer.go
  openmeter/customer/service/hooks/subjectcustomer_test.go
  openmeter/subject/service/hooks/customersubject.go
  openmeter/subject/service/hooks/customersubject_test.go
Labels: release-note/ignore

#3327 fix: missing usage attribution for deleted customer
  openmeter/customer/adapter/customer.go
  openmeter/customer/service/customer.go
  openmeter/customer/service/service_test.go
  openmeter/customer/testutils/env.go
Labels: release-note/bug-fix

#3335 fix: rm new tx for immutable operations in subject service
  openmeter/subject/service/service.go
Labels: release-note/misc

#3337 fix: check for deleted customer
  openmeter/app/httpdriver/customer.go
  openmeter/app/stripe/adapter/stripe.go
  openmeter/app/stripe/httpdriver/checkout_session.go
  openmeter/app/stripe/httpdriver/customer.go
  openmeter/billing/worker/subscription/reconciler.go
  openmeter/credit/driver/grant.go
  openmeter/customer/customer.go
  openmeter/customer/httpdriver/customer.go
  openmeter/customer/service/customer.go
  openmeter/customer/service/hooks/subjectcustomer.go
  openmeter/entitlement/balanceworker/subject_customer.go
  openmeter/entitlement/driver/v2/customer.go
  openmeter/entitlement/driver/v2/customer_metered.go
  openmeter/productcatalog/subscription/http/create.go
  openmeter/productcatalog/subscription/http/get.go
  openmeter/subscription/service/service.go
  openmeter/subscription/service/servicevalidation.go
  openmeter/subscription/validators/customer/validator.go
  openmeter/subscription/workflow/service/subscription.go
Labels: release-note/bug-fix

#3336 fix(db): add indexes for common queries
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/schema/customer.go
  tools/migrate/migrations/20250908130504_customer-indexes.down.sql
  tools/migrate/migrations/20250908130504_customer-indexes.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/ignore

#3357 fix(entitlement/repo): properly resolve entitlement's customer's cust…
  openmeter/customer/adapter/customer.go
  openmeter/entitlement/adapter/entitlement.go
Labels: release-note/bug-fix

#3356 chore: remove rollback debug logging
  pkg/framework/transaction/transaction.go
Labels: release-note/ignore

#3343 fix(stripe): send invoice payment collection method with period due date
  openmeter/app/stripe/entity/app/invoice.go
  test/app/stripe/invoice_test.go
Labels: release-note/bug-fix, area/billing

#3363 docs(api): remove request access text
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/cloud/main.tsp
  api/spec/src/main.tsp
Labels: release-note/ignore

#3341 feat: additional client options
  app/config/config.go
  app/config/postgres.go
  openmeter/watermill/driver/kafka/broker.go
  openmeter/watermill/driver/kafka/publisher.go
  openmeter/watermill/driver/kafka/saslscram.go
  openmeter/watermill/driver/kafka/subscriber.go
Labels: release-note/feature

#3392 fix: remove unnecessary deleted check on subject when fetching
  openmeter/entitlement/balanceworker/subject_customer.go
Labels: release-note/bug-fix

#3389 refactor(entitlement): use hooks to honor subscription managed entitlements
  e2e/productcatalog_test.go
  openmeter/customer/httpdriver/handler.go
  openmeter/customer/service/hooks/entitlementvalidator.go
  openmeter/entitlement/connector.go
  openmeter/entitlement/driver/entitlement.go
  openmeter/entitlement/driver/metered.go
  openmeter/entitlement/driver/v2/handler.go
  openmeter/entitlement/hooks/subscription/hook.go
  openmeter/entitlement/metered/connector.go
  openmeter/entitlement/metered/entitlement.go
  openmeter/entitlement/metered/entitlement_grant.go
  openmeter/entitlement/metered/hook.go
  openmeter/entitlement/metered/lateevents_test.go
  openmeter/entitlement/metered/reset.go
  openmeter/entitlement/metered/utils_test.go
  openmeter/entitlement/service/scheduling.go
  openmeter/entitlement/service/scheduling_test.go
  openmeter/entitlement/service/service.go
  openmeter/entitlement/service/utils_test.go
  openmeter/registry/builder/entitlement.go
  openmeter/registry/entitlement.go
  openmeter/server/router/router.go
  openmeter/server/server_test.go
  openmeter/subject/httphandler/handler.go
  openmeter/subject/service/hooks/entitlementvalidator.go
  openmeter/subscription/context.go
  openmeter/subscription/entitlement/adapter.go
  openmeter/subscription/service/service.go
  test/billing/subscription_suite.go
  test/customer/testenv.go
  test/entitlement/regression/framework_test.go
Labels: release-note/ignore

#3395 feat(streaming): list subjects
  go.mod
  go.sum
  openmeter/customer/adapter.go
  openmeter/customer/adapter/customer.go
  openmeter/customer/adapter/entitymapping.go
  openmeter/customer/customer.go
  openmeter/customer/service.go
  openmeter/customer/service/customer.go
  openmeter/ent/db/paginate.go
  openmeter/meter/httphandler/query.go
  openmeter/server/server_test.go
  openmeter/streaming/clickhouse/connector.go
  openmeter/streaming/clickhouse/meter_query.go
  openmeter/streaming/clickhouse/meter_query_test.go
  openmeter/streaming/clickhouse/queryhelper.go
  openmeter/streaming/connector.go
  openmeter/streaming/query_params.go
  openmeter/streaming/testutils/streaming.go
  pkg/framework/entutils/entpaginate/paginate.tpl
  pkg/framework/entutils/testutils/ent1/db/paginate.go
  test/customer/customer.go
  test/customer/customer_test.go
Labels: area/processor, release-note/ignore

#3398 feat(subject): remove manager
  app/common/subject.go
  app/config/config.go
  app/config/config_test.go
  app/config/subject.go
  openmeter/subject/manager/manager.go
Labels: release-note/ignore

#3403 chore: allow disabling topic provisioner
  app/common/kafka.go
  app/common/watermill.go
  app/config/config_test.go
  app/config/topicprovisioner.go
  cmd/balance-worker/wire.go
  cmd/balance-worker/wire_gen.go
  cmd/billing-worker/wire.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/internal/wire_gen.go
  cmd/notification-service/wire.go
  cmd/notification-service/wire_gen.go
  cmd/server/wire_gen.go
  cmd/sink-worker/wire.go
  cmd/sink-worker/wire_gen.go
  pkg/kafka/topicprovisioner.go
Labels: release-note/misc

#3412 fix: logging customer provisioning errors
  openmeter/customer/service/hooks/subjectcustomer.go
Labels: release-note/bug-fix

#3421 refactor: kafka config default setting
  app/config/ingest.go
Labels: release-note/ignore

#3422 chore: optimize subject queries
  go.sum
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/schema/subject.go
  tools/migrate/migrations/20250924131607_subject-index.down.sql
  tools/migrate/migrations/20250924131607_subject-index.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/misc

#3420 chore(api): mark subscriptionRestore as deprecated
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/routes.tsp
Labels: release-note/ignore

#3430 feat(streaming): meter query prewhere
  .dagger/versions_pinned.go
  app/common/streaming.go
  app/config/aggregation.go
  deploy/charts/openmeter/templates/clickhouse.yaml
  docker-compose.base.yaml
  examples/collectors/database/docker-compose.yaml
  openmeter/streaming/clickhouse/connector.go
  openmeter/streaming/clickhouse/meter_query.go
  openmeter/streaming/clickhouse/meter_query_test.go
Labels: area/processor, release-note/feature

#3435 fix(app): stripe portal session stripe custome not found
  openmeter/app/stripe/client/portal.go
Labels: release-note/bug-fix, area/apps

#3434 fix(grants): undo incorrect rename
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/entitlements/grant.tsp
  api/spec/src/entitlements/v2/grant.tsp
  e2e/e2e_test.go
  go.sum
  openmeter/credit/adapter/grant.go
  openmeter/credit/grant.go
  openmeter/credit/grant/events_2.go
  openmeter/credit/grant/grant.go
  openmeter/credit/grant/repo.go
  openmeter/ent/db/grant.go
  openmeter/ent/db/grant/grant.go
  openmeter/ent/schema/grant.go
  openmeter/entitlement/driver/metered.go
  openmeter/entitlement/driver/v2/mapping.go
  tools/migrate/migrations/20250926145502_grant-annotations.down.sql
  tools/migrate/migrations/20250926145502_grant-annotations.up.sql
  tools/migrate/migrations/20250926145930_null-grant-annotations.down.sql
  tools/migrate/migrations/20250926145930_null-grant-annotations.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/misc

#3423 feat(subs): add config for multi-subscription
  app/common/config.go
  app/common/ffx.go
  app/common/namespace.go
  app/common/openmeter_billingworker.go
  app/common/server.go
  app/common/subscription.go
  app/common/telemetry.go
  app/config/config_test.go
  app/config/productcatalog.go
  app/config/testdata/complete.yaml
  cmd/billing-worker/wire_gen.go
  cmd/jobs/internal/wire.go
  cmd/jobs/internal/wire_gen.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  openmeter/subscription/errors.go
  openmeter/subscription/featureflag.go
  openmeter/subscription/service/service.go
  openmeter/subscription/service/servicevalidation.go
  openmeter/subscription/testutils/service.go
  openmeter/subscription/workflow/service/service.go
  openmeter/subscription/workflow/service/subscription.go
  openmeter/subscription/workflow/service/subscription_test.go
  pkg/ffx/context.go
  pkg/ffx/featureflag.go
  pkg/ffx/static.go
  test/billing/subscription_suite.go
Labels: release-note/ignore

#3436 fix(sdk): zod schema generation
  api/client/javascript/.prettierignore
  api/client/javascript/.prettierrc.json
  api/client/javascript/biome.json
  api/client/javascript/eslint.config.js
  api/client/javascript/orval.config.ts
  api/client/javascript/package.json
  api/client/javascript/pnpm-lock.yaml
  api/client/javascript/scripts/add-as-const.ts
  api/client/javascript/scripts/generate.ts
  api/client/javascript/src/client/addons.ts
  api/client/javascript/src/client/apps.ts
  api/client/javascript/src/client/billing.ts
  api/client/javascript/src/client/common.ts
  api/client/javascript/src/client/customers.ts
  api/client/javascript/src/client/debug.ts
  api/client/javascript/src/client/entitlements.ts
  api/client/javascript/src/client/events.spec.ts
  api/client/javascript/src/client/events.ts
  api/client/javascript/src/client/features.ts
  api/client/javascript/src/client/index.ts
  api/client/javascript/src/client/info.ts
  api/client/javascript/src/client/meters.ts
  api/client/javascript/src/client/notifications.ts
  api/client/javascript/src/client/plans.ts
  api/client/javascript/src/client/portal.ts
  api/client/javascript/src/client/subjects.ts
  api/client/javascript/src/client/subscription-addons.ts
  api/client/javascript/src/client/subscriptions.ts
  api/client/javascript/src/client/utils.ts
  api/client/javascript/src/portal/index.ts
  api/client/javascript/src/zod/index.ts
  api/client/javascript/tsconfig.json
Labels: release-note/bug-fix

#3444 fix(api): map metadata on input
  openmeter/entitlement/driver/v2/mapping.go
Labels: release-note/bug-fix

#3450 refactor(subs): use servicevalidator for uniqueness testing
  app/common/subscription.go
  openmeter/billing/validators/subscription/validator.go
  openmeter/server/server_test.go
  openmeter/subscription/service.go
  openmeter/subscription/service/service.go
  openmeter/subscription/service/servicevalidation.go
  openmeter/subscription/subscriptionvalidator.go
  openmeter/subscription/testutils/mock.go
  openmeter/subscription/testutils/service.go
  openmeter/subscription/uniqueness.go
  openmeter/subscription/validator.go
  openmeter/subscription/validators/subscription/components.go
  openmeter/subscription/validators/subscription/validator.go
  test/billing/subscription_suite.go
Labels: release-note/ignore
