Repository openmeterio/openmeter, pull requests merged in 2025-08, with the labels that each got.

#3173 fix: invalid error on period correction
  openmeter/billing/worker/subscription/sync.go
Labels: release-note/bug-fix, area/billing, area/subscriptions

#3175 chore: reduce worker noise
  openmeter/entitlement/balanceworker/entitlementhandler.go
  openmeter/watermill/router/errors.go
  openmeter/watermill/router/metrics.go
Labels: release-note/misc, area/billing

#3181 chore: add more details into invoice update error messages
  openmeter/billing/service/invoice.go
  openmeter/billing/worker/subscription/invoiceupdate.go
Labels: release-note/ignore

#3185 feat(app): stripe add metadata to invoice
  openmeter/app/stripe/client/appclient.go
  openmeter/app/stripe/client/checkout.go
  openmeter/app/stripe/client/client.go
  openmeter/app/stripe/client/customer.go
  openmeter/app/stripe/client/invoice.go
  openmeter/app/stripe/entity/app/invoice.go
  openmeter/app/stripe/httpdriver/webhook.go
  test/app/stripe/invoice_test.go
Labels: release-note/feature, area/apps

#3188 fix(subs): remove up validation
  openmeter/subscription/subscriptionview.go
Labels: release-note/bug-fix

#3192 fix: hide leaked docs
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/entitlements/customer.tsp
Labels: release-note/ignore

#3212 fix(client): js sdk gen
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
Labels: release-note/ignore

#3209 ci: use nix for lint, e2e, quickstart
  .dagger/build.go
  .dagger/dev.go
  .dagger/generate.go
  .dagger/lint.go
  .dagger/test.go
  .dagger/test_e2e.go
  .dagger/utils.go
  .github/workflows/artifacts.yaml
  .github/workflows/ci.yaml
  .github/workflows/sdk-javascript-release.yaml
  .vscode/settings.json
  Dockerfile
  Makefile
  api/client/javascript/Makefile
  api/spec/Makefile
  docker-compose.base.yaml
  docker-compose.yaml
  e2e/.gitignore
  e2e/Makefile
  e2e/docker-compose.infra.yaml
  e2e/docker-compose.openmeter-latest.yaml
  e2e/docker-compose.openmeter-local.yaml
  e2e/docker-compose.openmeter.yaml
  e2e/e2e_test.go
  e2e/entitlement_test.go
  e2e/productcatalog_test.go
  e2e/setup_test.go
  flake.nix
  quickstart/.gitignore
  quickstart/README.md
  quickstart/docker-compose.ci.yaml
  quickstart/docker-compose.yaml
Labels: release-note/ignore

#3213 ci: speed up js sdk release job
  .dagger/release.go
  .github/workflows/sdk-javascript-dev-release.yaml
  .github/workflows/sdk-javascript-release.yaml
  .github/workflows/sdk-javascript.yaml
  api/client/javascript/Makefile
Labels: release-note/ignore

#3214 fix(streaming): filter for customer without group by
  openmeter/streaming/clickhouse/meter_query.go
  openmeter/streaming/clickhouse/meter_query_test.go
Labels: area/processor, release-note/bug-fix

#3216 chore: fix main integartion tests
  .github/workflows/artifacts.yaml
Labels: release-note/ignore

#3221 fix(nix): add postgresql pkg
  flake.nix
Labels: release-note/ignore

#3226 feat: subscription sync allow disabling continuous line logic
  openmeter/billing/annotations.go
  openmeter/billing/worker/subscription/patch.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/customer/adapter/entitymapping.go
  openmeter/ent/db/addon.go
  openmeter/ent/db/addon/addon.go
  openmeter/ent/db/addon_create.go
  openmeter/ent/db/addon_update.go
  openmeter/ent/db/billinginvoiceline.go
  openmeter/ent/db/billinginvoiceline_create.go
  openmeter/ent/db/billinginvoiceline_query.go
  openmeter/ent/db/billinginvoiceline_update.go
  openmeter/ent/db/customer.go
  openmeter/ent/db/customer_create.go
  openmeter/ent/db/customer_update.go
  openmeter/ent/db/entitlement.go
  openmeter/ent/db/entitlement/entitlement.go
  openmeter/ent/db/entitlement_create.go
  openmeter/ent/db/entitlement_update.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/notificationevent.go
  openmeter/ent/db/notificationevent/notificationevent.go
  openmeter/ent/db/notificationevent_create.go
  openmeter/ent/db/notificationevent_update.go
  openmeter/ent/db/planaddon.go
  openmeter/ent/db/planaddon_create.go
  openmeter/ent/db/planaddon_update.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/db/subscriptionitem.go
  openmeter/ent/db/subscriptionitem/subscriptionitem.go
  openmeter/ent/db/subscriptionitem_create.go
  openmeter/ent/db/subscriptionitem_update.go
  openmeter/ent/db/usagereset.go
  openmeter/ent/db/usagereset_create.go
  openmeter/ent/db/usagereset_update.go
  openmeter/productcatalog/http/mapping.go
  pkg/models/annotation.go
  tools/migrate/migrations/20250731160524_billing-second-resolution.up.sql
  tools/migrate/migrations/20250807075408_usageperiod-duration-calculations.up.sql
  tools/migrate/migrations/20250815072132_force-continuous-lines-annotation.down.sql
  tools/migrate/migrations/20250815072132_force-continuous-lines-annotation.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/misc, area/billing

#3230 chore: use lo for latest
  openmeter/credit/engine/grant.go
  pkg/slicesx/map.go
  pkg/timeutil/compare.go
Labels: release-note/ignore

#3236 chore: add jobs binary to image
  Dockerfile
Labels: release-note/bug-fix

#3232 refactor(billing): use interface based parent relationships
  openmeter/billing/adapter/invoicelinediff.go
  openmeter/billing/adapter/invoicelinediff_test.go
  openmeter/billing/adapter/invoicelinemapper.go
  openmeter/billing/adapter/invoicelines.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/invoice_test.go
  openmeter/billing/invoiceline.go
  openmeter/billing/service/lineservice/detailedlines.go
  openmeter/billing/service/lineservice/usagebasedline_test.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/subscription/sync_test.go
  pkg/models/model.go
  test/app/custominvoicing/invocing_test.go
  test/app/stripe/invoice_test.go
  test/billing/adapter_test.go
  test/billing/collection_test.go
  test/billing/discount_test.go
  test/billing/invoice_test.go
  test/billing/suite.go
  test/billing/tax_test.go
Labels: release-note/ignore

#3248 chore(collector): add lease health check to leader elector
  collector/benthos/input/kubernetes.go
  collector/benthos/internal/logging/logging.go
  collector/benthos/services/leaderelection/flags.go
  collector/benthos/services/leaderelection/service.go
Labels: release-note/misc

#3259 refactor(streaming): resolve customer_id with map
  openmeter/streaming/clickhouse/event_query.go
  openmeter/streaming/clickhouse/event_query_v2.go
  openmeter/streaming/clickhouse/event_query_v2_test.go
  openmeter/streaming/clickhouse/meter_query.go
  openmeter/streaming/clickhouse/meter_query_test.go
  openmeter/streaming/clickhouse/queryhelper.go
Labels: area/processor, release-note/ignore

#3263 feat(api): customer list search by partial key
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/customer/customer.tsp
  openmeter/customer/adapter/customer.go
Labels: area/api, release-note/feature

#3271 fix(stripe): app client error handling
  openmeter/app/stripe/adapter/customer.go
  openmeter/app/stripe/client/appclient.go
  openmeter/app/stripe/client/client.go
  openmeter/app/stripe/client/customer.go
  openmeter/app/stripe/client/errors.go
  openmeter/app/stripe/client/invoice.go
  openmeter/app/stripe/client/portal.go
  openmeter/app/stripe/entity/app/customer.go
  openmeter/app/stripe/entity/app/invoice.go
  test/app/stripe/appstripe.go
  test/app/stripe/invoice_test.go
Labels: release-note/bug-fix, area/apps

#3284 chore: bump nix env
  .envrc
  flake.lock
Labels: release-note/dependency-update, release-note/ignore

#3289 refactor: optimize updating usage attribution
  openmeter/customer/adapter/customer.go
Labels: release-note/ignore

#3292 fix: customer lookup by usage attribution
  openmeter/customer/adapter/customer.go
Labels: release-note/bug-fix

#3291 refactor: customer subject service hooks
  app/common/customer.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  openmeter/customer/service/hooks/subjectcustomer.go
  openmeter/customer/service/hooks/subjectcustomer_test.go
  openmeter/customer/service/hooks/subjectvalidator.go
  openmeter/customer/service/hooks/subjectvalidator_test.go
Labels: release-note/feature
