Repository openmeterio/openmeter, pull requests merged in 2025-05, with the labels that each got.

#2758 fix: add missing date pinning
  openmeter/entitlement/adapter/entitlement_test.go
Labels: release-note/bug-fix

#2757 fix: notifications dispatcher
  openmeter/notification/eventhandler/handler.go
  openmeter/notification/httpdriver/mapping.go
Labels: release-note/bug-fix

#2759 fix: missing event definitions
  openmeter/notification/webhook/events.go
Labels: release-note/bug-fix

#2761 refactor: recover from panic in eventhandler
  openmeter/notification/eventhandler/handler.go
  openmeter/notification/service/service.go
Labels: release-note/bug-fix

#2762 fix: nil check in app http mapper
  openmeter/app/httpdriver/mapper.go
Labels: release-note/bug-fix

#2760 fix: api grouping
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/app/custominvoicing.tsp
  api/spec/src/app/stripe.tsp
  api/spec/src/cloud/main.tsp
  api/spec/src/main.tsp
Labels: release-note/misc

#2764 feat(event): improve validation
  openmeter/meter/parse.go
  openmeter/meter/parse_test.go
  openmeter/meterevent/adapter/event.go
  openmeter/server/server_test.go
  openmeter/streaming/clickhouse/meter_query.go
Labels: release-note/feature

#2769 feat(app): stripe invoice create idempotency
  openmeter/app/stripe/client/invoice.go
  openmeter/app/stripe/entity/app/invoice.go
  test/app/stripe/invoice_test.go
Labels: release-note/feature, area/billing

#2768 feat: add fs for disabling invocing on a namespace
  app/common/billing.go
  app/common/config.go
  app/config/billing.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/internal/wire_gen.go
  cmd/server/wire_gen.go
  openmeter/billing/errors.go
  openmeter/billing/service.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoicestate.go
  openmeter/billing/service/service.go
  openmeter/billing/worker/collect/collect.go
  openmeter/billing/worker/subscription/handlers.go
  openmeter/server/server_test.go
  test/billing/invoice_test.go
  test/billing/suite.go
Labels: release-note/misc

#2783 fix: populate invoice at
  openmeter/billing/service/invoicestate.go
  test/app/custominvoicing/invocing_test.go
  tools/migrate/migrations/20250506182753_backfill-invoice-at.down.sql
  tools/migrate/migrations/20250506182753_backfill-invoice-at.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/bug-fix

#2784 feat(api): add createdAfter and createdBefore to list invoices
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices.tsp
  openmeter/billing/adapter/invoice.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/invoice.go
Labels: release-note/feature

#2767 refactor(notification): webhook handler
  app/common/config.go
  app/common/notification.go
  app/config/config_test.go
  app/config/svix.go
  cmd/notification-service/wire_gen.go
  cmd/server/wire_gen.go
  openmeter/notification/consumer/entitlementbalancethreshold.go
  openmeter/notification/consumer/entitlementreset.go
  openmeter/notification/service/service.go
  openmeter/notification/webhook/handler.go
  openmeter/notification/webhook/noop.go
  openmeter/notification/webhook/noop/noop.go
  openmeter/notification/webhook/svix.go
  openmeter/notification/webhook/svix/event.go
  openmeter/notification/webhook/svix/message.go
  openmeter/notification/webhook/svix/svix.go
  openmeter/notification/webhook/svix/webhook.go
  test/notification/channel.go
  test/notification/consumer_balance.go
  test/notification/event.go
  test/notification/notification_test.go
  test/notification/repository.go
  test/notification/rule.go
  test/notification/testenv.go
  test/notification/webhook.go
Labels: release-note/ignore

#2785 chore: bump nix env
  flake.lock
  flake.nix
Labels: release-note/ignore

#2787 feat(api): allow multiple group by filters elements
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/meters.tsp
  openmeter/meter/httphandler/mapping.go
  openmeter/meter/httphandler/query.go
Labels: release-note/feature

#2790 chore(deps): bump dagger to 0.18.6
  .github/workflows/ci-exp.yaml
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .github/workflows/sdk-javascript-release.yaml
  .github/workflows/sdk-javascript.yaml
  .github/workflows/sdk-python.yaml
  dagger.json
  flake.lock
Labels: release-note/ignore

#2781 chore: remove adopters.md
  ADOPTERS.md
Labels: release-note/ignore

#2745 Implement Usage Discounts for Addons
  openmeter/productcatalog/plan/service/service_test.go
  openmeter/productcatalog/planaddon.go
  openmeter/productcatalog/planaddon/service/service_test.go
  openmeter/productcatalog/ratecard.go
  openmeter/productcatalog/ratecard_test.go
  openmeter/subscription/addon/compatible.go
  openmeter/subscription/addon/extend.go
  openmeter/subscription/addon/extend_test.go
Labels: release-note/feature

#2788 chore(deps): bump Go version to 1.24.1
  .dagger/versions_pinned.go
  go.mod
Labels: release-note/misc

#2791 fix(streaming): finite numbers
  e2e/e2e_test.go
  openmeter/streaming/clickhouse/meter_query.go
  openmeter/streaming/clickhouse/meter_query_test.go
Labels: area/processor, release-note/bug-fix

#2793 ci: update dependabot config
  .github/dependabot.yaml
Labels: release-note/ignore

#2800 refactor: rm svix operation webhook
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/cloud/main.tsp
  api/spec/src/notification/main.tsp
  api/spec/src/notification/svix.tsp
  openmeter/server/router/notification.go
Labels: release-note/ignore

#2801 refactor(notification): event hander init
  app/common/notification.go
  cmd/notification-service/wire_gen.go
  cmd/server/wire_gen.go
  openmeter/notification/eventhandler/dispatch.go
  openmeter/notification/eventhandler/handler.go
  openmeter/notification/eventhandler/reconcile.go
  openmeter/notification/service.go
  openmeter/notification/service/service.go
Labels: release-note/ignore

#2802 Fix AffectedRateCards
  openmeter/subscription/addon/diff/affected.go
Labels: release-note/bug-fix

#2803 Fix Tracing Handler
  app/common/telemetry.go
Labels: release-note/misc

#2805 feat: make http server extensible by router hooks
  app/common/server.go
  app/common/telemetry.go
  cmd/server/main.go
  cmd/server/wire.go
  cmd/server/wire_gen.go
  openmeter/server/server.go
  openmeter/server/server_test.go
Labels: release-note/misc

#2808 SubscriptionAddon Debug Logging
  app/common/subscription.go
  openmeter/subscription/testutils/service.go
  openmeter/subscription/workflow/service/addon.go
  openmeter/subscription/workflow/service/service.go
  openmeter/subscription/workflow/service/subscription_test.go
  test/billing/subscription_suite.go
Labels: release-note/ignore

#2812 SubscriptionAddon: Add convenience so post can be used for updating quantity
  openmeter/subscription/addon/http/create.go
Labels: release-note/misc

#2809 feat(tax): configure stripe tax
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/profile.tsp
  openmeter/app/stripe/client/appclient.go
  openmeter/app/stripe/client/customer.go
  openmeter/app/stripe/client/invoice.go
  openmeter/app/stripe/client/stripe.go
  openmeter/app/stripe/entity/app/customer.go
  openmeter/app/stripe/entity/app/invoice.go
  openmeter/billing/adapter/profile.go
  openmeter/billing/defaults.go
  openmeter/billing/httpdriver/deprecations.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/httpdriver/profile.go
  openmeter/billing/invoiceline.go
  openmeter/billing/profile.go
  openmeter/billing/tax.go
  openmeter/billing/workflow.go
  openmeter/ent/db/billingworkflowconfig.go
  openmeter/ent/db/billingworkflowconfig/billingworkflowconfig.go
  openmeter/ent/db/billingworkflowconfig/where.go
  openmeter/ent/db/billingworkflowconfig_create.go
  openmeter/ent/db/billingworkflowconfig_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/schema/billing.go
  test/app/stripe/appstripe.go
  test/app/stripe/invoice_test.go
  test/billing/invoice_test.go
  test/billing/profile.go
  tools/migrate/migrations/20250512174316_billing_profile_workflow_config_tax.down.sql
  tools/migrate/migrations/20250512174316_billing_profile_workflow_config_tax.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/billing, area/apps

#2814 fix(stripe): payment method update
  openmeter/app/stripe/adapter/customer.go
  test/app/stripe/appstripe.go
Labels: release-note/bug-fix, area/apps

#2782 fix(cache): duplicates
  openmeter/streaming/clickhouse/cache.go
  openmeter/streaming/clickhouse/cache_test.go
  openmeter/streaming/clickhouse/cachemerge.go
  openmeter/streaming/clickhouse/cachemerge_test.go
Labels: release-note/bug-fix

#2815 fix(feature): deps check
  openmeter/productcatalog/adapter/feature.go
Labels: release-note/bug-fix, area/entitlements

#2820 feat(api): add validation errors to plan add-on assignment
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/errors.tsp
  api/spec/src/productcatalog/main.tsp
  api/spec/src/productcatalog/planaddon.tsp
  openmeter/productcatalog/addon/service/addon.go
  openmeter/productcatalog/errors.go
  openmeter/productcatalog/errors_test.go
  openmeter/productcatalog/planaddon.go
  openmeter/productcatalog/planaddon/httpdriver/mapping.go
  openmeter/productcatalog/planaddon/service/planaddon.go
  openmeter/productcatalog/ratecard.go
  openmeter/productcatalog/resource.go
  openmeter/productcatalog/resource_test.go
  openmeter/subscription/addon/extend_test.go
Labels: release-note/misc

#2822 Add observability to what happens during billing sync
  app/common/billing.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/internal/wire_gen.go
  cmd/server/wire_gen.go
  openmeter/billing/worker/subscription/phaseiterator.go
  openmeter/billing/worker/subscription/phaseiterator_test.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/subscription/sync_test.go
  pkg/slicesx/each.go
  pkg/slicesx/each_test.go
  test/billing/subscription_test.go
Labels: release-note/misc

#2825 fix(subsadd): check phase compatibility limit on quantity change too
  openmeter/subscription/addon/service/service.go
Labels: release-note/bug-fix

#2829 feat: capture invoice snapshot date
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices/invoice.tsp
  openmeter/billing/adapter/invoice.go
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/invoice.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoiceline.go
  openmeter/ent/db/billinginvoice.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/billinginvoice/where.go
  openmeter/ent/db/billinginvoice_create.go
  openmeter/ent/db/billinginvoice_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/db/setorclear.go
  openmeter/ent/schema/billing.go
  tools/migrate/migrations/20250516090128_billing-invoice-snapshotted-at.down.sql
  tools/migrate/migrations/20250516090128_billing-invoice-snapshotted-at.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/billing

#2837 fix: progressive billing billable period calculations
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices.tsp
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/invoice.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/lineservice/usagebasedline.go
  openmeter/billing/worker/collect/collect.go
  test/billing/invoice_test.go
Labels: release-note/bug-fix, area/billing

#2835 refactor: fix update test errors
  openmeter/billing/service/discounts.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoicecalc/calculator.go
  openmeter/billing/service/invoicecalc/discounts.go
  openmeter/billing/service/invoicecalc/mock.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/service/invoicestate.go
  test/billing/discount_test.go
  test/billing/invoice_test.go
Labels: release-note/bug-fix, area/billing

#2838 feat: add validation error to models
  pkg/models/error.go
  pkg/models/error_test.go
  pkg/models/validationissue.go
  pkg/models/validationissue_test.go
Labels: release-note/ignore

#2842 refactor: validation error for plan add-on assignment
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/errors.tsp
  openmeter/productcatalog/errors.go
  openmeter/productcatalog/errors_test.go
  openmeter/productcatalog/planaddon.go
  openmeter/productcatalog/planaddon/httpdriver/mapping.go
  openmeter/productcatalog/planaddon_test.go
  openmeter/productcatalog/ratecard.go
  openmeter/productcatalog/ratecard_test.go
  openmeter/productcatalog/resource.go
  openmeter/productcatalog/resource_test.go
  openmeter/subscription/addon/extend_test.go
Labels: release-note/ignore

#2847 fix(api): subscription addon create type
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/subscriptionaddon.tsp
Labels: release-note/misc

#2846 refactor(pc): return complete add-on object
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/planaddon.tsp
  openmeter/productcatalog/errors.go
  openmeter/productcatalog/planaddon.go
  openmeter/productcatalog/planaddon/httpdriver/mapping.go
  openmeter/productcatalog/planaddon_test.go
Labels: area/api, release-note/misc

#2817 Starting phase for Subscription Migrate & Change
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/routes.tsp
  api/spec/src/productcatalog/subscription.tsp
  openmeter/productcatalog/subscription/http/change.go
  openmeter/productcatalog/subscription/http/migrate.go
  openmeter/productcatalog/subscription/service.go
  openmeter/productcatalog/subscription/service/change.go
  openmeter/productcatalog/subscription/service/change_test.go
  openmeter/productcatalog/subscription/service/migrate.go
  openmeter/productcatalog/subscription/service/migrate_test.go
Labels: release-note/feature

#2849 Remove unnecessary validation
  openmeter/subscription/addon/diff/restore.go
  openmeter/subscription/addon/extend.go
  openmeter/subscription/addon/extend_test.go
Labels: release-note/bug-fix

#2850 chore(api): remove x-internal from addon endpoints
  api/api.gen.go
  api/client/go/client.gen.go
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/routes.tsp
Labels: release-note/misc

#2851 refactor: draft until
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices.tsp
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/service/invoicecalc/calculator.go
  openmeter/billing/service/invoicecalc/draftuntil.go
Labels: release-note/ignore, area/billing

#2833 feat(sdk): add addons to javascript SDK
  api/client/javascript/package.json
  api/client/javascript/pnpm-lock.yaml
  api/client/javascript/src/client/addons.ts
  api/client/javascript/src/client/index.ts
  api/client/javascript/src/client/subscription-addons.ts
  api/client/javascript/src/portal/index.ts
Labels: release-note/misc

#2857 Cadence Debug Logging
  openmeter/entitlement/uniqueness.go
  openmeter/subscription/subscriptionspec.go
  pkg/models/cadence.go
  pkg/models/cadence_test.go
Labels: release-note/misc

#2859 feat: extend validation issue type
  pkg/models/validationissue.go
  pkg/models/validationissue_test.go
Labels: release-note/ignore

#2864 Revert "chore(deps): bump the otel group with 12 updates"
  go.mod
  go.sum
Labels: release-note/ignore

#2860 fix: phase iterator in advance/in arreas
  openmeter/billing/worker/subscription/phaseiterator.go
  openmeter/billing/worker/subscription/phaseiterator_test.go
  openmeter/billing/worker/subscription/sync_test.go
Labels: release-note/bug-fix, area/billing

#2834 feat: collect usage on draft invoices
  cmd/jobs/billing/collect/collect.go
  openmeter/billing/adapter/invoice.go
  openmeter/billing/invoice.go
  openmeter/billing/service/collectionat.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoicecalc/calculator.go
  openmeter/billing/service/invoicecalc/collectionat.go
  openmeter/billing/service/invoicecalc/draftuntil.go
  openmeter/billing/service/invoiceline.go
  openmeter/billing/service/invoicestate.go
  openmeter/billing/worker/advance/advance.go
  openmeter/billing/worker/collect/collect.go
  openmeter/billing/worker/subscription/handlers.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/subscription/sync_test.go
  openmeter/billing/worker/worker.go
  openmeter/ent/db/billinginvoice/billinginvoice.go
  openmeter/ent/db/migrate/schema.go
  test/billing/collection_test.go
  test/billing/invoice_test.go
  test/billing/profile.go
  test/billing/suite.go
Labels: release-note/feature, area/billing

#2848 feat(metering): introduce LATEST aggregation
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/meters.tsp
  openmeter/ent/db/meter/meter.go
  openmeter/ent/db/migrate/schema.go
  openmeter/meter/meter.go
  openmeter/meter/parse.go
  openmeter/streaming/clickhouse/meter_query.go
  openmeter/streaming/clickhouse/meter_query_test.go
Labels: kind/feature

#2858 feat: collection tweaks
  app/common/billing.go
  cmd/jobs/internal/wire_gen.go
  openmeter/billing/invoice.go
  openmeter/billing/service.go
  openmeter/billing/service/invoice.go
  openmeter/billing/worker/collect/collect.go
  openmeter/server/server_test.go
Labels: release-note/ignore, area/billing

#2856 feat: snapshot action
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices.tsp
  api/spec/src/billing/invoices/invoice.tsp
  openmeter/billing/httpdriver/invoice.go
  openmeter/billing/invoice.go
  openmeter/billing/invoicestate.go
  openmeter/billing/service.go
  openmeter/billing/service/invoice.go
  openmeter/billing/service/invoicestate.go
  openmeter/server/router/billing.go
  openmeter/server/server_test.go
Labels: release-note/feature, area/billing

#2867 feat: expose collection at
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/invoices/invoice.tsp
  openmeter/billing/httpdriver/invoice.go
Labels: area/api, release-note/feature, area/billing

#2862 fix(streaming)!: time filters exclusive end
  openmeter/streaming/clickhouse/cache.go
  openmeter/streaming/clickhouse/cache_test.go
  openmeter/streaming/clickhouse/cachequery.go
  openmeter/streaming/clickhouse/cachequery_test.go
  openmeter/streaming/clickhouse/event_query.go
  openmeter/streaming/clickhouse/event_query_test.go
  openmeter/streaming/clickhouse/meter_query.go
  openmeter/streaming/clickhouse/meter_query_test.go
Labels: release-note/breaking-change, release-note/bug-fix

#2868 refactor: improve billing api docs
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/client/javascript/src/zod/index.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/billing/customeroverride.tsp
  api/spec/src/billing/invoices.tsp
  api/spec/src/billing/profile.tsp
Labels: release-note/misc, area/billing

#2874 revert: tracing handler changes
  app/common/telemetry.go
Labels: release-note/ignore

#2875 fix(query): cachable check
  openmeter/streaming/clickhouse/cache.go
  openmeter/streaming/clickhouse/cache_test.go
Labels: release-note/bug-fix

#2876 fix(streaming): cache dedupe
  openmeter/streaming/clickhouse/cachemerge.go
  openmeter/streaming/clickhouse/cachemerge_test.go
Labels: release-note/bug-fix

#2877 fix: paginate recalculation job
  openmeter/entitlement/balanceworker/recalculate.go
Labels: release-note/ignore, area/entitlements, area/notification

#2883 refactor: add helpers for flat fee line creation
  openmeter/billing/invoiceline.go
  openmeter/notification/internal/rule.go
  test/app/custominvoicing/invocing_test.go
  test/billing/collection_test.go
  test/billing/invoice_test.go
  test/billing/tax_test.go
Labels: release-note/ignore, area/billing

#2888 refactor(cache): query non-cache and fresh period in one go
  openmeter/streaming/clickhouse/cache.go
  openmeter/streaming/clickhouse/cache_test.go
  openmeter/streaming/clickhouse/connector.go
Labels: release-note/ignore

#2893 fix: only support qty=1 for flat fee lines
  openmeter/billing/invoiceline.go
  test/app/custominvoicing/invocing_test.go
  test/billing/invoice_test.go
  test/billing/suite.go
Labels: release-note/breaking-change, area/billing

#2886 feat: implement ubp flat fee
  openmeter/billing/adapter/invoicelinemapper.go
  openmeter/billing/httpdriver/invoiceline.go
  openmeter/billing/invoiceline.go
  openmeter/billing/service/invoicecalc/collectionat.go
  openmeter/billing/service/lineservice/detailedlines.go
  openmeter/billing/service/lineservice/priceflat.go
  openmeter/billing/service/lineservice/priceflat_test.go
  openmeter/billing/service/lineservice/service.go
  openmeter/billing/service/lineservice/usagebasedline.go
  openmeter/billing/service/lineservice/usagebasedline_test.go
  openmeter/billing/service/lineservice/usagebasedlineflat.go
  openmeter/ent/db/billinginvoiceusagebasedlineconfig.go
  openmeter/ent/db/billinginvoiceusagebasedlineconfig/billinginvoiceusagebasedlineconfig.go
  openmeter/ent/db/billinginvoiceusagebasedlineconfig/where.go
  openmeter/ent/db/billinginvoiceusagebasedlineconfig_create.go
  openmeter/ent/db/billinginvoiceusagebasedlineconfig_update.go
  openmeter/ent/db/migrate/schema.go
  openmeter/ent/db/mutation.go
  openmeter/ent/db/runtime.go
  openmeter/ent/schema/billing.go
  openmeter/notification/internal/rule.go
  test/app/custominvoicing/invocing_test.go
  test/app/stripe/invoice_test.go
  test/billing/collection_test.go
  test/billing/invoice_test.go
  test/billing/suite.go
  test/billing/tax_test.go
  test/billing/ubpflatfee_test.go
  tools/migrate/migrations/20250525121526_billing-ubp-fee-line.down.sql
  tools/migrate/migrations/20250525121526_billing-ubp-fee-line.up.sql
  tools/migrate/migrations/atlas.sum
Labels: release-note/feature, area/billing

#2898 feat: use UBP flat fee lines
  openmeter/billing/worker/subscription/feehelper.go
  openmeter/billing/worker/subscription/sync.go
  openmeter/billing/worker/subscription/sync_test.go
Labels: release-note/feature, area/billing, area/subscriptions

#2902 feat: add config for ubp flat fee lines
  app/common/billing.go
  app/config/billing.go
  cmd/billing-worker/wire_gen.go
  cmd/jobs/internal/wire_gen.go
Labels: release-note/ignore

#2908 fix: flat fee line do not validate meter
  openmeter/billing/service/lineservice/usagebasedlineflat.go
Labels: release-note/ignore, area/billing

#2895 refactor(productcatalog): validation errors
  api/api.gen.go
  api/client/go/client.gen.go
  api/client/javascript/src/client/schemas.ts
  api/openapi.cloud.yaml
  api/openapi.yaml
  api/spec/src/productcatalog/addon.tsp
  api/spec/src/productcatalog/plan.tsp
  openmeter/productcatalog/addon.go
  openmeter/productcatalog/addon/httpdriver/addon.go
  openmeter/productcatalog/addon/httpdriver/errors.go
  openmeter/productcatalog/addon/httpdriver/mapping.go
  openmeter/productcatalog/addon/service.go
  openmeter/productcatalog/addon/service/addon.go
  openmeter/productcatalog/discount.go
  openmeter/productcatalog/effectiveperiod.go
  openmeter/productcatalog/effectiveperiod_test.go
  openmeter/productcatalog/entitlement.go
  openmeter/productcatalog/errors.go
  openmeter/productcatalog/http/errors.go
  openmeter/productcatalog/http/mapping.go
  openmeter/productcatalog/http/resource.go
  openmeter/productcatalog/phase.go
  openmeter/productcatalog/plan.go
  openmeter/productcatalog/plan/adapter/phase.go
  openmeter/productcatalog/plan/addon.go
  openmeter/productcatalog/plan/httpdriver/errors.go
  openmeter/productcatalog/plan/httpdriver/mapping.go
  openmeter/productcatalog/plan/httpdriver/plan.go
  openmeter/productcatalog/plan/phase.go
  openmeter/productcatalog/plan/plan.go
  openmeter/productcatalog/plan/ratecard.go
  openmeter/productcatalog/plan/service.go
  openmeter/productcatalog/plan/service/plan.go
  openmeter/productcatalog/plan/validators.go
  openmeter/productcatalog/plan_test.go
  openmeter/productcatalog/planaddon.go
  openmeter/productcatalog/planaddon/httpdriver/errors.go
  openmeter/productcatalog/planaddon/httpdriver/mapping.go
  openmeter/productcatalog/planaddon/httpdriver/planaddon.go
  openmeter/productcatalog/planaddon_test.go
  openmeter/productcatalog/price.go
  openmeter/productcatalog/ratecard.go
  openmeter/productcatalog/subscription/service/plan.go
  openmeter/productcatalog/tax.go
  pkg/models/error_test.go
  pkg/models/errors.go
  pkg/models/errors_test.go
  pkg/models/fieldselector.go
  pkg/models/fieldselector_test.go
  pkg/models/validationissue.go
  pkg/models/validationissue_test.go
Labels: area/api, release-note/misc

#2914 fix: missing validations in product catalog
  openmeter/productcatalog/addon.go
  openmeter/productcatalog/addon/service/service_test.go
  openmeter/productcatalog/errors.go
  openmeter/productcatalog/planaddon.go
  openmeter/productcatalog/planaddon_test.go
Labels: release-note/bug-fix

#2917 chore: fix validation of child lines
  openmeter/billing/invoiceline.go
Labels: release-note/misc, area/billing

#2918 fix: updating gathering invoices with split lines
  openmeter/billing/service/invoice.go
Labels: release-note/bug-fix, area/billing
